### ISSUE TITLE
Is it possible to use --nopromot but with "y" option?

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#101]
I want to automate " sfdx sfdmu:run --sourceusername csvfile --targetusername FSCADK -p data/sfdmu/ --noprompt

But the default option is "n" and that ABORTS the command. Is there a way to supply default option with --noprompt?

**Comment by jrattanpal** [comment]
We are using this plugin for https://github.com/Vchalem/fsc-demo-pack. This is used by Salesforce partners to quickly create orgs with FSC installed with basic configuration.

**Comment by hknokh** [comment]
Hello @jrattanpal 
Switched to "yes" for --noprompt
Please retest.
