### ISSUE TITLE
Migrating data to a new custom object with a new name

### ISSUE THREAD

**Issue by datamike** [forcedotcom/SFDX-Data-Move-Utility#103]
I LOVE this project!!!  Thank you!

My use case is this:  I am migrating data from a managed package to a new custom object.  Both the Object Name and the Field names are changed, so I don't see how to do a direct migration using this tool.  Am I understanding that correctly?

**UPDATE**:  After digging further into the documentation, I see that is NOT CORRECT.  I should be able to do a direct migration.  Something is wrong with my package configuration.

**What would be most helpful is if some sample export.json files (for different use cases) could be posted in the wiki.**

Working on the basis that is indeed the case, I have exported the data to CSV file.  My second step is to try to import the data to the new custom object from the previously-exported CSV file.  I'm a bit stuck there, as I keep getting error:  COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE.

Does my FieldMapping.csv file need to be set up a bit differently?  Perhaps, like this:

>ObjectName,FieldName,Target
>csvfile,,Chapter__c
>csvfile,xApi__Site__c,Site__c
>csvfile,CurrencyIsoCode,CurrencyIsoCode
>csvfile,Name,Name
>csvfile,xApi__Banner__c,Banner__c

Thanks again

**Comment by hknokh** [comment]
Hello, @datamike !
Thank you for your positive feedback!

Regarding the field mapping, of course you can't migrate directly from the same org to the same org,  but if you are using different orgs it is possible to migrate to another object/fields using field mapping.

- First, set useFieldMapping to true
- Second, you FieldMapping.csv is incorrect:
1. You need to include only fields that their names are different between orgs.
2. "csvfile" is invalid value.

See the modified example. 
Let see that the old object was named OldChapter__c.
ObjectName,FieldName,Target
OldChapter__c,,Chapter__c
OldChapter__c,xApi__Site__c,Site__c
OldChapter__c,xApi__Banner__c,Banner__c

Create export.json filed using the **OLD object and field versions (OldChapter__c)**, then export records to the csv, then import then into the same org. Or use direct migration in case of different orgs.

Thanks!
