### ISSUE TITLE
Records not inserted.

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#104]
I have exported data from one org at https://github.com/Vchalem/fsc-demo-pack/tree/master/data/sfdmu. (data and export file)

WHen I import it to a newly created org, it doesn't add, AccountContactRelation records. BUt if I run that command again, it adds some records.

It was working on Friday when I tested it. But suddenly it's not working today. 

Can you please suggest any solutions? This table is critical to get Relationship Map working in FInancial Services Cloud demo org. 

I am attaching all log files (first one and then subsequent ones). 

I think I maybe missing something. Maybe I should construct export.json differently??

[2020-06-23__15_10_48.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4821476/2020-06-23__15_10_48.log)
[2020-06-23__15_22_57.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4821477/2020-06-23__15_22_57.log)

[2020-06-23__13_17_20.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4821474/2020-06-23__13_17_20.log)
[2020-06-23__14_55_57.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4821475/2020-06-23__14_55_57.log)

**Comment by jrattanpal** [comment]
Ok, I think I found the issue but not sure why.
Let's take "Rachel Adams" (0033h000008s54yAAA, 0013h00000CviBAAAZ) account. It should be linked with "Adams Household" (0013h00000CviB5AAJ). But it's getting linked to "Symonds Household" (0013h00000CviBDAAZ). 

https://github.com/Vchalem/fsc-demo-pack/blob/master/data/sfdmu/Contact.csv
https://github.com/Vchalem/fsc-demo-pack/blob/master/data/sfdmu/Account.csv
https://github.com/Vchalem/fsc-demo-pack/blob/master/data/sfdmu/AccountContactRelation.csv


I am not sure where the resolve is failing. 


Note: Not sure if you need it. BUt if you need sample org as mine then you can clone above repo and run https://github.com/Vchalem/fsc-demo-pack/blob/master/orgInit.sh

**Comment by hknokh** [comment]
Hello @jrattanpal 
I know about this problem regarding the AccountContactRelation. It is could be because of the wrong handling  of person/business accounts. I will fix it ASAP.
Thank you

**Comment by jrattanpal** [comment]
Thank you!

This is the last missing piece for me to move forward with this script. I also plan to use it for Health Cloud; to be used by partners (SIs and ISVs)

**Comment by hknokh** [comment]
Hello, @jrattanpal 
I checked the AccountContactRelation inserts / upserts and it is working fine for me.
Checked both for relationships between person accounts and business accounts.

Following the recomended coniguration for Inserting account/contacts with relationships:

{   
    "objects": [
        {
            "operation": "Insert",
            "externalId": "Name",
            **"master": true,**
            "query": "SELECT Id, LastName, FirstName, Type, Phone, AccountNumber, Name, RecordTypeId FROM Account WHERE Name LIKE 'TestTest%'"
        },
        {
            "operation": "Insert",
            **"externalId": "Account.Id;Contact.Id",**           
            "query": "SELECT Id, AccountId, ContactId FROM AccountContactRelation",
            **"master": false**
        },
        {
            "operation": "Insert",
            "externalId": "Name",         
            **"master": false,**           
            "query": "SELECT Id, AccountId, LastName, FirstName, Email, Name FROM Contact"
        }
    ]
}

I highlighted important elements.

- Update the plugin

- When you want update/upsert - switch operation to desired value.

- Omit RecordTypeId if you don't want to trasnfer this.

- Please, refer [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.) for the details about the configuration elements that I have used.
