### ISSUE TITLE
Question: Is the WHERE clause in our export.json file limited to 4k characters like a normal SOQL statement?

### ISSUE THREAD

**Issue by EliasLahham** [forcedotcom/SFDX-Data-Move-Utility#11]
I have an org that has thousands of records, and I want to only grab a specific set of those. I will have all the ids that I can copy into my WHERE clause. Just want to make sure this is possible. Thanks.

**Comment by hknokh** [comment]
Hello @EliasLahham 
You can put your ids into WHERE with IN operator, but be aware of the limitation of the permitted total length for SOQL query:
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
Also set allRecords=true for your sobject.
Regards.

**Comment by EliasLahham** [comment]
Additional question:

So is there a way for this plugin to only gather records from a list of ids from a csv? Like I alluded to in my first comment, I have 90k record ids in one column of a csv. I can't obviously put those in a WHERE clause due to the limit, but is there another way to only grab those?
