### ISSUE TITLE
[BUG]-Missing records when "master: false" is used

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#113]
**Describe the bug**
When I used "master:false" for objects like AccountContactRelation, no records were fetched. But when I removed that feature, it fetched records as expected.

**To Reproduce**
Use export1.txt to fetch records (From Health Cloud). 
Log 1 is the file for this
Can clone https://github.com/Appirio/Health-Cloud-Sfdx-Template (DataLoad Branch) and run https://github.com/Appirio/Health-Cloud-Sfdx-Template/blob/DataLoad/orgInitAndData.sh

**Expected behavior**
AccountContactRelation should have records

Check in the "Log 1" file that "AccountContactRelation" has 28 records but then nothing shows up later.

**Is it just misconfiguration? Should I not use master?**

I am using this as instructed in https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/104#issuecomment-649224849

**export.json**
Export 1 - [export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837248/export.txt)
Export 2 - [export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837267/export.txt)

**Log file**
Attach your full **.log** file.
Log 1 - [2020-06-26__09_27_01.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837241/2020-06-26__09_27_01.log)
Log 2 - 
[2020-06-26__09_36_25.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837269/2020-06-26__09_36_25.log)

**Comment by jrattanpal** [comment]
I just noticed that some objects are missing records. For example, in above log, Case starts with 17 records but ends up with 6.

**Comment by hknokh** [comment]
Total amount of the SOURCE records: 17 - is **NOT** the actual records that will be inserted!
The step of "GETTING THE TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY..." is the TOTAL amount of ALL records according to your input SOQL and **just for calculation of optimal  migration strategy**. 
The actual amount to be processed according to the current situation is in  "DATA RETRIEVING SUMMARY" section **AFTER** the retireveing the data!
For example for the Case object it is 6 only records to process.
Why 6 only? Because you are using **master: false** and only 6 Cases were found for your Accounts.

**Comment by hknokh** [comment]
Regarding AccountCOntactRelation try also to put master=  true to Contact object.
And don't put accountcontactrelation to true since it is always the **slave** object, not primary one

**Comment by kamalsomu** [comment]
> Total amount of the SOURCE records: 17 - is **NOT** the actual records that will be inserted!
> The step of "GETTING THE TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY..." is the TOTAL amount of ALL records according to your input SOQL and **just for calculation of optimal migration strategy**.
> The actual amount to be processed according to the current situation is in "DATA RETRIEVING SUMMARY" section **AFTER** the retireveing the data!
> For example for the Case object it is 6 only records to process.
> Why 6 only? Because you are using **master: false** and only 6 Cases were found for your Accounts (master = true for Account).
> This is the normal and actual amount of records depend on your record set and the configuration used.

@hknokh Thanks for the detailed clarifications :)
