### ISSUE TITLE
[BUG]-Logs show records processed but data not actually inserted

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#114]
**Describe the bug**
As per log, (for example), Case object had 17 records which were inserted/updated. But there are no records in the org.

{Case} Total processed within all steps (Insert + Update): 17 records

**To Reproduce**
Can clone https://github.com/Appirio/Health-Cloud-Sfdx-Template (DataLoad Branch) and run https://github.com/Appirio/Health-Cloud-Sfdx-Template/blob/DataLoad/orgInitAndData.sh

This is to get new org. Export file and log is attached

**Expected behavior**
Target org should have 17 Case records . I also checked AccountContactRelation and same happened there.

(base) :Health-Cloud-Sfdx-Template xxx$ sfdx force:data:soql:query -u HCADK -q "Select Id from Case"
Your query returned no results.
(base) :Health-Cloud-Sfdx-Template xxx$ sfdx force:data:soql:query -u HCADK -q "Select Id from AccountContactRelation"
Your query returned no results.
(base) :Health-Cloud-Sfdx-Template xxx$ 

**export.json**
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837385/export.txt)

**Log file**
[2020-06-26__09_50_51.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837382/2020-06-26__09_50_51.log)

**Comment by jrattanpal** [comment]
Ok, I read through the entire log file and I now see this.

[09:51:22.698][WARN] [Batch# REST:Insert] {Case} Incompleted. 0 records succeeded, 17 records failed.

But I don't know why those failed. And because it's REST (not Bulk), I don't have a way to look at errors. Do you capture more details?

I see --loglevel option but it's not clear what values can I use. And if those will log those failed API calls with error. (https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/3.-Running-the-Plugin.)

**Comment by jrattanpal** [comment]
I also checked MissingParentRecordsReport.csv. It's complaining about some missing parent IDs. BUt I checked all records and those are there in CSV files. So not sure where it's failing those.

I am attaching entire data folder with all files. You will need to rename it to remove ".txt" from the name,

[data.zip.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4837670/data.zip.txt)

**Comment by hknokh** [comment]
All the details about the errors are in the /target directory.
For example for Case you can fund Case_insert_target.csv
You have column Errors. See there the error messages per row.
For example in your case the Case object failed because of validation rule I guess: "Visible in Self-Service Portal: value not of required type:"
You have a lot of validation rules failed in every object. See in the target directory as described.
So you have missing records.
The solution:
Disable all validation rules that causes exception on data loading.

**Comment by jrattanpal** [comment]
Ok thank you! That column will help as I can see errors now.

**Comment by jrattanpal** [comment]
ANother point that I understand now is not to use "all" for query. While it's super helpful, it causes problem. I am now using a selective query (removing columns based on output in CSVIssuesReport.csv file) and "Error" column in those other objects (if those columns are not needed)

**Comment by hknokh** [comment]
You also can use All but exclude not wanted fields with excludeFields.

**Comment by hknokh** [comment]
And you have some other queries like readonly_false that selects all fields that can be transferred (not readonly) and all available combinations from this [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.1.-Advanced-features.-Field-multiselect.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.1.-Advanced-features.-Field-multiselect.)
