### ISSUE TITLE
[BUG]-Select fields are ignored when using "excludedFields"

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#116]
**Describe the bug**
I have excludedFields for some selects because of errors reports in CSVIssues file. It was complaining about missing fields even though I had not specified those in my select (not "all") statement.

1) Not sure why it still complained about missing fields when those are not in the select statement

2) When I added excluded fields, It only queried some fields and ignored my select statement

For Account, for example, I had the following

{
            "query": "SELECT Id,RecordTypeId,Name,IsPersonAccount,IsDeleted,MasterRecordId,LastName,FirstName,Salutation,Type,ParentId,..... FROM Account",
            "operation": "Upsert",
            "externalId": "Name",
            "master": true,
            "excluded": ["CleanStatus","DunsNumber","Tradestyle","NaicsCode","NaicsDesc","YearStarted","FinServ__ClaimsOnHouseholdPolicies__c","FinServ__HouseholdPolicies__c","FinServ__InsuranceCustomerSince__c","FinServ__TotalClaimAmountPaid__c","FinServ__TotalHouseholdPremiums__c"]
        },

In the CSV file (and that too it made "readonly" for some reason), it returned following fields:
Id,IsPersonAccount,Name

There were no warnings in the log file.

Although, for Contact object, it queried ALL fields. Completely skipped Lead object. And missed fields in FinServ__FinancialAccount__c.

It seems random and I can't see what the pattern maybe. 

**To Reproduce**
Clone: https://github.com/Vchalem/fsc-demo-pack/tree/DataLoad
Run orgInit.sh
Run "export" (need another trial org with data where I am pulling data from)

**Expected behavior**
It should pull all fields and ignore excluded fields.

**export.json**
[export copy.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4838948/export.copy.txt)

**Log file**
[2020-06-26__15_35_45.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4838949/2020-06-26__15_35_45.log)

ALL files: 
[data.zip.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4838953/data.zip.txt)

**Comment by jrattanpal** [comment]
I read the documentation again so maybe I just misread.

I can only use "excludedFields" when using multiselect like "Select all"?

In that case, when I am using selective SELECT, why do I still get warning about "fields missing from CSV but in script"?

**Comment by jrattanpal** [comment]
Ok, so no.

I tried following and it still only returned 3 fields for Account. (Unless I did it wrong)


        {
            "query": "SELECT all FROM Account",
            "operation": "Upsert",
            "externalId": "Name",
            "master": true,
            "excluded": ["CleanStatus","DunsNumber","Tradestyle","NaicsCode","NaicsDesc","YearStarted","FinServ__ClaimsOnHouseholdPolicies__c","FinServ__HouseholdPolicies__c","FinServ__InsuranceCustomerSince__c","FinServ__TotalClaimAmountPaid__c","FinServ__TotalHouseholdPremiums__c"]
        },

**Comment by hknokh** [comment]
Hey,
To exclude fields you should use **"excludedFields"** parameter but not **"exclude**d". excluded = true is to exclude the object from the processing.
Excluded fields working always with a normal query, even not used any multiselect keywords.

**Comment by hknokh** [comment]
Also you have error in the query:
"FinServ__RelatedAccount__cFROM Lead" :   FROM is not divided from previous verb
