### ISSUE TITLE
Attachment and Notes migration question

### ISSUE THREAD

**Issue by geza-mandli** [forcedotcom/SFDX-Data-Move-Utility#121]
Hi, Could you please help me with right configuration to migrate attachments and notes?

I tried to use the following query
"query": "SELECT Id, ParentId$AttachmentTest__c, Title, IsPrivate, Body FROM Note WHERE parent.type = 'AttachmentTest__c'",

1 .Is this query configurable in the desktop app? I could not add ParentId$AttachmentTest__c to query
2. If I did not add the $AttachmentTest__c to the query then it did not find the parent when I tried to migrate the CSV files.

Can you please give me a sample for the right configuration? Is this configurable by the desktop app too?

I have attached my config.

Thanks in advance

[AttachmentsAndNotes.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4850729/AttachmentsAndNotes.zip)

**Comment by hknokh** [comment]
Hello @geza-mandli 
I think,  your configuration  is good.
Answers you questions:
1. The GUI does not reflect the latest plugin changes and has no option of polymorphic fields.
2. Yes. If you will not add the parent object to the polymorphic field the plugin will not able to recognize and to handle the Attachments.
 refer here: 
https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.6.-Advanced-features.-Polymorphic-Lookup-Fields.
To make the polymorphic fields working properly update to v3.4.19
