### ISSUE TITLE
[FEATURE REQUEST]-Parameter on the scriptObject in export.json to control per object whether the source is a salesforce org or a csvfile

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#122]
**Is your feature request related to a problem? Please describe.**
For migration projects, sometimes data comes from other sources than just a source org. In my use case, some of my objects are loaded with CSV files whereas other come from a source org. 

**Describe the solution you'd like**
It would be great to set a parameter on the scriptObject in export.json to control per object whether the source is a salesforce org or a csvfile. This feature would enable the user to load some objects from a source org and other objects from csvfiles in one single run.

As an example, the parameter could look like this:
| Field                         | Data Type | Optional/Default        | Description                                                                                                                |
|-------------------------------|-----------|-------------------------|----------------------------------------------------------------------------------------------------------------------------|
| **ScriptObject**.useSourceCSVFile | Boolean   | Optional, Default false | When set to true and salesforce org is set as data source - It will use `<ObjectName>`.csv file as the source instead of the org. |

**Comment by hknokh2** [comment]
Hello @kevdo475 
Thanks again for the great idea.
It's implemented from the version 4.24.0
In the Documentation:
https://help.sfdmu.com/full-configuration
