### ISSUE TITLE
[BUG]-The plugin does not insert records at all

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/SFDX-Data-Move-Utility#123]
While using the plugin to insert Accounts from file to sandbox, the plugin does not try to insert any Accounts, even though the plugin recognizes their presence in file.

**To Reproduce**
1. Run sfdx sfdmu:run --sourceusername csvfile --targetusername Sandbox --verbose with attached files.
2. No Accounts are inserted.

**Expected behavior**
1. I expected all the new Accounts to be inserted.

**export.json**
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4852972/export.txt)

**Log file**
[2020-06-30__17_42_59.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4852945/2020-06-30__17_42_59.log)

**CSV File**
[Account.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4852949/Account.txt) (saved as txt for purpose of uploading)

I have a feeling there is some very basic mistake in there, can you help me with it? I really tried to strip it to very basic scenario and I just cannot make it work.

**Comment by hknokh** [comment]
Hi, @yahirah 

You have issues with your configuraiton and source csv.

1. For the csv. Never put the header columns in quotes. This is the right spelling:
**Name**
"Test"
"Test12"
"Test13"

2. For the expor.json
You have a misspelled parameter **"operator"**: "Upsert". The correct  one is: **"operation"** : "Upsert"
