### ISSUE TITLE
[BUG]-Wiki has incorrect parameter on 2.2. Full configuration.

### ISSUE THREAD

**Issue by paustint** [forcedotcom/SFDX-Data-Move-Utility#124]
**Describe the bug**
The script object lists the parameter `ScriptObject.deleteOldDatavaluemap`, but this should actually be `ScriptObject.deleteOldData` based on the code in the repo.

```diff
-ScriptObject.deleteOldDatavaluemap
+ScriptObject.deleteOldData
```

https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/c3fcfd2ecf2dee17623544178635b7e745ae4257/src/modules/models/script_models/scriptObject.ts#L56

![image](https://user-images.githubusercontent.com/5461649/86259487-4fa6f480-bb79-11ea-8a35-0ae599014989.png)

**To Reproduce**
N/A

**Expected behavior**
WIKI has accurate properties

**export.json**
N/A

**Log file**
N/A

**Comment by hknokh** [comment]
Thank you, @paustint !
Fixed.
