### ISSUE TITLE
[BUG]-Issues authenticating to an org, but SFDX has no problems using org

### ISSUE THREAD

**Issue by paustint** [forcedotcom/SFDX-Data-Move-Utility#125]
**Describe the bug**
I am having issues authenticating to my SFDX orgs. Is there something I am doing wrong or any way that I can troubleshoot in more detail?

`$` `sfdx sfdmu:run --sourceusername CAREFUL_PRODUCTION_CAREFUL --targetusername csvfile --filelog`
```
Execution of the command sfdmu:run has been started.

=== LOADING AND VALIDATING THE PACKAGE SCRIPT...
Running version: 3.4.19

Connecting to CAREFUL_PRODUCTION_CAREFUL using SFDX CLI...
Command in progress...... done
[ERROR] Command initialization error: Access token to the CAREFUL_PRODUCTION_CAREFUL has expired or the user has no access..
Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
Total time elapsed: 00h 00m 03s 495ms .
```

I can login to the org and run any commands using the regular `sfdx` commands

`$` `sfdx force:data:soql:query -u CAREFUL_PRODUCTION_CAREFUL -q "SELECT Id FROM Account LIMIT 1"`

```
ID
──────────────────
0010L01001z3Ym0QAE
Total number of records retrieved: 1.
```

**To Reproduce**
Run any `sfdx sfdmu:run` command with a valid org (I tried using the alias and username and tried against multiple orgs)

**Expected behavior**
I expected the commands to work correctly with my

**export.json**
No orgs property specified in `export.json`

```
{
  "pollingIntervalMs": 5000,
  "bulkThreshold": 200,
  "alwaysUseRestApiToUpdateRecords": false,
  "apiVersion": 47.0,
  "promptOnMissingParentObjects": true,
  "allOrNone": false,
  "promptOnUpdateError": true,
  "promptOnIssuesInCSVFiles": true,
  "validateCSVFilesOnly": false,
  "createTargetCSVFiles": true,
  "excludeIdsFromCSVFiles": false,
  "bulkApiV1BatchSize": 9500,
  "bulkApiVersion": 2.0,
  "importCSVFilesAsIs": false,
  "fileLog": true,
  "objects": [
...
    ]
}
```

**Log file**
```
[10:14:30.173] Execution of the command sfdmu:run has been started.

[10:14:30.179] LOADING AND VALIDATING THE PACKAGE SCRIPT...
[10:14:30.184] {"Running version":"3.4.19"}

[10:14:30.435] Connecting to CAREFUL_PRODUCTION_CAREFUL using SFDX CLI...
[10:14:33.669][ERROR] Command initialization error: Access token to the CAREFUL_PRODUCTION_CAREFUL has expired or the user has no access..
[10:14:33.670] Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
[10:14:33.670] Total time elapsed: 00h 00m 03s 495ms .
```

**Comment by paustint** [comment]
@hknokh - I think I found the issue. My company restricts logging in from the regular `test.salesforce.com` and instead we have to use our custom domain. Is it possible that this application is not using the Instance Url from sfdx and instead hard-coding the url based on the org type?

**Comment by hknokh** [comment]
@paustint 
When using the SFDX CLI connection flow, the Plugin uses in the background the standard force:org:display command.
You need to provide an org name previously authorized with the SFDX CLI using force:auth:web:login command (for ex.) and you must have an access to the specified org.  In your case I guess you need simply to reauthorize your org with SFDX CLI.

**Comment by paustint** [comment]
@hknokh - The org is listed and authorized using SFDX CLI and shows up when I run `force:org:list` and I can login, run queries, and do everything else with SFDX using the orgs.

When I run `force:org:display -u CAREFUL_PRODUCTION_CAREFUL` I get the org details returned, but I still get an authorization error when trying to use the org with `sfdmu:run`

As I mentioned in the initial description, I can run `sfdx force:data:soql:query -u CAREFUL_PRODUCTION_CAREFUL -q "SELECT Id FROM Account LIMIT 1"` and get results back (which is the same code `sfdmu` uses when confirming an org is authorized.

I looked through the code in this repo a bit more and I can see where you are string parsing the force:org:display and using the instanceUrl, so maybe that it not the auth issue. (though it seems like it would be easier to use the `--json` flag instead of relying on string matching)

Here is the output showing that my org is connected:

`sfdx force:org:display -u CAREFUL_PRODUCTION_CAREFUL --json`

```json
{
  "status": 0,
  "result": {
    "username": "pturner@foo.com",
    "id": "00DE0000000bApIMAU",
    "connectedStatus": "Connected",
    "accessToken": "foo",
    "instanceUrl": "https://foo.my.salesforce.com",
    "clientId": "PlatformCLI",
    "alias": "CAREFUL_PRODUCTION_CAREFUL"
  }
}
```


I even tried to add an entry to the `orgs` array with the accessToken and instanceUrl and it still has an authorization error.

**Comment by hknokh** [comment]
@paustint 
Unfortunatelly I can't help you with your issue. I also use a custom domain for the debugging without any issue and can't reproduce the issue. 
Your case looks  like a something specific and need to be debugged locally, if you can download the source and debug and tell me what to fix, your help would be appreciated. 
Thanks

**Comment by paustint** [comment]
@hknokh - ok, I found the issue and it is a user error mostly, but also a documentation error as well.

The `apiVersion` is listed in the documentation as a `float`, but in reality it is a string that happens to be formatted like a number. I was using `47.0` in my json instead of `"47.0"` and when I debugged I noticed the version number.

It might be worth updating the docs to indicate `apiVersion` is a `string` and not a `number`.

**Comment by hknokh** [comment]
@paustint  Thanks!

**Comment by vijayaditya1** [comment]
@paustint I am also facing the same issue. I tried updating export.json with apiVersion as "49.0" too. Anything else I can do as a workaround?

**Comment by hknokh** [comment]
Hello @vijayaditya1 
This is the right parameter format to be used: string as the number.
I already updated the wiki appropriately:

apiVersion | String (in float format) | Optional / Default "47.0" | API version number to use.
-- | -- | -- | --
