### ISSUE TITLE
Deleting Old Data From Target

### ISSUE THREAD

**Issue by Amit-Tripathi** [forcedotcom/SFDX-Data-Move-Utility#13]
How can we avoid Delete from Target, it seems to always run for me.What am i doing wrong?
Below is my export file:

{
	"objects":[
	
		{
			"query":"Select Name from TestObject1__c",
			"operation": "Insert",
			"deleteOldData": "false",
			"externalId" : "Name"
			
		
		}
	]

}

![image](https://user-images.githubusercontent.com/5682100/78955694-ffeeea80-7aad-11ea-88f7-dc68abc8a84e.png)

**Comment by hknokh** [comment]
Hello @Amit-Tripathi 
Try this: 
"deleteOldData": false
This parameter is boolean an must be used without quotation.
