### ISSUE TITLE
[BUG] - Custom User Lookups are not filled in during insert operation

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/SFDX-Data-Move-Utility#136]
**Describe the bug**
I have custom object with custom Lookup(User) field. It is not filled in when inserting new records. 

**To Reproduce**
1. Prepare CSV files with User and custom object records, that have lookup to user. 
2. All user records should exist in target org.
3. Try to migrate the date consisting of user assignment between csv file and org.

**Expected behavior**
User lookup should be filled in, if matching user is present in the target organization. 

`{
    "promptOnMissingParentObjects": false,
    "promptOnIssuesInCSVFiles": false,
    "bulkApiVersion" : "1.0",
    "bulkApiV1BatchSize": 50,
    "allOrNone" : false,
    "objects": [{
        "query": "SELECT readonly_false  FROM Account",
        "operation": "Upsert",
        "master": true,
        "externalId": "Name"
    }, {
        "query": "SELECT readonly_false  FROM Project__c",
        "operation": "Upsert",
        "externalId": "Project_Code__c",
        "useFieldMapping": true
    },{
        "query": "SELECT readonly_false, Employee_ref__c FROM Project_Member__c",
        "operation": "Upsert",
        "externalId": "External_Id__c",
        "excludedFields": ["sfdc_load_CreatedDate__c", "sfdc_load_External_Id__c","sfdc_load_LastModifiedDate__c"],
        "useFieldMapping": true
    }]`
Logs:
[2020-07-10__11_40_24.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4902924/2020-07-10__11_40_24.log)

**Comment by yahirah** [comment]
So I figured out that I need to add UserAndGroup.csv file when working with csvfiles. The same goes for RecordTypeId - new file is necessary. Can this info be added to documentation for future users?

**Comment by hknokh** [comment]
Hello, You are right.
You need to add ALL source files including RecordType and UserAndGroup.csv into the source CSV package.
Because the Plugin considers the CSV source files exactly like the Org source that has those records present.
I will add the mentioned considerations in the doc.

**Comment by skostojohn** [comment]
I am having this same issue, but not using CSV files.  Trying to migrate a custom object from one org to another, and the custom user lookup fields are not populating, even when the user is in both environments with the same Id value.

Any advice?

Thank you!

**Comment by hknokh** [comment]
Hello @skostojohn 
Please, open an issue by providing all necessary files as described in the OPEN NEW CASE GUIDELINES.
