### ISSUE TITLE
[FEATURE REQUEST]-Add run flag or export file flag to truncate too long fields

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#138]
**Is your feature request related to a problem? Please describe.**
During data loads, sometimes a field might contain too many characters. The error message received looks like this:
```
STRING_TOO_LONG:Description: data value too large
```

**Describe the solution you'd like**
In the standard salesforce data loader, there's an option to allow field truncation. This is listed with the following description:
https://help.salesforce.com/articleView?id=configuring_the_data_loader.htm&type=5
Allow field truncation | Select this option to truncate data in the following types of fields when loading that data into Salesforce: Email, Multi-select Picklist, Phone, Picklist, Text, and Text (Encrypted).In Data Loader versions 14.0 and earlier, Data Loader truncates values for fields of those types if they are too large. In Data Loader version 15.0 and later, the load operation fails if a value is specified that is too large.Selecting this option allows you to specify that the previous behavior, truncation, be used instead of the new behavior in Data Loader versions 15.0 and later. This option is selected by default and has no effect in versions 14.0 and earlier.This option is not available if the Use Bulk API option is selected. In that case, the load operation fails for the row if a value is specified that is too large for the field.
-- | --

A similar feature would be handy in sfdmu!

**Comment by hknokh** [comment]
Hi @kevdo475 
It's implemented, added AllowFieldTruncation parameter to the script
