### ISSUE TITLE
[BUG]-Upsert product hierarchy does not use external id in parent relation

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/SFDX-Data-Move-Utility#144]
**Describe the bug**
I have a hierarchy of Product2, related through a relation field call Pack__c (of type Product2).
I want to upsert products, using the field IDEXT__c as an external id.
SFDMU should identify the relationship towards parent with Pack__r.IDEXT__c, but it is using Pack__r.Name : this will not work if multiple parent products have the same name.

**To Reproduce**
Create  products called the same Product Name : 
- ProductCode = 'parent1', ProductName = 'parent', IDEXT__c = 'parent 1'
- ProductCode = 'parent2', ProductName = 'parent', IDEXT__c = 'parent 2'
- ProductCode = 'son', ProductName = 'son', IDEXT__c = 'son', Pack__c = points to parent1

Create export.json : 
{
        {
            "query": "SELECT Id, Name, ProductCode, IDEXT__c, Pack__c FROM PRODUCT2",
            "operation": "Upsert",
            "externalId": "IDEXT__c"
        },
}

Export from source.  Import to destination.

**Expected behavior**
3 products should upsert correctly.

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**Comment by AltiusRupert** [comment]
logfile : 
WARNING: [WARN] {PRODUCT2} 1 missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details.

MissingParentRecordsReport.csv : 
Date update,Id,Child ExternalId,Child lookup,Child SObject,**Missing value**,Parent ExternalId,Parent SObject
2020-07-15  18:55:57.745,01t1r000008N936AAC,Pack__r.Name,Pack__c,PRODUCT2,**prod**,Name,Product2

"Missing value" is actually not missing, but duplicate

**Comment by AltiusRupert** [comment]
I just noticed that this issue is also present with a different child object, eg ProductToProductRelation__c with 2 lookups to Product.
In each case, the relationships foreign key used is the Name field of the Product, and not the IDEXT__c field.

**Comment by hknokh** [comment]
Hello, @AltiusRupert 
Can't reporduce.
I've tested exactly in your configuration and data and it working perfectly and assigns the parent 1 to son as per IDEXT__c
{
 "objects": [
        {
            "operation": "Upsert",
            "externalId": "IDEXT__c",            
            "master": true,
            "query": "SELECT Id, ProductCode, Name, Pack__c, IDEXT__c FROM Product2 WHERE Name IN ('parent','son')"
        }
  ]
}

Of course you should use the latest version of the Plugin 3.5.5
Check if the field IDEXT__c is writeable, check the script spelling.

**Comment by hknokh** [comment]
I think the issue is the name of the Product2 object in the query: PRODUCT2.
You need to specify object name and the object fields **exactly**, it is **case sensitive**.

**Comment by AltiusRupert** [comment]
Hi @hknokh , thanks for the answer and the fix.
What is the reason for this constraint ?  I do not think that it is a Salesforce constraint. Can I help relieve the constraint in the plugin, by contributing ?

**Comment by hknokh** [comment]
Hi @AltiusRupert 
Thanks for the readiness to contribute, but it so far is not necessary.
I can't explain you briefly the reason, because it is pretty complex. The SOQL used here in another way then in the Salesforce it seld. The constraint is a part of the Plugin User Guide and I left it on the responsibility of the End User.

**Comment by AltiusRupert** [comment]
I'm familiar with SFDX CLI plugin development, have made a private plugin for some internal stuff for our company.
If you provide a pointer, I can take a look from there and tell you if I can help.

**Comment by hknokh** [comment]
I understand you. Thank you again, and I sure that you will do it according to the best practices, but still I would prefer to dial with my Plugin myself.
In this case technically no problem to do this, but it requires additional time and it is not so necessary for my opinion to spend time on it. This is my stance about  this subject.

**Comment by AltiusRupert** [comment]
OK, I understand.

**Comment by hknokh** [comment]
See, you are right... please, open a  feature request for this, I will put it on the development queue

**Comment by hknokh** [comment]
@AltiusRupert 
Thanks for your suggestion! 
This feature really can be useful. I've opened a feature request and added the job to the milestone:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/146
