### ISSUE TITLE
[FEATURE REQUEST]-Enhancement to explain which records are in error

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/SFDX-Data-Move-Utility#145]
**Is your feature request related to a problem? Please describe.**

Here is an example of a Product insert operation :
`[Job# 7503O000003r1vMQAQ:Insert] {Product2} The job has been created. Uploading data...
[Batch# 7503O000003r1vMQAQ:Insert] {Product2} The batch has been created. Uploading data...
[Batch# 7503O000003r1vMQAQ:Insert] {Product2} Processing... 200 records succeeded, 3 records failed.
[Batch# 7503O000003r1vMQAQ:Insert] {Product2} Processing... 600 records succeeded, 3 records failed.
[Batch# 7503O000003r1vMQAQ:Insert] {Product2} Processing... 785 records succeeded, 5 records failed.
WARNING: [WARN] [Batch# **7503O000003r1vMQAQ:Insert**] {Product2} Incompleted. 785 records succeeded, 5 records failed.
{Product2} The Insert API operation has been finished.
`

When I look at the Bulk Data Load Job 7503O000003r1vM, I see that 5 records are in error, but I cannot see which records because the "View results" column is empty

![image](https://user-images.githubusercontent.com/33985/87699713-8e51c700-c795-11ea-923f-5546210d0f48.png)

**Describe the solution you'd like**

I would like a way : 
- either to be able to view records in error in the Salesforce Bulk Data Load Job
- either find a log file 7503O000003r1vM.log stored locally, which details these errors

**Comment by hknokh** [comment]
Hello @AltiusRupert 
You have such report in target directory
please refer: [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/5.-Reports.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/5.-Reports.)

**Comment by AltiusRupert** [comment]
Oops, thanks :)
