### ISSUE TITLE
[BUG]- some valid SOQL syntax is not accepted

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/SFDX-Data-Move-Utility#147]
**Describe the bug**
I want to specify a complex WHERE clause, with ANDs and ORs.
I have discovered that the simple clause
`WHERE (ProductCode='ASSEQP' AND LastModifiedDate=TODAY)`
with parentheses, which is valid, generates an error, when the other valid syntax
`WHERE ProductCode='ASSEQP' AND LastModifiedDate=TODAY`
is accepted.

The consequence is that it makes it impossible to export 
`WHERE (ProductCode='ASSEQP' AND LastModifiedDate=TODAY) OR CreatedDate=TODAY`
which is a valid clause but generates the same error.

**To Reproduce**
Export data from source with the following export.json

**Expected behavior**
Should succeed without an error.

**export.json**
        {
            "query": "SELECT Id, Name, ProductCode FROM Product2 WHERE (ProductCode IN ('ASSEQP') AND LastModifiedDate=TODAY)",
            "operation": "Upsert",
            "externalId": "Tech_ExtKey__c"
        }

**Log file**
[ERROR] Error during execution of the command: line 1:121 extraneous input ')' expecting {<EOF>, GROUP, LIMIT, WITH, FOR, UPDATE, OFFSET, ORDER}.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).

**Comment by hknokh** [comment]
Hello, @AltiusRupert 
I guess the problem not with the parentheses but with the TODAY keyword that is not supported by the js soql parser library,  that I am using. I will check it.
Could you please attach the whole .log file?

**Comment by hknokh** [comment]
Hello @AltiusRupert 
The issue has been solved.
Please, update to v3.5.6 and retry
