### ISSUE TITLE
Undefined Error for Optional Lookup Relationships with Composite External Ids

### ISSUE THREAD

**Issue by brentrahn** [forcedotcom/SFDX-Data-Move-Utility#15]
Hello,

I'm running into an issue with "undefined" parent lookup external Ids when using multiple external Ids on the parent. It appears that the application is trying to evaluate the composite key of the parent, even when the parent lookup is not populated. 
![Blank Diagram (1)](https://user-images.githubusercontent.com/1413072/81130482-be126200-8efc-11ea-9eb9-6d9efa5af7f7.png)
Consider the above object model.

Assumptions:

1. Parent__c on Child_Object__c is an optional lookup field.
2. Some Child_Object__c records have Parent__c populated, others do not. 
3. Both Parent_Object__c and Child_Object__c are included in the data migration.
4. ExternalId for Parent_Object__c has been set to ```Key1__c;Key2__c```

Child_Object__c records that do not have a value populated for Parent__c will produce the following line in MissingParentRecordsReport.csv:

Child sObject | Child external Id field | Parent external Id field | Parent sObject | Missing external Id value
------- | ----------- | ----------- | ------------- | -------------
Child_Object__c | Parent__r.$$Key1__c$Key2__c | $$Key1__c$Key2__c | Parent_Object__c | ;undefined;undefined

Obviously, a workaround would be doing two loads and filtering the one with the parent object included by the parent lookup being populated, but it seemed like this behavior was not intentional. If the lookup is null on the source, it should remain so on the target.

**Comment by hknokh** [comment]
Hello,
Should be fixed, please recheck

**Comment by hknokh** [comment]
But keep in mind to reinstall the tool before retry

**Comment by brentrahn** [comment]
Looks like it works! Thank you for the quick turnaround and your work on this tool!
