### ISSUE TITLE
[BUG]-SOQL Error when using subquery WHERE Clause

### ISSUE THREAD

**Issue by kableeth** [forcedotcom/SFDX-Data-Move-Utility#151]
**Describe the bug**
The following query works in Salesforce Query Editor without error, but when I use it as a query parameter in export.json I receive the following error.

SOQL Query
```"SELECT Name FROM Account WHERE Id IN (SELECT Account__c FROM Scheduling__c WHERE CreatedDate = LAST_N_DAYS:30)"```

Error
```[ERROR] Error during execution of the command:
FROM Account WHERE Id IN (SELECT Account__c FROM Scheduling__c WHERE
                                 ^
ERROR at Row:1:Column:50
No such column 'Account__c' on entity 'Scheduling__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call 
for the appropriate names..
```

**To Reproduce**
I tried to make this reproducible with a subquery of a standard object, but it works fine. However it will not work with my custom Scheduling__c object

**Expected behavior**
The error should not occur

**export.json**

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4950473/export.txt)

**Log file**
[2020-07-20__18_20_47.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4950474/2020-07-20__18_20_47.log)

**Comment by hknokh** [comment]
Hello, you have typo in the subquery in your export.json.
Instead of writing Account__c you have witten Account that is not the existing custom field on the object Scheduling and it is missing.

**Comment by kableeth** [comment]
Hi, the log file I had attached was from me trying to troubleshoot without the "__c". I just attached the log where I tried it with "__c" and still received the same error. Really appreciate
[2020-07-20__21_48_52.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4951014/2020-07-20__21_48_52.log)
 the help!

**Comment by hknokh** [comment]
Hello, @kableeth 
If so, it's really weird (:, but again, I only can say, that this error (I say it on the basis of the error message) - has returned directly **from the Salesforce API**, it's not a runtime error of the Plugin, so please ensure that you have this field in the both (Source and Target) envs in the Schedule object. 
If the issue didn't go away, I would suggest to try cloning the source and to debug on your local machine and to tell me your findings.
Thanks.

**Comment by kableeth** [comment]
It was a permissions issue :-(. Somehow the object didn't have permissions even though I was using system admin profile. Once I applied permissions to the object for System Admin profile it worked.
