### ISSUE TITLE
[FEATURE REQUEST]-Configuration-Windows

### ISSUE THREAD

**Issue by thomasmilleratosnet** [forcedotcom/SFDX-Data-Move-Utility#153]
On my company laptop the Documents folder is synced with OneDrive and hence under Windows Information Protection (i.e. the files are marked as business and ediatable only by registered applications). Hence the SFDMU GUI app cannot write into it and fails. I got it working by temporarily stopping sync for the Documents folder but that's not a permanent solution.
It would be helpful to allow configuring where the SFDMU folder is stored.

**Comment by hknokh** [comment]
Hello @thomasmilleratosnet 
Currently I'm working on the completelly new version of the GUI App and I will add this to the development path.
Thanks for the suggestion.
