### ISSUE TITLE
Installation failure with either option

### ISSUE THREAD

**Issue by krusty7** [forcedotcom/SFDX-Data-Move-Utility#155]
**Installation using plugin install command:**

sfdx plugins:install sfdmu
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning sfdmu > deep.clone@2.1.2: No longer maintained. Moved to https://npm.im/@reallyland/node_mod.
warning sfdmu > @salesforce/core > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning sfdmu > alasql > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdmu > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
/Users/adam/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/yarn/lib/cli.js:78722
    compromised = compromised || function (err) { throw err; };
                                                  ^

Error: Unable to update lock within the stale threshold
    at /Users/adam/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/yarn/lib/cli.js:78644:66
    at FSReqCallback.oncomplete (fs.js:146:23) {
  code: 'ECOMPROMISED'
}
Installing plugin sfdmu... !
Error: yarn add sfdmu@latest --non-interactive --mutex=file:/Users/adam/.local/share/sfdx/yarn.lock --preferred-cache-folder=/Users/adam/Library/Caches/sfdx/yarn --check-files exited with code 1
    at ChildProcess.<anonymous> (~/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

**Installation using source - fails at npm install step as follows:**

npm install
npm WARN deprecated deep.clone@2.1.2: No longer maintained. Moved to https://npm.im/@reallyland/node_mod.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> dtrace-provider@0.6.0 install /Development/sf_dev/SFDX-Data-Move-Utility/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
npm notice created a lockfile as package-lock.json. You should commit this file.
added 761 packages from 1298 contributors and audited 771 packages in 246.22s

26 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (8 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by hknokh** [comment]
Hello, @krusty7 
Unfortunatelly can't reproduce your issue.
Right now I tried to reinstall the plugin and it's succeeded.
See screenshot attached
![Uploading 12333.jpg…](Uploading 12333.jpg)
Looks like the issue with yarn/npm.  Anyway this what need to be investigated directly on your machine and not depend to the plugin installation process itself.

**Comment by hknokh** [comment]
![12333](https://user-images.githubusercontent.com/15181301/89187968-abb0ce80-d5a6-11ea-813f-9c6080c0c528.jpg)

**Comment by krusty7** [comment]
Hi thanks for looking - i wondered if it was because some of the dependent install/libraries were first time installs for me as not used this plugin before and maybe most, yourself included were generally updating versions as opposed to starting from new.
i'll see what i can find locally.
