### ISSUE TITLE
[FEATURE REQUEST]-Easy way to exclude compound fields.

### ISSUE THREAD

**Issue by prescod** [forcedotcom/SFDX-Data-Move-Utility#156]
**Is your feature request related to a problem? Please describe.**

Consider a simple config file like this:

```
{
    "objects": [
        {
            "query": "SELECT all FROM Account",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT all FROM Contact",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}
```

It will fail with the following error:

```
[ERROR] Error during execution of the command: InvalidBatch : Failed to process query: FUNCTIONALITY_NOT_ENABLED: Selecting compound data not supported in Bulk Query.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
```

**Describe the solution you'd like**

I think that "all" should include only fields which will not cause an error with Salesforce.

Changing the `all` to `createable_true` did not help but `updateable_true` looks like it may be a workaround? It's still running....

**Comment by hknokh** [comment]
Hello,  @prescod 
to exclude certain unwanted fields when using multiselect keywords you can use ScriptObject.excludedFields option.
See [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.)
The plugin could not automatically recognize what fields are necessary or valid, so it's on the user's responsibility depend on each org configuration.
