### ISSUE TITLE
[BUG]-The Record Type is not set up correctly when imported from CSV

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/SFDX-Data-Move-Utility#164]
**Describe the bug**
When importing from CSV files to sandbox, record type id is not set up correctly. I assume something is wrong with the name/content of RecordType.csv file? What should be there?

**To Reproduce**
1. Prepare file with desired objects and recordtypeid column.
1. Prepare RecordType.csv file, consisting of Id, Name, SObjectType.
1. Try importing the file. 
1. Result: record type id is not set and is not present in neither target or source files.

**Expected behavior**
1. Record Type is correctly set on created/updated record.

**Comment by hknokh** [comment]
Hello, 
the correct columns for the RT csv are:
Id,**DeveloperName**,SobjectType
