### ISSUE TITLE
[HELP]-Is GUI App Being Updated with these fixes?

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#166]
I see a number of recent commits to this app but not so for related GUI application. We are getting GUI to connect and update metadata for Production and Sandbox org but not scratch org. Tried killing the node processes, multiple times, as the docs suggest. Also updated and restarted CLI, multiple times. App says it's connected to org but it doesn't give me the CLI Permission dialog box like I might expect. When move to 2nd step error says not connected to scratch org.

**Comment by hknokh** [comment]
Hello, 
Currently I'm working on the completelly new GUI App and it should be released very soon. That is why I stopped supporting the old App. The new version should include a large amount of improvements and fixes. 
Continue following the repo updates.

**Comment by hknokh** [comment]
As a spoiler, the new GUI will not contain any more the built in feature to connect to the orgs. Instead it has a button to retrieve the list of the currently connected sfdx orgs (the app uses force:org:list command  for this purpose) and the user will select from the existing connected orgs. So all responsibility of org authentication will be on the sfdx platform, not on the app any more.

**Comment by hknokh** [comment]
FYI @veaux 
I've released the new version of the GUI Application.
You can try it, hope it will be free from the issues you've faced before.

**Comment by veaux** [comment]
Thank you for the notice @hknokh. After you said the GUI was being redone I spent some time learning/configuring the JSON data move files and putting into a script so I'm probably not going to use the GUI at this point. I'll keep it in mind though for some quick projects that might come up.
