### ISSUE TITLE
[FEATURE REQUEST] - Access Token validation requires READ access on Account sObject

### ISSUE THREAD

**Issue by zerkz** [forcedotcom/SFDX-Data-Move-Utility#167]
### **Describe the Enhancement**
Access to `Account.Id` is required to validate an access token. This seems a bit faulty for Orgs that do not give out Account access. The tool is amazing and useful for all kinds of objects. 

https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/models/script_models/scriptOrg.ts#L106-L107

**To Reproduce**
Try to do any sort of SFDX data command with a source org where you do not have access to `Account`. 

Get a message saying your `Access token to the sourceOrg has expired or the user has no access..`

**Expected behavior**
I would expect no sObject access be assumed to validate an access token. I will research alternatives and post them as suggestions on this issue. Should I find one that makes sense, I will post a pull request! 

**export.json**
N/A

**Log file**
N/A

Thank you for this tool!

**Comment by hknokh** [comment]
Hello, @zerkz 
Thanks for the positive feedback and for the suggestion! Great to hear, that you found the Tool helpful!
I was basing my assumption on, that normally Account is the most common sobject, which every user profile has at least a read 
access to it.  I would just be curious to know in which case user that allowed to access other sobjects can be blocked from accessing to Account ? This is first time that I facing such use case.
For now have no idea how to validate access token without accessing any object. I also need to check this from my side if any alternative approach is there.

**Comment by zerkz** [comment]
@hknokh 

Thanks for your quick reply! I work for a pretty large org and  while we do have account objects, we do not make use of them too often. the majority of our stuff is custom. 

I haven't verified this yet -- but i assume that `User.Id` might be a  "always readable" value for any User on the salesforce platform.  Will have to investigate. 

Maybe could do something like `Select Id  from User where UserName = ${orgUserName}`? (JS template string).

**Comment by hknokh** [comment]
@zerkz 
Seems that your idea is working.
Implemented in the latest v3.6.0
Please retest

**Comment by gidglass** [comment]
@hknokh - FYI, after updating the plugin to latest version this morning I started getting the following error:
```
[ERROR] Command initialization error: Access token to the sourceOrg has expired or the user has no access..
```

**Comment by zerkz** [comment]
@gidglass are you able to debug the plugin or maybe execute the query via SFDX directly (the new "user" query for the access token check)? 

your access token could also be expired, but this is one way to check. I would be very surprised if you can't see/access `Id` on `User`, but maybe its possible?

**Comment by gidglass** [comment]
@zerkz I've confirmed I do 100% have access (made the query directly) - will debug a little more. Also confirmed that access tokens are still valid. I even re-authenticated just to be sure...

**Comment by zerkz** [comment]
ahh! We could do `Select Id from User LIMIT 1` -- i do not believe there is any sort of `User` sharing from my knowledge.

**Comment by gidglass** [comment]
@zerkz - The full username is captured by the plugin in a variable named `userName` (see `src/modules/models/script_models/scriptOrg.ts` line 152). The above query just needs to be fixed to reference that variable (or assign the value to `orgUserName` if that is preferred. 

It runs smoothly once that is done 👍

**Comment by hknokh** [comment]
@zerkz  @gidglass 
Thanks for the contribution!
Yeap, this just an annoying typo.... userName / orgUserName.
I uploaded the patch. Please retry.

**Comment by gidglass** [comment]
@hknokh - working fine now. Thanks!
