### ISSUE TITLE
[BUG]-Cannot connect to an org

### ISSUE THREAD

**Issue by 0cv** [forcedotcom/SFDX-Data-Move-Utility#175]
**Describe the bug**
The authentication does not seem to work using the UI

**To Reproduce**
I picked up "CSV" for the source, then selected an org, then click next and gets the error message:

![image](https://user-images.githubusercontent.com/1253866/92576017-4af17180-f289-11ea-89aa-e3afcb5a2136.png)

The authentication for that org works in VSCode. I also made sure to refresh the access token by logging in before executing the "next" command in the UI.

**export.json**
Not sure where it is

**Log file**
Not sure where it is

Additional information:
Running on the latest version of OSX, latest version of sfdx (7.73.2-feef087df8). I installed `SFDX-Data-Move-Utility` and `SFDX-Data-Move-Utility-Desktop-App` from the Github repo.

**Comment by hknokh** [comment]
Hello, @0cv 
Does your user have an access to Account object ?

**Comment by 0cv** [comment]
@hknokh yes, it's a system admin user. I tried both production, and non-production account resulting in the same issue

**Comment by hknokh** [comment]
Also please go to test sfdx command tab and perform org:list or org:display for the selected envs. Do you have correct output ?

**Comment by 0cv** [comment]
Half. `org:list` works, but by clicking on `run force:org:display`:
![image](https://user-images.githubusercontent.com/1253866/92582965-f0a8de80-f291-11ea-8d3e-73c696faf350.png)

**Comment by hknokh** [comment]
Can you try org:display with your org alias directly in the Terminal/Console. 
What do you get ?

**Comment by 0cv** [comment]
hah thank you! org:display was returning both an error, and a success. A success for the alias I was querying and a error, unrelated, but because one of my (many) alias was not valid anymore. It was unrelated but it was still throwing an error in the SFDX tooling. And I suppose that the Data Move Utility was not handling this situation:
![image](https://user-images.githubusercontent.com/1253866/92594078-8f3d3b80-f2a2-11ea-87a9-cbf02bf50176.png)

By deleting (in ~/.sfdx/) my alias which was outdated, it removed as well the error message in the terminal, and I can now click on the `next` button. Closing the issue

**Comment by hknokh** [comment]
Yes... the tool need a clean command line output)
