### ISSUE TITLE
[BUG]-Contact fields on Person Account not loaded

### ISSUE THREAD

**Issue by programmel** [forcedotcom/SFDX-Data-Move-Utility#176]
**Describe the bug**
When extracting person accounts from a source org, then the recordtype is set correctly. However, fields that resides on the contact are not transferred.

**To Reproduce**
1. Create custom field on contact "CPR__c" (e.g. Text).
2. Create a Person Account in source org with the fields CPR__pc and PersonEmail filled.
3. Run sfdmu with configuration.
4. CPR__pc and PersonEmail are blank in target org.

**Expected behavior**
PersonAccount is identical on selected Contact-fields (CPR__pc, PersonEmail) in target org.

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5201484/export.json.txt)

**Log file**
[2020-09-10__14_01_44.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5201499/2020-09-10__14_01_44.log)

**Comment by hknokh** [comment]
Hello @programmel 
The configuration seems incorrect for your purpose.
1) Incorrect usage of Record type lookup.
2) Missing Contact object as the slave (child) object.
All objects that you want to move need to be specified explicitly, even for Person Contacts.

Try this:
{
    "objects": [
        {
            "query": "SELECT FirstName, LastName, CPR__pc, PersonEmail,  **RecordTypeId** FROM Account WHERE Party_Id__c IN ('181009E')",
            "operation": "Insert"
       },
       {
             "query": "SELECT  FirstName, LastName, **AccountId**  FROM Contact",
            "operation": "Insert",
            **"master": false**
       }
    ]
}

**Comment by programmel** [comment]
Hi @hknokh 

Thanks for looking at it, but the values are still not copied to the contact fields (CPR, Email). I also tried below but with no luck :/

{
	"objects": [
		{
			"query": "SELECT **Id**, FirstName, LastName, CPR__pc, PersonEmail, RecordTypeId FROM Account WHERE Party_Id__c IN ('181009E')",
			"operation": "Insert"
		},
		{
			"query": "SELECT FirstName, LastName, AccountId, **CPR__c, Email** FROM Contact",
			"operation": "Insert",
			"master": false
		}
	]
}

**Comment by hknokh** [comment]
Are you sure that the account records you filtered by the where clause are person accounts?)

**Comment by hknokh** [comment]
Also maybe need to involve AccountContactRelation

**Comment by programmel** [comment]
Yes, should be - IsPersonAccount is True :)

I did not find any relations via AccountContactRelation in the source org, but tried below config with no luck.

I am not familiar with the internals of sfdmu, but it puzzles me a bit why it identifies 7 contacts for the target org (may not be related to the issue here, though).

=== GETTING THE TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY...
{RecordType} Total amount of the SOURCE records: 9
{RecordType} Total amount of the TARGET records: 9
{Account} Total amount of the SOURCE records: 1
{Account} Total amount of the TARGET records: 0
{Contact} Total amount of the SOURCE records: 94681
{Contact} Total amount of the TARGET records: 7
{AccountContactRelation} Total amount of the SOURCE records: 25175
{AccountContactRelation} Total amount of the TARGET records: 0


== export.json
{
	"objects": [
		{
			"query": "SELECT Id, FirstName, LastName, CPR__pc, PersonEmail, RecordTypeId FROM Account WHERE Party_Id__c IN ('181009E')",
			"operation": "Insert"
		},
		{
			"query": "SELECT FirstName, LastName, AccountId, CPR__c, Email FROM Contact",
			"operation": "Insert",
			"master": false
        },
        {
            "query": "SELECT AccountId, ContactId FROM AccountContactRelation",
            "operation": "Insert",
            "master": false
        }
	]
}

**Comment by hknokh** [comment]
Hello @programmel 

First of all, a little explanation for the puzzles )

The 7 TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY is simple the result of the following query:
**SELECT COUNT() FROM Contact** You have 7 contacts in your Target.
But be aware that this **does not say that you will have for sure 7 record updated in the target.**!
This number is for overall indication. The plugin will also filter the records by the dependecies between objects when master=false. So, don't rely on this number. 
You can run the query above from the developer console of the target org to verify the total records amount.

Second, please try the following.
Change the query to:
SELECT Id, FirstName, LastName, CPR__pc, PersonEmail, RecordTypeId FROM Account WHERE Party_Id__c IN ('181009E') **AND IsPersonAccount = true**
- and tell me how many records appear in the section of TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY.

Thx.

**Comment by programmel** [comment]
=== GETTING THE TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY...
{RecordType} Total amount of the SOURCE records: 9
{RecordType} Total amount of the TARGET records: 9
{Account} Total amount of the SOURCE records: 1
{Account} Total amount of the TARGET records: 0
{Contact} Total amount of the SOURCE records: 94688
{Contact} Total amount of the TARGET records: 7
{AccountContactRelation} Total amount of the SOURCE records: 25184
{AccountContactRelation} Total amount of the TARGET records: 0

**Comment by programmel** [comment]
Hi @hknokh Did you have a chance to look at this? Thanks!

**Comment by hknokh** [comment]
Hello, sorry, forgot about your case because it was closed. Reopened for review.

**Comment by hknokh** [comment]
Can you please make the additional checks :

- Check that CPR__c is both updateable / creatable for your profile.

- You should find a csv file named something like Account_insert_[person]_target.csv that has to be created by the plugin in the /target directory. Check if CPR__pc is included in the csv columns.

**Comment by programmel** [comment]
Hi @hknokh, sorry for the late reply.

Yes, CPR__c is both updateble and createable for my profile. I can also do an insert via the API with the same data as sfdmu reads from target.

CPR__pc does not exists in target/Account_insert_person_target.csv (header line is: FirstName,LastName,RecordTypeId,Errors,Id). It is also the only file in target/ (no contact file).

**Comment by hknokh** [comment]
Ok, that's says that CPR__pc is not recognized by the plugin as an updateable field...
I don't know, why. Do you have an option to debug the process ? 
Or maybe you want to give me an access to a scratch org where I can reporduce the issue ?

**Comment by programmel** [comment]
Sorry, can't give you access to the scratch org. I don't mind to debug the process - can you provide a few pointers to have I set it up, and what to look for?

**Comment by hknokh** [comment]
I checked on my org for the updating the __pc fields. 
Didn't reproduce this in any case. It working good on my side. I still think about the permission issue on your side.
Sorry, but again, this kind of error that need to be debugged or reproduced on the client end.

**Comment by programmel** [comment]
Thanks, for checking. Is it possible that you can upload your working configuration? Then I can create the same fields, and also verify that I have not overlooked something subtle.

**Comment by hknokh** [comment]
Ok, I will rerun the check and provide you with the results.

**Comment by hknokh** [comment]
Hello @programmel 
After rechecking I found bug regarding the update of __pc fields.

Update to 3.7.4 and try the following coniguration:

{
     "objects": [
      {
          "query": "SELECT FirstName, LastName, CPR__pc, PersonEmail, RecordTypeId FROM Account WHERE Party_Id__c IN ('181009E')",
         "operation": "Insert"
      }
   ]
}

No need to include Contact object.

**Comment by programmel** [comment]
Perfect. Verified - works! Thanks :)
