### ISSUE TITLE
[BUG]-platform-folders doesn't install 

### ISSUE THREAD

**Issue by prdpklyn** [forcedotcom/SFDX-Data-Move-Utility#178]
**Describe the bug**
When trying to install the desktop-app the installation fails with the following error

```
> platform-folders@0.5.1 install C:\code\salesforce\SFDX-Data-Move-Utility-Desktop-App\node_modules\platform-folders
> node-gyp rebuild


C:\code\salesforce\SFDX-Data-Move-Utility-Desktop-App\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
gyp ERR! stack     at TLSSocket.emit (events.js:223:5)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:794:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\code\salesforce\SFDX-Data-Move-Utility-Desktop-App\node_modules\platform-folders
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! platform-folders@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the platform-folders@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```
**To Reproduce**
Describe steps to reproduce the behavior.

clone repo and run npm install

**Expected behavior**

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.
[2020-09-10T18_42_11_311Z-debug.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5204045/2020-09-10T18_42_11_311Z-debug.log)

**Comment by hknokh** [comment]
Hi, please  reinstall, looks like an installation issue.

**Comment by hknokh** [comment]
Maybe a general nodejs platform issue on your local machine, anyway it's not something that depend on the application itself.

**Comment by prdpklyn** [comment]
Hi @hknokh, I tried both on mac and windows before opening a ticket, It the same error. I'm not behind any proxy 

I tired cloning the platform-folders to my local machine so I can add a local dependency. It is not installing

**Comment by hknokh** [comment]
Ok, weird, need to check...

3 questions.

What is your nodejs version?

Only this dependency is peoblematic?

After adding local droendency does the app start?

**Comment by prdpklyn** [comment]
node version 12.4.x  

yes, only platform-folders dependency is the only issue and it does not work with local dependency either.

I see the package is used to getDesktopFolder . Apart from the desktop folder, Is it used elsewhere? 

I can try to update my local base and exclude the package.

**Comment by hknokh** [comment]
Tried to reinstall it on my nachine from scratch the installation is is working fine.
See screenshot.  Please check your environment.
I also found the similar issue:
https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate
![istallation-screebshot](https://user-images.githubusercontent.com/15181301/92861306-02a98f00-f402-11ea-9c19-427133683e7b.png)

**Comment by prdpklyn** [comment]
It's a great tool! thank you for making it open source
