### ISSUE TITLE
[BUG] 1950 mismatched input 'OIL' expecting ')' SOQL Error

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#185]
**Describe the bug**
Got error on un-escaped character: 1950 mismatched input 'OIL' expecting ')'. 

**To Reproduce**
Setup an object where e.g. the Name column (used as External Id) has data including parenthesis. 

**Expected behavior**
Values in SOQL Strings should be escaped.

**export.json**

**Log file**
`[15:00:38.990] {ccrz__E_Product__c} Query string: SELECT Id, Name  FROM  ccrz__E_Product__c WHERE Name IN ('HIBISCUS FLAVOUR L-129227', 'BRANDY FLAVOUR QL13940', 'CHERRY FLV L-129588', 'MELON P300 FLV QL91428', 'ROAST BEEF FLAV CSF 1.04.41/K', 'RASPBERRY US151 FLV PHS-218169', 'VANILLA FLAVOUR L-034272', 'CHICKEN POACHED....
[15:00:39.60][ERROR] Error during execution of the command: line 1:1950 mismatched input 'OIL' expecting ')'.
[15:00:39.61] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).`

**Comment by hknokh** [comment]
@JeroenSfdc 
Looks like something is happening with quotes in the Name field.  Try to verify and to escape required symbols.

**Comment by JeroenSfdc** [comment]
Hi @hknokh the `Name` column indeed can hold quotes; but that shouldn't be a problem right?

**Comment by hknokh** [comment]
Hello @JeroenSfdc 
I will check this and update you

**Comment by hknokh** [comment]
@JeroenSfdc 

I re-checked. The values are already being escaped in the code when constructing the query.
But it was replacing only the first occurence of quote in the name.
Shoud work now, please retry.
