### ISSUE TITLE
[BUG] Bad Message 414 reason: URI Too Long using virtual ExternalId

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#189]
**Describe the bug**
Configured a virtual ExternalId. While executing it throws a `URI Too Long` error. 

**To Reproduce**
Create a significantly long virtual ExternalId like

`SBQQ__Quote__r.SBQQ__Account__r.IntegrationId__c;SBQQ__Quote__r.SBQQ__Key__c;SBQQ__Product__r.FullSegmentsNumber__c;Quant__c;UOM__c;SBQQ__Quote__r.IncoTerms2__c;CurrencyIsoCode`

**Expected behavior**
No error

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5221066/export.json.txt)

**Log file**
[2020-09-14__23_05_37.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5221067/2020-09-14__23_05_37.log)

**Comment by hknokh** [comment]
Hello @JeroenSfdc 
This issue seems touching the normal limitation of the REST API and I can't provide significal solution. 
For extermely long external ids, please create a standard formula field to use as ExtgernalId instead.

**Comment by JeroenSfdc** [comment]
Hi @hknokh this is not an extremely long externalId IMHO. I haven't look in the code to see how you construct your REST API queries in detail. But what is like a practical limit? Is there a more verbose way of logging to see the full URI in case the process runs into an exception?

**Comment by hknokh** [comment]
No, I have no , I am using third party library jsforce and all is done internally i have not controll over it.

**Comment by JeroenSfdc** [comment]
But you somehow divide your queries into smaller chunks right (e.g. where you take into account how many predicates you add to not have an excessively long SOQL)?

**Comment by hknokh** [comment]
Of course I am dividing

**Comment by hknokh** [comment]
This case need to debug on your side...

**Comment by hknokh** [comment]
Need to see the constructed query and how it handles this
