### ISSUE TITLE
[BUG] SFDMU Desktop App loosing manually entered ExternalId

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#190]
**Describe the bug**
Often, the manually entered 'External Id' gets lost. When navigating between objects suddenly this error is shown:

![image](https://user-images.githubusercontent.com/27854769/93139626-645b4900-f6e1-11ea-9a35-d404b214b72a.png)

It always relates to the 'External Id' being wiped. 

![image](https://user-images.githubusercontent.com/27854769/93139798-b0a68900-f6e1-11ea-8130-b3efb082cf44.png)

**To Reproduce**
Typically this happens when you execute the script, and after that navigate back to the 'Step 2. Configuration'

**Expected behavior**
Entered value should not be wiped.

**export.json**
n/a

**Log file**
n/a

**Comment by hknokh** [comment]
@JeroenSfdc 
It's fiexed, please reinstall
