### ISSUE TITLE
[BUG] Minor typo 'Configurataion Objects' (tab label in Desktop app)

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#191]
**Describe the bug**
Minor typo 

![image](https://user-images.githubusercontent.com/27854769/93139922-dfbcfa80-f6e1-11ea-85ad-0eea8b97c30c.png)

**To Reproduce**
n/a

**Expected behavior**
n/a

**export.json**
n/a

**Log file**
n/a

**Comment by hknokh** [comment]
@JeroenSfdc 
It's fixed, please reinstall
