### ISSUE TITLE
[BUG]-Cannot run outside a valid Salesforce DX project

### ISSUE THREAD

**Issue by haddi3** [forcedotcom/SFDX-Data-Move-Utility#192]
**Describe the bug**
Executing 
   sfdx sfdmu:run --sourceusername ... --targetusername ... 
in a directory not part of a DX project return the error message
   ERROR running sfdmu:run:  This directory does not contain a valid Salesforce DX project
I am using the most recent sfdx-version: 
   sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3 
In prior version of sfdx and/or sfdmu executing sfdmu:run worked in any directory. 
 
**To Reproduce**
 sfdx sfdmu:run --sourceusername ... --targetusername ... 

**Expected behavior**
 sfdx sfdmu:run running in any directoy, like _sfdx force:org:list_, etc 

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**Comment by haddi3** [comment]
Workaround: just have a (dummy) sfdx-project.json file in the current directory

**Comment by hknokh** [comment]
Hello @haddi3 
Did you install from the source code ?

**Comment by haddi3** [comment]
Hello @hknokh,
I installed via 
    sfdx plugins:install sfdmu

BTW: thanks for your great job - that's an amazing tool!

**Comment by hknokh** [comment]
Thanks @haddi3 !
Regarding the issue I have no clue why it's asked for the sfdx project manifest... 
First time I am getting such issue from the users and can't reproduce it here. Anyway I had some google results about this. It's a known issue about sfdx as I understand.
