### ISSUE TITLE
[BUG] SFDMU App v3.1.1 - 'Excluded Fields' filtering incorrectly applies case-sensitivity

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#193]
**Describe the bug**
When filtering the 'Excluded Fields' the case-sensitivity is not respected (should be case-insensitive)

![image](https://user-images.githubusercontent.com/27854769/93233141-054a1280-f77b-11ea-8828-b094c1774e50.png)

But this does not find the field (it should return `QuoteLineReporting__c`)

![image](https://user-images.githubusercontent.com/27854769/93233184-12ff9800-f77b-11ea-9745-4f95f87d0542.png)

**To Reproduce**
See description

**Expected behavior**
Case insensitive searches.

**export.json**
n/a

**Log file**
n/a

**Comment by hknokh** [comment]
@JeroenSfdc 
This is fixed.
