### ISSUE TITLE
[FEATURE REQUEST] Ability to use 'Data Anonymization' when using ** all ** fields feature

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/SFDX-Data-Move-Utility#199]
**Is your feature request related to a problem? Please describe.**
When you use the `** all **` fields feature, I'd like to be able to still use the 'Data Anomyization' feature to mock a certain field. However when using `** all **` it considers all fields to be assigned. 

![image](https://user-images.githubusercontent.com/27854769/93429600-b35fd480-f8c1-11ea-87bd-d9749a4d5a45.png)

Use case: For all migrated data I'd like to update a field `Migrated__c` on the target a `true`. Such that I can easily identify migrated data (and e.g. delete it if needed). 

**Describe the solution you'd like**
Don't block `Data Anomyzation` when all fields are assigned, but make it override.

**Comment by hknokh** [comment]
Hello @JeroenSfdc 
This is fixed. Please reinstall and try.
