### ISSUE TITLE
How can we use externalId field to lookup the parent in case we are upserting parent and child with differnt export.json files(parent name has duplicate values)?

### ISSUE THREAD

**Issue by vijay8432** [forcedotcom/SFDX-Data-Move-Utility#203]
We are facing an issue with "**SFDMU**" command while inserting child **sobject** records when parent objects are imported already via another export.json file & having duplicate records/auto-number  and our current export.json file having reference to those parent lookup records. 

In that case, we are getting "**record not found**" issue in "MissingParentRecordsReport.csv" even we have records in our target org.

Facing the same issue If parent records having **auto-number** field as name field. 

**SFDMU** considering 'Name' as **external-Id** while inserting dependent lookup records with child object records.

Is there any way to use our custom **external-Id** fields instead of "**standard name field"** used while importing dependent parent/child records via different export.json file?

Thanks

**Comment by hknokh** [comment]
Hello @vijay8432 
Basically you can put any field (formula, custom + composite external ids) containing unique values that are matching between the source and the target in the externalId property of the parent sobject to bind parent-child related records.
Refer:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format
https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys

**Comment by vijay8432** [comment]
Hi @hknokh
Thanks for the quick response. We will check and let you know.
Thanks
