### ISSUE TITLE
[FEATURE REQUEST]-Text field containing ID used as lookup ID to related record

### ISSUE THREAD

**Issue by krusty7** [forcedotcom/SFDX-Data-Move-Utility#204]
We have a custom Text field which contains an Id value of a related record and we want the record to be migrated to the new Org and be associated to the correct record. Should be a Lookup type field but for now it isn't.

e.g. User selects a Queue and the Id of the Queue rather than the Name is stored in this Text field. Id would be invalid in target Org and relationship is not maintained by plug-in as there's no defined relationship.

Solution:
Add option into export.json to define relationship where a field is being used as a pseudo lookup Id.

e.g.    "SelectedQueue__c" has value "03g55000000m5peAAA" and Queue.Name is "SomeNewQueue"
{
  "query": "SELECT Name, SelectedQueue__c, somefield1, somefield2 FROM CustomObj__c",
  "operation": "Upsert",
  "extermalId": "Name",
  "PseudoLookupField": "QueueSObject$SelectedQueue__c;Queue.Name"
}

whereby another lookup CSV is created (as per UserAndGroup.csv) from Source Org export containing
Id, Queue.Name
03g55000000m5peAAA, SomeNewQueue

Import: 
1. Use "SelectedQueue__c" field value to lookup "Queue.Name" from CSV above
2. Query Target Org for "QueueSObject" (taken from export.json definition) where "Queue.Name" equals the value from step 1
3. Save the queried Id value in the "SelectedQueue__c" field on Target

Alternatively, the "PseudoLookupField" definition could be an option in field mapping with clearer parameters.

**Comment by hknokh** [comment]
Hello @krusty7 
Very interesting feature... Thx. 
I 'm putting it in the road map.

**Comment by krusty7** [comment]
Hi,
I disagree on your two points
1. Only salesforce can have polymorphic lookup fields like those on task, so other app providers have to use the text field lookup where we want to give customers flexibility without having to add a lookup field per sObject approach.
2. The Salesforce record id has specific format that can be validated from source org to target where sObject name is included along with record id without real impact on integrity.

So you may not choose to include it but that’s not a feasibility question but your preference.


Sent from my iPhone

On 21 Feb 2026, at 20:00, Haim Knokh ***@***.***> wrote:

﻿
[https://avatars.githubusercontent.com/u/15181301?s=20&v=4]hknokh left a comment (forcedotcom/SFDX-Data-Move-Utility#204)<https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/204#issuecomment-3939340036>

Hello,

Thank you for the suggestion.
I reviewed this case again.
At this time, implementing this feature is not feasible.

Reasons:

  *   Cross-org lookup resolution should rely on stable business keys, not raw source IDs stored in text fields.
  *   Generalized text-ID-to-lookup conversion would be unsafe without strict object-specific key contracts.

If additional opportunity appears, I will revisit this case.
Thank you for understanding.

Best regards
