### ISSUE TITLE
[BUG]-Unexpected runtime error 

### ISSUE THREAD

**Issue by nmhegde** [forcedotcom/SFDX-Data-Move-Utility#207]
**Describe the bug**
Running this the Below job gives the following error

**To Reproduce**
Just run the job

**Expected behavior**
The Job should have continues instead it stops with an error

**export.json**
`{
    "objects": [
        {
            "query": "SELECT Id,all FROM SBQQ__LineColumn__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__ProductFeature__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__ProductOption__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__QuoteTemplate__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__TemplateContent__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__LineColumn__c",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT Id,all FROM SBQQ__RelatedContent__c",
            "operation": "Upsert",
            "externalId": "CPQ_EXTERNAL_ID__c"
        }
    ],
    "pollingIntervalMs" : 10000,
    "promptOnMissingParentObjects" : false
}`

**Log file**
[2020-09-25__14_43_53.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5285537/2020-09-25__14_43_53.log)

**Comment by hknokh** [comment]
Hello @nmhegde 
Your issue seems to be solved. 
Because I can't exactly reproduce this error on my end that is why I made a fixing by my guess only.
Please retry.

**Comment by JeroenSfdc** [comment]
Interesting, @nmhegde - you're also working by any changes towards a source-controlled / CI way to move CPQ meta data across?

**Comment by nmhegde** [comment]
@JeroenSfdc  Yes. I'm trying to build a job to move CPQ data across sandboxes.
