### ISSUE TITLE
Allow automatically selecting all Creatable fields on a SOQL query

### ISSUE THREAD

**Issue by pventurino** [forcedotcom/SFDX-Data-Move-Utility#21]
The current implementation requires that every field is explicitly queried on each object's SOQL statement. For objects that have a large amount of fields, this can become tedious to maintain.

It would be nice to automatically generate a SOQL query that selects all Creatable fields, maybe even adding an "ignore" list. E.g.
```
SELECT :CREATABLE(-One__c,-Two__c,-Three__c) FROM MyObject__c`
```

**Comment by hknokh** [comment]
Hello!
Thank you for suggestion. I will add it to the project milestone

**Comment by hknokh** [comment]
@pventurino The automatic field multi-selection was implemented. 
You can use the new multieselect feature. 
See readme for the details.
