### ISSUE TITLE
[QUESTION] - RecordType matching

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#211]
Hello,

I have a problem with record types. As I understood, it should be preserved when moving records from one org to another, however in my case the record type is always set to the default one in the target org. I am not sure if I am doing something wrong. Should I change something in export.json to make it work?

Please find attached a screenshot of my export.json file. The command I am using is:

sfdx sfdmu:run --sourceusername szymon.kowalczyk@gz.pl.prdsupport --targetusername szymon.kowalczyk@gz.pl.devtest

![RecordType issue](https://user-images.githubusercontent.com/49412136/94446042-6aa0f900-01a8-11eb-96f8-8556eace2b7a.png)

**Comment by hknokh** [comment]
Hello, @kowszymon In order to transfer the record type you should always add **RecordTypeId** to your query:
**SELECT all, **RecordTypeId** FROM Account**
