### ISSUE TITLE
[FEATURE REQUEST] - Add standard_true/false multiselect keyword

### ISSUE THREAD

**Issue by ittogo** [forcedotcom/SFDX-Data-Move-Utility#214]
When writing my query statement, for a managed package, I was able to get all the fields by using this query:

"query":"Select Id, Name, custom_true from ......"

If I am copying fields from a stadard object, is there a similar command that will keep me from having to write out all the fields?

**Comment by hknokh** [comment]
Hello, 
Thanks for the suggestion, it's a new feature and I've added it to the roadmap.

**Comment by hknokh** [comment]
Hello, @ittogo 
For selecting the standard fields you can use either custom_false or standard_true keywords.
