### ISSUE TITLE
[BUG] - Developer name in query problem

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#215]
Hello,

after adding RecordTypeId to query I cannot transfer any records due to a problem with "DeveloperName" column on Entity Account, which is not an account field. When I was using a query "SELECT all FROM Account" the record types weren't assigned properly, but the problem didn't occur.

Please find attached export.json file and full logs.

![DeveloperName error log 2](https://user-images.githubusercontent.com/49412136/94534132-53154f00-0240-11eb-9b6c-3a4cf8e2ac42.png)
![DeveloperName error log 1](https://user-images.githubusercontent.com/49412136/94534146-5577a900-0240-11eb-8204-1ead4408126c.png)
![DeveloperName error export json](https://user-images.githubusercontent.com/49412136/94534150-56a8d600-0240-11eb-9090-cebef6833271.png)

**Comment by hknokh** [comment]
Hello,  @kowszymon 
Your export.json file seems incomplete and is not matching the log screenshot (in the log I can see more objects then in the export.json). Please follow issue tracker guideline and attach the **full versions of the files, not the screenshots.**
-------------
Anyway, I have checked your export.json as it's provided on my end and was able to transfer the account data without issues.
Since I can't reproduce the issue, it should be debugged on your local machine, alternatively you can provide me access to the relevant org and I can check it for you.

**Comment by hknokh** [comment]
BTW. Please update the plugin to the 3.7.9 (latest). I checked it on this version.
thanks

**Comment by kowszymon** [comment]
Hello @hknokh,
I updated the version to 3.7.10 and the problem is still the same. The screenshot I sent to you is whole, there aren't any other objects. Please provide your email address, so I will create a user for you and you will be able to check it on my instances.

**Comment by hknokh** [comment]
Hi, send me the credentials to haim.knokh@gmail.com

**Comment by hknokh** [comment]
Hello, @kowszymon 
 I think you have sent me the credentials.
I have no the password and also can't reset it due to the error message:
"PASSWORD RESET
To reset your password, we'll need your username.
We'll send password reset instructions to the email address associated with your account.
Cancel"

**Comment by kowszymon** [comment]
Hello, I sent you an email with some information, can we move this conversation there?

**Comment by hknokh** [comment]
Hello, yes we can discuss using email.
Please, reset the passwords again. The links are already expired.
Also resend the information to my email. I don't see your direct email for the conversation.

**Comment by kowszymon** [comment]
Hi,
I sent you the email once again. I also reseted the passwords again now.

sob., 17 paź 2020 o 19:09 Haim Knokh <notifications@github.com> napisał(a):

**Comment by hknokh** [comment]
Hi @kowszymon 
Is it solved for you and can be closed ?

**Comment by kowszymon** [comment]
Thank you Haim,

I have no time to check it now. You can close and if there is still a
problem I will let you know.

czw., 22 paź 2020 o 17:43 Haim Knokh <notifications@github.com> napisał(a):
