### ISSUE TITLE
Facing Error While Trying To Hit Next Button

### ISSUE THREAD

**Issue by VikasPoddar1319** [forcedotcom/SFDX-Data-Move-Utility#216]
Hello,

Whenever we try to click on the Next button. We are facing this issue: https://prnt.sc/upxfcx
We tried Org to Org, Org to CSV file & CSV file to Org.
We also uninstalled the SFDMU and installed again but still, the error remains the same!

we are waiting for your response!

Thanks

**Comment by hknokh** [comment]
Hello @VikasPoddar1319 
Please check for this issue:
https://help.sfdmu.com/faq/gui-app/the-application-is-failing-to-connect

**Comment by VikasPoddar1319** [comment]
> Hello @VikasPoddar1319
> Please check for this issue:
> https://help.sfdmu.com/faq/gui-app/the-application-is-failing-to-connect

I already tried this but it didn't work for me!

**Comment by hknokh** [comment]
Ok, understand, but you still need to check if you have any issue while connecting to the same org using the console / terminal.

**Comment by hknokh** [comment]
The tool is using the console output to capture the org credentials, if the output is not clean or any other issues it will not connect.

**Comment by hknokh** [comment]
Try **sfdx force:org:display --targetusername yourorg** and send me the output what you see in the console.

**Comment by VikasPoddar1319** [comment]
Thanks @hknokh for the reply. I found the issue error is in my terminal setting!
