### ISSUE TITLE
[QUESTION] - We are facing "COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE" After updating SFDMU Version

### ISSUE THREAD

**Issue by vijay8432** [forcedotcom/SFDX-Data-Move-Utility#218]
We are running with some weird issues after updating SFDMU plugging. We are not querying "OwnerId, CreatedById, LastModifiedById" these fields in our export.json file but still, we are getting below issues.

1. We are facing the "COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE" issue when we removed "UserAndGroup.csv" from the list of CSV files those we are retrieving from Source Org.

2. We are facing the "OwnerId" child missing error in "MissingParentRecordsReport.csv" even we don't use "OwnerId" in our SOQL queries in the export.json file.

We are not able to understand why plugging adds 'ownerId' field on retrieved CSV files from source org but the strange thing is that we are not facing that error with all objects.

**NOTE:-**
Facing that issue with some of the objects.
[https://prnt.sc/uqkhye](url)
[https://prnt.sc/uqkio5](url)
Thanks

**Comment by hknokh** [comment]
Hello, @vijay8432 

First, ensure that you have not implicitly included these lookup fields (such as ownerid) in the query using multiselect keyword like **all**. If the case, the option is exclude all unnecessary fields with **excludedFields** property.

But basically, the COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE is just in terms of a warning and it's not a critical for the migration process if you don't want to populate those lookups in the Target org.

--------
BTW. I would ask you when opening cases in future, to kindly use one of our issue tracker templates + to provide the export.json & .log file.  
Cause very mostly, these details are critical to analyse the issue and to provide a correct solution.
Thanks you!

**Comment by vijay8432** [comment]
Hello @hknokh 
We used "excludedFields" property and added these fields but still facing the same issue.

Thanks

**Comment by hknokh** [comment]
Can you provide the export.json + .log file please ?

**Comment by vijay8432** [comment]
Hello @hknokh 
Please check the below link and let me know If you need any other information.
[https://drive.google.com/drive/folders/1wn1xUDkZVOjNnnI_STzBKOyYEns2Rg6-?usp=sharing
](url)

Thanks

**Comment by hknokh** [comment]
Hello @vijay8432 
First, you put Id for upsert operation, note that it will not work for org2org and will always create new records since the Id is different in both orgs.
Regarding the subject.
This row in the log:
[19:31:48.336] The parent sobject User for the lookup field Contact.Customer_Portal_User__c has been included into the process. The externalId is set to 'Name'.
...  says that you are including lookup field Contact.Customer_Portal_User__c, that is referencing the User sobject, that is why the Plugin is automatically adding User sobject as readonly into the migration schema and it creating it on Org2Csv and requiring it on Csv2Org.

**Comment by hknokh** [comment]
But regarding the OwnerId  I don't see this field referenced neither in log file nor in export.json.
Please recheck, that the provided CSVIssuesReport.csv is matching the latest log files.

**Comment by vijay8432** [comment]
Hello @hknokh 
Yes, The CSVIssuesReport.csv  and Export are the latest ones. It will be good If we will connect and discuss the same, The Issues occurs after re-installing the SFDMU plugin.

Thanks

**Comment by hknokh** [comment]
Hello, @vijay8432 
Yes, I see, that it includes User into the schema and have no clue why.  This should be checked and debugged on your end on live org. 
Unfortunatelly I can't help you in this from my end...

**Comment by hknokh** [comment]
Sorry @vijay8432 
Yes, this what I said, you incuded PagesApi__Menu__c in the query on the form object that referencing the User object, so it includes the USer into the schema.

**Comment by vijay8432** [comment]
Hello @hknokh 
How can we debug the same? Can you please help us?
Thanks

**Comment by hknokh** [comment]
For self-debugging, please follow this article:
https://help.sfdmu.com/plugin-basics/basic-usage/debugging
the file that you need to check is script.ts, primaraly review this method  processObjectsMetadataAsync()

Or you can provide me the credentials to your org where you have the issue + relevant version of the export.json and I can debug it myself.
Normally, I am in holiday and can't provide you support now only next week, but you have the option for the self-debugging.

**Comment by vijay8432** [comment]
Hello @hknokh 
Thanks for the quick response.

I will try the same by myself and will let you know and share the credentials and all details If I am not able to debug the same issue

Thanks

**Comment by vijay8432** [comment]
Hello @hknokh 
I found the issue in **"sfdx.ts"**  **async describeSObjectAsync** function here you are getting the complete info of the target object and I guess you are not filtering the described Result of the target object with export Json SOQL query for that respected object.

Able to resolve the issue but not 100% sure whether its a valid workaround or not.

**I just added that condition for now.**
 if(!field.referenceTo.includes('Group') && !field.referenceTo.includes('User') && !f.label.includes('Tradestyle')){
                sObjectDescribe.fieldsMap.set(f.name, f);
  }

**Old Code is** 

  sObjectDescribe.fieldsMap.set(f.name, f);

**async describeSObjectAsync** function you are returning the array of sObject as per queries in export.json.

Please have a look once you will be back.

Thanks

**Comment by hknokh** [comment]
Hello, 
I still in vacation). But I just had a look on your soultion and It's not the solution)) 
Because it will omit **any lookup field to the User object** and so will block the Plugin from handling all user lookups. 
Think, I need to take a look on in on your end. If you could provide me access I will be able to investigate.

**Comment by vijay8432** [comment]
Hello @hknokh 
Yes, I know that was not a good approach. I debugged the code and I was found the Issue but unfortunately, my VS code stop debugging, and now I am not able to debug the code for typescript on VS code.

I guess when we try to get a distinct field list from the **described object Array** and **our SOQL query** field array then there might be some code issue that adds **ownerId** fields for some of the objects. 

We are facing issue with Account object as well. In our Source org column **"TradeStyle"** is not available but In our target Org that column available in Target org for Account Object.

Please check **CSVIssuesReport.csv**.
[https://docs.google.com/spreadsheets/d/1v8SWShLVxbwPxdfKlW3iXHQmpg6zAU3k1pKFgpEyzPc/edit?usp=sharing](url)

Shall I share Org Id and grant access to the SFDC support team from Org?
OR Shall I share the Org username and password for Source and Target Org?
Please let me know so that I will share the same with you.

Thanks

**Comment by hknokh** [comment]
Hello @vijay8432 
Thank you for the update.
I removed the provided credentials from the public access but saved this for me privately.
I will look on it ASAP.

**Comment by vijay8432** [comment]
Hello @hknokh 
Thanks for the update. Sure, Please let me know if you need any further information.
Thanks

**Comment by hknokh** [comment]
Hello
- Can't access the dev/prod org because of OAuth Error (maybe SSO is enabled or/and I am not a member of your organizartion).
- Can't also access the second org (sandbox) because of verification number is required.
Please create a dedicated user for haim.knokh@gmail.com with the same profile as yours and check for the access to the dev org (login.saleforce.com).

**Comment by vijay8432** [comment]
Hello @hknokh 
Thanks for the quick response. I created a new user for **target & Source org** and removed the IP Address range specified for **Source org**. 

Please check and let me know If you need further information.

**Target Org Url**: [https://app-momentum-9119-dev-ed.lightning.force.com/](url)
**Source Org Url**: [https://gcouuk6ys.lightning.force.com/](url)

Thanks

**Comment by hknokh** [comment]
Hello @vijay8432 
I did a quick check and was able to reproduce the issue.
I will update you further.
Can I delete / modify data from the target org ?

**Comment by vijay8432** [comment]
Hello @hknokh 
Yes, You can do whatever you want
Thanks

**Comment by vijay8432** [comment]
Hello @hknokh 
I hope you are doing well. Is there any update regarding the issue?
If you need any help feel free to let me know.
Thanks

**Comment by hknokh** [comment]
Hello @vijay8432 
I'm sorry, have no time to tackle this for now due to very busy with my primary job.
I will do it soon.

**Comment by hknokh** [comment]
@vijay8432 
The issue should be solved. Please update and retry

**Comment by vijay8432** [comment]
Hello @hknokh 
Sure, I will check and let you know.
It will be good to know If you will let me know about the issue.
Thanks

**Comment by hknokh** [comment]
The problem was with the resoultion of the misspelled SOQL query string. 
When there is no such field or sobject in the org the plugin is trying to match the closest field and use it instead of the original one, it was applied OwnerId instead of one of the missing fields in the target org.

**Comment by vijay8432** [comment]
Thanks for the quick response and clear the thing. I checked the merged request changes as well. 
I tested after updating SFDMU and It's working fine.
Thanks
