### ISSUE TITLE
[QUESTION] - Upsert Account & Insert Contact Record

### ISSUE THREAD

**Issue by ShravanKumar1988** [forcedotcom/SFDX-Data-Move-Utility#219]
I am looking to upsert account and simultaneously contact record from one org to other org. The contact records are getting inserted correct, however the account lookup field on the contact record is not getting populated. I tried various JSON format with no avail. So requesting your advice on how to go about this requirement. Thank you for the help in advance.

**Comment by gitmemattb** [comment]
I am getting this problem also.  I tried used sfdmu version 4.4.6
