### ISSUE TITLE
[QUESTION] - The Query misses out some fields

### ISSUE THREAD

**Issue by lukasPovilonisAvieco** [forcedotcom/SFDX-Data-Move-Utility#222]
I couldn't determine what causes for a field to be 'missing'.

I'm sure the field is in the query, I can also see the field in query string that is printed in command line.

Though, the field is not in the target/[object_name]_insert_target.csv.

The field security is not an issue.

I'm also able to retrieve the field using Workbench and other reset services.

**Comment by hknokh** [comment]
Hello, please follow our guidelines to open the issues. Thanks

**Comment by hknokh** [comment]
You need to provide complete .log/ export.json file.
