### ISSUE TITLE
[QUESTION] - Data not Anonymization not working.

### ISSUE THREAD

**Issue by vksrinu** [forcedotcom/SFDX-Data-Move-Utility#223]
Hi,

I am trying to Anonymize the data but its not working, data is copying from source to target but its not Anonymization. I do have mentioned the mockFields in it. 

My json:
 "query": "SELECT all FROM Account",
 "operation": "Upsert",
 "externalId": "Name",
  "mockFields": [
      {
        "name": "name",
        "pattern": "name"
      }
    ]
 }

Do i need to install any other packge

**Comment by hknokh** [comment]
Hello,
please use correct field names (case sensitive) in the data anonymizatin schema:
"Name" instead of "name"
