### ISSUE TITLE
[APP-BUG]-Step 1 Connection is not working

### ISSUE THREAD

**Issue by Sakthes** [forcedotcom/SFDX-Data-Move-Utility#228]
**Describe the bug**
The GUI App is not able to connect to the Source Org while SFDX commands are working well
Thank you for your help.
**To Reproduce**
After I run the "Test SFDX Commands" with "RUN force:org:lit" I have the list of org in Source and Target Connection so I select my sandbox dev as Source and CSV File as target and click on Next, an error message is displayed:
"Error: Unable to connect to the Source Org. Check your SFDX authentication data."

**Expected behavior**
I expect to pass from step 1 to 2 by clicking on the next button

![image](https://user-images.githubusercontent.com/68962151/95203144-a0fef980-07e2-11eb-9e88-f837334a684b.png)

**Comment by hknokh** [comment]
Hello @Sakthes 
What output do you get after running force:org:display command ?
Try it in the TEST SFDX COMMAND tab and directly in the Console as well.

**Comment by Sakthes** [comment]
> Hello @Sakthes
> What output do you get after running force:org:display command ?
> Try it in the TEST SFDX COMMAND tab and directly in the Console as well.

I still have an error while running force:org:display command:
![image](https://user-images.githubusercontent.com/68962151/95229808-55a81380-0801-11eb-9dd5-0feb88b9f165.png)

But I don't have any error while running force:org:list
![image](https://user-images.githubusercontent.com/68962151/95230115-b7687d80-0801-11eb-93dc-9b5949dbb5db.png)

**Comment by hknokh** [comment]
Please show me the output of **force:org:display**, not list

**Comment by hknokh** [comment]
Execute it durectly via the Terminal/Console

**Comment by Sakthes** [comment]
Hello,

I've runned the command in the Windows Console and actually I have several old org that were deleted but still in my list so I had those errors:
ERROR:  Error: getaddrinfo ENOTFOUND xxx--devxx.my.salesforce.com

I've deleted the old file in .sfdx as described here https://salesforce.stackexchange.com/questions/181780/removing-old-hub-org-or-non-scratch-org-from-salesforce-dx-org-list

And I was able to pass to the next step.

Thank you.

**Comment by hknokh** [comment]
Thank you for the update.
You are right. I need to document it in the help center.
