### ISSUE TITLE
[QUESTION] - Question title Child Objects Not Getting Populated

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#229]
- Ask your question or what kind of help you need.
After a lot of tries having difficulty understanding from the docs how to construct the JSON so that child records are populated. I get a few but that's by luck. 

1. Say I've got a child object, not Master Detail, that has a lookup to Account and another field for lookup to Contact.
2. So some records have the lookup to Account populated, others the lookup to Contact.
3. I pull in 10 Accounts and 10 Contacts using the utility
4. What references do I need in my Child object to get children of those 10 Accounts and 10 Contacts?

**Comment by hknokh** [comment]
Hello,
For the child sobjects put **"master": false**
