### ISSUE TITLE
[QUESTION] Step 2 Filtering records by Name ERROR

### ISSUE THREAD

**Issue by chrisvreug** [forcedotcom/SFDX-Data-Move-Utility#230]
I'm currently trying to transfer data from csv files into my org. Everything seems to work until Step 2 when it retrieves the records by filtering by Name, which obviously creates an error. Am I doing something wrong or is this a bug?

When exporting from my org to my csv this isnt an error.

Thanks in advance,
See my log and export.json below

Error in Log:
{Contact} Retrieving the TARGET data from Org (STEP 2: filtered records)...
Command in progress...... done
[ERROR] Error during execution of the command:
AccountId, Name FROM Contact WHERE Name IN ('Bryson Dechambeau')

export.json:
{
    "bulkThreshold": 0,
    "promptOnUpdateError":false,
    "bulkApiV1BatchSize": 100,
    "objects": [
        {
            "query": "SELECT AccountNumber,AccountSource,BillingCity,BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,BNC_ID__c,Client_Deceased_Date__c,Communication_Language_PrimaryContact__c,Communication_Language__c,Description,Email__c,End_of_Fiscal_Year__c,Facebook_primaryContact__c,Facebook__c,Fax,FirstName,HomePhone__c,Household_Phone_Extension__c,Inactive_Date__c,Investment_Trading_Notes__c,LastName,Linkedin_primaryContact__c,LinkedIn__c,MiddleName,Mobile_Phone__c,MyWealth_Rate__c,NBF_Client_Status__c,NBF_Segmentation__c,Operating_Name__c,OSS_Primary_Root__c,PCIS_Username__c,PersonBirthdate,Phone,Phone_Extension__c,PO_Org_Fiscal_Year_EndDate__c,PO_Org_Fiscal_Year_EndMonth__c,PO_Org_Legal_Form_Code__c,Primary_Contact__c,Primary_Email_PrimaryContact__c,Primary_member_rollup__c,Primary_Phone_PrimaryContact__c,Quebec_Registration_Number__c,Rating,RecordTypeId,Registration_Number__c,Salutation,Suffix,Twitter_pimaryContact__c,Twitter__c,Type,Website,Work_Phone_Extension__c,Work_Phone__c FROM Account WHERE RecordType.DeveloperName='PersonAccount' and Client_Status__c ='Prospect'",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT Account_Access_level__c,Account__c,Case_Access_level__c,IACode_Id__c,Opportunity_Access_level__c FROM AccountAccessGroup__c WHERE AAG_Key_Indexed__c <> null and Account__c in (Select Id FROM Account Where RecordType.DeveloperName='PersonAccount' and Client_Status__c ='Prospect') ",
            "operation": "Upsert",
            "externalId": "Account__r.Name;IACode_Id__r.IACode__c"
        },
        {
            "query": "SELECT IACode__c FROM IACode__c",
            "operation": "Upsert",
            "externalId": "IACode__c"
        },
        {
            "query": "SELECT Account__c,Area_Code__c,Category__c,Country_Code__c,Country__c,Description__c,Electronic_Contact_Information_Name__c,Email__c,End_Date__c,Extension__c,Fax__c,Id,Number__c,PartyContactEffctvDt_Text__c,PartyContactMethdGroupUpdDt_Text__c,PartyElectronicCtcInfoUpdDt_Text__c,PartyTlcPhoneUID_Text__c,PartyTlcPhoneUpdDt_Text__c,PartyTlcUpdDt_Text__c,PCM_Party_Electronic_Contact_Method_UID__c,PCM_Party_Elec_Contact_Info_Meth_UID__c,PCM_Party_Elec_Contact_Method_Update_Dt__c,PC_Complete_Phone_Number__c,PC_Country_Code__c,PC_Effective_Date__c,PC_Method_Group_Update_Date__c,PC_Method_UID__c,PC_Method_Update_Date__c,PC_Phone_UID__c,PC_Phone_Update_Date__c,PC_UID__c,PC_Update_Date__c,Phone_Number_clickable__c,ptyElectronicCtcInfoUID_Text__c,RecordTypeId,RootId__c,Source__c,Type__c,Usage_Type__c,Website__c FROM Contact_Method__c WHERE Account__r.RecordType.DeveloperName='PersonAccount' and Account__r.Client_Status__c ='Prospect'",
            "operation": "Upsert",
            "externalId": "Account__r.Name"
        },
        {
            "query": "SELECT CreatedById, EventType, CreatedDate, Details__c, EventDate, Household__r.Name, OwnerId FROM PersonLifeEvent",
            "operation": "Upsert",
            "externalId": "OwnerId"
        },
        {
            "query": "SELECT Id, Name, CreatedDate, CreatedById, Account__c, Personal_Interest_Category__c FROM Personal_Interest__c WHERE Account__r.RecordType.DeveloperName='PersonAccount' and Account__r.Client_Status__c ='Prospect'",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT Id, Name, RecordTypeId, CreatedDate, CreatedById, Account__r.Name, Client_Desired_Outcomes__c, Household__c, Advice_Path_Activity__c, Advice_Path_Topic__c FROM Advice_Path_Topic__c WHERE Account__r.RecordType.DeveloperName='PersonAccount' and Account__r.Client_Status__c ='Prospect'",
            "operation": "Upsert",
            "externalId": "Account__r.Name"
        },
        {
            "query": "SELECT Id, Name, RecordTypeId, CreatedDate, Account__c, Amount__c, Description__c, Household__c FROM Cashflow__c WHERE Account__c in (Select Id FROM Account WHERE RecordType.DeveloperName='PersonAccount' and Client_Status__c ='Prospect')",
            "operation": "Upsert",
            "externalId": "Account__r.Name"
        },
        {
            "query": "SELECT LastModifiedEndUserDate__c, Id, Name, CreatedDate, Account__c, Address_Notes__c, Address__c, City__c, Civic_Number__c, Country__c FROM Address__c WHERE Account__c in (Select Id FROM Account WHERE RecordType.DeveloperName='PersonAccount' and Client_Status__c ='Prospect')",
            "operation": "Upsert",
            "externalId": "Account__r.Name"
        },
        {
            "query": "SELECT RecordTypeId, Id, WhoId, WhatId, WhoCount, WhatCount, Subject, ActivityDate, Status, Priority, IsHighPriority, OwnerId, Description, Type, AccountId, IsClosed, CreatedDate, CreatedById, RecurrenceStartDateOnly, RecurrenceEndDateOnly, RecurrenceTimeZoneSidKey, RecurrenceType, RecurrenceInterval, RecurrenceDayOfWeekMask, RecurrenceDayOfMonth, CallObject, CallDisposition, ReminderDateTime, TaskSubtype, CompletedDateTime, FinServ__Expectations__c, FinServ__Household__c, FinServ__NextSteps__c, FinServ__Objectives__c, FinServ__Regarding__c, Follow_Up__c, Merged_Contact_Id__c, Merged_Account_Id__c, Pre_Meeting_Notes__c, Log_as_a_Trade__c, Non_Solicited__c, Stock_Symbol__c, Regarding__c, LastModifiedEndUser__c, Financial_Account__c, LastModifiedEndUserDate__c, Commission_Amount__c FROM Task WHERE WhatId in (Select Id FROM Account WHERE Record_Type_Name__c = 'PersonAccount')",
            "operation": "Upsert",
            "externalId": "WhatId"
        }
    ]
}

# #
[2020-10-06__11_44_58.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5335154/2020-10-06__11_44_58.log)

**Comment by hknokh** [comment]
Hello, 
**Account__r.Name** is incorrect ExternalId definition. You shoud use only the object field, for example **Name**.
However, to use single field as a compound external id - you can try to put semicolon at the end: **Account__r.Name;** 
I think it should work, but I am not sure. 
Normally the compound externalid is intended to be used with multiple fields for example **Name;Account__r.Name** not with single field.

**Comment by hknokh** [comment]
Regarding the error in the query string, try to execute 
SELECT Id, IsPersonAccount, AccountId, Name  FROM  Contact WHERE Name IN ('Bryson Dechambeau')
in the sf developer console, fop you get the same error ?

**Comment by chrisvreug** [comment]
Thanks for the quick response! I just had another look at the documentation for the external Id... my mistake thanks for the tip.
Yes I had tried that before, here is the error message that pops up:

**[object Object]: AccountId, Name FROM Contact WHERE Name IN ('Bryson Dechambeau') ^ ERROR at Row:1:Column:64 field 'Name' can not be filtered in a query call.**

I assumed that it might be a bug in the backend since I dont make it directly in my export.json. Also, it might be worth mentionning that in STEP 2 of the data retrieval for the target all objects are queried for all records 

**ex: {RecordType} Retrieving the TARGET data from Org (STEP 2: all records)...**

Except for the Contact object where it displays:

**{Contact} Retrieving the TARGET data from Org (STEP 2: _filtered records)_...**

Might give you a better idea of where to debug in the code.

**Comment by hknokh** [comment]
Hello!

1. Please update the Plugin and retry because v3.7.0 is very very old version and might have bugs.
Never use updated verison of the Plugin. The latest for this moment is 3.7.13 and it contains amount of important bug fixes.
-----
2.  It's normally, the Contact is included automatically in the migration schema because I think one of your lookup fields referencing the Contact object. I would suggest you to update the Plugin and retry. In the most recent version you will able to see which llokup field causes the Contact object to be included in the migration schema.
-----
3. The menitoning all / filtered is important to us to distinguish between the **native** or **user** queries (from the export.json) and the helper queries generated by the Plugin in order to find out the related records between the objects by the given external id. So the meaning is not exactly **filtered** but like in terms of **autogenerated**. 
The Plugin **always** queryes the target in "filtered mode" when usinbg Upsert or Update, because we need to bind between the source and the target records and retrieve **only** those records from the Target, that are matching the previously fetched source records and it can be done only when we will include include the addtional filtering by the external id field.
----
4. Regarding how to debug.
Refer here:
https://help.sfdmu.com/plugin-basics/basic-usage/debugging

**Comment by chrisvreug** [comment]
Hello, I updated the plugin and made the changes to the external IDs but I still have the same issue. 
Yes, this issue also occurs in the Salesforce Development Console.

**Comment by hknokh** [comment]
Ok. As per I understand it's not a Plugin issue. 
Find the similar issue here https://trailblazers.salesforce.com/answers?id=9063A000000a0CuQAI
The query to Contact is generated as a part of a  normal migration process because as I mentioned you have some contact lookups in other objects.  Normally you must have all necessary permissions in your orgs and ability to perform all CRUD operations in order to run the Plugin. 
As a solution I can only suggest you 2 options:
1. Remove all lookups to Contact object.
2. Explicitly add the Contact object into the export.json in Readonly mode and specify externalid **other then Name** (by default it uses Name for Contact).
