### ISSUE TITLE
[QUESTION] - Multiple queries with different external IDs for the same object in one export.json

### ISSUE THREAD

**Issue by dmgerow** [forcedotcom/SFDX-Data-Move-Utility#231]
Is it possible to supply queries for the same object with different fields and/or external IDs in the same export.json?

For example, I may want to update a subset of fields on ALL records in the Product2 object with a non-selective query and make my external ID the ID field, but then update ALL creatable fields on a different subset of records via a different external ID on the same object.

Is this possible?

**Comment by hknokh** [comment]
Hello,
No, directly it's not possible. You need to create separated export.json for every type of job.

**Comment by dmgerow** [comment]
Thanks @hknokh
