### ISSUE TITLE
[FEATURE REQUEST]- the sfdmu command should use the local or global "defaultusername" configured on the user's machine.

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/SFDX-Data-Move-Utility#232]
**Describe the bug**
The run command requires that the `--targetusername` flag be set and ignores if there is a "defaultusername" set in the local or global config.

The `run.ts` command file clearly [supports the inclusion of the username](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/commands/sfdmu/run.ts#L34), but [it is not required](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/commands/sfdmu/run.ts#L35).   I would suggest that the `requiresUsername` value should be set to true.  

Also, at [run.ts line 170](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/commands/sfdmu/run.ts#L170), there is a manual check requiring the presence of the `targetusername` flag.  This is inconsistent with the behavior of the Salesforce CLI in general and should be removed.

**To Reproduce**
* Assume "myScratchOrg" is an alias to an org
* execute command `sfdx config:set defaultusername=myScratchOrg`
* execute command `sfdx sfdmu:run -s csvfile` -- Note the absence of the `--targetusername` flag

**Expected behavior**
* the sfdmu command should use the local or global "defaultusername" configured on the user's machine.

**export.json**
n/a

**Log file**
n/a

**Comment by hknokh** [comment]
Hello @ImJohnMDaniel 
The default sfdx flags are not supported yet. 
You need to provide --targetusername explicitely.
I replaced the type of your case by new feature request and it will be review further.

**Comment by ImJohnMDaniel** [comment]
@hknokh -- Thanks for the information.

Just curious, where are the release notes posted for SFDMU?  I wanna be on the lookout for this change.

Cheers!

**Comment by hknokh** [comment]
Normally this is the changelog page
https://help.sfdmu.com/full-documentation/additional-information/changelog
I'm documenting only the major changes like new features or very important patches.
You can follow this.

**Comment by ImJohnMDaniel** [comment]
Thanks!

**Comment by jonny-harte** [comment]
Hi, has this been released? If so, how do you specify the target as the current defaultusername?

**Comment by hknokh** [comment]
@jonny-harte hello,
No it's not implemented yet. There is some technical obstacles with this. May I will find aresolution in the future.

**Comment by hknokh** [comment]
Hello,

Thank you for the suggestion.
I reviewed this case again.
At this time, implementing this feature is not feasible.

Reasons:
- Requiring explicit usernames in migration commands is an intentional safety control to reduce wrong-org execution risk.
- Switching core behavior to implicit defaultusername resolution is not planned at this time.

If additional opportunity appears, I will revisit this case.
Thank you for understanding.

Best regards
