### ISSUE TITLE
[QUESTION] - Should the MissingParentRecordsReport.csv contain records that ultimately still get imported?

### ISSUE THREAD

**Issue by nicholasglesmann** [forcedotcom/SFDX-Data-Move-Utility#235]
I've noticed that when importing records to a Scratch Org, the MissingParentRecordsReport.csv gets populated with a list of records that are missing parent references. However, all the records that I've looked at in this file have still been imported properly to the Scratch Org.

Is the plugin supposed to behave in this fashion OR should the MissingParentRecordsReport.csv file contain ONLY records that are NOT imported correctly? Thanks!

**Comment by hknokh** [comment]
Hello @nicholasglesmann 
Normally, child records marked as not found parent relationships should still be populated but they will have nulls in the lookups listed in the MissingParentRecordsReport.csv, since the relationship was not resolved correctly.
