### ISSUE TITLE
[BUG]-module import missnamed

### ISSUE THREAD

**Issue by ChristopherMGlass** [forcedotcom/SFDX-Data-Move-Utility#238]
**Describe the bug**
received message   'Error: Cannot find module './addonMAnifestDefinition' when using command `sfdx force:data:tree:import`

**To Reproduce**
use command `sfdx force:data:tree:import` with latest version

Looks like import in lib/modules/models/script_models/script.js. should be renamed to `'./addonManifestDefinition'` instead of `'./addonMAnifestDefinition'`

**Comment by hknokh** [comment]
Hello @ChristopherMGlass 
Thanks for the finding. It's fixed, please reinstall the Plugin.
