### ISSUE TITLE
[QUESTION] - Empty RecordTypeId

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#246]
Hello,

I have a problem with Record Type. I have two record types named Sold_To, but only one of them is used. One of them is from managed package, the second not. On my source org I have Accounts only of the second type. For some reason the Sold_To Accounts have their RecordTypeId empty in the insert target file. I know it happened before, then it was working for some time, and now we have that problem again. Have you got an idea what is going on?
[SFDX DMU Case 21-12-2020.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5724253/SFDX.DMU.Case.21-12-2020.zip)

**Comment by hknokh** [comment]
Hello @kowszymon 
You should have RT with **distinct DeveloperName value per sobject**. The Plugin takes RT as an external id for RecordType object by default. If you have any other field or several fields on the RT object that can compose some distinct external id, you can explicitely add RecordType object to your export.json with ReadOnly operation and define there other externalid than the default DeveloperName, even I think you can go with the Composite External Id feature todefine something unique.
https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys

**Comment by hknokh** [comment]
Also you can set a SOQL, that queries only records with desired record types.
