### ISSUE TITLE
[QUESTION] - Error after batch size added

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#247]
Hello,

I added the bulkApiVersion = 1.0  and bulkApiV1BatchSize = 100 attributes but the insert fails with Exit code 4 (COMMAND_EXECUTION_ERROR) after updating first 100 records. Am I doing something wrong?

Please find attached log and export.json file.

[SFDX DMU Case 21-12-2020 batch size.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5724953/SFDX.DMU.Case.21-12-2020.batch.size.zip)

**Comment by hknokh** [comment]
Helo, @kowszymon 
First, try to replace bulkApiV1BatchSize=100 instead of bulkApiV1BatchSize="100", it's numeric property.
