### ISSUE TITLE
[BUG]-The SOQL query for sObject Product2 does not include any field can be updated or inserted.

### ISSUE THREAD

**Issue by tomekduda** [forcedotcom/SFDX-Data-Move-Utility#248]
**Describe the bug**
I am trying to upsert `Product2` csv to an empty sandbox. I've cut down my sample to 2 fields and it still fails. On upsert it dies with bit cryptic `TypeError: Cannot read property 'child__rSFields' of undefined`. But in the log I can see warnings like:

```
[WARN] Field Product2.ExternalId__c is missing in the Target.
[WARN] Field Product2.ProductCode is missing in the Target.
[WARN] Field Product2.Name is missing in the Target.
Processing the sObject Product2...
[WARN] The SOQL query for sObject Product2 does not include any field can be updated or inserted.
```
I am on std. System Administrator profile, checked the object- and field-level security, checked capitalisation of letters in the source file. Tried with `SELECT all FROM Product2` and with hand-crafted query. No idea what I'm doing wrong.

**To Reproduce**
Create `ExternalId__c` field, then attempt to load this
```
PROD_KEY,PROD_NAME
"abc123","Lorem ipsum"
"def456","dolor sit amet"
```

with mapping file
```
ObjectName,FieldName,Target
Product2,PROD_KEY,ExternalId__c
Product2,PROD_NAME,Name
```

and `sfdx sfdmu:run --sourceusername csvfile --targetusername username`

(I've tried injecting `Product2,,Product2` line to mapping file too, no luck)

**Expected behavior**
Successful upsert of these 2 records. I've used your awesome utility in another project (but without column mapping step), no idea what I'm doing wrong now.

**export.json**
```
{
    "objects": [{
		"query": "SELECT ExternalId__c, Name FROM Product2",
		"operation": "Upsert",
		"externalId" : "ExternalId__c",
		"useFieldMapping": true
	}]
}
```

**Log file**
[2020-12-21__23_35_43.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5727001/2020-12-21__23_35_43.txt)

**_target.csv** file.
N/A

**Comment by hknokh** [comment]
Hello, @tomekduda 
- I don't understand your mapping configuration:
what are the fields PROD_KEY,PROD_NAME ? There are no such fields (sustom or standard)  in the Product2.
-  you put externalid as "externalId" : "ExternalId__c", but you have mapped different unrecognized PROD_KEY field to ExternalId__c as target. It's not correct mapping configuration. Externalid definition must be BEFORE field mapping, so it should be   PROD_KEY according to your configuration.

**Comment by tomekduda** [comment]
Hi @hknokh, thanks for looking into my issue!
PROD_KEY, PROD_NAME come form my csv's source system. I thought I can use field mapping during the load rather than having to edit the CSV on the fly and rename them to proper Product2 fields (ExternalId__c, Name)
Salesforce is not the only consumer of the file so asking for rename at source will be tricky.

So - can field mapping be used like that or is it primarily for sobject->sobject mapping?

**Comment by hknokh** [comment]
Yes, it's exactly sobject -> sobject. You must include only the fields that does exist in the target org because when you are importing csv files, the Tool is first checking the source csv against the **original target** org metadata and applied the field mapping when updating the target.
So rename your columns properly.
