### ISSUE TITLE
[QUESTION] - Email Anonymization help needed.

### ISSUE THREAD

**Issue by CovertCode** [forcedotcom/SFDX-Data-Move-Utility#249]
I'm exporting data from production but to import it in another org. For test purpose I'm trying to export as CSV and anonymize email address using GUI. But it does not nothing to email addresses. They are saved as original. Can someone please tell me which regex should be used in Data Anonymization for email scramble? Probably just change the email domain to anything so no actual email is sent.
I added this regex in include regex block(full email) : **/[a-z\d]+([\.\_]?[a-z\d]+)+@[a-z\d]+(\.[a-z]+)+/igm**
For domain: **"/[^\sw\.@/]([0-9a-zA-Z\-\.]*[0-9a-zA-Z\-]+\.)(de|com|org|net|edu|DE|COM|ORG|NET|EDU)/g"**

**Comment by hknokh** [comment]
Hello @CovertCode 
The format of the regex supported by the tool for the anonymization must not include slashes and flags like 'g'
Try expressions without "//igm".
Refer:
https://help.sfdmu.com/full-documentation/advanced-features/data-anonymization

**Comment by CovertCode** [comment]
> 
> 
> Hello @CovertCode
> The format of the regex supported by the tool for the anonymization must not include slashes and flags like 'g'
> Try expressions without "//igm".
> Refer:
> https://help.sfdmu.com/full-documentation/advanced-features/data-anonymization

Thanks, it worked. I also used the same but it didn't worked before. So I redownloaded the repo and it worked.
