### ISSUE TITLE
[NEW FEATURE] - Take in account a Namespace while handling the RecordType

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#250]
Hello,

This is continuation of my previous Issue, where you suggested adding RecordType to retrieved objects and setting custom externalId. Unfortunately, nothing changed when I added this to sobjects:

{
            "query": "SELECT all FROM RecordType",
            "operation": "Readonly",
            "externalId": "NamespacePrefix;DeveloperName",
            "createTargetCSVFiles": true
}

Still "SoldTo" accounts have "RecordTypeId" empty.

NamespacePrefix is the only field on RecordType that separates 2 "Sold To" record types. One is "ivybase", the other is empty. Can't these fields be used as a composed externalId?

Please find attached my export.json file, logs and target data.
[SFDX DMU Case 28-12-2020 RecordTypeId.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5748099/SFDX.DMU.Case.28-12-2020.RecordTypeId.zip)

**Comment by hknokh** [comment]
Hello @kowszymon 
Very sorry for the delay, I was on vacation, now I have a lot of work.
I will look on it ASAP when will have more time.
Thanks for the patience.

**Comment by kowszymon** [comment]
Hello Haim,

OK, I see. Happy New Year!

Meanwhile I tried to do a workaround by inserting the failed Accounts from csvfile with manually fulfilled RecordTypeIds but when they were inserted the field was empty again.

**Comment by hknokh** [comment]
Hello @kowszymon 
How are u? Is the issue resolved ?
I've checked your cofiguraiton.
Unfortunatelly for the RT object the **DeveloperName** is only the externalid field and it is hardcoded regardless other settings.
There is no option to separate between similar developer names in different namespaces, all RTs have to be differentiated by the develper name only.

**Comment by hknokh** [comment]
I can think about how to upgrade the tool to accept namespaces besides the developer name but I can not promise that it will be included in the nearest development milestone,  maybe yes, maybe no)

**Comment by hknokh** [comment]
Anyway, your issue was added to the roadmap.

**Comment by hknokh** [comment]
Hello @kowszymon 
I did a patch to solve your issue with the record type.
Please reinstall and retry and let me know if the RT is populating now.
You can remove the RT object definition from the export.json. It should be added automatically.
Apologize for the delay, I'm very loaded with my regular job)

**Comment by hknokh** [comment]
Hello @kowszymon 

I am reopening this case. I've reverted back the version 3.8.0 in the newest patch (3.8.2). 

Unfortunatelly my latest fix of your issue (v3.8.1) caused a regression in other place... 
But I am working on the final solution.

Did you test the patch 3.8.1 that the record type is handled properly with that version?

Thank you!

**Comment by kowszymon** [comment]
Hello @hknokh ,

I tested it today and it worked perfect. I am finally able to finish my task from before 6 months. Thank you very much. I am looking forward to bringing back the handling of record types. Please let me know when it is available again.

**Comment by hknokh** [comment]
Hello @kowszymon 
I update the Plugin to support your case. 
Please reinstall and let me know if it does work for you.
Thanks.

**Comment by kowszymon** [comment]
Hello @hknokh , I updated it and got an error described in a new issue.

**Comment by hknokh** [comment]
@kowszymon Closed this, the converstaion has moved  to the new issue.
