### ISSUE TITLE
[QUESTION] - Is there any way to enable Serial / Parallel when enabling BUlk API V1 ?

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#251]
Enabling Serial Mode when using Bulk v1.0 is very common to avoid row locks. This option is available in Bulk API v1.0
Is this option exposed to users in Export.json file? I do not see any option like this. It would be good to add it in the roadmap! :-)

**Comment by hknokh** [comment]
Hello @jorgesolebur 
Thank you for the suggestion.
 I've added it in the roadmap and I'm checking the options.

**Comment by hknokh** [comment]
Hello @jorgesolebur 
Added the  new **concurrencyMode** parameter to the script (acceptable only if using the Bulk V1):
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format
@ylhutter
