### ISSUE TITLE
[QUESTION] - CollaborationGroupMember.MemberId Field does not get set.

### ISSUE THREAD

**Issue by angad-pathak** [forcedotcom/SFDX-Data-Move-Utility#257]
Hi,

I am currently setting up this utility to seed data from Production to Sandbox. First I export from production to csv file and then load csv file into Sandbox.

The problem is with the CollaborationGroupMember.MemberId field. It gets exported in the csv file, however but it is not mapped when importing into sandbox and in the output file there is error "Required field missing : MemberId".

Here are the files:

[2021-02-03__13_54_30.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5918546/2021-02-03__13_54_30.log)

[export - Copy.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5918550/export.-.Copy.txt)

---
One similar issue I faced was in the opportunitylineitem or the quotelineitem object. There the field "PricebookentryId" was not set due to which the import fails.

Could you suggest what could be wrong?

Thanks!

**Comment by angad-pathak** [comment]
FYI: It seems the field with createable property = true but updateable property = false are not getting imported. 

That's true for the CollaborationGroupMember.MemberId and the QuoteLineItem.PricebookEntryID field.

Looking forward to your advise what should be done. Thanks !

**Comment by hknokh** [comment]
Gello @angad-pathak 
First, do not specify keepObjectOrderWhileExecute = true, let the tool to decide the order of the import.
The second, CollaborationGroup was not created in the target, you need to check it first why it whon't import.
Third, ensure that you have the same users with the same Names in both orgs.
Let check these points and let me know if there is still an issue. 
Next time, please attach _target.csv files to you case as well. These files normally give you an information about the errors why records are failing.

**Comment by angad-pathak** [comment]
@hknokh Thanks for your prompt response.

I reran the utility considering these 3 points.

1. Have removed the keepObjectOrderWhileExecute = true param
2. It seems it was an intermittent error. I was trying multiple times and if the collaboration group is already present, it won't create again because of the same name. In this run the colloboration group got created. 
3. Yes the names of the user match.

Still the error is coming in the target files "Required fields are missing: [MemberId]". 

[Files.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5925843/Files.zip)

**Comment by hknokh** [comment]
Hello @angad-pathak 
As I see from the_target file, the **all** pattern does not include MemberId into the CollaborationGroupMember. Try to include MemberId explicitly (SELECT all, MemberId etc.) Normally not all fields especially lookups incuded using **all** pattern, it varies depend on the concrete sobject metadata. You need to complete missing fields with explicit including into the SOQL.
