### ISSUE TITLE
[BUG]- SQL Parser not working after last update

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#262]
**Describe the bug**
Some SQL Parser error.

**To Reproduce**
Try to move records from one org to another using enclosed json, which worked fine before last update.

**Expected behavior**
Move records from one org to another

**export.json**
[SFDMU Error 10.02.2021.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5957552/SFDMU.Error.10.02.2021.zip)

**Log file**
Attached

**_target.csv** file.
There isn't any.

**Comment by hknokh** [comment]
Hello @kowszymon 
I took a deep look on your issue and tried to investigate where it could happen. I can not reporduce it on my test envs.
Because unfortunatelly there is no way to find where is it failing from my side, so may be you can debug it on your side please ?
The problematic code area (as I guess) - **script.ts** - the function **processObjectsMetadataAsync()**
Thank you in advance for the help!

**Comment by kowszymon** [comment]
Hello @hknokh, I added some logs and as I can see, the problem is when retrieving RecordType. Please find attached script.ts with my debugs and log file. In the last working version it looked like this: 

query: `SELECT Id, ${Common.getComplexField(externalId)} FROM ${referencedObjectType}`,

Now it is:

 query: `SELECT Id, ${externalId} FROM ${referencedObjectType}`,

So now the generated query is:

 SELECT Id, DeveloperName;NamespacePrefix;SobjectType FROM RecordType

And the semicolon makes problems.
[DEBUG SFDMU 11.02.2021.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5964636/DEBUG.SFDMU.11.02.2021.zip)

**Comment by kowszymon** [comment]
I thought that maybe if you could exclude inactive Record Types it would be easier? That would also satisfy me, because I deactivated one of the duplicate record types.

**Comment by hknokh** [comment]
I don't understand your idea.
Normally I am not controlling or modifying any data coming from the env.

**Comment by kowszymon** [comment]
When you look for matching record types on target org you find all Record types and try to match them by DeveloperName. If you looked only through active record types on the target org, on my org you would find only one active with this DeveloperName and the problem would not occur.

**Comment by hknokh** [comment]
Ok, I understand you, but it is not the solution, it's a patch and I don't want to go this way, I want to underwstand the root case of this. Can provide me sandbox access to allow me to reporduce and to debug it ?

**Comment by kowszymon** [comment]
OK,

So the source sandbox is this:

haim.knokh@@gz.pl.prdsupport (you already logged in there, let me know if
you want me to reset your password)

And the target sandbox is this:
haim.knokh@gmail.com.devtest2 (I reseted the password)

czw., 11 lut 2021 o 13:27 Haim Knokh <notifications@github.com> napisał(a):

**Comment by hknokh** [comment]
Please reset also to haim.knokh@gz.pl.prdsupport

**Comment by kowszymon** [comment]
Done.

czw., 11 lut 2021 o 14:42 Haim Knokh <notifications@github.com> napisał(a):

**Comment by hknokh** [comment]
Hello @kowszymon 
I've fixed it in 3.9.2 It was just a broken git branch merge. 
And you are right it was a problem of Common.getComplexField(externalId), but it also has several mixed commits together.  
Please reinstall and recheck.
---
BTW, regarding the IsActive = true to use only active RTs.
By default, when you omit the RecordType object in your object list, the Tool automatically adds the RecordType object with some default parameters. 
In other case, when you want to only use the active RecordTypes - you just have to include the RecordType object explicitely like below:
{
      "query": "SELECT Id FROM RecordType WHERE IsActive = true"
}

The Tool uses a compound externalid **'DeveloperName;NamespacePrefix;SobjectType'** as the default for the RecordType object, by you can set your own, for ex: 
{
       "query": "SELECT Id FROM RecordType WHERE IsActive = true",
       "externalId" : "DeveloperName;SobjectType"
}

**Comment by hknokh** [comment]
Hello @kowszymon 
Closed this case due to no response. Please reopen if any issue.
