### ISSUE TITLE
[QUESTION] - Support for Queues/Groups

### ISSUE THREAD

**Issue by davidlarrimore** [forcedotcom/SFDX-Data-Move-Utility#266]
I have been leveraging Queue assignments on Cases, but Records fail when going from one org to another because it can't find the Queue's. I have verified that the queue exists.

**Comment by hknokh** [comment]
Hello, @davewongillies  
Refer to https://help.sfdmu.com/faq/configuration/how-to-assign-queue-to-cases
Please, update the Plugin to v3.9.3, I fixed the Queues/Groups handling

**Comment by hknokh** [comment]
@davidlarrimore 
Closed this case due to no response. Please reopen if any issue.
