### ISSUE TITLE
[QUESTION] - Lookup query on Name field of Contact

### ISSUE THREAD

**Issue by nhaney1** [forcedotcom/SFDX-Data-Move-Utility#272]
How do I change what column is used to do a lookup to a different external id?  When I have a query that does a lookup to the contact object to get the contact ids, it by default uses the name column to do the lookup.   However the standard **Name** is not a queryable field on several objects.

Sample Query:
SELECT Id, Name, Contact__c FROM Contact_Method__c

..
[16:07:28.321] Getting metadata for Contact (SOURCE)
[16:07:30.190] Getting metadata for Contact (TARGET)
[16:07:33.441] The parent sobject Contact for the lookup field Contact_Method__c.Contact__c has been included into the process. **The externalId is set to 'Name'.**
..

..
SELECT Id, Name FROM Contact WHERE Name IN ('Test User1', 'Test User2'
                                   ^
ERROR at Row:1:Column:36
**field 'Name' can not be filtered in a query call.**
[16:08:16.583] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
...

**Comment by hknokh** [comment]
Hello @nhaney1 
If you just want to set the externalId for the Contact object, you need to include Contact object in your export.json with "operation": "Readonly", then set the externalId for the Contact to another field than Name.
See also:
http://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

**Comment by hknokh** [comment]
Hi there.
The case has been closed for the current moment.
Feel free to reopen if your issue still persists.

**Comment by nhaney1** [comment]
That worked great!  Thank you so much for your help.   I am amazed I couldn't see an example of this anywhere, but it works like a charm.   Great application and excellent support/documentation.

**Comment by hknokh** [comment]
Thank you for the feedback !
