### ISSUE TITLE
[BUG]  Account names containing backslashes are not handled properly

### ISSUE THREAD

**Issue by szymon-halik** [forcedotcom/SFDX-Data-Move-Utility#274]
First of all, I want to express my gratitude for this tool and extensive documentation. Nevertheless, I've just encountered a problem during the migration with some corrupted data for instance: a few Accounts are named with backslash - `Edge\Communications GB`. Due to that I am receiving and the following error:
`Error during execution of the command: line 1:735 token recognition error at: ''Edge\C'.`

 Is there any way to configure how the job should escape invalid characters like: backslashes, forward-slashes  single quotes,  duble quotes etc

**Comment by hknokh** [comment]
Hello, @szymon-halik 
Do you use these invalid characters in the query string in the export.json or the issue is coming from the Tool during its internal operation ?

Could you provide your latest export.json + .log files to review ?

**Comment by szymon-halik** [comment]
Hi @hknokh,

I am not using invalid characters in the query string in the export.json. It's exactly how you describing it - the error occurs during the job so it's coming internally form the Tool. I believe it's not a wrong logic, but the parser my interpret the following expression `Edge\Communications` as an attempt to escape a character.

Here are the export and log files fo further investigation(I've deleted the data related to the customer to be compliant)
[2021-03-15__14_31_48 copy.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6149242/2021-03-15__14_31_48.copy.log)

[export copy.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6149279/export.copy.txt)


Is it possible to introduce a new feature? I am thinking about some kind of parameter or expression to control how the parser should escape the invalid characters during the data migration if any are met

**Comment by hknokh** [comment]
Hi @szymon-halik 

I understand your issue, but the tool should handle those characters normally, not need to arrange it as an extended feature.

It's seems like a bug, I will look on it. Please tell me, your names have only backslashes or mb any other weird characters as well?

**Comment by szymon-halik** [comment]
Hi @hknokh ,

Thanks for clarification, I am facing an issue with Accounts and Opportunities containing the following string- it's a name of the parent Account: `TBWA\Helsinki Ot`

**Comment by hknokh** [comment]
@szymon-halik 
Fixed please reinstall the plugin and retry.

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen if your issue still persists.
