### ISSUE TITLE
[BUG] "sObject type Group_* is not supported" error when migrating data from production to a sandbox

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/SFDX-Data-Move-Utility#275]
**Describe the bug**
When running a simple data migration from production to a sandbox for two custom objects (namely Skill__c and User_Skill__c), I'm getting the following error:
`sObject type 'Group_Skill__c' is not supported`
This error looks odd because the Group_Skill__c object has never existed on any of our environments, and the export.json file doesn't contain any reference to this object.

**To Reproduce**
Create the following custom objects with their core fields.

* Skill__c
  * Name, Text(80)
  * Description__c, Long Text Area(4000)
* User_Skill__c
  * Name, Auto Number
  * Skill_ref__c, Lookup(Skill)
  * User_ref__c, Lookup(User)

**Expected behavior**
The data should be migrated as normal because both objects are deployed, accessible to System Admin Profile, and have Bulk API enabled.

[**export.json**](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6151551/export-json.txt)
[**sfdmu-logs**](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6151428/sfdmu-logs.log)

**Comment by hknokh** [comment]
Hi @pgumiela 
As I understood from your export.json you are using readonly_false keyword. This will automatically include all updateable fields including all lookups which basically could  be updated.
In this case I would recommend you to use excludeFields feature:
https://help.sfdmu.com/faq/configuration/what-kind-of-fields-can-i-exclude-with-excludefields-feature
to exclude unwanted fields from the update.

**Comment by hknokh** [comment]
Hi there.
The case has been closed for the current moment.
Feel free to reopen if your issue still persists.

**Comment by pgumiela** [comment]
@hknokh, this problem still persists even though I was using excludeFields, I'll update you today.

**Comment by hknokh** [comment]
Ok, provide me the the updated .log/export.json.

**Comment by pgumiela** [comment]
I'm uploading the new export.json and log files. Unfortunately, the log looks almost the same. The strange part is that Group_Skill__c object doesn't exist at all on our org, so I can't understand why it tries to query this object even though it's not included in the export.json file. If you can share your email address, I can prepare two dev sandboxes (source and target), so we could try to replicate this problem and debug it.

[export-v2.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6167218/export-v2.json.txt)
[sfdmu-logs-v2.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6167217/sfdmu-logs-v2.log)

**Comment by hknokh** [comment]
@pgumiela 
Did you exclude **ALL** lookup fields to the **Group_Skill__c** object both from **Skill__c** and **User_Skill__c** ?
I didn't see that in your export.json, for example: 
"excludedFields": [
       "**Group_Skill__c**",
        "CreatedDate",
        "LastModifiedDate",
        "sfdc_load_CreatedDate__c",
        "sfdc_load_External_Id__c",
        "sfdc_load_LastModifiedDate__c"
      ]
The goal is to prevent picking up and processing all unwanted lookups / fields uing excludedFields property.

**Comment by hknokh** [comment]
***
The case has been closed due to no response. 
Please, reopen it if you have any additional issue.

**Comment by pgumiela** [comment]
@hknokh, can we please reopen this issue? I know that I'm repeating myself, but the thing is that there is no Group_Skill__c object on our org (really, this object was never available on our org at any time, we have the Skill and User Skill but not Group Skill). This is why it doesn't make sense to exclude the field or set the object excluded in the export.json. To be 100% sure, I've tried to set this field as excluded for every single object mentioned in the export.json, but the same exception is thrown. This is why I wanted to ensure with you that this isn't a problem with the tool itself. I can't expose too many details in public, but if you could share your email, I can prepare the source and target dev sandboxes for you, and we could check this together.

![2021-05-01_20-05-09](https://user-images.githubusercontent.com/7087639/116791188-e6558200-aab8-11eb-8f5f-954e906b3c4d.png)

**Comment by hknokh** [comment]
Hey @pgumiela 
Please provide me the access to the source->target orgs where I can reproduce this using your export.json, I will check.
My email is haim.knokh@gmail.com

**Comment by pgumiela** [comment]
Great, I've just sent you an email.

**Comment by hknokh** [comment]
Hey @pgumiela 
Yes, I received the credentials and logged in successfully, thanks. I hope to look on the issue today at night.

**Comment by hknokh** [comment]
Hello @pgumiela 
The issue is solved.
Still some records have failed due to **"Owner ID: owner cannot be blank"**, but it's correct behavior.
To troubleshoot it, you should analyse the **_target.csv** files and make sure that you have the Users with the same names in the both orgs. 
I didn't check this point myself.

**Comment by pgumiela** [comment]
@hknokh, thanks a lot, you've made my day :). Now it works fine for these previously affected objects.

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen it if you will have any additional questions or issues.
