### ISSUE TITLE
[QUESTION]-Smart order not picking up all related records

### ISSUE THREAD

**Issue by db-Services** [forcedotcom/SFDX-Data-Move-Utility#276]
**Describe the bug**
The app is missing parent records for about 15% of the records I'm migrating from production to a developer sandbox. I made sure to include all of the objects that are showing up in the MissingParentRecordsReport.csv and also made sure they were marked with master:false. I'm using the GUI app to seed a developer sandbox with two master objects and their related objects. There are 17 objects in total. It seems like the smart order isn't working in all situations. Tried looking through the documentation on information about the smart order but there isn't much (as far as I saw).

**To Reproduce**
This org is heavily customized and has a few managed packages in it. I really don't know how to give you the steps to reproduce. I can do a Zoom screen share or make a video if that would help.

**Expected behavior**
I would expect the app to find the parent records for any children imported as long as the parents are included as one of the objects in the configuration.

Here is the export.json. I would send over the other logs but some of the data in the logs are sensitive.
[export.json.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6161945/export.json.zip)

**Comment by hknokh** [comment]
Hello @db-Services 
Is the issue already solved ?

**Comment by hknokh** [comment]
***
The case has been closed due to no response. 
Please, reopen it if you have any additional issue.
