### ISSUE TITLE
Read data from external data source

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#277]
Hello - Can we use this utility to load data from external data source (Oracle, SQL Server, Teradata etc.)  like data loader spring framework? We've batch jobs that updates /extracts data from salesforce from our legacy and ERP systems

Also, can we automate the batch load using this utility? execute script from a scheduler.

**Comment by gvpatel** [comment]
We're using data loader spring framework to load data in Salesforce. 

Is salesforce plan to replace data loader with this utility in future?

**Comment by hknokh** [comment]
Hello, @gvpatel

Sorry for the late replay, I'm on vacation.
 
- Regarding the external objects. I did not check this part especially, but normally by the implementation you can use this utility to load external data source objects (__x) into the Salesforce env.

- Some users successfully use this plugin from the automated processes, but I really don't know how exactly they are doing this. 
@ylhutter do you have any information about how to automate running?

- This utility still is not the official Salesforce Data Loader. It's an open-source plugin, which is fully approved and digitally signed by the Salesforce to use with all envs. Regarding the future  plans, currently I have no such information.

**Comment by ylhutter** [comment]
Hi @gvpatel,

About automation with this tool, a good example will be using Jenkins as the scheduler to jobs that can run SFDX plugin commands.
If you would like to combine loads from external systems that are not Salesforce, the option of csv files import is only relevant here and also can be used with automation like Jenkins (where files are stored on the server running this job).
I hope this helps closely to what you are looking for.

**Comment by gvpatel** [comment]
Hi @hknokh, regarding external objects, we've to use ODATA protocol which is an additional steps. Not all database support ODATA protocol and it requires custom code or Middleware solution.

If you could add external objects support in data mover utility using JDBC that would be great. Data loader is supporting JDBC which allows us to connect to any datasource (Oracle, SQL Server, DB2, Aurora etc.)

**Comment by hknokh** [comment]
Hi @gvpatel 
Thank you for the suggestion. I agree that it would be a great feature and we take it for the future milestone.
However, the primary advantage of the SFDMU is the automatical resolution and migration of complex data models which is not supported by the Data Loader. And I think, if you have a lot of related objects to process, you will still save a time in using our tool with any middleware like excel.

**Comment by hknokh** [comment]
The case has been closed for the current moment.
Feel free to reopen if your you have additional questions.
