### ISSUE TITLE
[BUG]-ENOTFOUND -3008 error in the middle of moving data

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#278]
**Describe the bug**
Hello, I have the latest version of SFDMU and it has been working properly so far. Now I get an error when trying to move data from one org to another. The operation stops with this error message:

[Batch# 7513N000005WNYKQA4:Insert] {ivybase__Route_Details__c} The batch has been created. Uploading data ...
Error: getaddrinfo ENOTFOUND gz--devtest2.my.salesforce.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'gz--devtest2.my.salesforce.com'
}
[ERROR] {ivybase__Route_Details__c} The Insert API operation FAILED.
Command in progress ...... done
[ERROR] Error during execution of the command: {ivybase__Route_Details__c} The Insert API operation FAILED..
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).

It happens at different points, in the middle of the job. Sometimes after a couple of thousand Accounts is done, now Accounts completed and it occured when trying to move Route Details. I think it is not an Internet connection issue, because it happened yesterday and today and at that time had no break in internet access. Have you gout an idea what might cause this?

**To Reproduce**
Move data from one org to another, at some random point it stops.

**Expected behavior**
 All data should move properly

**export.json**
[SFDMU Bug 31.03.2021.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6235117/SFDMU.Bug.31.03.2021.zip)

**Log file**
It is in zip with export.json

**_target.csv** file.
It is not an issue with rows

**Comment by hknokh** [comment]
Hi, it sounds like your org sometimes stopped responding or it is timeout issue. This is not what i can help here.

**Comment by hknokh** [comment]
The case has been closed for the current moment.
Feel free to reopen if your have any additional question.
