### ISSUE TITLE
[QUESTION] - Question title

### ISSUE THREAD

**Issue by elchacha** [forcedotcom/SFDX-Data-Move-Utility#280]
- **How is the tool selecting the import order for the objects ?**

I have a json file where select query are in this order :
select ... from **B**
select ... from **C**
select ... from **A**

When importing, it imports the records in the order : **B** then **A** then **C** ( Not understanding the order as it is not **DESC** or **ASC**).
How can set the ordering as due to MasterDetail Relation, order is really important or it will fail

**Comment by hknokh** [comment]
Hello @elchacha 
The order is not important - it always tries to automatically resolve the best processing order depend on the relationship between the objects.

**Comment by hknokh** [comment]
The case has been closed for the current moment.
Feel free to reopen if your you have additional questions.

**Comment by elchacha** [comment]
[exemple.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6489478/exemple.zip)
Sorry to reopen the case but either I was misunderstood or I miss something but it's not working as expected

the zip contains objects metadata so that you can recreate a scratch org.
The script\apex contains an apex script to create data within the src org

working.export.json as named is working fine. (Object_B is listed first)
notWorking.export.json as named is not working fine. (Object_B is listed second)
Order seem to matter in fact. I try to remove the Master, it's still the same




[notWorking.export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6489486/notWorking.export.json.txt)
[working.export - Copie.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6489487/working.export.-.Copie.json.txt)
