### ISSUE TITLE
[BUG]-Cannot read property 'autoNumber' of undefined

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#281]
**Describe the bug**
When I try to get move records, I get an error "Execution of the command was ABORTED due to unexpected error: Cannot read property 'autoNumber' of undefined.". This happened when the tool added new object that where parents to those listed by me. When I added the objects, the next one showed the same message. Now I get "The SOQL query for sObject SlaProcess does not include any field can be updated or inserted". I have no Idea what to do next. Please advise what can I do. I want to move listed objects' and only the records that are connected to Accounts retrieved by this specified query.

**To Reproduce**
Try to move records from org to csvfile.

**Expected behavior**
Should move records

**export.json** **Log file**
[SFDMU Bug 15.04.2021.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6320443/SFDMU.Bug.15.04.2021.zip)

**Comment by kowszymon** [comment]
@hknokh Nevermind, I debugged and found it. It was AccountContactRelation object that was problematic. I excluded it and now it works.

**Comment by hknokh** [comment]
Hello @kowszymon 
Thank you for the update. Very interesting...)
Can I ask you, what is the rule "WHERE Id = null" ? it will skip all records. Or you want to add only those records which are related to master object, or may be there is a different goal of this ?

And how can I reproduce the issue on my machine, I would like to debug it myself, I guess also I have bug there with the identification of default external id ? 
I know at one time you gave me access to source/target envs. Can you recheck how to reproduce the bug there ?
Thx.
