### ISSUE TITLE
Cant map Id to external Id field

### ISSUE THREAD

**Issue by zefreak** [forcedotcom/SFDX-Data-Move-Utility#282]
I would like to map the record Id from the source org to an external Id field in the target org - Id > Production_Id__c

However, the following does not work:
```
            "useFieldMapping": true,
            "fieldMapping": [
                { "targetObject": "Test__c" },
                {
                    "sourceField": "Id",
                    "targetField": "Production_Id__c"
                },
                {
                    "sourceField": "Name",
                    "targetField": "Production_Name__c"
                }
            ],
```

I know the fieldMapping is working because Name correctly maps to Production_Name__c - however Production_Id__c does not exist in the target csv and remains null in the target org.

Is this not supported because it is an Id column in the CSV (which is eventually overwritten in the target csv with the new record Id)? Is there an alternative way to accomplish what I want without having to create new fields on the source org (such as a formula field which references the record Id)?

**Comment by hknokh** [comment]
Hello @zefreak

**Comment by hknokh** [comment]
Hello @zefreak 
I fixed the mapping of the record id in the version 4.0.1.
However, I didn't publish the release to the NPM, because of waiting for the approval to sign this release, so you can't update your local version using  **sfdx plugins:install sfdmu**.  
But you still can pull the updated version from the git and use **plugins:link**

**Comment by hknokh** [comment]
@zefreak 
The plugin is already uploaded to the npm so you can reinstall it normally **(sfdx plugins:uninstall sfdmu / sfdx plugins:install sfdmu)** and retry.
***
I am closing the case for now, if it does not solved on your side feel free to reopen.

**Comment by zefreak** [comment]
Thank you @hknokh for the quick response. I tested the new version and the issue does not seem to be fixed - the target CSV does not have the Production_Id__c column, but does have the Production_Name__c column mapped. The deployment continues to fail because of this

**Comment by hknokh** [comment]
Hello @zefreak 
I applied another patch. Please retest again with v4.0.3

**Comment by hknokh** [comment]
***
The case has been closed due to no response. 
Please, reopen it if you have any additional issue.

**Comment by mobilizer** [comment]
Hey @hknokh,
I have an additional question: Is it possible to use the fieldMapped "Production_Id__c" field as externalId.

Just playing with the thought of adding a field "Production_Id__c" to target orgs. So the entries can be mapped between source "Id" and target "Production_Id__c".

```
"operation": "Insert",
"externalId": "Production_Id__c",
"useFieldMapping": true,
"fieldMapping": [
      {
          "sourceField": "Id",
          "targetField": "Production_Id__c"
],
```

Is this okay? Or is it a missunderstanding of the functionality of SFDMU? Thanks.

**Comment by hknokh2** [comment]
Hello
Sorry for accidently closed issue.
I think you can find the exact response to your last question in this article:
https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping#mapping-external-id-field
Regards.
