### ISSUE TITLE
Use SFDX data move utility to migrate Salesforce CPQ data

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#284]
Hi , We'll be starting Salesforce CPQ project soon. Salesforce CPQ is managed package.

Can we use SFDX data mover utility to migrate Salesforce CPQ meta data such as

Product rules
Pricing rule
Product bundles
Summary Variables 
Configuration attributes
Discount Schedules etc....

from Sandbox to production or any other Salesforce environment?

Thanks,

**Comment by hknokh** [comment]
@gvpatel 

The Plugin is already used with some CPQ projects. I think it's possible also for yours.

I can't give you concrete recommendations, but it will be good to transfer CPQ records including custom fields etc, even it's coming from managed package.

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen if your you have additional questions.
