### ISSUE TITLE
[QUESTION] - Delete records: Input CSV file and output: target org

### ISSUE THREAD

**Issue by claudiazuppy** [forcedotcom/SFDX-Data-Move-Utility#288]
- Ask your question or what kind of help you need.
HI,
i have a question. I'm trying to use the tool to delete records in an org. In input i prepare the CSV i use th command:
sfdx sfdmu:run --sourceusername csvfile   --targetusername "userNameOrg".
In the last days we have noticied that with this operation the all records are deleted while before (one week ago) the tool did a match between the records in the csv file and the record in the org. I attach the export.json, the input csv file and the target files , that the tool produces. If you see the target file of the quote it contains only a record that is the records it must not to delete.
could you help me to understand because the tool considers all quote if in the input file i passed different ids?
[Files.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6364647/Files.zip)

Thanks,
Claudia

**Comment by hknokh** [comment]
Hello @claudiazuppy 
As I know the behavior of my Tool, it should never take in account the source CSV file while  deleting.
You also can see in the log file that the DELETE is the most first operation before the source records are retrieved. 
It's strange what you say that  Plugin was somewhen matching the source records against the target while deleting.
The only option to restrict the deleted records is to use a WHERE clause of the main query string or to setup the deleteQuery property.

**Comment by hknokh** [comment]
Since your question has been aswered, I'm closing the case for the current moment.
Feel free to reopen if your you have any additional questions.

**Comment by claudiazuppy** [comment]
HI @hknokh, thanks for you support and for your response. I have another question, how to you see in my export.json i have inserted some queries in particular for account and opportunity i defined the master attribute = true and in the query there is a where conditions to consider a particular account and its opportunities. because i defined the opportunity like a master object why during the elaboration the all quotes in the environment, are they deleted? if i try a migration data between 2 orgs and i use the same export.json with operation=insert the tool considers only the data related of the account(the opportunityies, the quotes, the contacts etc).
Thanks,
Claudia
