### ISSUE TITLE
DELETE based on export.json

### ISSUE THREAD

**Issue by claudiazuppy** [forcedotcom/SFDX-Data-Move-Utility#289]
Hi,
i want delete some records from org, but i would use the feature of the tool that build the object relationship.
if in my export.json i have a query on account and opportunity with a where condition and parameter master=true i want delete only the quotes related on the opportunity or account. if the operation defined in the json is "readonly" the extraction is correct but with the delete operation doesn't work because the all quotes are deleted.
Could you adapt and introduce this features also for the delete operation?
Thanks,
Claudia

[fileJson.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6376005/fileJson.zip)

**Comment by hknokh** [comment]
Hello @claudiazuppy 
I introduced the new feature for this, please see the documentation:
https://help.sfdmu.com/full-documentation/advanced-features/delete-from-source
You can use it for your job to delete related data. 
Please, update the local plugin version.

**Comment by claudiazuppy** [comment]
Hi @hknokh, 
thanks for speed and support for introducing this new feature. we are trying to do some testes (delete account and releated case) but we obtain this error:
12:23:12.862][ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'autoNumber' of undefined.
[12:23:12.865] [STACK TRACE] TypeError: Cannot read property 'autoNumber' of undefined
    at ScriptObject.get hasAutonumberExternalId [as hasAutonumberExternalId] (C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptObject.js:151:27)
    at C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJob.js:46:69
    at Array.forEach (<anonymous>)
    at MigrationJob.setup (C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJob.js:33:29)
    at RunCommand.createJobAsync (C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:65:18)
    at Run.run (C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:39:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Run._run (C:\Users\davide.musarra\AppData\Local\sfdx\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (C:\Users\davide.musarra\AppData\Local\sfdx\client\7.98.0-e361fce\node_modules\@oclif\config\lib\config.js:173:24)
[12:23:12.866] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[12:23:12.867] Total time elapsed: 00h 00m 07s 383ms .

[SFDMU Test Aborted.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6383796/SFDMU.Test.Aborted.zip)
Thanks,
Claudia

**Comment by hknokh** [comment]
Ok, I will check it.

**Comment by hknokh** [comment]
Hello @claudiazuppy 
I can not reproduce it on my side, in order to debug and to fix it, I need you to provide me the access to your test org where I can run the export.json as is and get the same issue.
Thanks

**Comment by hknokh** [comment]
Hello @claudiazuppy 

It should work now. Please update the Plugin and retry.

I tested it to delete Accounts + related Cases & Opportunities,

I would propose you the follow working configuration:

{
    "objects": [
        {
            "query": "SELECT Id FROM Account where id in ('0011w00000uk7f7AAA')",
            "operation": "Delete",
            **"externalId": "Name"**,
            "deleteFromSource": true,
            "master": true
        },
        {
            "query": "SELECT AccountId FROM Case",
            "operation": "Delete",
            "deleteFromSource": true,
            "master": false
        },
        {
            "query": "SELECT AccountId FROM Opportunity",
            "operation": "Delete",
            "deleteFromSource": true,
            "master": false
        }
    ]
}

Use **Name** as the external id field for Account. 
The Id can be used only for **Insert** and **Source Delete**, NOT for **Update** and **Upsert**. So using Name field or other unique field except of Id would always be a better practice...

Let me know if now it's work.

**Comment by claudiazuppy** [comment]
Hi @hknokh ,
thank for your support. we have done some testes and now it works. i have a question about a thing that we have notieted.
we have the following scenario:
an account, a contact related to the account and a case linked to account and contact. If we run the tool with this json:
{
    "objects": [
        {
            "query": "SELECT Id FROM Contact where id in ('0031w00000qnickAAA')",
            "operation": "Delete",
            "externalId": "Id",
            "deleteFromSource": true,
            "master": true
        },
        {
            "query": "SELECT AccountId FROM Case",
            "operation": "Delete",
            "deleteFromSource": true,
            "master": false
        }
        
    ]

we receive the warning : WARN] [Batch# REST:Delete] {Contact} Incompleted. 0 records succeeded, 1 records failed--> the tool delete only the case.
if after this run we will run again the tool now the contact is deleted.
We have tried also to include in the json:
{
            "query": "SELECT Id FROM Account where id in ('0011w00000ukbLKAAY')",
            "operation": "ReadOnly",
            "externalId": "Id",
            "master": true
        },

but we have the same error.

i attach the zip with all files.
Thanks for your collaboration
[test_tool.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6393302/test_tool.zip)

Claudia

**Comment by hknokh** [comment]
Hello @claudiazuppy 
There is an incorrect configuration for the Case.
If you want to handle relationships between objects you need to add **proper** **lookup** **field**.
F.ex. if you have Concats as a master  - you should use:
"query": "SELECT ContactId FROM Case"
The tool does always resolve the relationships based on the lookup fields used in the corresponding SOQL query. 
If you don't add lookup into the query - the tool wil not able to resolve the object hierarchy.

**Comment by hknokh** [comment]
Hello @claudiazuppy 

It's solved.
*
Finally you can use following configuration depend on your requirements (note, that you can omit the externalId for the deleteFromSource object and it always set to Id by default, also master=true by the default and can be omited as well) :


- If you can directly provide Contact Ids for the deleted Cases:

{
"objects": [
	{
		"query": "SELECT ContactId FROM Case",
		"operation": "Delete",
		"deleteFromSource": true,
		"master": false
	},
	{
		"query": "SELECT Id FROM Contact WHERE Id IN ('0031w00000qnsyMAAQ')",
		"operation": "Delete",	
                "deleteFromSource": true
	}
]
}


- If you know only the Account Ids and want to Delete all related Cases & Contacts, 
in this case the objects will be automatically retrieved by the following order:  Account->Contact->Case:

{
"objects": [
	{
		"query": "SELECT ContactId FROM Case",
		"operation": "Delete",
		"deleteFromSource": true,
		"master": false
	},
	{
		"query": "SELECT Id, AccountId FROM Contact",
		"operation": "Delete",
		"deleteFromSource": true,		
		"master": false
	},
	{
		"query": "SELECT Id FROM Account where id in ('0011w00000ukwsYAAQ')",
		"operation": "Readonly",
		"externalId": "Id"
	}
]
}

**Comment by claudiazuppy** [comment]
Hi @hknokh,
now seems ok and works correctly. During these days we will continue to do some testes for our scope and we will update you
Thanks for support and collaboration
Claudia

**Comment by hknokh** [comment]
Sounds good, @claudiazuppy 
In addition, if you have a csv file with list of record ids you want to delete them from the sf org, you can also utilize the new  **deleteByHierarchy** option:
https://help.sfdmu.com/full-documentation/advanced-features/delete-by-hierarchy
Please update the plugin version before using this new feature.

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen it if required.

**Comment by claudiazuppy** [comment]
Hi @hknokh,
we trying to use the new functionality but probably we are doing something wrong in the use. we have tried with the following resources but the deletion is missing.
Thanks,
Claudia
[toolFile.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6413740/toolFile.zip)

**Comment by hknokh** [comment]
The record you tried to delete 0011w00000v5I0jAAE does not exist in the org

**Comment by claudiazuppy** [comment]
HI @hknokh,
sorry we accidentally deleted that record. you can try with a new record (id=0011w00000v5S0FAAU)
Thanks,
Claudia

**Comment by hknokh** [comment]
Ok, I see. I will check it.

**Comment by hknokh** [comment]
Yes, I found issue there... I need to fix it. I will update you when done. 
I made some tests and deleted something like 8 Accounts during these tests. I understood, it's not a problem to delete any record there ? I have to continue debugging and  testing to resolve the issue. 
If you have any restrictions or preferences regarding the records, please let me know.
Thx.

**Comment by claudiazuppy** [comment]
HI @hknokh,
yes in this environment is not a problem,just a note on wednesday we will have a demo so tomorrow in the afternoon we have to prepare some test datas, so please you could not delete or restrict you investigation in a set of accounts (please don't delete 0011w00000ukwsZAAQ,0011w00000v3zkvAAA)
Thanks,
Claudia

**Comment by hknokh** [comment]
Hey @claudiazuppy 
Working for me now.
Please update and retest.

**Comment by claudiazuppy** [comment]
Hi @hknokh,
thanks now it works!!!
i have a question just for confirmation for my understanding: if i have a custom object related to the account by lookup (with this setting: 

**What to do if the lookup record is deleted? | Clear the value of this field.**

If i want delete also this record i have insert the csv for it and insert the reference in the json, is it correct?
{
    "objects": [
        {
            "operation": "DeleteHierarchy",
            "externalId": "Id",
            "query": "SELECT Id FROM Account"
        },
        {
            "operation": "Delete",
            "externalId": "Id",
            "query": "SELECT Id, Account__c FROM testLL__c"
        }
    ]
}

thanks,
Claudia

**Comment by hknokh** [comment]
Hello Claudia,

Your question not so clear for me, but just want to explain how does csv source work.

There are 3 steps in the process:

1) It always loads ALL records from each source CSV file, ignoring SOQL restrictions as WHERE, LIMIT etc.
It never respects relationships between the objects. 
(Relationships are being processed **ONLY** when **a SF ORG used as data source but NOT a CSV.**)

2) Then (after loading all records from the CSV files by the prev step) it selects  ALL records from the Target org, which are matching the loaded csv records using the given unique externalId field. 
(Also here it won't respect SOQL and relationships - instead it takes ALL records from the Target **which are matched** the loaded source by the externalId values)

3) It updates or deletes the target records, selected in the previous step.
 
**
The configuration to delete both Accounts and TestObject records by CSV files:

When Account Names and TestObject Names are unique and equal between the csv file and the Target org, so the Name field can be used as external id for both objects. If not - use other unique external id. 
The  Record Id field also can be used but if the **Id** column in your csv file contains exactly the record ids in the Target org.

Let's say that AccountId = 0012400000A7GLDAA3 - is the parent Account record you want to delete this account with the related TestObjects.

**Account.csv:**
Id | Name
-- | --
**0012400000A7GLDAA3** | ACC_TEST 1

**TestObject__c.csv:**
Id | Account__c | Account__r.Name
-- | -- | -- | --
a001p000019XvbaAAC | **0012400000A7GLDAA3** | ACC_TEST 1
a001p000019LJpGAAW | **0012400000A7GLDAA3** | ACC_TEST 1

**export.json:**
"objects": [
        {
            "operation": "DeleteHierarchy",
            "externalId": "Name",        
            "query": "SELECT Id FROM Account"
        },
        {
            "operation": "DeleteHierarchy",
            "externalId": "Name",           
            "query": "SELECT Account__c, Id FROM TestObject__c"
        }
    ]

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen it if you will have any additional questions or issues.

**Comment by claudiazuppy** [comment]
HI @hknokh,
thanks a lot for support and explanations.
Best regards,
Claudia

**Comment by hknokh** [comment]
You are welcome.
Wanted to add that if your CSV contains  exactly the record Ids you want to delete in the target org (so does not need external ids) then the config becomes simpler:
 

**Account.csv:**
Id |
-- |
0012400000A7GLDAA3

**TestObject__c.csv:**
Id |
-- |
a001p000019XvbaAAC
a001p000019LJpGAAW

**export.json:**
"objects": [
{
"operation": "DeleteHierarchy",
"externalId": "Id",
"query": "SELECT Id FROM Account"
},
{
"operation": "DeleteHierarchy",
"externalId": "Id",
"query": "SELECT Id FROM TestObject__c"
}
]
