### ISSUE TITLE
Limit number of Parent Records

### ISSUE THREAD

**Issue by jackwphillips** [forcedotcom/SFDX-Data-Move-Utility#3]
First, a big thank you for creating this plugin. I explored several plugins to help move data between orgs, and yours was the only one that worked well, had sufficient documentation, and handled complicated object relationships. 

Second, I am having some trouble limiting the number of parent records inserted into a new org with a limited number of child records.

E.g., Object_A__c (Parent) has many Object_B__c (Child). I only want a few Object_B__c records in the new org with the related Object_A__c records. The query for Object_B__c is "SELECT Id, Object_A__c FROM Object_B__c LIMIT 10". 

How do I limit the imported Object_A__c records to only the parents of the 10 selected Object_B__c records? Right now, all Object_A__c records are being imported.

Thanks for any insight you can offer.

**Comment by hknokh** [comment]
Hello, thank you for the feedback!

Basically your question sounds like in your migration schema you also have another child sObject let's call it Object_C__c, that also has Object_A__c as a lookup parent. If so and Object_C__c is not limited, this may force the Plugin to process all Object_A__c records even your Object_B__c is limited.

The LIMIT clause is like "suggested" to the Plugin as if you tell to the Plugin to TRY taking as less records as possible closest to your LIMIT depend on relationship between sObjects in your data model. In real life It is very difficult and in most cases impossible to automatically determine and track exact intersection between records in complex data model to process exact amount of 
records. But if you explicitly set the limits using WHERE clause not LIMIT it will really limit the records for you.

So in your case that you are using LIMIT clause I would suggest to set limitation MOST TOP LEVEL objects in your objects hierarchy, for example Object_A__c.
So the  Object_B__c should be limited automaically (in case that it has no child records from another sObjects that in some cases can "extend" it again).

**Comment by jackwphillips** [comment]
Thank you for your quick response. That was really helpful and I was able to limit the number of records using the appropriate WHERE clause. I still have some refining to do for my user case which has a lot of relationships between objects.
