### ISSUE TITLE
[FEATURE REQUEST]-Giving an option to simulate the target update without actual update

### ISSUE THREAD

**Issue by hknokh** [forcedotcom/SFDX-Data-Move-Utility#304]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to just see which target records will be affected by the data migration process prior to actulal record update. 
For example when we are deleting records, we would like to see how many records are about to be be deleted in order to ensure that we have anough available space in the recycle bin to restore the records in future.

It might be useful  when working with a real data.

**Describe the solution you'd like**
Having a new 'simulation' mode without actual update with some logging feature, saying how many records are about to be updated / deleted. So we will ensure that we are anough clear with this export.json configuration to run it in a live mode.

**Comment by hknokh** [comment]
Hello @claudiazuppy
In addition I implemented the new feature called "Simulation mode".
It allows you to check which target records will be affected by the export.json configuration without actial update / delete / insert. 
It produces the same output as the live mode (target files / logs) but no actual records affected.

To enable the simulation just set to true the new property in the global export.json scope:

{
      "objects": [
          ........
     ],
      **"simulationMode": true**
}

**Comment by claudiazuppy** [comment]
Hi @hknokh,
thanks for your support. For this new feature i have 2 questions:
1)the tool produces the csv files with id of the records, if we need more details (for example the name or other fields) is there a way to produce them?
2) just for confirmation, does the tool produce the csv files only for the objects that we have indicated in the json file?

Thanks,
Claudia

**Comment by hknokh** [comment]
Helo @claudiazuppy 

For the first question : try to add more fields to the delete query for example **select id, name from account**, for my opinion it should output all the fields which are included in the query.

For the second: yes.  
But if you're adding any extra lookups to the sobject query, for example you want to add RecordTypeId field - so RecordType.csv will also be produced. 
However, don't worries - it will not delete any extra sobjects in the live mode, because all objects which are not originally listed in the export.json will always have Readonly operation.
So you can check only the CSVs, which objects are explicitely included in the export.json file having Delete operation, because only those will be finally deleted when the tool is running in the live mode

**Comment by claudiazuppy** [comment]
Hi @hknokh,
for the use case 1 i attach the zip with our json and our result files. How you can see in the target folder we have 4 files but they contain only the id , for the file of the recordtype the tool produces the list of **all** recordtype in the org, i don't know the 
reason.
Also in the folder userCase1 we have only a csv file ( RecordType.csv) that contains the all recordType
 in the org, Why?

while for the use case 2: if you start the cancellation from account the tool delete also the opportunities and quotes, for example, i think that for the nature of the relationship between account - opty or account-quote, is it correct my interpretation?

[UseCase_1.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6478196/UseCase_1.zip)

Thanks,
Claudia

**Comment by hknokh** [comment]
Hi @claudiazuppy 

- For the RecordTypes - it's normally that it outputs all record types, this is how the Tool works, dismiss this.
BTW, generally, does not make sence to put RecordTypeId in the Opportunity for deletion - so that you will not have the RecordType.csv file produced at all.

- For the Opportunity and Quotes deleting - honestly, I don't understand your question.
What I see and can say you: in your export.json which file you sent me - you have put DeleteSource operation for all 3 objects: Account, Opportunity and Quote - so fo course it will delete all these objects. For the dependency handling only - use ReadOnly for undeletable objects.
The point is that you define by your own, which relationships between objects you want to process by putting correct lookup fields in the query. If you omit  lookup field in the child object,  it will not handle the parent dependency even the parent object is also in the export.json. All releationships are managed by lookups, staring from the master objects.

-  Recarding only id column in the CSV - indeed I see and have checked it.
According to the current implementation of the deletion, it uses only Id field and removes other fields from the query even you put them, so finally it produces only list of ids in the  target CSV.

**Comment by claudiazuppy** [comment]
Hi @hknokh,
thanks for your explanation. for the point 2 the situation is the following:
If you dont't put in the json file the opty and quote but only the account with the cancellation the record of related opty and quote are deleted also and you have the same result if you delete an account by UI of salesforce, so in this case the related records are deleted for the nature of the lookup o master-detail. 
thanks,
Claudia

**Comment by hknokh** [comment]
Hello @claudiazuppy 

It's correct **only in case of master-detail relationship**: if you will delete the parent record with SF UI so all related children will be deleted. This is is think will work for the Account -> Quotes (suppose it's master-detail).

But in case of **lookup relationship** it's **not correct**. If you delete the parent record this **will not delete its children automatically** but **only will clear the related lookup field** for the child records.
