### ISSUE TITLE
[FEATURE REQUEST]-Prompting confirmation when target is production

### ISSUE THREAD

**Issue by jkincaid-dbservices** [forcedotcom/SFDX-Data-Move-Utility#307]
**Is your feature request related to a problem? Please describe.**
The plugin could overwrite or destroy data in production if the target is accidentally set to production instead of a sandbox or scratch org.

**Describe the solution you'd like**
The plugin should prompt the user to type in a confirmation if the target is production (aka login.salesforce.com), similar to this article: https://uxmovement.com/buttons/how-to-make-sure-users-dont-accidentally-delete/. This prompt should happen right before running the migration. Ideally the user would type the my domain or instance domain name to their production org as a confirmation. That should prevent any accidents.

**Comment by hknokh** [comment]
Hello @jkincaid-dbservices 
Accepted. Thank you for the suggestion. I will check what I can do here.

**Comment by claboran** [comment]
Just one remark here, we are using sfdmu as an important part of our CI/CD pipelines. It is of course a good idea to have such a feature to prevent accidents, but it should work in pipelines so that you could set another switch like "I know what I am doing"...

**Comment by hknokh** [comment]
Hi 
this feature has been implemented since v4.4.0
See the changelog:
https://help.sfdmu.com/full-documentation/additional-information/changelog
and about the new flag:
https://help.sfdmu.com/full-documentation/configuration-and-running/run-the-migration-job

**Comment by hknokh** [comment]
***
The case has been closed for the current moment.
Feel free to reopen it if you will have any additional questions or issues.
