### ISSUE TITLE
Fields specified in the query string are being ignored

### ISSUE THREAD

**Issue by Kirill-H** [forcedotcom/SFDX-Data-Move-Utility#308]
Hi,

looks like with the latest version when when I specify fields names they are being ignored and the query only pulls the Id and extranlId fields from source org.

Now the log file line looks like:
Query string: SELECT Id, Deployment_Key__c  FROM  SBQQ__PriceRule__c.

Whilst before it was:
Query string: SELECT Id, Name, SBQQ__Active__c, SBQQ__AdvancedCondition__c, SBQQ__ConditionsMet__c, SBQQ__ConfiguratorEvaluationEvent__c, SBQQ__EvaluationEvent__c, SBQQ__EvaluationOrder__c, SBQQ__LookupObject__c, SBQQ__Product__c, SBQQ__TargetObject__c, Deployment... FROM  SBQQ__PriceRule__c.

The export.json file didn't change - and this is true to all objects in the file - this is just an example.

When I use built in functionality like readonly_false - it works as expected and the query string is correct.

Please look into it.

**Comment by hknokh** [comment]
Hi,
This case is closed due to the incorrect format of the request.
Please reopen it following our CASE OPENING GUIDELINES.
Thanks.
