### ISSUE TITLE
Issue loading quote / quote line items 

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#315]
Hello - We're using Salesforce CPQ. I'm testing data move utility and trying to load quote / quote line items  but getting errors.

Quote and Quote line items has master-detail relationship

I've attached export.txt and other files please help
[SBQQ__Quote__c_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6528865/SBQQ__Quote__c_insert_target.csv)
[SBQQ__QuoteLine__c_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6528866/SBQQ__QuoteLine__c_insert_target.csv)
[MissingParentRecordsReport.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6528867/MissingParentRecordsReport.csv)
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6528868/export.txt)

**Comment by gvpatel** [comment]
[2021-05-23__16_08_30.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6528871/2021-05-23__16_08_30.log)
log file

**Comment by hknokh** [comment]
Hello @gvpatel 
This query: SELECT Id, createable_true FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = 'a0q5e000000mY1FAAU'"
will not automatically include the lookup field to  SBQQ__Quote__c by createable_true.
Try to include the lookup field to SBQQ__Quote__c explicitely.

**Comment by hknokh** [comment]
***
Looks like your question is answered and we are closing the case for the current moment.
Feel free to reopen if you will have any additional questions.

**Comment by gvpatel** [comment]
hi @hknokh ,
I included the field SBQQ__Quote__c explicitly but still getting error.
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6532248/export.txt)
[SBQQ__Quote__c_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6532249/SBQQ__Quote__c_insert_target.csv)
[SBQQ__QuoteLine__c_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6532250/SBQQ__QuoteLine__c_insert_target.csv)
[MissingParentRecordsReport.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6532251/MissingParentRecordsReport.csv)
[2021-05-24__08_11_52.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6532252/2021-05-24__08_11_52.log)

**Comment by hknokh** [comment]
@gvpatel 
It is not an issue with the SFDMU.
The SBQQ__Quote__c is not inserted as well due to"invalid cross reference id" - so that the quote line records have no parent lookup record to populate.
You have to analyse why the error on the sobject SBQQ__Quote__c is there. 
Maybe - just i guess - recordtype is also need to be included in the SBQQ__Quote__c qiuery,

**Comment by gvpatel** [comment]
Hi @hknokh,

I investigated the issue and here is why i'm getting invalid cross reference id" error. Its due the incorrect row_id (foreign key)  in SBQQ__Quote__c object





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/patelgv/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/patelgv/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">








SBQQ__PriceBook__c | SBQQ__PricebookId__c
-- | --
01s5e000001phc0AAA | 01s5e000001phPcAAI








SBQQ__PriceBook__c  - 01s5e000001phc0AAA - This is the Id of CPQ5 Salesforce org of pricebook object. This is fine

 SBQQ__PricebookId__c - 01s5e000001phPcAAI - This is the Id of **CPQ4** Salesforce org of pricebook object


can you tell why I'm seeing Id of CPQ4 instance in the csv file? I'm migrating data from CPQ4 to CPQ5 org

**Comment by hknokh** [comment]
Hello @gvpatel 
Not sure that I am understanding you.
But may be you can try to incude field mapping definition to the SBQQ__Quote__c object to map between SBQQ__PricebookId__c and SBQQ__PriceBook__c (CPQ4-CPQ5) ?

**Comment by hknokh** [comment]
***
Hi,

We hope, that your case is already resolved and you're completely happy with our Plugin. 

We are closing the ticket for the current moment.

However, feel free to reopen it, if you want to add a response or you have any additional questions/ issues in relation to this subject.

Thanks!
