### ISSUE TITLE
[BUG] - Field Mapping On Custom Object With CSV Not Working But JSON Does

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#316]
When using Field Mapping on a namespaced custom object it is working fine if we put the fields in the JSON; however, if we use a CSV instead for the same fields we are not getting any results. We have confirmed the CSV does not have extra spaces or commas.

This is only happening on our custom object. Using Account and Contact the CSV is working fine.

**Comment by hknokh** [comment]
Hi, @veaux 
This case is closed due to the incorrect format of the request.
Please reopen it following our CASE OPENING GUIDELINES.
Thanks.

**Comment by hknokh** [comment]
***
Hi,

We hope, that your case is already resolved and you're completely happy with our Plugin. 

We are closing the ticket for the current moment.

However, feel free to reopen it, if you want to add a response or you have any additional questions/ issues in relation to this subject.

Thanks!

**Comment by veaux** [comment]
Missed this comment asking for files but did see dm saying fix was put in few weeks ago,
Did run into the issue again today. This time in the query as it appears to be looking for the targetField vs the sourceField. CSV mapping does not work but Json field mapping does.
12_46_44 log didn't work, other did.

[FieldMapping.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6639978/FieldMapping.txt)
[2021-06-11__12_46_44.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6639962/2021-06-11__12_46_44.log)
[2021-06-11__12_47_49.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6639963/2021-06-11__12_47_49.log)

**Comment by hknokh** [comment]
Hello @veaux 
Please, attach also the export.json which is using field mapping and it's working for you as you said.
Thx.

**Comment by veaux** [comment]
[exportjson.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6655862/exportjson.txt)
The file has a number of other objects in it. The object here I believe was hdone__Identifier__c. That is the section the fieldmapping is referring to.

**Comment by hknokh** [comment]
Hello @veaux 

While analysing your export.json,  I have seen something that isn't so clear for me:

- It's not correct to put "deleteOldData": true or Insert operation for the recordtype. 
https://help.sfdmu.com/full-documentation/advanced-features/handling-record-type
-  Account and Contact are mapped to the same objects - Account and Contacts. Why ?

Regarding your question.
As I understand, your FieldMapping.csv has incorrect format.

For example, the first row has **prov__Identifier__c** as the source object name (the **ObjectName** column)
And it also has **prov__AccountCustomerId__c** as a target object name (the **Target** column) but it appears to be a field name not an sobject name.
Please refer for the documentation about the correct  FieldMapping,csv format:
https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping

By your export.json definition your csv should look something like this:

**ObjectName**	**FieldName**	**Target**
hdone__Identifier__c	 	prov__Identifier__c
hdone__Identifier__c	hdone__AccountCustomerId__c	prov__AccountCustomerId__c
hdone__Identifier__c	hdone__Type__c	prov__Type__c
hdone__Identifier__c	hdone__Value__c	prov__Value__c

Moreover the **mockFields** definitions should contain the source field not the target (that is you are trying to mock the **prov__Value__c** which is target field according to the mapping definition of the same object). You need to mock hdone__Value__c instead.

**Comment by hknokh** [comment]
Hi,
We hope, that your issue is already successfully resolved and we are closing the case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
Thanks.
