### ISSUE TITLE
[GUI APP] Auto number, lookup field as external Id getting disappeared from the config file

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#319]
Hello - I'm testing data move for Salesforce CPQ. Here is my observation.

Auto number, lookup field as external Id is getting disappeared. - I updated External id (with 
Auto number, lookup fields) and it's getting automatically nullified.

Auto number, lookup fields NOT available in external Id lookup

<img width="884" alt="Screen Shot 2021-06-04 at 3 46 23 PM" src="https://user-images.githubusercontent.com/18720022/120855319-5047c800-c54c-11eb-8d05-b010dc0ad9a9.png">

**Comment by hknokh** [comment]
Hello @gvpatel 

Sorry, not fully understand your issue.

- Does you issue only with GUI APP ?

- I tried to put ID as External Id and it's accepted and applied to the JSON Config:
![image](https://user-images.githubusercontent.com/15181301/121236801-025df780-c89f-11eb-9e48-bdf2e6557417.png)
![image](https://user-images.githubusercontent.com/15181301/121237106-5c5ebd00-c89f-11eb-9133-e68315cb275d.png)

- lookup-type field can't be set as external id for the object, it should be other type (text, integer, auto-number, formula etc).

- What does it mean _"I updated External id (with Auto number, lookup fields) and it's getting automatically nullified."_ 
Do you mean, that you are using FieldMapping feature and there is a mapping from autonumber to some other field and it does not get populated in the Target with the source values ? 
If so, please supply all necessary files as described in our OPEN CASE GUIDELINES in order that I will be able to investgate your configurations and outputs.

**Comment by hknokh** [comment]
Hi, @gvpatel 
We hope, that your issue is already successfully resolved and we are closing the case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
Thanks.
