### ISSUE TITLE
[QUESTION] - Data upload via Query and CSV file and Compound fields

### ISSUE THREAD

**Issue by surajsinghstackaero** [forcedotcom/SFDX-Data-Move-Utility#322]
Hi,
We have installed the SFDMU plugin and are trying to use it to migrate data from a Salesforce org to a scratch org using the below two methods:
1. **Query** : The Geolocation fields are not getting created and there is no error logged. We followed the link - https://help.sfdmu.com/faq/troubleshooting/geolocation-data-type-data-not-updating-in-target-org
Below is the export.json file for the same.
[export.json_query.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6741093/export.json_query.txt)

2. **CSV file** : We added a CSV file in the same location as the export.json file but we get the below error in CSVIssuesReport file and no records are loaded. Can we insert geolocation field values as well with this method? : 
"Date update,Child sObject,Child field,Child value,Parent sObject,Parent field,Parent value,Error
2021-06-30  23:01:37.159,Airport__c,,,,,,CSV FILE DOES NOT EXIST"

The export.json file for CSV upload is attached below - The source fields are the exact column names in the CSV file used.
[export.josn_csv.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6741132/export.josn_csv.txt)

For CSV file method, can we please get a sample csv file with a sample export.json file to follow?

Please advice.

Thanks,
Surajsingh

**Comment by hknokh** [comment]
Hello
What i think, that first i am not sure, that compound geo fields are supported by the field mapping feature, i didnt check it. May be yes, but may be no. 
The query is correct.
Second, the field mapping rules are applied after the csv is loaded, so in the csv you need to have csv files named as the source  objects and contain the source fields, not the mapped ones.
To get proper csv file format working with geolocation fields i would advice to make a test migration org2csv with your configuration and see what csvs are created.

**Comment by hknokh** [comment]
Hi,
We hope, that your issue is already successfully resolved and we are closing the case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
Thanks.
