### ISSUE TITLE
[BUG]-In Windows sfdx sfdmu:run due to path parsing can't run

### ISSUE THREAD

**Issue by shawnholt** [forcedotcom/SFDX-Data-Move-Utility#324]
**Path using windows format fails, using local file it works**

**sfdx sfdmu:run --sourceusername GCOMigrate --targetusername csvfile --path G:\My Documents\SFDMU_APP\data\xxxxx-yyyyyyyyyyyyyyy-com\FirstConfig\ --verbose**

Gives error:
The flag value "G:\My Documents\SFDMU_APP\data\xxxxx-yyyyyyyyyyyyy-com\FirstConfig" --verbose" is not in the correct format for "directory."

**Will run**
If I substitute a "." for the path value, it processes.  e.g.
sfdx sfdmu:run --sourceusername GCOMigrate --targetusername csvfile --path . --verbose

Note I tried using double quotes around the path folder name but that didn't work. Seems to be a problem with the path parsing but not sure what it is.

**Comment by nvuillam** [comment]
Maybe you can try with / instead of \ in the path ? :)

**Comment by hknokh** [comment]
Hello @shawnholt 
As for me, when the path does not contain spaces or other weird symbols, I'm putting the path as is without any quotes . But if you have spaces, it can make problems. Try to move export.json to another directory or run the plugin from the destination directory, so you do not need to use -p. 
From my side, I'm using the built-in function to read flags from the CLI command, so can't control how the platform recognizes their values.

I'm closing this case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
