### ISSUE TITLE
[BUG]-No such column 'FirstName' on entity 'Group'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..

### ISSUE THREAD

**Issue by perseveregary** [forcedotcom/SFDX-Data-Move-Utility#332]
**Describe the bug**
I am trying to insert a single user from source org to target org and getting following error : 
No such column 'FirstName' on entity 'Group'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..

**To Reproduce**
Describe steps to reproduce the behavior.

**Expected behavior**
User record is inserted in target org

**export.json**
Attached

**Log file**
Attached
[export - Copy.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6927847/export.-.Copy.json.txt)
[2021-08-04__10_51_42.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6927850/2021-08-04__10_51_42.log)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello.
By the plugin implementation, migration of Users is not supported.
https://help.sfdmu.com/faq/common-questions/can-i-migrate-users-with-the-plugin
