### ISSUE TITLE
[QUESTION] - Anonymize data only if it is populated in Source org field

### ISSUE THREAD

**Issue by maninder-singh-liqid** [forcedotcom/SFDX-Data-Move-Utility#333]
I want to know if it is possible to anonymise data only if the field has value in source org. 
Example: 
- `Contact.Phone` has no value in the source org.
- `Contact` Object Settings:
updateWithMockData: `true`
- Data Anonymization settings:
Object: `Contact`
Field: `Phone`
Pattern: `Phone`
Exclude RegExp:
Include RegExp: `^(?!\s*$).+` (to exclude white spaces and blanks)
- When import is completed, it populates the `Contact.Phone` in target org with a mock value.

Expected: Since the source org field did not have a value, it should not populate mock value in target org field.

What Regexp i have tried?
I have tried Exclude RegExp: `^$` (checks for blank or null values)

**Comment by hknokh** [comment]
Hello @maninder-singh-liqid 
I think that I need to add this as a new option to the anonymization feature.
I will update you when done.

**Comment by hknokh** [comment]
Hello @maninder-singh-liqid 
I have added new feature to include/exclude empty values
https://help.sfdmu.com/full-documentation/advanced-features/data-anonymization
see "*" and "^*" special regex pattern
Please update the Plugin and let me know if it is working

**Comment by hknokh** [comment]
Hi there,
I hope, that your issue is already successfully resolved and I am closing this case for the current moment. 
However, feel free to ask for the additional help.
Thanks.
