### ISSUE TITLE
Insert getting failed when trying to move records from Sandbox to scratch org

### ISSUE THREAD

**Issue by rahulAlladaWAL** [forcedotcom/SFDX-Data-Move-Utility#336]
**1) How do i get the logs on why the insert is getting failed?** 
The logs which i get after running the command is:
 === LOADING AND VALIDATING THE PACKAGE SCRIPT ...
Running version: 4.4.5

[[Core Manifest]] Loading addon manifest ...
[[User Manifest]] Loading addon manifest ...
Connecting to fundpanel@demo.com.portalui3a using SFDX CLI ...
Successfully connected to fundpanel@demo.com.portalui3a.
Connecting to test-oakogjebbjgi@example.com using SFDX CLI ...
Successfully connected to test-oakogjebbjgi@example.com.
Package script: C:\Users\Lenovo.DESKTOP-PJIBGUQ\Documents\Aduro-ScratchOrgs\Aduro\SFDX-Data-Move-Utility\export.json.
SOURCE:         fundpanel@demo.com.portalui3a.
TARGET:         test-oakogjebbjgi@example.com.

=== GETTING AND ANALYSING OBJECTS METADATA ...
Getting metadata for Account (SOURCE)
Getting metadata for Account (TARGET)

=== PREPARING DATA MIGRATION JOB ...
Building migration strategy ...
Order of objects to retrieve data: Account
Order of objects to delete data: Account
Order of objects to update data: Account
Preparing has been finished.

=== GETTING THE TOTAL AMOUNT OF RECORDS LIMITED BY THE OBJECT'S SOQL QUERY ...
{Account} Total amount of the SOURCE records: 32
{Account} Total amount of the TARGET records: 1

=== PROCESSING ADDON HANDLERS ...
No handlers to process.

Ready to process the data.

=== DELETING OLD DATA FROM THE TARGET ...
{Account} No records to delete.

=== RETRIEVING THE DATA STEP 1 ...
{Account} Retrieving the SOURCE data from Org (STEP 1: all records) ...
{Account} Retrieving the SOURCE data has been completed. Fetched 32 new records.
Retrieving the data STEP 1 has been completed.

=== RETRIEVING THE DATA STEP 2 ...
PASS 1
=============
No records

PASS 2
=============
No records

PASS 3
=============
No records

PASS 4
=============
No records

TARGET
=============
{Account} Retrieving the TARGET data from Org (STEP 2: all records) ...
{Account} Retrieving the TARGET data has been completed. Fetched 1 new records.
Retrieving the data STEP 2 has been completed.

=== PROCESSING ADDON HANDLERS ...
No handlers to process.

=== DATA RETRIEVING SUMMARY
{Account} Total retrieved within all steps (source/target): 32/1 records.

=== UPDATING THE TARGET STEP 1 ...
{Account} The Insert API operation has been started using REST API.
[Job# REST:Insert] {Account} The job has been created. Uploading data ...
WARNING: [WARN] [Batch# REST:Insert] {Account} Incompleted. 0 records succeeded, 32 records failed.
{Account} The Insert API operation has been finished.
{Account} Updating the Target has been completed. Processed 32 records.
Updating the Target (STEP 1) has been completed. Total processed 32 records.

=== UPDATING THE TARGET STEP 2 ...
Nothing was updated

=== PROCESSING ADDON HANDLERS ...
No handlers to process.

=== DATA PROCESSING SUMMARY
{Account} Total processed within all steps (Insert + Update): 32 records.

=== PROCESSING ADDON HANDLERS ...
No handlers to process.

Command in progress ...... done
Command succeeded.
Execution of the command sfdmu:run has been finished. Exit code 0 (SUCCESS).
Total time elapsed: 00h 00m 58s 383ms .

**It would be helpful if i get the logs on why it is getting failed!**

**Comment by hknokh** [comment]
Hello @rahulAlladaWAL 
Please take a look on the _target.csv files, produced by the plugin on each run.
These are intended to report the details about the reason of the failures.
https://help.sfdmu.com/full-documentation/reports/the-target-csv-files
