### ISSUE TITLE
Self Lookup fields not getting inserted (Account.parentId)

### ISSUE THREAD

**Issue by rahulAlladaWAL** [forcedotcom/SFDX-Data-Move-Utility#337]
My **export.json** has:

{
    "objects": [
        {
            "query": "SELECT Id, Name,parentId,recordTypeId FROM Account",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}
**We have a validation which is in place that "Accounts(only specific recordType) are not supposed to get inserted without the parentId" and this validation is getting fired. Is the mapping with ParentId done after the accounts are inserted?** If yes, is there any tweak to perform to bypass this validation without deactivating the validation?

**Comment by hknokh** [comment]
Hello @rahulAlladaWAL 
The order as the Plugin acts is :
- Inserting records with recordtypeid
- Populating parentid
So no way, you shoud manually disable and enable the validation rule on the target.
