### ISSUE TITLE
[FEATURE REQUEST] - Ability to create, upsert Users

### ISSUE THREAD

**Issue by lodossDev** [forcedotcom/SFDX-Data-Move-Utility#338]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to create test users that only exists in sandboxes, and when these sandboxes get refreshed it would be nice to easily migrate these test users back into the sandbox.

**Describe the solution you'd like**
Ability to create or upsert users into sandboxes.

solution profiles and roles should exist in order for users to be created or upserted, my understanding is salesforce is supporting to create profiles through soap soon.

**Comment by hknokh** [comment]
Hello @lodossDev 
Thank you for the suggestion.
Currently we do not plan this update, but we will put it to the future roadmap.

**Comment by doudou23** [comment]
Hi,

I guess than this is why my User object is skipped. Da*** really need it too for sandboxes data. Btw is there a list of supported object? 

Many thanks !
