### ISSUE TITLE
[BUG]-Smart order swapping master detail child before parent even if parent is already before child

### ISSUE THREAD

**Issue by jkincaid-dbservices** [forcedotcom/SFDX-Data-Move-Utility#339]
**Describe the bug**
I have an example of a master detail child being swapped in front of the parent in the migration job task list when smart order is used.

**To Reproduce**
I haven't debugged the code extensively to know why the problem is happening, but I can show you a screenshot of vs code's debugger and what line I updated to fix the problem (line 221 in migrationJob.ts). The fix may not be the best way to resolve the problem as I don't understand the wider design of the codebase but wanted to show you what I did to fix it for my config.

**Expected behavior**
Smart order shouldn't put a master detail child insert job in front of a parent.

**export.json**
export.json, log and two screenshots attached. The two screenshots are the original code demonstrating the problem in debugger and the updated code that fixed the problem for my configuration.

[Smart Order Master Detail Bug 2021-08-28.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7071121/Smart.Order.Master.Detail.Bug.2021-08-28.zip)

**Comment by jkincaid-dbservices** [comment]
I ran into another issue with the smart order and master details (at least it seems like an issue because I don't understand the original reasons why some of these things are in the code): dynamic __r fields were being flagged as master detail fields, which was causing issues with the smart order. Please see this screenshot below:

![Screen Shot 2021-08-28 at 4 13 17 PM](https://user-images.githubusercontent.com/84359677/131230858-9268fcee-0434-4c61-b3eb-a5e6d2c4ddc7.png)

The smart order was assuming the security lookup was a master detail in the holding object because these dynamic __r fields are not updateable and are flagged as lookups, which meets the definition of a master detail in the sFieldDescribe.ts file's isMasterDetail( ) function.

I updated line 120 in sFieldDescribe.ts to ensure that __r fields are not flagged master detail. Please see this screenshot.

<img width="707" alt="Screen Shot 2021-08-28 at 5 02 56 PM" src="https://user-images.githubusercontent.com/84359677/131230942-3a408846-a553-49fb-a373-15544da306cf.png">

Adding that extra condition fixed the smart order issue I was running into.

**Comment by ethanmichel0** [comment]
@jkincaid-dbservices Hey, what is your top level object here? Is the account field 'CC_Email_Recipient__c' a lookup to AIM_Entity__c ?

**Comment by jkincaid-dbservices** [comment]
The master is AIM_Entity__c. CC_Email_Recipient__c is a lookup to user in the account object.

**Comment by hknokh** [comment]
Hello @jkincaid-dbservices 
First, thank you for the debugging and trying to find the solution to this issue.
I'm not completely understand how to reproduce this and what is happening.
In order to accept your solution I need to make my checks in real environment which I can see the same problems but there isn't.
Anyway I'm happy to hear that your change is working for you configuration.

**Comment by jkincaid-dbservices** [comment]
Thanks @hknokh. If I create a new trailhead org, am able to reproduce the issues, and then give you access to the org so you can debug the config on your end, would that work?

**Comment by jkincaid-dbservices** [comment]
Ok I believe I've reproduced the issue. Here are the steps:

1. Create two trailhead playground orgs.
2. Install this [unlocked package](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t6g000008ateoAAA) in both of them. It'll create the schema and records for the LWC superbadge challenge. The main focus with this schema is the master detail relationship between contact and boat (contact is master, boat is detail).
3. In both orgs, in the account object, create a lookup to contact. Doesn't matter what you call it but I named mine Primary Contact.
4. In both orgs, in the contact object, create a lookup to boat. Doesn't matter what you call it but I named mine Primary Boat.
5. Use this config file for your config: 
[Smart Order Issue Reproduction.cfg.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7112816/Smart.Order.Issue.Reproduction.cfg.zip). There should only be three objects: Accounts, Contacts, Boats. Boat is master. Each object is importing the all special field.
6. Run sfdmu. Doesn't matter which org is source and which is target since they are identical.

If all goes well, you'll see the migration job task order has boats importing before contacts, even though boat is a detail in the master detail.

<img width="1432" alt="Screen Shot 2021-09-05 at 9 53 45 PM" src="https://user-images.githubusercontent.com/84359677/132149948-d5ad77c7-ed86-4c3c-8ec2-9f55413bfe1c.png">

**Comment by jkincaid-dbservices** [comment]
You may be able to generalize this by doing the following in an existing org, but I haven't confirmed this:

1. Create a custom object in the existing org
2. In the custom object, add a master detail relationship field to contact.
3. In the account object, add a lookup field to contact.
4. In the contact object, add a lookup field to the custom object.
5. Create a config in SFDMU that includes these three objects, with the custom object as master, and all three importing the all special field.
6. Run SFDMU

**Comment by hknokh** [comment]
Hello, 
Thanks for the details provided!
I will look on it and let u know.

**Comment by jkincaid-dbservices** [comment]
Hi @hknokh do you have any additional questions about this? Would you like me to provide any additional information?

**Comment by hknokh** [comment]
Hi there,
I hope, that your issue is already successfully resolved and I am closing this case for the current moment. 
However, feel free to ask for the additional help.
Thanks.
