### ISSUE TITLE
[BUG]-Resources.json 'Suceeded' should be replaced with 'Processed'

### ISSUE THREAD

**Issue by ethanmichel0** [forcedotcom/SFDX-Data-Move-Utility#342]
**Describe the bug**
Here is a screen shot for the language after a batch is completed (resources.json)
![image](https://user-images.githubusercontent.com/55289720/132077192-2e89d093-0d33-47da-9ef6-c7779b177aa7.png)

The words should be 'processed' rather than 'suceeded', as the variable that is substituted represents the total records processed 

(see migrationjobtask.ts line 1667)

**To Reproduce**

This can be reproduced with any upload that is greater than the batch threshold (default is 200, see https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format). 

Here is the log output that occurred when I tried to seed accounts from one sandbox to another:

![image](https://user-images.githubusercontent.com/55289720/132077294-ebe1a850-4fb8-415a-90f6-844ccf8a6770.png)

As can be seen in the picture, in the lines before when the batch is 'In progress' there are 7859 accounts listed as 'Processed' and 
411 as 'Failed'. I confirmed that this number was correct by querying in the org. However on the next time there are 7859 accounts listed as 'Suceeded' which is not correct. 

**Expected behavior**
'Suceeded' should be replaced with 'Processed' to match the In process log outputs and the correct org

**export.json**

{
  "objects": [
    {
      "query": "SELECT Id ,AccountSource ,BillingCity ,BillingCountry ,BillingGeocodeAccuracy ,BillingLatitude ,BillingLongitude ,BillingPostalCode ,BillingState ,BillingStreet ,Credentialing_Type__c ,Default_Terms__c ,Description ,Fax ,Industry ,IsPartner ,Jigsaw ,MasterRecordId ,Name ,NumberOfEmployees ,One_Line_Invoices__c ,OperatingHoursId ,OwnerId ,ParentId ,Phone ,QuickbooksID__c ,Quickbooks_BillAddress_ID__c ,Quickbooks_Billing_Email_Address__c ,Quickbooks_Sync_Date_Time__c ,Quickbooks_Sync_Flag__c ,Quickbooks_Sync_Message__c ,SBQQ__AssetQuantitiesCombined__c ,SBQQ__CoTermedContractsCombined__c ,SBQQ__CoTerminationEvent__c ,SBQQ__ContractCoTermination__c ,SBQQ__IgnoreParentContractedPrices__c ,SBQQ__PreserveBundle__c ,SBQQ__PriceHoldEnd__c ,SBQQ__RenewalModel__c ,SBQQ__RenewalPricingMethod__c ,SBQQ__TaxExempt__c ,Separate_Invoice_Categories__c ,ShippingCity ,ShippingCountry ,ShippingGeocodeAccuracy ,ShippingLatitude ,ShippingLongitude ,ShippingPostalCode ,ShippingState ,ShippingStreet ,SicDesc ,Source_Key__c ,Type ,VOC__c ,Website FROM Account",
      "operation": "Upsert",
      "externalId": "Name"
    }
  ]
}

**Log file**

Relevant picture is attached above.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello @ethanmichel0 
This is fixed. 
Thanks
