### ISSUE TITLE
[QUESTION] - Documentation web down

### ISSUE THREAD

**Issue by janhudecek** [forcedotcom/SFDX-Data-Move-Utility#345]
Hi,

First of all, thanks for the tool, it's pretty cool.
However, the documentation site seems to be down (https://help.sfdmu.com/).

Hope you'll resolve it quickly.

Thanks a lot!

**Comment by hknokh** [comment]
Hello @janhudecek 
Thank you so much for your feedback!
Regarding the documentation site right now checked, it's up.
Please recheck from your side.

**Comment by hknokh** [comment]
I am closing this case for the current moment. However, feel free to ask for the additional help if need.
Thanks.

**Comment by janhudecek** [comment]
You're right, it's up now!

Once again, thanks for your work!
