### ISSUE TITLE
[QUESTION] - sfdmu finishing abruptly ? no error or warning whatsoever

### ISSUE THREAD

**Issue by perseveregary** [forcedotcom/SFDX-Data-Move-Utility#348]
i updated to latest version today and using the same export.json that was working before.  it starts processing but then just stops and says below

=== RETRIEVING THE DATA STEP 1 ...
{RecordType} Retrieving the SOURCE data from Org (STEP 1: all records) ...
{RecordType} Retrieving the SOURCE data has been completed. Fetched 142 new records.
{User} Retrieving the SOURCE data from Org (STEP 1: all records) ...
Command in progress ...... done

uploading log file and export.json file
[2021-10-01__16_09_32.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7264609/2021-10-01__16_09_32.log)
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7264613/export.json.txt)

**Comment by hknokh** [comment]
Hello.
It's weird. I did not make any critical or breaking changes for the last long time ago including several latest releases. So completelly can't tell you what is the reason of your issue. Re-Check your installation and try to run again.

**Comment by hknokh** [comment]
Hi there,
I hope, that your issue is already successfully resolved and I am closing this case for the current moment. 
However, feel free to ask for the additional help.
Thanks.

**Comment by hknokh** [comment]
Hello @perseveregary
Sorry for the late reply. 
I think that the Plugin failing to retrieve 1078727 users from your org. It's very large amount and can cause memory issues with the default environment settings. 
The brutal solution is extend the Node memory: 
https://help.sfdmu.com/faq/troubleshooting/i-have-an-javascript-heap-out-of-memory-error-how-to-resolve
The more recommended approach is to reduce the size of retireved user records.
Remove all lookups to the User object.
Hope it will help.
