### ISSUE TITLE
[QUESTION] - Contact lookup to Account not populating

### ISSUE THREAD

**Issue by gitmemattb** [forcedotcom/SFDX-Data-Move-Utility#352]
**Describe the bug**
When loading an Account, and a related Contact, the Contact loads successfully, except it does not populate the lookup to related Account.  (Contact field "AccountID".  No errors are given, both the Account and Contact load successfully other than the Contact->AccountID field not getting populated.

**To Reproduce**
Set up an export.json with Account, Contact, where the Contact references the Account by the Contact field AccountID.

**Expected behavior**
Once loaded, the Contact field AccountID is pointing to the Account, and the Contact shows up under related list under Account.

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7296591/export.json.txt)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (
[Contact_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7296586/Contact_insert_target.csv)
at least 1-2 relevant full rows).
[2021-10-06__12_12_53.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7296579/2021-10-06__12_12_53.log)

**Comment by hknokh** [comment]
Hello
Regarding the Upsert operation defined for the accounts, the record Id can't be used as externalid. Only insert operation supports record id to be an external id. Replace it with different unique field, like Name for instance.
And generally, it is highly recommended to put fields with a correct letter case in the query string, letting the plugin to better parse it.
