### ISSUE TITLE
[QUESTION] - Why does the app not detecting my org?

### ISSUE THREAD

**Issue by drewbalcita** [forcedotcom/SFDX-Data-Move-Utility#353]
I am trying to use the GUI app but the org where I will get the data records is not in the source list. 

![image](https://user-images.githubusercontent.com/87849119/136937984-6f638e23-9a30-4c80-9214-e27f2db88f83.png)

I have this error:

 Currently, there is no any salesforce Org defined in your current user profile.
Click here to retrieve the complete list of the salesforce orgs registered with the SFDX platform.

**Comment by drewbalcita** [comment]
@hknokh any update???

**Comment by hknokh** [comment]
Hello @drewbalcita 
Did you authorize your orgs to the SFDX using sfdx auth:web:login ?
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_flow.htm

**Comment by drewbalcita** [comment]
Hi @hknokh thank you for the response. Yes I have authorized the org and it is listed when I run the force:org:list.

**Comment by drewbalcita** [comment]
> BTW. Indeed I see all the cases opened, but as stated in the readme, we have no SLA regarding this project. Unfortunatelly, sometimes I have no time to respond right away, and it can take a long time, even weeks in some cases )) Sorry again.

>okay, I understand @hknokh

**Comment by hknokh** [comment]
Can you provide the output of your org:list (but don't forget to remove the sensitive data). 
Use 'Save as json button' to generate the file.
Thanks

**Comment by drewbalcita** [comment]
The Save as json button is not working too.

![image](https://user-images.githubusercontent.com/87849119/137079630-1110f3be-38d4-4e32-88fb-70b08ae1b284.png)

**Comment by hknokh** [comment]
Hi there,
I hope, that your issue is already successfully resolved and I am closing this case for the current moment. 
However, feel free to ask for the additional help.
Thanks.

**Comment by drewbalcita** [comment]
@hknokh thank you! will update the version and let you know
