### ISSUE TITLE
Is it possible to insert data with correct RecordType not using RecordTypeId?

### ISSUE THREAD

**Issue by hknokh** [forcedotcom/SFDX-Data-Move-Utility#373]
### Discussed in https://github.com/forcedotcom/SFDX-Data-Move-Utility/discussions/370

<div type='discussions-op-text'>

<sup>Originally posted by **ppeersgi** October 29, 2021</sup>
We are using sfdmu as part of a Salesforce project that is using sfpowerscripts as packaging an build system. We have some configuration data (custom object records) that we keep in our git repo, and that gets inserted into a target org using sfdmu insert operation. To be able for the inserted record to have the correct RecordType, we need to add an extra RecordType.csv file to the repo, which has an Id field, and refers to a field RecordTypeId in the custom object records csv file. It would be nice to not have the RecordType.csv in our repo (because RecordTypes are already stored there as metadata), and just use the RecordType.Name to have the correct RecordType being populated during the insert. Is that possible?</div>

**Comment by hknokh** [comment]
The issue was found in the CSV file parser when using the CSV sources w/o ID columns.
Working on the solution.
CC: @ppeersgi

**Comment by yuyutsa** [comment]
@hknokh Hey, I am not able to achieve this. Can you check if something is wrong below?

Export.json: 
{
    "objects": [
        {
            "query": "SELECT Id, Name,RecordType.DeveloperName FROM Account limit 1",
            "operation": "Insert",
            "externalId": "RecordType.DeveloperName"
        }
    ]
}

Account.csv:

Name,RecordType.DeveloperName
SFDMU test,AccRecType
