### ISSUE TITLE
[QUESTION] - Error The Delete API operation FAILED with message: self signed certificate in certificate chain.

### ISSUE THREAD

**Issue by claudiazuppy** [forcedotcom/SFDX-Data-Move-Utility#380]
Hi, 
during the run of the tool we have in the log the following error:
The Delete API operation FAILED with message: self signed certificate in certificate chain.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).

I attached the log file , the export.json 

Could you help me to understand the nature of the error?
Thanks,
Claudia
[2021-11-10__15_46_24.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7513824/2021-11-10__15_46_24.log)
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7513959/export.txt)

**Comment by hknokh** [comment]
Hello
Sorry, really don't know the nature of this.
Need to check the access to the SF from the local machine.
