### ISSUE TITLE
[APP-BUG]-windows based- Blank screen on GUI

### ISSUE THREAD

**Issue by arshi-hclt** [forcedotcom/SFDX-Data-Move-Utility#382]
*I followed the instructions installed all the software, checked the versions too, still getting  a blank screen for SFDMU GUI app.
I am using windows only

**Comment by arshi-hclt** [comment]
Can I have an update how to resolve this issue

**Comment by hknokh** [comment]
Hello
This is installation issue depend on the target environment configuration.
Need to reinstall until it will work.

**Comment by arshi-hclt** [comment]
there is no failure, no runtime error, just the screen is blank. I followed the same steps mentioned, request your help please

**Comment by hknokh** [comment]
The app should not give any warnings in this case. The blank screen is for incorrect installation of the electron component. Need to remove all and reinstall. I can not reproduce it but some users are having this ussue on their end.
@ylhutter I know you've faced similar issue. What is workarround?

**Comment by ylhutter** [comment]
Hi Arshi-hclt

From my experience back then when I tested this with Windows machine, I
managed to solve this problem by simply updating the SFDX CLI and
reinstalling the Electron.
Please try this and hoping this will unblock you to use the GUI.

Best,
Eyal

**Comment by sumanth-bolledla-acn** [comment]
Hi @hknokh / @ylhutter ,
I have the exact same issue, I tried updating sfdx-cli, and reinstalling Electron from scratch, but it didn't help. I'm still getting the blank screen.
I then tried downgrading to older version, I can see the GUI properly in older version, but then the older version fails to fetch the sfdx connections I have on my machine.

Hoping to get some fix on this.

Thanks,
Sumanth

**Comment by hknokh** [comment]
Hello guys
I'm very sorry, but currently I have no anough free time to fix it. 
The permanent solution requires deep remastering of the project files.  
I will look on it again as soon as I can. 
Sorry again.

**Comment by Benjamin38600** [comment]
@hknokh found a workaround: delete SFDMU GUI app folder > uninstall electron > install 
[windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) with "npm install --global windows-build-tools" > install again electron globally "yarn global add electron" > clone again repository of "SFDX-Data-Move-Utility-Desktop-App" > npm install > npm start 

It was for company PC environment installation.

Regards,
