### ISSUE TITLE
[BUG]-CSV Validation Missing Lookup ID Columns When IDs Excluded

### ISSUE THREAD

**Issue by georgwittberger-the-nu-company** [forcedotcom/SFDX-Data-Move-Utility#383]
When setting `"excludeIdsFromCSVFiles": true` in `export.json` and then importing data from CSV files using `-s csvfile` command line option the CSV validation yields `COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE` for all lookup ID fields used in `query` properties in `export.json`.

**Steps to reproduce**

1. Create `export.json` listed below.
2. Export data from org to CSV file using `-s sourcealias -u csvfile`.
3. Import data from CSV file to org using `-s csvfile -u targetalias`.

**Expected behavior**

Data import does not yield any CSV validation warnings because the CSV file contains the transformed lookup column.

It is expected (and working correctly) that lookup columns are not `RecordTypeId` and `TNU1_BillToContact__c` anymore but `RecordType.$$DeveloperName$NamespacePrefix$SobjectType` and `TNU1_BillToContact__r.Name` as transformed by the plugin during data export. CSV validation should take this special setting into account and check for transformed column names.

**export.json**

```json
{
    "excludeIdsFromCSVFiles": true,
    "promptOnIssuesInCSVFiles": false,
    "objects": [
        {
            "query": "SELECT DeveloperName, NamespacePrefix, SobjectType FROM RecordType WHERE SobjectType = 'Account' ORDER BY DeveloperName",
            "operation": "Readonly",
            "externalId": "DeveloperName;NamespacePrefix;SobjectType"
        },
        {
            "query": "SELECT Name FROM Contact WHERE Name = 'Existing Test Contact'",
            "operation": "Readonly",
            "externalId": "Name"
        },
        {
            "query": "SELECT Name, RecordTypeId, TNU1_BillToContact__c FROM Account WHERE Name LIKE 'TEST %' ORDER BY Name",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}
```

**Log file**

```
=== GETTING AND ANALYSING OBJECTS METADATA ...
Getting metadata for RecordType (TARGET)
Getting metadata for Contact (TARGET)
Getting metadata for Account (TARGET)

=== PREPARING DATA MIGRATION JOB ...
Building migration strategy ...
Order of objects to retrieve data: RecordType; Contact; Account
Order of objects to delete data: Account; Contact; RecordType
Order of objects to update data: RecordType; Contact; Account
Validating and repairing of the source CSV files ...
WARNING: [WARN] During the validation of the source CSV files 2 issues were found. See CSVIssuesReport.csv file for the details.
WARNING: [WARN] During the validation of the source CSV files 2 issues were found. See CSVIssuesReport.csv file for the details.
Preparing has been finished.

=== ANALYSING THE OVERALL DATA VLOLUME ...
{RecordType} Total amount of the TARGET records should be retrieved by the object's SOQL query: 5
{Contact} Total amount of the TARGET records should be retrieved by the object's SOQL query: 1
{Account} Total amount of the TARGET records should be retrieved by the object's SOQL query: 3
...
```

**CSVIssuesReport.csv**

```csv
Date update,Child sObject,Child field,Child value,Parent sObject,Parent field,Parent value,Error
2021-11-17  16:03:00.930,Account,RecordTypeId,,,,,COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE
2021-11-17  16:03:00.930,Account,TNU1_BillToContact__c,,,,,COLUMN DEFINED IN THE SCRIPT IS MISSING IN THE CSV FILE
```

**Comment by hknokh** [comment]
Hi.
I recently have fixed issue with the excludeIdsFromCSVFiles, can you please update to the latest version and retry?

**Comment by georgwittberger-the-nu-company** [comment]
I have tested plugin version 4.10.3 on Salesforce CLI version 7.129.0-c662c12 - unfortunately, the CSV issues are still reported during import from CSV file.

**Comment by hknokh** [comment]
Ok.

Can you tell me, which columns do you have in your source CSVs for each object ? 

Consider the following:

The **excludeIdsFromCSVFiles=true** does not make any special magic, it just says, that in your source CSV files you can omit columns for the lookup ids as RecordTypeId or TNU1_BillToContact__c.

But you still **HAVE** to include the column for all external id fields for the parent objects as well as all reference fields like TNU1_BillToContact__r.Name and RecordType.$$DeveloperName$NamespacePrefix$SobjectType for the child objects. 

These fields are **mandatory** to be included, since they are the highly required **PARENT / CHILD  External ID fields** which should be provided in order to let the Tool compare between the Source and the Target recods. 

The lookup ids are not mandatory when using **excludeIdsFromCSVFiles=true**.

Check if you are including all necessary fields in your CSVs. Even it compains about lookup id fields, the real issue can be with the missing child external ids.

**Comment by hknokh** [comment]
Ok, I will check it

**Comment by georgwittberger-the-nu-company** [comment]
The issue still persists with version 4.11.2 on Salesforce CLI version 7.130.1.

It seems like import of a CSV file does not take into account that with `"excludeIdsFromCSVFiles": true` it should not expect the pure ID fields but the transformed references created from the external IDs of the related objects.

However, please note that it is not a severe issue because it can be worked around easily by setting `"promptOnIssuesInCSVFiles": false` in the config file. This still prints the warning messages but makes the import complete successfully.

**Comment by hknokh** [comment]
Hello @georgwittberger-the-nu-company 
Maybe you are right and this is the broken scenario.  
I have to check if "promptOnIssuesInCSVFiles": true REQUIRES  leaving out all the lookup id fields.

**Comment by hknokh** [comment]
@georgwittberger-the-nu-company 

I've fixed the warning messages not to show them when it's unnecessary for missing lookup id columns (if "excludeIdsFromCSVFiles"= true)

So, for example, for missing TNU1_BillToContact__c it will not produce warning any more, but still will produce for Name.

BTW. besides of using "promptOnIssuesInCSVFiles": false you can also disable all prompts globally by putting --noprompt in the command line. 

I'm closing the ticket for now, please reopen upon your needs.
