### ISSUE TITLE
[QUESTION]-Trying to import FeedComment records linked to FeedItem through FeedItem Id polymorphic field

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#392]
**Describe the bug**
I am trying to to import FeedItem and its comments (FeedComment records) linked to FeedItem through FeedItem Id polymorphic field for a specific custom object (TR_User_Story__c). As far as I know in FeedComment object, FeedItem ID is a polymorphic lookup. I am following the steps to fo polymorphic lookups from SFDMU documentation. However SFDMU is adding into the query FeedItem.Name and this is what makes the query to fail:

> [09:42:24.473] {FeedComment} Query string: SELECT Id, CommentType, FeedItemId, IsRichText, Revision, Status, ThreadChildrenCount, ThreadLastUpdatedDate, ThreadLevel, CommentBody, FeedItem.Id, FeedItem.Name  FROM  FeedComment.
> [09:42:24.861][ERROR] Error during execution of the command: No such relation 'FeedItem' on entity 'FeedComment'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
> [09:42:24.863] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).

**To Reproduce**
Execute SFDMU with the below export.json file

**Expected behavior**
SFDMU should be able to import FeedComments and link them to their respective FeedItems previously imported in Salesforce, through FeedComment.FeedItemId polymorphic lookup

**export.json**
_{
            "query": "select CommentCount, IsRichText, LikeCount, ParentId$TR_User_Story__c, Revision, Status, Title, Type, Body, LinkUrl from FeedItem where Type IN ('TextPost', 'LinkPost', 'ContentPost') and Parent.Type = 'TR_User_Story__c' ",
            "operation": "Insert",
            "master": "true",
            "excludedFields": [
                "RelatedRecordId"
            ]
        },
        {
            "query": "select id, CommentType, FeedItemId$FeedItem, IsRichText, Revision, Status, ThreadChildrenCount, ThreadLastUpdatedDate, ThreadLevel, CommentBody  from FeedComment  ",
            "operation": "Insert",
            "master": "true",
            "excludedFields": [
                "RelatedRecordId"
            ]
        },_

**Log file**
> [09:42:24.473] {FeedComment} Query string: SELECT Id, CommentType, FeedItemId, IsRichText, Revision, Status, ThreadChildrenCount, ThreadLastUpdatedDate, ThreadLevel, CommentBody, FeedItem.Id, FeedItem.Name  FROM  FeedComment.
> [09:42:24.861][ERROR] Error during execution of the command: No such relation 'FeedItem' on entity 'FeedComment'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
> [09:42:24.863] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by jorgesolebur** [comment]
@hknokh can u take a look to the above issue? Thanks :-)

**Comment by hknokh** [comment]
Hello
FeedItemId of FeedComment is NOT a polymorhic field. It's standard refernece field to FeedItem entity.
Probably you should remove the ....$FeedItem ploymorhic definition from your query.
Reference here:
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_feedcomment.htm
See
![image](https://user-images.githubusercontent.com/15181301/147706206-b30bae08-21fa-40f8-a155-34d314bed728.png)
 Hope this will help you)

**Comment by jorgesolebur** [comment]
Hi @hknokh , 

However FeedItemId in FeedComment IS a polymorphic lookup. Salesforce documentation might not be updated. If you take a look to Describe API for FeedComment object (/services/data/v53.0/sobjects/FeedComment/describe) you will see the following : 

_{
            "aggregatable": true,
            "aiPredictionField": false,
            "autoNumber": false,
            "byteLength": 18,
            "calculated": false,
            "calculatedFormula": null,
            "cascadeDelete": false,
            "caseSensitive": false,
            "compoundFieldName": null,
            "controllerName": null,
            "createable": true,
            "custom": false,
            "defaultValue": null,
            "defaultValueFormula": null,
            "defaultedOnCreate": false,
            "dependentPicklist": false,
            "deprecatedAndHidden": false,
            "digits": 0,
            "displayLocationInDecimal": false,
            "encrypted": false,
            "externalId": false,
            "extraTypeInfo": null,
            "filterable": true,
            "filteredLookupInfo": null,
            "formulaTreatNullNumberAsZero": false,
            "groupable": true,
            "highScaleNumber": false,
            "htmlFormatted": false,
            "idLookup": false,
            "inlineHelpText": null,
            "label": "Feed Item ID",
            "length": 18,
            "mask": null,
            "maskType": null,
            "name": "FeedItemId",
            "nameField": false,
            "namePointing": false,
            "nillable": false,
            "permissionable": false,
            "picklistValues": [],
            "polymorphicForeignKey": true,
            "precision": 0,
            "queryByDistance": false,
            "referenceTargetField": null,
            "referenceTo": [
                "AccountFeed",
                "AdvAccountForecastFactFeed",
                "AdvAcctForecastSetPartnerFeed",
                "ApiAnomalyEventStoreFeed",
                "AssessmentIndicatorDefinitionFeed",
                "AssessmentTaskContentDocumentFeed",
                "AssessmentTaskDefinitionFeed",
                "AssessmentTaskFeed",
                "AssessmentTaskIndDefinitionFeed",
                "AssessmentTaskOrderFeed",
                "AssetFeed",
                "AssetRelationshipFeed",
                "AuthorizationFormTextFeed",
                "BatchJobFeed",
                "BatchJobPartFailedRecordFeed",
                "BatchJobPartFeed",
                "CampaignFeed",
                "CaseFeed",
                "CollaborationGroupFeed",
                "CommSubscriptionChannelTypeFeed",
                "CommSubscriptionConsentFeed",
                "CommSubscriptionFeed",
                "CommSubscriptionTimingFeed",
                "ConsumptionScheduleFeed",
                "ContactFeed",
                "ContentDocumentFeed",
                "ContractFeed",
                "CredentialStuffingEventStoreFeed",
                "CreditMemoFeed",
                "CreditMemoLineFeed",
                "DashboardComponentFeed",
                "DashboardFeed",
                "DocumentChecklistItemFeed",
                "EngagementChannelTypeFeed",
                "EnhancedLetterheadFeed",
                "EntitlementFeed",
                "EntityMilestoneFeed",
                "EventFeed",
                "FeedItem",
                "ImageFeed",
                "InvoiceFeed",
                "InvoiceLineFeed",
                "LeadFeed",
                "LegalEntityFeed",
                "LocationFeed",
                "LocationGroupFeed",
                "OpportunityFeed",
                "OrderFeed",
                "OrderItemFeed",
                "OtherComponentTaskFeed",
                "PartyConsentFeed",
                "Product2Feed",
                "ProductFulfillmentLocationFeed",
                "ProductItemFeed",
                "ProductItemTransactionFeed",
                "ProductRequiredFeed",
                "ProductTransferFeed",
                "ReportAnomalyEventStoreFeed",
                "ReportFeed",
                "SOSSessionFeed",
                "ServiceContractFeed",
                "SessionHijackingEventStoreFeed",
                "ShipmentFeed",
                "ShipmentItemFeed",
                "SignatureTaskFeed",
                "SignatureTaskLineItemFeed",
                "SiteFeed",
                "SolutionFeed",
                "TR_Technical_Design__Feed",
                "TR_Test_Execution_Step__Feed",
                "TR_Test_Execution__Feed",
                "TR_Test_Script__Feed",
                "TR_Ticket__Feed",
                "TR_User_Story__Feed",
                "TaskFeed",
                "ThreatDetectionFeedbackFeed",
                "TopicFeed",
                "UserFeed",
                "VisitFeed",
                "VisitedPartyFeed",
                "VisitorFeed",
                "WorkOrderFeed",
                "WorkOrderLineItemFeed"
            ],
            "relationshipName": null,
            "relationshipOrder": null,
            "restrictedDelete": false,
            "restrictedPicklist": false,
            "scale": 0,
            "searchPrefilterable": false,
            "soapType": "tns:ID",
            "sortable": true,
            "type": "reference",
            "unique": false,
            "updateable": false,
            "writeRequiresMasterRead": false
        },_

Also if I remove the "$FeedItem" from the query I get the following warning while runnning SFDMU (which makes sense because in the describe metadata API FeedItemId is polymorphic:

_Getting metadata for FeedComment (SOURCE)
Getting metadata for FeedComment (TARGET)
[WARNING] Object FeedComment: the field FeedItemId is missing declaration of the referenced sObject type (e.g. FeedItemId$Account). The field will be excluded from the process._

Thanks

**Comment by hknokh** [comment]
Ok, will recheck it

**Comment by jorgesolebur** [comment]
Thanks @hknokh :-)

**Comment by jorgesolebur** [comment]
Hey @hknokh did you have any time to look into this issue? Thanks ;-)

**Comment by hknokh** [comment]
Hey. 
No. I have currently no time for the Tool. Will update you when have news about your issue.

**Comment by jorgesolebur** [comment]
Hi @hknokh ! Did you have the chance to take a look? I would need to know if this is something SFDMU covers or not. We have a Chatter Data migration happening soon and our final approach depends on the feedback from this issue. Many thanks! 😄

**Comment by hknokh** [comment]
Hi @jorgesolebur 
My apologies...
I already put your issue on my pipeline for today/tomorrow. 
Lets look forward to get good news )

**Comment by jorgesolebur** [comment]
Hi @hknokh  - many thanks for your reply ! Waiting for any updates :-)

**Comment by hknokh** [comment]
Hey
Unfortunatelly, I'm not feeling well today... Have no other choice, but to postpone looking on this case. But will do once will feel better.
Good day.

**Comment by jorgesolebur** [comment]
Hi @hknokh  no worries I understand. I hope you can take a look next week if you have some time

**Comment by hknokh** [comment]
Hello  @jmattholland 

I was managed to investigated your case.

First, you should pay attention that FeedItemId is not updateable:

```
"sortable": true,
"type": "reference",
"unique": false,
*****"updateable": false,*****
"writeRequiresMasterRead": false
},
```
that is why you should simply get rid of whole FeedComment object from your export.json because it's not necessary and will cause problems. Leave only the FeedItem and the appropriate comments will be migrated automatically.

Please update to the latest version and retry without FeedComment object.
On my side it was tested on the Account feed items and found working well. The same thing must be for your custom object TR_User_Story__c.

**Comment by jorgesolebur** [comment]
Hi @hknokh , I hope you are doing well! I am not sure if you are aware, but in FeedItem Salesforce stored the main chatter posts taht users are doing in Chatter. However if someone reply to a post (by clicking into button "Comment") then that data is not stored as FeedItem but rather as FeedComment. After downloading the updated sfdmu version and runnin sfdmu, I realized that the main posts (FeedItem) have been successfuly migrated. However the comments that people can do towards these posts (feedComments) have not been migrated. Here is a quick example:
Original org - we have 1 post with 1 comment:
<img width="1619" alt="Screenshot 2022-03-11 at 8 43 55 PM" src="https://user-images.githubusercontent.com/31279773/157869
143-98b610f0-04e1-42cf-83ca-ae1d46705b9e.png">

But this is what was migrated: only the main post and not the comment:
<img width="538" alt="Screenshot 2022-03-11 at 8 45 47 PM" src="https://user-images.githubusercontent.com/31279773/157869267-a9a4fc5d-484c-4fa1-91ce-6f5337dffdc3.png">

How can we migrated FeedComment? I do not think we should remove feedcomment form export.json because it is necessary to be migrated. If we are not including it we will not migrate the comments that people do on top of posts.

**Comment by Paul-SFDC** [comment]
hi @jorgesolebur , did you find a solution for this? I'm currently trying to migrate FeedComments as well and noticed this message in the log file:
`sObject FeedComment will be excluded from the process.`
thx

**Comment by hknokh** [comment]
Hello @Paul-SFDC @jorgesolebur 
Good news!) I've added the support to FeedItem/FeedComment to the SFDMU
Note that only the **Insert** is supported for that objects.
Use the export.json like yours, but include FeedItemId  in the FeedComment's query **without** polymorphic syntax.

**Comment by hknokh** [comment]
Note! You should put FeedComment to **"master": "false"** to allow automatic selecting all child FeedComments to the selected parent FeedItems
