### ISSUE TITLE
[BUG] - Files attachments between 2 orgs

### ISSUE THREAD

**Issue by mathieurodrigues** [forcedotcom/SFDX-Data-Move-Utility#394]
**Describe the bug**
I try to transfer contacts with files attached from an org to another. I've got an error at the end of the process, see log file attached.

**To Reproduce**
Create a contact with a file test.txt attached, execute command _sfdx sfdmu:run --sourceusername testsource --targetusername testdest_. The contact is imported in destination org but not the file.

**Expected behavior**
The file attached with the contact in source org is imported in destination org.

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7792318/export.json.txt)

**Log file**
[2021-12-29__16_24_48 .log.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7792319/2021-12-29__16_24_48.log.txt)

Thanks for your help.
Regards

**Comment by mathieurodrigues** [comment]
It works, thanks Haim ! :)

**Comment by hknokh** [comment]
Good news!
