### ISSUE TITLE
Does not appear to work with scratch orgs

### ISSUE THREAD

**Issue by svallejo** [forcedotcom/SFDX-Data-Move-Utility#4]
The following command does not work  sfdx sfdmu:run -s csvfile -u migDest
where migDest is a scratch org.  

Root cause appears to be the authentication verification method in SFDXUtils , which uses sfdx force:org:display  results with the ConnectedStatus parameter.  For scratch orgs, this property is not present, as illustrated by the below value : 

```
Access Token     00D0R0000002pZi!AQwAQMt.Ski1KbeogS9z0YfRnRCEFdnb2z8Y6h8yT6jTAPg                                                                               aDSXWaeKad3J641DRy8nA_e0ILqGGS1G0_mPsDwNX8P3.BA4f
Alias            testSprint-08
Client Id        PlatformCLI
Created By       123digitaladmin@bsci.com
Created Date     2020-03-04T01:25:08.000+0000
Dev Hub Id       123digitaladmin@bsci.com
Edition          Enterprise
Expiration Date  2020-03-11
Id               00D0R0000002pZiUAI
Instance Url     https://force-enterprise-253.cs94.my.salesforce.com/
Org Name         123PlatformDX
Status           Active
Username         test-wssnura6bemv@example.com
```

This causes all auth attempts to fail.

**Comment by hknokh** [comment]
Thank you for the detailed report. I will fix that and will update the case status ASAP.

**Comment by hknokh** [comment]
The issue should be solved. Update you version of the SFDMU and retry. I have no option to test it with scratch org myself. Please keep me updated if it is working for you.
