### ISSUE TITLE
[QUESTION] - BadWords filter article :)

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#401]
I created an article with a tutorial about how to use SFDMU to detect badwords in the database

If you want to add it in [documentation](https://help.sfdmu.com/full-documentation/add-on-api/records-filter-core-add-on-module), it may help users :)

@hknokh I mentioned you with your github account, but if you prefer a twitter or linked in, or even not be mentioned, please tell me and I'll update the article :)

https://nicolas.vuillamy.fr/how-to-detect-bad-words-in-salesforce-records-using-sfdx-data-loader-and-sfdx-hardis-171db40a9bac

Best regards

**Comment by hknokh** [comment]
Hey @nvuillam 
Wow! Cool article. Great job done!
Did you already test the new BadWords filter ? Is it working as expected ?
BTW, suggest you to check the updated version. I've already checked it in my side but would be great you to recheck it again.

**Comment by nvuillam** [comment]
I made the article tutorial demo with the latest version of sfdmu + the tiny updates of my latest PR, so I confirm it works well :)

**Comment by hknokh** [comment]
Thank you  @nvuillam 
Looking forward to collaborate with you.
