### ISSUE TITLE
[BUG]-Breaking change from 4.11.9 to 4.11.10 when using the "readonly_false" multiselect keyword.

### ISSUE THREAD

**Issue by tfuda** [forcedotcom/SFDX-Data-Move-Utility#403]
**Describe the bug**
I have an export.json file that looks like the following:
```
{
  "objects": [
    {
      "query": "SELECT readonly_false, RecordTypeId FROM Account",
      "operation": "Upsert",
      "externalId": "Name",
      "master": true
    },
    {
      "query": "SELECT readonly_false, RecordTypeId FROM Contact",
      "operation": "Upsert",
      "externalId": "Name"
    }
  ],
  "allOrNothing": true,
  "keepObjectOrderWhileExecute": true,
  "promptOnUpdateError": true,
  "promptOnIssuesInCSVFiles": true,
  "promptOnMissingParentObjects": true
}
```
I exported Accounts and Contacts from a scratch org to the "csvfile" target using this export.json with SFDMU version 4.11.9. The resulting Contact.csv file looked like the following:
```
Id,Name,AccountId,LastName,FirstName,Salutation,OtherStreet,OtherCity,OtherState,OtherPostalCode,OtherCountry,OtherLatitude,OtherLongitude,OtherGeocodeAccuracy,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry,MailingLatitude,MailingLongitude,MailingGeocodeAccuracy,Phone,Fax,MobilePhone,HomePhone,OtherPhone,AssistantPhone,ReportsToId,Email,Title,Department,AssistantName,LeadSource,Birthdate,Description,EmailBouncedReason,EmailBouncedDate,Jigsaw,CleanStatus,IndividualId,Account.Name,ReportsTo.Name,Individual.Name
0031D00000gAyydQAC,Test Contact 1,0011D000013Xc1IQAS,Contact 1,Test,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Pending,,Test Account 1,,
0031D00000gAyyiQAC,Test Contact 2,0011D000013Xc1SQAS,Contact 2,Test,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Pending,,Test Account 2,,
```
Note the presence of the AccountId column in the exported Contact.csv file. When I subsequently use these exported CSV files to import the data into a different scratch org, the Contacts and Accounts are correctly linked via the Contact.AccountId field. However, if I perform the same export operation using version 4.11.10, I get the following Contact.csv file:
```
Id,Name,LastName,FirstName,Salutation,OtherStreet,OtherCity,OtherState,OtherPostalCode,OtherCountry,OtherLatitude,OtherLongitude,OtherGeocodeAccuracy,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry,MailingLatitude,MailingLongitude,MailingGeocodeAccuracy,Phone,Fax,MobilePhone,HomePhone,OtherPhone,AssistantPhone,Email,Title,Department,AssistantName,LeadSource,Birthdate,Description,EmailBouncedReason,EmailBouncedDate,Jigsaw,CleanStatus
0031D00000gAyydQAC,Test Contact 1,Contact 1,Test,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Pending
0031D00000gAyyiQAC,Test Contact 2,Contact 2,Test,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Pending
```
Note that AccountId is no longer included in the exported Contact.csv file. Naturally this causes problem when importing these Contacts and Accounts into a different org, because they are not properly linked together via the Contact.AccountId relationship.

**To Reproduce**
* Install SFDMU plugin version 4.11.10 or higher.
* Create an SFDX project and create two scratch orgs; one to serve as the "source" and one the "target".
* Create one or more Contacts, each with a parent Account in the "source" org.
* Create a "data" directory at the root of your project folder and copy content of the export.json I provded above into an export.json file in the "data" directory.
* Execute the command ```sfdx sfdmu:run -s <sourceorguser> -u csvfile -p ./data``` (or .\data on Windows)
* Observe the Contact.csv file created in the "data" directory does NOT contain the AccountId field
* Import the data into the target org using the command ```sfdx sfdmu:run -s csvfile -u <targetorguser> -p ./data``` (or .\data on Windows)
* View the imported Contacts and Accounts in the target org. You will notice they are unbound; Contact.AccountId is null, and the Contacts related list on the Accounts have no child records.
* Delete the imported Contacts and Accounts from the target org.
* Uninstall the SFDMU plugin and install version 4.11.9 and repeat the command to export the data.
* Observe the Contact.csv file now contains AccountId.
* Import the data again. This time you will notice the Contacts and Accounts are properly bound.

It should also be noted that when exporting with v4.11.9, empty Individual.csv and OperatingHours.csv files get created, because the Contact query includes the IndividualId field, and the Account query includes the OperatingHoursId field. These are not created with 4.11.10. 

**Expected behavior**
I expect the "readonly_false" multiselect keyword in the queries specified in export.json to result in the same fields being exported between versions 4.11.9 and 4.11.10 and higher.

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7817724/export.json.txt)

**Log file**
Attaching two logs; one generated by exporting using 4.11.10, and one with version 4.11.9:
[v4.11.10.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7817732/v4.11.10.log)
[v4.11.9.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7817743/v4.11.9.log)

**_target.csv** file.
N/A

**Comment by alinmocanuwork** [comment]
I don't think this is because readonly_false, but about any related records, they are not queried and matched anymore
It happens for me too, I hope it's a small fix

**Comment by tfuda** [comment]
@alinmocanuwork my point in calling attention to readonly_false is that I believe the change made in 4.11.10 made it so that when readonly_false is used, the list of fields that get injected into the generated query is now omitting M/D and Lookup fields, so yes, it's more than just AccountId that is being excluded from the query. I was trying to provide a simple repro case. I have a complex schema with many custom objects and multiple levels of parent/child relationships. I'm seeing that with 4.11.10, I cannot import the data that I exported using 4.11.9 any more, because the queries generated by the readonly_false multiselect keyword are leaving out the fields that define these parent/child relationships.

**Comment by alinmocanuwork** [comment]
Even if I try to put, in the query, manually, let's say: select accountid from contact, he cannot match it right. Even if it queries the field, it doesn't play with right with the external id

**Comment by alinmocanuwork** [comment]
@tfuda until we have a fix for this. Do you have any idea how can I install that exact version 4.11.9, that is working? I really need this to work next week

**Comment by tfuda** [comment]
Be sure to uninstall the currently installed version first:
```
sfdx plugins:uninstall sfdmu
sfdx plugins:install sfdmu@4.11.9
```

**Comment by pgumiela** [comment]
@hknokh, just wanted to highlight that it's not an isolated case. I have the same problem and needed to downgrade the plugin as well.

**Comment by hknokh** [comment]
Hey all
I've fixed that issue. 
It should now include lookups into multiselects. 
Please update to the latest v4.12.3 and check it.

**Comment by tfuda** [comment]
Thank you for the quick fix. I can confirm that version 4.12.3 solves the problems I was seeing with importing records related via M/D and Lookup fields.
