### ISSUE TITLE
[QUESTION] - Unable to retrieve the Source metadata. Check your Org access.

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#405]
- Ask your question or what kind of help you need.

Thank you for this awesome data migration solution. I am using the 3.1.11 of the GUI app and have done multiple migrations. However, today, when trying to connect and move from two Salesforce Sales Demo orgs. I get the following error: Unable to retrieve the Source metadata. Check your Org access.

force:org:display shows connected. If I run an export.json created from a previous Sales Demo Org, using the CLI command, the data migration works. It seems only the GUI app has an issue reading the metadata from these two IDOs.

Thanks,
Carlton

**Comment by hknokh** [comment]
Hello
You should make sure that you have no any errors while performing "normal" SFDX CLI commands via the CMD or terminal. 
Please, refer here:
https://help.sfdmu.com/faq/gui-app/the-application-is-failing-to-connect

In summary, the org:list / org:display commands must give a clean result  without any extra messages or texts besides the correct output.

Thanks
