### ISSUE TITLE
Issue migrating data, but no detailed error

### ISSUE THREAD

**Issue by fedegiust** [forcedotcom/SFDX-Data-Move-Utility#41]
Hi 

I'm trying to test this plugin which looks great but haven't been able to make it work

I am trying to migrate 3 objects, only 1 record per object

There is a master object, then a child object

![image](https://user-images.githubusercontent.com/1804862/82712091-9b52ae00-9c5d-11ea-8c1a-6025c87ab81b.png)

Is there any way to see more details? I tried with the debug logs but couldn't figure it out

Thanks

**Comment by hknokh** [comment]
Hello,
You can find details about all failed records in the **Target CSV File**, created by the Plugin.
Please, see the information about this feature here:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/5.-Reports.
Regards
