### ISSUE TITLE
[QUESTION] Virtual External Id field for lookups

### ISSUE THREAD

**Issue by steals** [forcedotcom/SFDX-Data-Move-Utility#410]
Hello,

Is it possible to configure the Virtual External id field for a lookup field? I.e. I have several parent records with the same name but different values in a custom field. Also I have several child records linked to the previous ones. And I need to migrate child records.
As I understood from the logs lookup fields are matched based on the "Name" field, but is it possible to configure to match not only be name but name + some custom field?

**Comment by hknokh** [comment]
Hello @steals 
Hope this is what you are looking for:
https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys
