### ISSUE TITLE
[FEATURE REQUEST] - SFDMU:RUN command with "-h" flag produces error

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/SFDX-Data-Move-Utility#414]
**Describe the bug**
Running the `sfdmu:run -h` command produces the following error 
```
ERROR running sfdmu:run:  HelpClass is not a constructor
```
There was a recent [CLI issue #1325](https://github.com/forcedotcom/cli/issues/1325) which references this error.  It appears that it was solved but may be relevant to what this issue is about.

**To Reproduce**
* Install `sfdx-cli@7.134.0`
* Install `sfdmu@4.12.6` 
* Run command `sfdx sfdmu:run -h` 

**Expected behavior**
See the help menu for the command

**export.json**
n/a

**Log file**
n/a

**_target.csv** file.
n/a

**Comment by hknokh** [comment]
@ImJohnMDaniel 
ok. Thank you for directing me. You are definitely right regarding the dependencies. 
But from other hand --help command is not something breaking issue that actually prevents from using the plugin so for my opinion it's not so urgent to be handled. My main problem is that changing the dependencies may cause issues in the plugin. And probably need to do a lot of regression tests so I don't so happy to play with dependencies.
But will see how to do it in future.

**Comment by hknokh** [comment]
Yes you are right. 
I already have put this thing in my Roadmap.
Thanks !
