### ISSUE TITLE
[QUESTION] - Should self referencing import work from csv files?

### ISSUE THREAD

**Issue by gretarvp** [forcedotcom/SFDX-Data-Move-Utility#415]
When I import accounts from one org to another with ParentId the account parent-child relationships are created in the target org.  When I use the same setup but first create csv files and then import those csv files to the target org the parent-child relationships are not created. Is this as expected?

**Comment by hknokh** [comment]
Hello

Understand that you have an issue with self-reference field.

Can't reproduce it on my end.

I've checked importing/exporting of self-reference fields with the following configuration:
{
    "objects": [
        {
            "operation": "Insert",
            "externalId": "Name",
            "deleteOldData": true,
            "query": "SELECT ParentId FROM Account WHERE Name = 'ACC_10000' OR Name = 'ACC_10084' "
        }
    ]
}

I have  ACC_10084 is parent for ACC_10000

When exporting to CSV, I got this CSV:
Id,ParentId,Name,Parent.Id,Parent.Name
0011p00002Zh1jVAAR,0011p00002Zh1krAAB,ACC_10000,0011p00002Zh1krAAB,ACC_10084
0011p00002Zh1krAAB,,ACC_10084,,

After csv import both ACC_10000 and ACC_10084 are created for me and ACC_10000 has parent account record of ACC_10084 as expected.

Attached image from the target org:
![image](https://user-images.githubusercontent.com/15181301/153547785-a35ed543-2ef7-46bf-8061-afaea2bfb24b.png)

Please recheck your configraiton
