### ISSUE TITLE
[APP-BUG]- SFDX-Data-Move-Utility-Desktop-App-3.1.8 window has no content.

### ISSUE THREAD

**Issue by JCripe-AuthorSolutions** [forcedotcom/SFDX-Data-Move-Utility#422]
**Describe the bug**
When starting the SFDX-Data-Move-Utility-Desktop-App-3.1.8, running with SFDX-Data-Move-Utility-4.12.5, the window opens, but doesn't have any content at all.

**To Reproduce**
1. Installed SFDX-Data-Move-Utility-4.12.5 per directions, and did available security updates.
2. Installed SFDX-Data-Move-Utility-Desktop-App-3.1.8 per directions, and did available security updates.
3. Opened a command window in the SFDX-Data-Move-Utility-Desktop-App-3.1.8 directory and ran "npm start".
4. The app window opened, showing "sfdx-data-move-utility-desktop-app" in the window's title bar, but the window itself had no contents whatsoever.

**Expected behavior**
The window should have shown the app.

**Comment by JCripe-AuthorSolutions** [comment]
My co-worker was having the same problem.

**Comment by hknokh** [comment]
Hello
Seems to be installation problem. Try to reinstall.
***
In generally, the GUI app is not maintained any more and the repo has been archieved.
I forgot to put notification about this and did this now. I also have unlinked the SFDMU repository from the GUI repo.
You can still continue using the GUI App as is but there is no support and no bugfixes.
For this momen you should try to create the export.json for the SFDMU manually using our [Documentation](https://help.sfdmu.com)
