### ISSUE TITLE
How to use the tool for Upsert

### ISSUE THREAD

**Issue by nikhileshmishra** [forcedotcom/SFDX-Data-Move-Utility#424]
My team uses below command for upsert csv file with records

sfdx force:data:bulk:upsert -s Letter_Attributes__c -f ./src-data/Letter_Attributes__c/Letter_Attributes__c.csv -i Letter_Name_External__c --json --wait 10 -u QA

We have installed sfdx dmu plugin in our system
Can you please guide how can we use the plugin performing above operation ?
Please guide with the command

**Comment by hknokh** [comment]
Hello,
Thank you for using the SFDMU.
Unfortunatelly, as stated in our repo's README, for the moment we don't provide support for configuration/migration-related questions or issues.
Please reffer our [Help Center](https://help.sfdmu.com/) instead.

**Comment by nikhileshmishra** [comment]
How do we use for upsert using the tool in general can u share.

**Comment by hknokh** [comment]
You use the Upsert operation for the object you want to upsert:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format
https://help.sfdmu.com/quick-start

**Comment by nikhileshmishra** [comment]
@hknokh Thanks a lot
