### ISSUE TITLE
[QUESTION] - Encountered error while running command

### ISSUE THREAD

**Issue by nikhileshmishra** [forcedotcom/SFDX-Data-Move-Utility#425]
we have our export.json ready in directory in the format mentioned .
and we ran below command after authorization to upsert the csv file with records from the root directory where csv & export.json is present.
**sfdx sfdmu:run --sourceusername Letter_Attributes__c.csv -u qa**

We encountered below error .please suggest with solution if any steps missed
======================================
Execution of the command sfdmu:run has been started.

=== LOADING AND VALIDATING THE PACKAGE SCRIPT ...
Running Plugin version: 4.12.6
Running Add-On Api version: 1.3.0

Loading core Add-On declarations ...
Connecting to Letter_Attributes__c.csv using SFDX force:org:display ...
ERROR running force:org:display:  No authorization information found for username Letter_Attributes__c.csv.
Command in progress ...... done
[ERROR] Execution of the command was ABORTED due to unexpected error: Command failed: sfdx force:org:display --targetusername Letter_Attributes__c.csv
ERROR running force:org:display:  No authorization information found for username Letter_Attributes__c.csv.
.
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
Total time elapsed: 00h 00m 08s 389ms .
PS C:\Users\nmishr39\aarp-crm-sf\src-data\Letter_Attributes__c>

**Comment by hknokh** [comment]
Hello @nikhileshmishra 
I noticed, you use incorrect syntax of CLI command.
Make as following:
- Put the Letter_Attributes__c.csv in the same folder where the export.json file is located.
- Go to this folder and run: sfdx sfdmu:run --sourceusername **csvfile** -u qa
This tells that you want to use csv files as a data source (not org).
I believe that you have a correct export.json containing definition for Letter_Attributes__c
Reffer also here: 
https://help.sfdmu.com/full-documentation/configuration-and-running/run-the-migration-job

**Comment by nikhileshmishra** [comment]
@hknokh Thanks a lot for your solution. Works now.
