### ISSUE TITLE
[BUG] - Incorrect MD detection

### ISSUE THREAD

**Issue by hknokh** [forcedotcom/SFDX-Data-Move-Utility#426]
Possible issue with MD detection while creation of  migration job plan.

_Originally posted by @hknokh in https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/411#issuecomment-1026576215_

**Comment by nazim-aliyev** [comment]
Hi @hknokh, I see this item is marked as closed, but we are still struggling to make it work with out data model setup :(

We are forced to have a local fork with fix from PR #411 to make it somehow work.

Any chance you could look into this please? Happy to provide any additional information required to move this forward.

Additional note, that have been missed in my initial description, we are not really migrating from org-to-org, we are importing from CSV files that we generated as part of export.

Thanks!

**Comment by hknokh** [comment]
Hi @nazim-aliyev 

Please, create a new feature branch from the current Contribute branch with your fix and submit a new PR according to our actual [Contribution Policy](https://help.sfdmu.com/full-documentation/additional-information/code_contribution_policy)
I will look on it again.

Thanks!

**Comment by hknokh** [comment]
I think your fix is already applied:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/a647be5107dda0a700be2d8ea1dc2ea5d002a350/src/modules/models/job_models/migrationJob.ts#L199

**Comment by nazim-aliyev** [comment]
Hi @hknokh, thanks for re-opening this!

I did create a new PR to Contribute branch with proposed fix - https://github.com/forcedotcom/SFDX-Data-Move-Utility/pull/503


> I think your fix is already applied:
> https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/models/job_models/migrationJob.ts#L199

My fix is exactly the same, but for `___putMasterDetailsBefore` function (line 221), fix you linked does it for `___updateQueryTaskOrder` function. Logic of both functions is very similar, so it really makes sense to do the same check there.

**Comment by hknokh** [comment]
@nazim-aliyev 
Merged & Deployed to the master.
Thx.

**Comment by nazim-aliyev** [comment]
@hknokh Thank you very much!
