### ISSUE TITLE
[BUG]-Export Document Object Records without binary

### ISSUE THREAD

**Issue by lioram** [forcedotcom/SFDX-Data-Move-Utility#429]
**Describe the bug**
I try to export some Documents Records with the plugin SFDX and I not get the binary part when I import to the sandbox I don't have the right file. I obtain a blob error.

**To Reproduce**
{
      "query":"SELECT Id, FolderId$Folder, Name, DeveloperName, NamespacePrefix, ContentType, Type, IsPublic, BodyLength, Body, Url, Description, Keywords, IsInternalUseOnly, IsBodySearchable FROM Document",
      "operation":"Upsert",
      "externalId":"Name",
      "master": false,
      "afterAddons" : [
        {
            "module": "core:ExportFiles",
            "args" : {
                "operation" : "Insert"
            }
        }
    ]
    }

**Expected behavior**
Export and Import Document into my sandbox

**export.json**
{
      "query":"SELECT Id, FolderId$Folder, Name, DeveloperName, NamespacePrefix, ContentType, Type, IsPublic, BodyLength, Body, Url, Description, Keywords, IsInternalUseOnly, IsBodySearchable FROM Document Where Folder.Name='PDF Template'",
      "operation":"Upsert",
      "externalId":"Name",
      "master": false,
      "afterAddons" : [
        {
            "module": "core:ExportFiles",
            "args" : {
                "operation" : "Insert"
            }
        }
    ]
    }

**Comment by hknokh** [comment]
Document object is NOT currently supported by the exportfiles add on. Currently only ContentDocument and its related sobjects are supported. See the docs related to the ExportFile  addon.
However,  I have put this feature request on my development roadmap.
Thanks for the mentioning me!
