### ISSUE TITLE
[QUESTION] - Mismatch org metadata error: Object Banker is missing in the Source

### ISSUE THREAD

**Issue by AndreyShestakovACN** [forcedotcom/SFDX-Data-Move-Utility#430]
**Describe the bug**
When trying to retrieve Banker records, I'm receiving the error:
`=== GETTING AND ANALYSING OBJECTS METADATA ...
Getting metadata for Banker (SOURCE)
Command in progress ...... done
[ERROR] Mismatch org metadata error: Object Banker is missing in the Source..
Execution of the command sfdmu:run has been finished. Exit code 3 (ORG_METADATA_ERROR).`

**The SOQL query on export.json is confirmed in the sandbox.**

**To Reproduce**
1. Create **export.json**
2. run the command:
`sfdx sfdmu:run --sourceusername <Sanbox_Alias> --targetusername csvfile`

**Expected behavior**
I was able to retieve other objects, such standard Account, Lead, as well as FSC Finserv_FinancialAccount__c

**export.json**
`{
    "objects": [
        {
            "query": "SELECT Id, Name FROM Banker",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}`

**Log file**
[19:21:22.128] {"Running version":"4.4.7"}

[19:21:22.252] [[Core Manifest]] Loading addon manifest ...
[19:21:22.267] [[User Manifest]] Loading addon manifest ...
[19:21:26.489] Connecting to <Sandbox_Alias> using SFDX CLI ...
[19:21:47.372] Successfully connected to <Sandbox_Alias>.
[19:21:47.861] {"SOURCE":"<Sandbox_Alias>.","TARGET":"csvfile.","Package script":"C:\\data\\export.json."}

[19:21:47.867] GETTING AND ANALYSING OBJECTS METADATA ...
[19:21:47.869] Processing the sObject Banker ...
[19:21:47.872] Getting metadata for Banker (SOURCE)
[19:21:48.110][ERROR] Mismatch org metadata error: Object Banker is missing in the Source..
[19:21:48.113] Execution of the command sfdmu:run has been finished. Exit code 3 (ORG_METADATA_ERROR).
[19:21:48.116] Total time elapsed: 00h 00m 26s 067ms .

**_target.csv** file.
no target file for Banker object created

**Comment by AndreyShestakovACN** [comment]
found the cause - the default API version SFDMU uses is 52.0. **Branch Management** objects requires 53.0 or better 54.0
So, on the export.json - I added the apiVersion:
`"apiVersion": "54.0"`

**Comment by hknokh** [comment]
Thank you very much for location the issue.
Probably I will add a detection of the latest apiversion supported by the client's org and this will become the default api version unless set explicitly via export.json.

**Comment by hknokh** [comment]
Hello @AndreyShestakovACN,

Thank you again for the feature suggestion.
This feature has been implemented in the latest version of the SFDMU.
Please reinstall the plugin and try.

Please, see also the doc articles:
- [Script Object - apiVersion (String in float format)](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object#apiversion-string-in-float-format) - default auto-selection rules and explicit override behavior.
- [Running - --apiversion](https://help.sfdmu.com/running#--apiversion) - CLI override behavior and default auto-detection flow.
- [Run Command Flags - apiversion](https://help.sfdmu.com/full-documentation/reports/run-command-flags#apiversion) - quick reference for the flag and default selection logic.

Best regards
