### ISSUE TITLE
[BUG]-Unable to import Attachment - Error during execution of the command: line 1:45 extraneous input ','

### ISSUE THREAD

**Issue by grand-wazoo** [forcedotcom/SFDX-Data-Move-Utility#431]
**Describe the bug**
SFMDU version 4.4.5 works fine (!!!!). This functionality broke in a later version. When I import an attachment with latest version - it throws an error (see log for full stack):
[ERROR] Error during execution of the command: line 1:45 extraneous input ','
When I downgrade back to version 4.4.5 it starts working again. Unfortunately, I need to use the latest.

**To Reproduce**
Import record into object with attachment using latest version of SFDMU

**Expected behavior**
sfdmu should not crash.

**export.json**

>  {
>     "objects": [
>       {
>         "operation": "Upsert",
>         "externalId": "Name",
>         "mockFields": [],
>         "fieldMapping": [],
>         "deleteOldData": false,
>         "updateWithMockData": false,
>         "mockCSVData": false,
>         "targetRecordsFilter": "",
>         "excluded": false,
>         "useCSVValuesMapping": false,
>         "useFieldMapping": false,
>         "useValuesMapping": false,
>         "master": true,
>         "excludedFields": [],
>         "query": "Select Id, Auto_Upload_To_EDM__c, Name, SDOC__Active__c, SDOC__Allow_Create_New_Attachment__c, SDOC__Allow_Edit__c, SDOC__Allow_Toggle_Task_Creation__c, SDOC__Auto_Create_Attachment_On_Email__c, SDOC__Base_Object__c, SDOC__Base_Related_Object__c, SDOC__Box_Enabled__c, SDOC__Component_IDs__c, SDOC__ContactRole__c, SDOC__Contact_Quick_Pick_Clause__c, SDOC__Content_Version_Field_JSON__c, SDOC__Core_Version__c, SDOC__Create_Attachment_Name__c, SDOC__Create_Attachment__c, SDOC__Create_File__c, SDOC__Create_New_Attachment_with_Each_Edit__c, SDOC__Default__c, SDOC__Description__c, SDOC__Document_Category__c, SDOC__Dont_Save_Mass_Merge_Docs__c, SDOC__Dont_Wrap_Word_Doc_In_Table__c, SDOC__E_Sign_Days_Until_Expiration__c, SDOC__E_Sign_Vendor__c, SDOC__Email_From_OrgWideAddressId__c, SDOC__Email_From_OrgWideAddress_Only__c, SDOC__Email_From_Use_Signature_If_User_Email__c, SDOC__Email_From_User_Override__c, SDOC__Email_Lock_Body__c, SDOC__Email_Lock_SendTo__c, SDOC__Email_Lock_Subject__c, SDOC__Email_Lock_bcc__c, SDOC__Email_Lock_cc__c, SDOC__Email_Require_Subject__c, SDOC__Email_Restricted_Domains__c, SDOC__Email_ReturnToRecord__c, SDOC__Email_SendTo__c, SDOC__Email_Send_To_Long__c, SDOC__Email_Subject__c, SDOC__Email_bcc__c, SDOC__Email_cc__c, SDOC__Enable_Detail_Reports__c, SDOC__Finished_Preprocessing_Docx_Template__c, SDOC__Footer2__c, SDOC__FooterSame__c, SDOC__Footer__c, SDOC__GD_Enabled__c, SDOC__GD_Use_Native_Format__c, SDOC__Google_Drive_Folder_Id__c, SDOC__Has_Error__c, SDOC__Header2__c, SDOC__HeaderSame__c, SDOC__Header__c, SDOC__InclArticles__c, SDOC__Language__c, SDOC__MSX_Rich_Text_Image_Dimensions__c, SDOC__MS_Embed_Images__c, SDOC__MS_FPFooter_BackGrndImgStyle__c, SDOC__MS_FPFooter_BackGrndImgUrl__c, SDOC__MS_FPFooter_Content__c, SDOC__MS_FPHeader_BackGrndImgStyle__c, SDOC__MS_FPHeader_BackGrndImgUrl__c, SDOC__MS_FPHeader_Content__c, SDOC__MS_Header_And_Footer_Definitions__c, SDOC__MS_Line_Items_In_Header_Or_Footer__c, SDOC__MS_Page_Definition__c, SDOC__MS_Page_Footer_Margin__c, SDOC__MS_Page_Header_Margin__c, SDOC__MS_Page_Height__c, SDOC__MS_Page_Margin_Left__c, SDOC__MS_Page_Margin_Right__c, SDOC__MS_Page_Width__c, SDOC__MS_SPFooter_BackGrndImgStyle__c, SDOC__MS_SPFooter_BackGrndImgUrl__c, SDOC__MS_SPFooter_Content__c, SDOC__MS_SPHeader_BackGrndImgStyle__c, SDOC__MS_SPHeader_BackGrndImgUrl__c, SDOC__MS_SPHeader_Content__c, SDOC__MS_Unit_of_Measure__c, SDOC__MS_Use_Advanced_Properties__c, SDOC__Mass_Merge_Allow_Email__c, SDOC__Mass_Merge_Clear_Email_Jobs__c, SDOC__Mass_Merge_Clear_Jobs__c, SDOC__Mass_Merge_Exclude_Page_Breaks__c, SDOC__Mass_Merge_Page_Break_Every_N_Docs__c, SDOC__Mass_Merge_Sort_Field__c, SDOC__Mass_Merge_Summary_Document__c, SDOC__Master_Template__c, SDOC__Num_Splitters__c, SDOC__Org_Agnostic_ID__c, SDOC__PDF_Unicode__c, SDOC__Preview_ID__c, SDOC__Related_Lists__c, SDOC__Remind_After_Generate__c, SDOC__Remind_Before_Expire__c, SDOC__Remove_Attachment_On_Delete__c, SDOC__Restore_Link__c, SDOC__S3_Enabled__c, SDOC__SD_K__c, SDOC__SSign_Hide_Logo__c, SDOC__Save_Data__c, SDOC__Show_Warning_Messages__c, SDOC__Tags_2__c, SDOC__Tags__c, SDOC__Task_Auto_Create_Default__c, SDOC__Task_Auto_Create__c, SDOC__Task_Details_Override__c, SDOC__Task_Due_Add_Business_Only__c, SDOC__Task_Due_Add_Days__c, SDOC__Task_Status__c, SDOC__Task_Subject__c, SDOC__Template_CSS_XML__c, SDOC__Template_Format__c, SDOC__Template_XML10__c, SDOC__Template_XML2__c, SDOC__Template_XML3__c, SDOC__Template_XML4__c, SDOC__Template_XML5__c, SDOC__Template_XML6__c, SDOC__Template_XML7__c, SDOC__Template_XML8__c, SDOC__Template_XML9__c, SDOC__Template_XML_Encode10__c, SDOC__Template_XML_Encode2__c, SDOC__Template_XML_Encode3__c, SDOC__Template_XML_Encode4__c, SDOC__Template_XML_Encode5__c, SDOC__Template_XML_Encode6__c, SDOC__Template_XML_Encode7__c, SDOC__Template_XML_Encode8__c, SDOC__Template_XML_Encode9__c, SDOC__Template_XML_Encode__c, SDOC__Template_XML__c, SDOC__Terms_XML_Encode__c, SDOC__Terms_XML__c, SDOC__TranslationTags__c, SDOC__Unicode_Level__c, SDOC__User_Choice_Definitions__c, SDOC__Version_History_Keep_Limit__c, SDOC__Version__c, SDOC__XML_Mass_Merge_Master_Tag__c FROM SDOC__SDTemplate__c WHERE Name in ('P201')"
>       },
>       {
>         "operation": "Upsert",
>         "externalId": "Name;BodyLength",
>         "query": "SELECT Body, BodyLength, Id, Name, ParentId$SDOC__SDTemplate__c FROM Attachment",
>         "master": false
>       }
>     ],
>     "pollingIntervalMs": 5000,
>     "bulkThreshold": 200,
>     "bulkApiVersion": "2.0",
>     "bulkApiV1BatchSize": 9500,
>     "keepObjectOrderWhileExecute": false,
>     "allOrNone": false,
>     "promptOnUpdateError": true,
>     "promptOnMissingParentObjects": false,
>     "promptOnIssuesInCSVFiles": false,
>     "validateCSVFilesOnly": false,
>     "apiVersion": "49.0",
>     "createTargetCSVFiles": true,
>     "importCSVFilesAsIs": false,
>     "alwaysUseRestApiToUpdateRecords": false,
>     "excludeIdsFromCSVFiles": false,
>     "fileLog": true,
>     "allowFieldTruncation": false
> }

**Log file**
[2022-02-23__20_02_24.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8128840/2022-02-23__20_02_24.log)

**_target.csv** file.
N/A

**Comment by hknokh** [comment]
Hello @grand-wazoo 
Thanks for finding the bug.
Fixed, please retest again.

**Comment by grand-wazoo** [comment]
Confirmed. Thank you.
