### ISSUE TITLE
[BUG]-Exclude ContactId from "all" when used on Opportunity

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#432]
**Describe the bug**

The use of "all" field crashed when the SObject is opportunity
The reason is that Opportunity.ContactId is not a "normal" lookup relationship but more some SF internal hack -> querying Opportuniy.Contact.stuff does not work, as explained in the following post

https://salesforce.stackexchange.com/a/268070/33522

```shell
[ERROR] Error during execution of the command:
Campaign.Name, Pricebook2.Name, Contact.Name, LastAmountChangedHistory.Id
                                ^
ERROR at Row:1:Column:1315
Didn't understand relationship 'Contact' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
```

**To Reproduce**
On any org, use the following export.json configuration

```json
{
  "objects": [
    {
      "query": "SELECT all FROM Opportunity",
      "operation": "Upsert",
      "externalId": "Name"
    }
  ]
}
```

**Expected behavior**
No crash :)

**To solve**

Exclude Opportunity.ContactId from automated built list of field from "all"

I tried to make a PR but got a little lost... @hknokh I'm sure you know how to do that quickly 👼 

Many thanks :)

**Comment by hknokh** [comment]
Hello @nvuillam 
Thanks for directing me to the issue.
Fixed. Please recheck.

**Comment by nvuillam** [comment]
@hknokh thanks a lot, I'll provide feedback once tested, probably tomorrow:)
