### ISSUE TITLE
[FEATURE REQUEST]-SFDMU Documentation should include reference to case sensitivity for composite keys

### ISSUE THREAD

**Issue by shaunvallejo** [forcedotcom/SFDX-Data-Move-Utility#437]
For composite external id fields(at least), the attribute access for the composition of the external key is case sensitive to the API name of the field being accessed.  In instances where the field does not match, the external id component for the mismatched field is simply ignored.   It would be great if this requirement is explicitly stated in the documentation in sfdmu.help

**Comment by hknokh** [comment]
Hello @shaunvallejo 
Thanks for the suggestion.
Added this statement:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format
![image](https://user-images.githubusercontent.com/15181301/159263596-18ebc530-9a2a-4aaa-bd33-70934dceca5b.png)
