### ISSUE TITLE
[BUG]-externalId field is not recognized as part of the query string

### ISSUE THREAD

**Issue by Kirill-H** [forcedotcom/SFDX-Data-Move-Utility#438]
**Describe the bug**
**externalId** field is not recognized as part of the query string
Look at the log file at line 17

**To Reproduce**
Run a simple Upsert with multiselect fields and where condition on account object

**Expected behavior**
As I provide the field in the query string, I expect it to be recognized

**export.json**
`{
    "objects": [
        {
            "query": "SELECT Unique_Id__c, readonly_false FROM Account WHERE (PersonMailingCity = 'Birmingham' OR ShippingCity = 'Birmingham' OR Physical_City__c ='Birmingham') AND Agent__c = 'LMUK' AND Unique_Id__c !='' ORDER BY ParentId NULLS FIRST",
            "excludedFields" : ["Active_Account_Plan__c", "Primary_Contact__c", "Magento_Store__c", "CloudGento__Magento_Store__pc"],
            "operation": "Upsert",
            "externalId": "Unique_Id__c"
        }
    ]
}`

**Log file**
[2022-03-21__11_28_33.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8312309/2022-03-21__11_28_33.log)

**Comment by hknokh** [comment]
@Kirill-H 
Didn't manage to reproduce.
I used this export.json:
{
    "objects": [
        {
            "operation": "Upsert",
            "externalId": "TEST_RO__c", 
            "query": "SELECT TEST_RO__c, readonly_false FROM Account WHERE Name = 'ACC_10000'"
        }
    ]
}

It successfully recognizes the TEST_RO__c with the rest of fields and incudes it into the query string.
I tried both formula and text field types for the externalid - all is working fine.

In the bottom line, the message, that you have:
"[INFO] Resolution of the child lookup field Account.ParentId: the external Id field Unique_Id__c set for the sobject Account is not found in the query string of Account. Id will be used instead as the external Id for this object." - says that the Tool failed to find metadata for the Unique_Id__c in the Source and/or in the Target org.
I would suggest to verify the metadata existance in both orgs and the field access.

**Comment by Kirill-H** [comment]
Thanks for looking into it @hknokh
I ran again today from a different PC and the issue didn't repeat.
I spent all morning yesterday trying to see what I was doing wrong without success, today just changing to a different PC and the issue is gone.
Do you think it might have something to do with VS-Code authentication to Salesforce and storing an access token that might not had access to the field? Thinking that the initial token didn't have access to the field as it was deployed recently, when the token expired and a new one was generated it received access to the new field?

**Comment by hknokh** [comment]
Honestly, don't know to say you. Don't think that this is something wrong with VSCode, mostly with the org authentication itself. 
Access token is intended to give user a general access to org, including all user's permissions, regardless of specific permissions to objects or  fields whether they are old or new. The access token or refresh token seem not to be referenced to any snapshots of user's permissions. But indeed it's a good practics to reconnect on any permission issue.
