### ISSUE TITLE
No message about the reason of failed insertions

### ISSUE THREAD

**Issue by ilanhazan** [forcedotcom/SFDX-Data-Move-Utility#44]
Hello,
I am trying to insert new records. In the Source there are 46 records however the process insert 0 records and I cant find the reason.

=== RETRIEVING THE DATA STEP 1...
{Commitment__c} Retrieving the SOURCE data from Org (STEP 1: all records)...
{Commitment__c} Retrieving the SOURCE data has been completed. Fetched 46 new records.
Retrieving the data STEP 1 has been completed.

=== RETRIEVING THE DATA STEP 2...
PASS 1
=============
No records

PASS 2
=============
No records

PASS 3
=============
No records

PASS 4
=============
No records

TARGET
=============
No records
Retrieving the data STEP 2 has been completed.

=== DATA RETRIEVING SUMMARY
{Commitment__c} Total retrieved within all steps (source/target): 46/0 records.

=== UPDATING THE TARGET STEP 1...
Nothing was updated

=== UPDATING THE TARGET STEP 2...
Nothing was updated

=== DATA PROCESSING SUMMARY
{Commitment__c} Total processed within all steps (inserted + updated): 0 records

Command in progress...... done
Command succeeded.
Execution of the command sfdmu:run has been finished. Exit code 0 (SUCCESS).
Total time elapsed: 00h 00m 20s 322ms .

**Comment by hknokh** [comment]
Hello @ilanhazan 
I guess you are trying to Upsert (in future, please, provide also your export.json to let me better understand your problem). 
Therefore, when you are performing upsert or update and the target records  have no any differencies with the source records (meaning you didn't make any changes in the source after last update of the target) the Plugin detects that the records are equal and does nothing. 
The Plugin always compares the records before processing to avoid overuse of the API.

**Comment by hknokh** [comment]
@ilanhazan 
And of course it would better if you could debug it locally, because in such kind of issues these are just my assumptions and I can miss something)

**Comment by ilanhazan** [comment]
Hello,
I added more fields in the query:
 {
            "operation": "Insert",
            "externalId": "Name",
            "query": "SELECT Id, Name, Deal__c, Status__c, Type__c FROM Commitment__c where Deal__r.Name LIKE 'MigVax%'",
            "allRecords": false
        }     
and now it fails but showing only this comment:
[Job# REST:Insert] {Commitment__c} The job has been created.
WARNING: [WARN] [Batch# REST:Insert] {Commitment__c} Incompleted. 0 records succeeded, 46 records failed.

Where should I look?

**Comment by hknokh** [comment]
Morning @ilanhazan 
Well, now I can understand why previously you didn't have anything updated: the reason is because you didnt add any updateable fields in your query.
Ok, now the next step is to get information about failed records and you need to look in /target subdirectory that should be created by the plugin where your export.json sits.
Find the file named like Commitment__c_insert_target.csv, you have Error column says what's the error message on each row.
Let me know if you have this file there.
And this is the doc about the reports produced by the plugin:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/5.-Reports.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/5.-Reports.)

**Comment by ilanhazan** [comment]
Thank you @hknokh 
I found the file and it reports on missing field.
I will investigate it and let you know about this issue.
A question: why it happened for only this object that I query only for Id,Name it didnt show any message? These are new records as the target is empty.

**Comment by hknokh** [comment]
@ilanhazan 
Maybe your name is autonumber

**Comment by hknokh** [comment]
You need at leas one updateable field in your query
