### ISSUE TITLE
[BUG] How Do We Use Boolean Values For ValueMapping?

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#440]
Keep getting error "value not of required type" for boolean field. The org value is false and I want the target to be true. Tried:
#N/A,1
false,true
FALSE,TRUE
'false','true'
0,1

Same error for all of the above. All other fields that are not using ValueMapping are working fine.

**Comment by hknokh** [comment]
Hello @veaux 
You should use like:
ObjectName,FieldName,RawValue,Value
Account,TEST_CHK__c,false,true
Please update and retry because I made some fix for this.
