### ISSUE TITLE
RecordTypeId in Desktop Application  

### ISSUE THREAD

**Issue by krushithAnde** [forcedotcom/SFDX-Data-Move-Utility#443]
Im trying to work with Desktop Application where i need to send SObject data from one org to another based on record type id,
Recordtype id's are different in source and target orgs. can you please suggest any work around how to send data to Sobject with different recordtype Ids and some SObjects and fields are not picking up , that are api version 51 or later.

**Comment by hknokh** [comment]
Hello @krushithAnde 
This is the article about RecordType:
https://help.sfdmu.com/full-documentation/add-on-api/custom-sfdmu-add-on-api
