### ISSUE TITLE
[FEATURE REQUEST]-strict mode to secure use in production

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#446]
**Is your feature request related to a problem? Please describe.**
It's great that sfdmu does not crash a lot, but I think that sometimes it should, especially when we deal with production environments

**Describe the solution you'd like**
Would it be possible to add a `--strict` mode to avoid messing with production databases and seing it only later when checking in `target` folder logs ?

Here are some cases that I already noticed when trying to import data from manually built CSV files

- Field not accessible to the current user
  - current behavior: the records are imported, without setting the field value
  - expected behavior: error saying "The field OBJ.FIELD that you are trying to import is not accessible to the current user: please provide RW  rights on OBJ.FIELD to be able to import this data workspace

- Missing parent Id record (example Contact.AccountId)
  - current behavior: the Contact is imported without AccountId
  - expected bahavior : 
    - if AccountId is hardcoded , just use it instead of removing it  
    -  else trigger error and not import contacts without setting AccountId
    - or even better: find corresponding Account Id from Account.Name if it is in Contact.csv

- Missing columns for composite externalId (ex: `FirstName;LastName;BirthDate`) with upsert mode:
  - current behavior: it inserts values where contacts with the same FirstName, LastName, BirthDate exists in the database
  - expected behavior:
    - trigger an error and tell the user to add a column $$FirstName$LastName$BirthDate in Contact.csv
    - or even better: build this column dynamically, as we already have columns FirstName, LastName and BirthDate in Contact.csv

Many thanks for your feedbacks :)

**Comment by nvuillam** [comment]
@hknokh any thoughts about this issue ? :)

**Comment by hknokh** [comment]
Hello @nvuillam  
I don't understand the point of your idea.
In order to make those checks, e.g. trigger checks, you have to actually create the target records.
So, if your idea is to create the test target records in the PROD env until it working well, then to do the final data import into the same PROD env - we don't get any benefit from this approach.
If your idea is to test the CSV files on the SB env, then finally to import the same into the PROD env - this is the normal  usage of the tool.
Can you plz to explain more ?

**Comment by nvuillam** [comment]
My use cases are usually to create CSV files with other ways than a SFDMU extraction, then load it into orgs (that can be production of sandboxes, depending of the typology of projects and tasks)
Whe I load those CSV files using SFDMU, if something goes wrong I would like to know it, errors to be triggered, instead of guessing the errors AFTER the load :/

Of maybe SFDMU is not suitable for such use cases, and should just be used for exporting then importing in sandboxes / scratch orgs ? :/

**Comment by hknokh** [comment]
I think you can try to use this option: **simulationMode**.
It can help you to fix errors which can be detected without actual data load.
Refer here:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

**Comment by nvuillam** [comment]
That does not solves the issue I decribed... but it may allow to start to avoid them, thanks...
Would it be possible to have the option as CLI argument , to avoid to have to update config file everytime we want to simulate or not ?

**Comment by hknokh** [comment]
Not understand why it does not solve that issue. The simulation mode acts the same as the live mode and can allow to isolate most of issues which can happen. The rest of issues require live mode to be detected and must be tested on full sb. 
Anyway I will and --simulation flag to the cli.

**Comment by hknokh** [comment]
Hello @nvuillam 
I've added a new \-\-simulation flag.
It acts just like the **simulationMode**

**Comment by ETERNAL153** [comment]
does "--simulation" detects the missing required fields in csv? @hknokh
