### ISSUE TITLE
[FEATURE REQUEST] - Option to populate self-reference on insert

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/SFDX-Data-Move-Utility#448]
First of all thanks for the plugin, it is awesome and saves a lot of time. 🍾 

**Is your feature request related to a problem? Please describe.**
For a minority set of objects, Salesforce restricts the amount of them for a given parent. So, it would be helpful to have an option to divide the upsert or insert records based on the parent/child relationship (potentially in multiple chunks).

One of such objects is [ProductCategory](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_productcategory.htm) which can have 100 of them under the same parent otherwise they fail to insert or update ([the same with Data Categories](https://help.salesforce.com/s/articleView?id=000319179&type=1)). This validation cannot be turned off and the workaround is to use another tool and perform the inserts first (using an external id and retrying the failures simulating chunking).

**Describe the solution you'd like**
An option to allow populating the parent id during the insert phase. It could divide the insert into multiple chunks inserting the null parents first (top-level records), then second level and so on.

I understand that this would not be optimal for resource usage but it will help to overcome such a problem.

**Comment by hknokh** [comment]
Hello @jefersonchaves 

As I understand, you meant, that we can insert / update only 100 child ProductCategories linked to the same parent ProductCategory (by ProductCategoryId) at once.  
So the solution may be to split the job into small chunks.
I think you can use the following existing options which guarantee you the uploading of record chunks no larger than 100 at once:

**"bulkApiV1BatchSize": 100,
"restApiBatchSize": 100,**

Set these options for the ProductCategory object.

**Comment by jefersonchaves** [comment]
Hello @hknokh - This still fails with the same error. The problem seems that it tries to insert them all (in different batches or not), and Salesforce blocks them because it makes more than 100 child ProductCategories. Any other suggestions?

**Comment by hknokh** [comment]
Please confirm that you are requesting the option to limit insertion to only 100 child records PER PARENT.
Since there is no existing solution for this,
I will put this on the road map for the future development.

**Comment by jefersonchaves** [comment]
Hello @hknokh - Thanks for your quick replies. If this option to limit insertion to only N child records populates the parent after each execution then I agree.

Example (I see this running 3 bulks - the first with 1 & 2, the second with 3, and the third with 110):
```
Migration Id,Name,Parent Migration Id
1,First Parent,
2,Second Parent,
3,First Child First Parent,1
...
110,First Grand-child First Child First Parent,3
```

**Comment by jefersonchaves** [comment]
Hello @hknokh : was this delivered with another feature? My bad if I missed the update.

Maybe this is related to #503.

**Comment by hknokh** [comment]
Hello @jefersonchaves 
I didn't implement this feature yet )
Hope it will come soon.
