### ISSUE TITLE
[FEATURE REQUEST]-Generate composite externalId from source CSV

### ISSUE THREAD

**Issue by mmablom** [forcedotcom/SFDX-Data-Move-Utility#452]
**Problem**
I'm using SFDMU to import some new data into an org from CSV files. Some data already exists, so this would be an Upsert operation. In this case there are existing Products from another system, with prices (in multiple currencies) that will be added as PricebookEntries on multiple (existing) Pricebooks. The `externalId` for the PricebookEntry is set to `Product2.Trade_Code__c;Pricebook2.Name;CurrencyIsoCode`. I was struggling with this as the plugin kept trying to insert PricebookEntries that already existed. After trying some exports, I realized I had to add a column `$$Product2.Trade_Code__c$Pricebook2.Name$CurrencyIsoCode` to the PricebookEntry CSV file, with the proper generated `externalId`. I had expected that the plugin would have created this column by itself to match the source CSV data.

I also tried using the following externalId: `Product2Id;Pricebook2Id;CurrencyIsoCode`. This did not work either however.

**Solution**
If possible, can the plugin generate the required externalId column based on the columns present in the CSV? This would allow easier imports of new data.

**Examples**
_PricebookEntry CSV_
```csv
Product2.ProductCode,UnitPrice,Pricebook2.Name,CurrencyIsoCode,IsActive,UseStandardPrice,$$Product2.ProductCode$Pricebook2.Name$CurrencyIsoCode
123456,70,Standard Price Book,PLN,TRUE,FALSE,1113442;Standard Price Book;PLN
123456,15.5,Standard Price Book,EUR,TRUE,FALSE,1113442;Standard Price Book;EUR
```
_export.json_
```json
{
  "objects": [
    {
      "query": "SELECT Name FROM Pricebook2",
      "operation": "Readonly",
      "externalId": "Name"
    },
    {
      "query": "SELECT all FROM Product2",
      "operation": "Upsert",
      "externalId": "ProductCode",
    },
    {
      "query": "SELECT all FROM PricebookEntry",
      "operation": "Upsert",
      "externalId": "Product2.ProductCode;Pricebook2.Name;CurrencyIsoCode"
    }
  ],
  "excludeIdsFromCSVFiles": true
}
```

**Comment by hknokh** [comment]
Hello @mmablom 

Thanks for the suggestion.

There are some cases when you can't populate composite external ids from the existing csv data.

1. you are not use "all" keyword and didn't include the necessary columns in the source csv.
2.  your composite external id is more complex contains several object levels, like:   **Product2.Trade_Code__r.Currency__r.Name**;Pricebook2.Name;CurrencyIsoCode

In the last case you also will need to include 2 additional files Trade_Code__c.csv + Currency__c.csv
or add the column Trade_Code__r.Currency__r.Name in the Product2.csv which is not allowed and/or not intuitive.

In other hand in most cases you can populate composite externalid automatically.
But  maybe we even can populate all kind of external ids (also a simple externalid like **Product2.Trade_Code__c**) from the source CSV ? 

Anyway thank you for the suggestion. Although I don't think that I will implement it in the nearest releases, but I put this on the development roadmap for one of the future releases.
