### ISSUE TITLE
[FEATURE REQUEST]- Hard delete operation available through Bulk 2.0 API 

### ISSUE THREAD

**Issue by szymon-halik** [forcedotcom/SFDX-Data-Move-Utility#453]
I would like to have the possibility to run quarterly jobs in the org to reduce the data storage without moving those records to the recycle bin. I want to keep the management of the recycle bin just for admins, if there are unnecessary records I want to permanently delete them using `hardDelete` operation [available in Bulk 2.0](https://help.salesforce.com/s/articleView?id=000314271&type=1)

**Comment by hknokh** [comment]
Hello @szymon-halik 
Thank you for the suggestion.
I will check this.

**Comment by hknokh** [comment]
Hi. The contribute branch hasn't updated.
Try to create a feature branch with your changes + pr from the master.  I will review your code further. Thx. Did you already tested well your changes?

**Comment by hknokh** [comment]
Hello.
The contribute branch is now up to date you can work with it.
This is our contribution policy:
https://help.sfdmu.com/full-documentation/additional-information/code_contribution_policy
And indeed you don't have the permissions to create a new feature branch in this original repo. 
Instead try to create a new feature request **from the** **contribute** branch using your own forked repository, see more below:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
Note, that your new PR should be into the **contribute** branch, **not** into the **master**.

**Comment by hknokh** [comment]
Hey 
I've merged your PR into the master release with some other improvements and bug fixes:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/pull/502

Please update and check the hard delete operation if it's working as expected.

**Comment by alexsied** [comment]
Hi @hknokh ,

Sorry for the very late reply.

It's working as expected.
Great work.
Many thanks for your time on this.

cheers,

Alex

**Comment by hknokh2** [comment]
Hi  @alexsied 
Thanks for the update. 
Glad it's working for you!
Cheers
