### ISSUE TITLE
[BUG]-Can't retrieve Org connections with the GUI App "Failed to execute force:org:list command or no SFDX orgs were detected in your system."

### ISSUE THREAD

**Issue by Benjamin38600** [forcedotcom/SFDX-Data-Move-Utility#454]
**Describe the bug**
Hi hknokh,
Can't retrieve Org connections with the GUI App
![image](https://user-images.githubusercontent.com/17900430/166987188-e897c7fa-b5f2-4a01-b669-0569866cd5c2.png)
when I "click here", I can read the pop-up "Failed to execute force:org:list command or no SFDX orgs were detected in your system."
![image](https://user-images.githubusercontent.com/17900430/166987350-a546501d-c6c2-4acb-9a11-937f8f1bc8a3.png)

The same with :
![image](https://user-images.githubusercontent.com/17900430/166987457-dd896905-2263-40ca-ab27-f68b85510ee7.png)

I know that we have old issues with the same problem. I was checking solution like update to the last SFDX CLI version, check outdated connections or unclear answer to the command 'sfdx force:org:list' or 'sfdx force:org:display -u ALIAS'. But this is okey here: 
![image](https://user-images.githubusercontent.com/17900430/166989214-f452eee1-5089-4bee-ac88-6a5563558222.png)

Thanks in advance for help, and thanks for your sfmu plugin that is a wonderful and clever tool !

**Comment by hknokh** [comment]
Hi. As I see you have sfdx cli error message BEFORE the actual command output. Thus can prevent reading the connection info by the app. Fix the error to get clean output and retry.

**Comment by Benjamin38600** [comment]
That's work, thank you so much !
