### ISSUE TITLE
[FEATURE REQUEST]- Be able to perform multiple different operations with different queries for the same object (proposition of a solution)

### ISSUE THREAD

**Issue by Benjamin38600** [forcedotcom/SFDX-Data-Move-Utility#455]
### _**Is your feature request related to a problem? Please describe.**_

Hello, Hknokh! You seem to know CPQ package, but to be sure, I will explain without tacit knowledge. So this is a real case during CPQ data migration that is very frustrating for **every CPQ expert of the world**:
**- Context:** you have "price rules" that is the parent object of "price conditions". On the parent object, you can choose operator 'AND'; 'OR'; 'CUSTOM LOGIC' in a picklist field to describe logic between those conditions.
**- Problem:** managed validation rule from CPQ package prevent inserting "price rule" with operator "CUSTOM LOGIC" without "price conditions" related to it. And because it's a master-detail relationship, you can't insert child "price conditions" before related "price rules". And we can't deactivate this packaged validation rules because it's managed. The snake biting its tail.
**- Workaround :** very famous problem which obliges us during CPQ Data deployment to:
1. Insert price rules with operator field different from 'CUSTOM LOGIC' to prevent to fire this managed validation rule
2. Insert related price conditions records
3. update price rules with the right operator 'CUSTOM LOGIC' for those where it is needed.

### _**Describe the solution you'd like**_

As you can understand here, we have to perform one insert operation and one update operation in the same object "price rules" to solve that specific case. But SFDMU plugin allows only one operation/query per object, today if we have multiple query for the same object in the same export.json file, only the first one query is performed. 

**Workaround:** Call _2 different export.json files with twice "sfdmu:run path1/export.json -u ALIAS -s ALIAS" and "sfdmu:run path2/export.json -u ALIAS -s ALIAS" commands_.

Now imagine that we want also to clear all CPQ objects in json order (with keepObjectOrderWhileExecute = true) in the target Org before data migration, explicitly without "deleteOldData". So we need now _3 different export.json files_ (delete, insert and update operation in the same "Price rules" Object in this real famous example). Which is annoying when trying to make a single script to be productive and deploy an entire CPQ configuration in one shot with one 'run' command.

### **_Brainstorming_**

The smart auto "deployment plan maker" feature seems to be complex. Allow us to perform multiple operation/query for the same object should be a lot of work maybe on your algorithm to order automatically every operation correctly, depend on the objects' hierarchy. 

But maybe the solution to resolve this problem : "perform multiple operation/query in the same object with one "sfdmu:run" command", could be to allow simply multiple scripts in one export.json like 

![image](https://user-images.githubusercontent.com/17900430/167041895-d7c318b2-f90b-4752-8db5-75314ca7f305.png)

**Then, your complex algorithm doesn't change and don't ask many times to evolve on this case, and the "sfdmu:run" command detects in export.json that we have _to run your entire algorithm three times for each "sub-script"_, and SFDMU tool productivity should be the best for the entire CPQ world** :)

**Comment by hknokh** [comment]
Hello @Benjamin38600 
I agree it would be usefull feature.
Put it on my roadmap.
Thx

**Comment by hknokh** [comment]
Hello @Benjamin38600 
Implemented this feature. 
It's not documented yet, I will give you a quick preview.
I've added new property called **objectSets**
Now besides the regular "objects" array (still supported) you have an additional set of "objects" arrays.

Specify the same object multiple times in the same job like that way:

{
   "objectSets": [
         {
                "objects": [
                      {
                             "query" : "SELECT Id FROM Account",
                             "operation": "Delete"
                      },
                       {
                             "query" : "SELECT Id FROM Opportunity",
                             "operation": "Delete"
                      }
                 ]
          },
          {
                "objects": [
                      {
                             "query" : "SELECT all FROM Account",
                             "operation": "Upsert"
                      }
                 ]
          }
    ],
"objects": [],
.....
}

1. Each "objectSet" runs separated sub-job with the same main script parameters. 
The main job executes untill all subsets are completed.

2. Each sobject definition in objectSets/objects - has its own independent parameters including Operation.

3. If you have both "objects" and "objectSets" - the Plugin will first execute "objects", then will run all "objectSets".

Please update to latest and try it.

**Comment by Benjamin38600** [comment]
Hello @hknokh, thank you very much for your reactivity, I will try to combine my different export.json files to give you feedback soon as a beta tester :)

**Comment by hknokh** [comment]
Cool Thx
This is the doc
https://help.sfdmu.com/full-documentation/advanced-features/multiple-object-sets

**Comment by doudou23** [comment]
Hi, seems a nice feature, but is there a way to define several object.csv files?
Let say i would like to load PersonAccount Data in my set one and load Account in my set 2, this can't be done with a single Account.csv, right? any idea here? 

Thank you

**Comment by hknokh** [comment]
> Hi, seems a nice feature, but is there a way to define several object.csv files? Let say i would like to load PersonAccount Data in my set one and load Account in my set 2, this can't be done with a single Account.csv, right? any idea here?
> 
> Thank you

Hi @doudou23 
Your proposition of above is added to the Roadmap #559 
Thanks!

**Comment by hknokh** [comment]
> Hi, seems a nice feature, but is there a way to define several object.csv files? Let say i would like to load PersonAccount Data in my set one and load Account in my set 2, this can't be done with a single Account.csv, right? any idea here?
> 
> Thank you

This feature was recently implemented.
Please refer:
https://help.sfdmu.com/full-documentation/advanced-features/multiple-object-sets
