### ISSUE TITLE
[BUG]-IsPersonAccount unknown on Account/Contact

### ISSUE THREAD

**Issue by novumcoder** [forcedotcom/SFDX-Data-Move-Utility#460]
**Describe the bug**
My target org does not have Contact.IsPersonAccount, also Account.IsPersonAccount. Now i get this error. I think you need to check if this field exists before using it. Or? Im having 4.14.1 installed

**To Reproduce**
Import from one org with Contact.IsPersonAccount into an org without that field.

**Expected behavior**

**export.json**
[export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8654016/export.zip)

**Log file**

> {Account} Deleting old records from the Target ...
{Account} The Delete API operation has been started using Bulk API V2.0 (SIMULATION MODE).
{Account} The Delete API operation has been finished.
{Contact} Deleting old records from the Target ...
Command in progress ...... done
[ERROR] Execution of the command was ABORTED due to unexpected error:
SELECT Id FROM Contact WHERE (IsPersonAccount = false)
                              ^
ERROR at Row:1:Column:31
No such column 'IsPersonAccount' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
[STACK TRACE] INVALID_FIELD: 
SELECT Id FROM Contact WHERE (IsPersonAccount = false)
                              ^
ERROR at Row:1:Column:31
No such column 'IsPersonAccount' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
    at HttpApi.getError (C:\Users\EEsen\AppData\Local\sfdx\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\Users\EEsen\AppData\Local\sfdx\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\Users\EEsen\AppData\Local\sfdx\node_modules\promise\lib\core.js:37:12)
    at C:\Users\EEsen\AppData\Local\sfdx\node_modules\promise\lib\core.js:123:15
    at flush (C:\Users\EEsen\AppData\Local\sfdx\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).

**Comment by hknokh** [comment]
What is your export.json ?
Do you have PersonAccounts enabled in your orgs ?

**Comment by hknokh** [comment]
Looks like the SFDMU detected that you have PersonAccounts in your org.
Do you have PersonAccout enabled in the Source org but not in the Target org ?

**Comment by novumcoder** [comment]
> Looks like the SFDMU detected that you have PersonAccounts in your org. Do you have PersonAccout enabled in the Source org but not in the Target org ?

Yes, the source org has has it enabled, but the target org doesn't and i cannot enable it.

**Comment by hknokh** [comment]
@novumcoder 
That's should be. I cant check this on my end but it should work.
Please update the plugin and retry.
