### ISSUE TITLE
[BUG]- Multiselect keywords 'all' doesn't inculde 'RecordTypeId' field that is referenced as a 'standard lookup'

### ISSUE THREAD

**Issue by Benjamin38600** [forcedotcom/SFDX-Data-Move-Utility#462]
**Describe the bug**
Multiselect keywords 'all' doesn't inculde 'RecordTypeId' field that is referenced as a 'standard lookup'

**To Reproduce**
Make this query on account object:
![image](https://user-images.githubusercontent.com/17900430/167638110-c6f4ae1e-e125-4085-848d-ce1328705b39.png)

**Expected behavior**
RecordTypeId is set after running the script on accounts with only this multiselect keyords

**Check with UI app**

![image](https://user-images.githubusercontent.com/17900430/167638639-01f89ba1-0816-4529-958f-5b9741b2b471.png)

Explicit query translation in the UI app : 
![image](https://user-images.githubusercontent.com/17900430/167638934-cb3e0563-8e86-474c-b603-f7cd3037bedc.png)
> result without RecordTypeId field in select part. After running the script, the record type id is wrong in the target Org

I know that I can explicitly add 'RecordTypeId' field in the query but the documentation say:
![image](https://user-images.githubusercontent.com/17900430/167639232-5f884845-638f-48a0-a3f3-5da324cc4c47.png)

> so, this seems to be a bug

Have a nice day,

Looking forward to collaborating again ;)

**Comment by hknokh** [comment]
Hello
The RecordTypeId is not included by the multiselect keyword by the current Plugin implementation.
I can't add this right now since it can cause regressions in the existing export.jsons across the global SFDMU users.
At this moment you shoud add this besides all: SELECT all, RecordTypeId FROM Account
Sorry for the inconvenience
I will update the documentation accordingly.

**Comment by hknokh** [comment]
By the way it already was mantioned in the documentation:

![image](https://user-images.githubusercontent.com/15181301/167717653-2ceb3c4d-fd22-45fe-9d7d-9abc5ba52a78.png)

**Comment by Benjamin38600** [comment]
thx @hknokh, clear !
