### ISSUE TITLE
[QUESTION] - Are Tasks with Groups assigned as Owner possible?

### ISSUE THREAD

**Issue by novumcoder** [forcedotcom/SFDX-Data-Move-Utility#469]
Hey guys,

just trying to import Task data and i saw nearly all Task records have Groups assigned as Owner. But on my target org the data imported has no OwnerId filled. The final CSV file is showing empty values for OwnerId.

Any idea why?

**Comment by hknokh** [comment]
Hello
Did you ensure that the groups in the source and the target  have the same names?

**Comment by hknokh** [comment]
Also make sure you have OwnerId included in the query

**Comment by novumcoder** [comment]
Hi @hknokh,
both your questions can be answered with Yes. I include all fields available using the SOQL tool from the workbench. The target org is a refresh from production. I also added both the User and Group SOQL with all fields selected, just to be sure. Now the last time i saw some Task.OwnerId field were filled with Group references but most aren't. The missing group link does exist on the target org too. 

Any other reason for this field not getting filled. The log does not even give me an error for those records.

Currently i am even only using the "Update" operation for Task, so it is actually updating existing Tasks. externalId is set to "Id".

**Comment by novumcoder** [comment]
Just for info:

This is the sobject config: 
![image](https://user-images.githubusercontent.com/6917790/170695327-0dfc8f9a-4b04-412e-8d27-d051703531d6.png)

The task exists on both systems with the same RecordId, but the CSV file does not contain the Task from prod, so it is never updated. The SOQL works fine on both systems returning the Task record. Why is the tool not even taking the record from PROD for updating?

**Comment by hknokh** [comment]
Sorry. Could not reproduce. On my side the tasks are liked properly to the groups. I didn't detect any bug with this. For now I have no good idea why it can happen. Need to connect to your sf organizations and to debug using the  source code of the sfdmu.

**Comment by novumcoder** [comment]
Another issue i found is this: 
`FIELD_INTEGRITY_EXCEPTION:You can only add up to one what relation.:TaskId --`

I have existing Tasks, but WhatId is empty. With the tool i want to fix that with a link to a custom object from production.

I checked TaskRelation, there is not a single record pointing to those tasks, so why is Salesforce giving this error?

**Comment by hknokh** [comment]
Hello.

Try to include the taskrelation object + all objects which are related to Tasks into the configuration.

Generally, we currently give support only to critical runtime errors + new feature requests as stated in the our Readme. Your question is mostly related to the plugin configuration + sf platform specifications. Try to play with the export.json according to our documentation. If you will experience specific runtime error, feel free to report us this issue.
Our apologies.
