### ISSUE TITLE
[BUG]-Cannot read property 'chunks' of undefined

### ISSUE THREAD

**Issue by novumcoder** [forcedotcom/SFDX-Data-Move-Utility#471]
**Describe the bug**
Iam importing data from a production org from a custom object. Since we have some flows running there, i have to import it in small chunks. So i enabled restApi Only for Update since i am using only the update feature matching by Id.

That runs for a while but keeps breaking with the below error message.

**To Reproduce**
Describe steps to reproduce the behavior.

**Expected behavior**
To import my data from the ..._report__c table in small chunks sized 10.

**export.json**
[export.copy.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8803199/export.copy.zip)

**Log file**
[2022-05-31__09_22_17.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8803183/2022-05-31__09_22_17.log)

**_target.csv** file.
[ibszpsalesext__Visit_report__c_update_target.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8803213/ibszpsalesext__Visit_report__c_update_target.zip)

**Comment by hknokh** [comment]
Hello @novumcoder 
It's not for the large number of jobs created. I've just checked it with your config.
It's working at my end vwithout error. As I remember I already fixed it in one of the latest versions.
Please update and retry.
Thanks
