### ISSUE TITLE
[BUG]-sfdmu:run failing with COMMAND_INITIALIZATION_ERROR on sfdx 7.158.1

### ISSUE THREAD

**Issue by jeffreyazevedo** [forcedotcom/SFDX-Data-Move-Utility#473]
**Describe the bug**
When using the current sfdx release candidate (7.158.1), sfdmu is failing during org connection with the following error:
```
[09:04:53.334] Connecting to TestScratchOrg using SFDX force:org:display ...
[09:05:02.531][ERROR] Command initialization error: Attempt to connect to TestScratchOrg failed. Please, try to refresh your local SFDX CLI connection..
[09:05:02.533][ERROR] [STACK TRACE] Error: Attempt to connect to TestScratchOrg failed. Please, try to refresh your local SFDX CLI connection.
```
When using the current stable version of sfdx (7.157.0), there is no issue. It looks the difference between the two is that on 7.158.1, `sfdx force:org:display` returns a table where there is now a space between each line as well as a space at the beginning of each line. 

My guess it that is throwing off the following bit of code where SFDMU tries to parse the result and where it's expecting each line to begin with an attribute name:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/models/script_models/scriptOrg.ts#L144-L166

It seems that maybe SFDMU should be using the JSON version of the results instead of trying to parse the human readable output?

https://developer.salesforce.com/blogs/2020/02/using-salesforce-cli-output-and-scripting
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_json_support.htm

**To Reproduce**
* Upgrade sfdx to 7.158.1
* Perform an sfdmu:run command

**Expected behavior**
For SFDMU to be able to connect to an org using the current sfdx release.

**Log file**
[2022-07-05__09_04_53.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9048809/2022-07-05__09_04_53.log)

**Comment by cristiand391** [comment]
Hey all 👋🏼 

oclif v2 included some minor changes in the table printer code, we bumped it here:
https://github.com/salesforcecli/plugin-org/pull/332

As mentioned in the blog post linked in the issue, consumers should be relying on the json output (or sfdx-core: https://github.com/forcedotcom/sfdx-core/).

**Comment by hknokh** [comment]
Hey all
Fixed. 
Switched to the json output
Please update & recheck

**Comment by jeffreyazevedo** [comment]
Looks good! Thanks so much for the quick turn around, really appreciate!
