### ISSUE TITLE
[ERR_REQUIRE_ESM] Error Plugin: sfdmu [ERR_REQUIRE_ESM]: require() of ES Module ...\SFDX-Data-Move-Utility\node_modules\globby\index.js

### ISSUE THREAD

**Issue by JCripe-AuthorSolutions** [forcedotcom/SFDX-Data-Move-Utility#481]
When trying to run the v4.15.0 version of sfdmu, installed with source code, I get an error with recommended corrective action:

(node:47672) **[ERR_REQUIRE_ESM] Error Plugin: sfdmu [ERR_REQUIRE_ESM]: require() of ES Module** C:\[install path]\SFDX-Data-Move-Utility\node_modules\globby\index.js from C:\Users\[User]\AppData\Local\sfdx\client\7.159.0-f8fac41\node_modules\@oclif\config\lib\plugin.js not supported.
**Instead change the require of index.js in C:\Users\[User]\AppData\Local\sfdx\client\7.159.0-f8fac41\node_modules\@oclif\config\lib\plugin.js to a dynamic import() 
which is available in all CommonJS modules.**
module: @oclif/config@1.18.3
task: not loading commands, globby not found
plugin: sfdmu
root: C:\[install path]\SFDX-Data-Move-Utility

**Comment by JCripe-AuthorSolutions** [comment]
depcheck output when it is run in the SFDX-Data-Move-Utility app directory:
> depcheck
Unused dependencies
* @oclif/command
* @oclif/config
* @oclif/errors
* @types/bunyan
* alasql
* casual
* csv-writer
* deep.clone
* fastest-levenshtein
* glob
* madge
* promise-parallel-throttle
* tslib
Unused devDependencies
* @oclif/plugin-help
* @oclif/test
* @types/chai
* chai
* globby
* ts-node
Missing dependencies
* request: .\src\modules\components\api_engines\bulkApiV2_0Engine.ts
* @salesforce/ts-types: .\src\commands\sfdmu\run.ts

**Comment by hknokh** [comment]
1. I don't experience such issue on my end. Sounds like an installation issue.
2. The output regarding the unused deps isn't correct. I recognize a lot of deps which are in use such as casual, csw writer etc.
3. Did you correctly complete the npm install command ? Note If your are on the Mac, you should use sudo while installing the deps.
4. Which sfdx cli version do you use ?

**Comment by JCripe-AuthorSolutions** [comment]
This problem is on Windows 10.

sfdx version is 8.14.0, and this morning, I uninstalled then reinstalled sfdx totally, using npm.

I uninstalled SFdmu, (installed with source code,) then installed it with npm,

Now I get a different error 'TypeError: Cannot read properties of undefined (reading 'prototype')'.

**Comment by JCripe-AuthorSolutions** [comment]
When I install SFDMU, I get warnings:

> sfdx plugins:install sfdmu                        
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for sfdmu.
Finished digital signature check.
warning ..\..\..\package.json: No license field
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.  
Installing plugin sfdmu... installed v4.15.0

Are these warnings expected?

**Comment by hknokh** [comment]
HelloI've checked the production version of project.
There are no such warnings present neither on Mac nor in Windows.

Below is the plugins:install output:
MacOs:
![image](https://user-images.githubusercontent.com/15181301/179435060-ffcbea7f-1988-4a9c-a374-487070e8e86a.png)

Win:
![image](https://user-images.githubusercontent.com/15181301/179435894-9e1e6d55-1326-4a72-a94e-85223c23098b.png)

The outputs are looking quite the same.
You can get warnings about some outdated dependencies but you can disregard these, they are not critical.

My platform versions (npm / sfdx-cli are most fresh):
sfdx-cli: 7.159.0 
node: 16.13.1, 
npm: 8.14.0

I would suggest you to check your local infrastructure + update nodejs / npm / sfdx-cli

**Comment by hknokh** [comment]
Regarding the cloned version I did also not experience such issues.
Below is my output.
![image](https://user-images.githubusercontent.com/15181301/179436687-b2db35ac-e474-400a-bb56-d5a7b0cd1247.png)

As I said you should try to investigate the reasons of the issues locally on your machne.

**Comment by hknokh** [comment]
![image](https://user-images.githubusercontent.com/15181301/179437131-e4fdcecb-0732-41e9-bf6a-d1791fdedcac.png)
This above shows that the sfdmu is running after the git clone
