### ISSUE TITLE
[QUESTION] - Uploading Business and Person Account at the same time via CSVFile to Target Org.

### ISSUE THREAD

**Issue by BongskySFDX** [forcedotcom/SFDX-Data-Move-Utility#482]
- Ask your question or what kind of help you need.
I checked the documentation but was not able to find any information about how to prepare the data for loading both business and person account at the same time.

I can verify that this works fine for Org to Org execution.

Has anyone here had any success in uploading it by manually creating the data file?

Thank you in advance.

**Comment by hknokh** [comment]
Hello
Maybe I can suggest you to extract an example of csv file containing data of both BA and PA from the source org, then let see, which CSV columns the SFDMU is creating, then create your CSV file with populating the the same columns, then import that file into the target org (sfdx sfdmu:run -u you@org.com -s csvfile)

**Comment by BongskySFDX** [comment]
Hi,

Thank you for getting back to me.

I have done this before but it did not work, for the sake of testing, I simulated another one.

I have created test data via Dev Console by inserting a list of combined PA (Person Account) and BA (Business Account). See the code below.

List<Account> personAndBusinessListForInsert = new List<Account>();

for(Integer i = 0; i < 11; i++) {
    Account pa = new Account();
    pa.FirstName = 'Person';
    pa.LastName = 'Account ' + i;
    pa.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    personAndBusinessListForInsert.add(pa);
    
    Account ba = new Account();
    ba.Name = 'This Is A Business Account ' + i;
    ba.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    personAndBusinessListForInsert.add(ba);
}

insert personAndBusinessListForInsert;

This is the content of the CSV file extracted from the source org.

Id,Name,RecordTypeId,FirstName,LastName,RecordType.$$DeveloperName$NamespacePrefix$SobjectType
0010w00000yxWf9AAE,This Is A Business Account 0,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfAAAU,Person Account 1,0120w000001SOv1AAG,Person,Account 1,PersonAccount;Account
0010w00000yxWfBAAU,This Is A Business Account 1,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWf8AAE,Person Account 0,0120w000001SOv1AAG,Person,Account 0,PersonAccount;Account
0010w00000yxWfCAAU,Person Account 2,0120w000001SOv1AAG,Person,Account 2,PersonAccount;Account
0010w00000yxWfDAAU,This Is A Business Account 2,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfEAAU,Person Account 3,0120w000001SOv1AAG,Person,Account 3,PersonAccount;Account
0010w00000yxWfFAAU,This Is A Business Account 3,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfGAAU,Person Account 4,0120w000001SOv1AAG,Person,Account 4,PersonAccount;Account
0010w00000yxWfHAAU,This Is A Business Account 4,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfIAAU,Person Account 5,0120w000001SOv1AAG,Person,Account 5,PersonAccount;Account
0010w00000yxWfJAAU,This Is A Business Account 5,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfKAAU,Person Account 6,0120w000001SOv1AAG,Person,Account 6,PersonAccount;Account
0010w00000yxWfLAAU,This Is A Business Account 6,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfMAAU,Person Account 7,0120w000001SOv1AAG,Person,Account 7,PersonAccount;Account
0010w00000yxWfNAAU,This Is A Business Account 7,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfOAAU,Person Account 8,0120w000001SOv1AAG,Person,Account 8,PersonAccount;Account
0010w00000yxWfPAAU,This Is A Business Account 8,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfQAAU,Person Account 9,0120w000001SOv1AAG,Person,Account 9,PersonAccount;Account
0010w00000yxWfRAAU,This Is A Business Account 9,0120w000001SOv0AAG,,,Business_Account;Account
0010w00000yxWfSAAU,Person Account 10,0120w000001SOv1AAG,Person,Account 10,PersonAccount;Account
0010w00000yxWfTAAU,This Is A Business Account 10,0120w000001SOv0AAG,,,Business_Account;Account

I uploaded the same CSV file and end up with an error.

Name,RecordTypeId,FirstName,LastName,Errors
This Is A Business Account 0,0120w000001YwzDAAS,,,"Account: bad field names on insert/update call: LastName, FirstName"
Person Account 1,0120w000001YwzEAAS,Person,Account 1,Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.

When running csvfile to target org it will create one single account insert file. sfdx sfdmu:run -s csvfile -u my@org.com

![image](https://user-images.githubusercontent.com/50150397/179450424-ff2f18e5-99a2-4fbc-95cb-c851f7504457.png)

When running ORG to ORG it will create two account insert one is appended with person. sfdx sfdmu:run -s my@org.com -u csvfile

![image](https://user-images.githubusercontent.com/50150397/179450612-609d5b1f-62e5-4ba9-9ab4-de0fcf617ffe.png)

**Comment by hknokh** [comment]
OK, understand. I  will check it

**Comment by hknokh** [comment]
@BongskySFDX 
I applied small fix to it and now it should import person accounts & business accounts from single Account.csv

The format of the Account.csv fro mixed account record types should be like this:

Id,Name,FirstName,LastName,IsPersonAccount
0018d00000Gk3xbAAB,Test_Person Account 0,Test_Person,Account 0,true
0018d00000Gk3xcAAB,Test_Business Account 0,,,false

- You should provide both Name field for BAs and FirstName/LastName for PAs
- Add IsPersonAccount column to tell the SFDMU which type of account is this (PA or BA).

The example of the export.json like this:
{
	"objects": [
		{
			"query": "SELECT Name, FirstName, LastName FROM Account WHERE Name LIKE 'Test_%'",
			"operation": "Insert"
		}
	]
}
