### ISSUE TITLE
[QUESTION] - After a "virgin" install of npm and sfdx, and SFDMU by NPM, still can't sfdmu:run

### ISSUE THREAD

**Issue by JCripe-AuthorSolutions** [forcedotcom/SFDX-Data-Move-Utility#484]
**Describe the bug**
After totally uninstalling SFDMU, SFDX, and even Node/NPM and then reinstalling them, running sfdmu, I get "TypeError: Cannot read properties of undefined (reading 'prototype')".

> **sfdx sfdmu:run --sourceusername [source name removed] -targetusername [target name removed]**
>     **TypeError: Cannot read properties of undefined (reading 'prototype')**

**To Reproduce**

1. Uninstall SFDMU, SFDX, Node/NPM following the NPM type uninstall directions for each, rebooting as needed.
2. Reinstall all the above, following the NPM  type installation directions for each, confirming good installs using --version.
3. Run SFDMU with this command, (source and target as appropriate,) and get a "TypeError," with no log files or target.csv file: **sfdx sfdmu:run --sourceusername [source name removed] -targetusername [target name removed]**

>     **TypeError: Cannot read properties of undefined (reading 'prototype')**

The error may be related to missing configuration file(s) having to do with "@oclif\dev-cli" as running "inspect" gives this output and an error:

>  **sfdx plugins:inspect sfdmu**
> sfdmu
>   version: 4.15.0
>   tag: latest
>   homepage: https://help.sfdmu.com
>   location: C:\Users\[User]\AppData\Local\sfdx\node_modules\sfdmu
>   commands:
>     sfdmu:run
>   dependencies:
>     @oclif/command: 1.8.16
>     @oclif/config: 1.18.3
> failed
>     **Error: ENOENT: no such file or directory, open 'C:\Users\[User]\AppData\Local\sfdx\node_modules\@oclif\dev-cli\package.json'**
>     Code: ENOENT

**Expected behavior**
Sfdmu should have run, copying the contents identified in the json file from the source to the target Orgs.

**export.json**
Attach your **export.json** file

**Log file**
None created

**_target.csv** file.
None created

**Comment by JCripe-AuthorSolutions** [comment]
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9238406/export.json.txt)
Remove the ".txt" extension.

This export file copies a particular Account and related Contact.

**Comment by hknokh** [comment]
@mshanemc 
Do you know something about this issue ? Seems related to the sfdx framework.

**Comment by JCripe-AuthorSolutions** [comment]
It looks like @oclif/dev-cli, which appears to involved with this bug, is depreciated:

@oclif/[dev-cli](https://github.com/oclif/dev-cli)

>This library has been replaced by oclif and is now in maintenance mode. We will only consider PRs that address security concerns.

If @oclif/dev-cli still referenced by SFDMU, can the reference be refactored to use @oclif instead: [@oclif](https://github.com/oclif)?

**Comment by hknokh** [comment]
@JCripe-AuthorSolutions 
Thanks for the direction.
I will male a check how to replace the outdated dependencies

**Comment by hknokh** [comment]
I've checked this.
I can't upgrade the dependencies of oclif.
These are used by the core SFDX Plugin platform and it's dangerous to play with them.
For me the @oclif/dev-cli is installed correctly even it's archieved. 
Please, try to investigate on your side why you are not able to install the Plugin.

**Comment by hknokh** [comment]
Finally I ended with refactoring of the entire SFDMU using the latest SFDX custom plugin template.
It should incorporate all working dependencies like @oclif/core.
I will update this case when done.

**Comment by JCripe-AuthorSolutions** [comment]
Thanks!  Good luck!

**Comment by hknokh** [comment]
I spoke internally with @mshanemc and he said me that  it looks like a bug in oclif. He has shared this with the SFDX CLI team.
From my side the redesign if the SFDMU is still in work. I wil update you when done.
For now to make the SFDMU working on your side you can possible revert the SFDX CLI to previous stable version.
