### ISSUE TITLE
[BUG] SFDMU online doc is down :(

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#485]
![image](https://user-images.githubusercontent.com/17500430/182417883-663a5c10-f330-4402-a8f8-e7cfb9ee2d7e.png)

**Comment by hknokh** [comment]
Hi
It's working for me now
Please recheck

**Comment by nvuillam** [comment]
It's back,thanks :)
![image](https://user-images.githubusercontent.com/17500430/182619887-93366567-31d5-4b14-8769-8fe939d10434.png)
