### ISSUE TITLE
Entity type ManagedContentInfo does not support query.

### ISSUE THREAD

**Issue by JaniszewskiMarcin** [forcedotcom/SFDX-Data-Move-Utility#491]
Hi,
So when retrieving data from target I have error like this. I see that this object can does not support query but how I can exclude it from the process? I deleted it from export.json and CSV files because I am using SFDMU with CSV records import to target org. Is there any workaround?

```
{ManagedContentInfo} Retrieving the TARGET data from Org (STAGE 2: all records) ...
Command in progress ...... done
[ERROR] Error during execution of the command: entity type ManagedContentInfo does not support query.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
```

**Comment by hknokh** [comment]
To exclude object from the process, use **excluded = true** with the object definition.
Please, refer here:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

**Comment by hknokh** [comment]
Hey @JaniszewskiMarcin 
I've fixed the issue with the excluded objects.
You can now exclude  ManagedContentInfo in two ways:
1. In  a "normal way": using "excluded": true in the object definition (this should work now as expected):
{
    objects: [
                {
			"query": "SELECT Id FROM ManagedContentInfo",
			"excluded": true
               }
   ]
 }
3. The alternative way: I've added the completely new property to the script definition to exclude list of sobjects:
{
 "objects" : [],
 "excludedObjects": [
      "ManagedContentInfo"
   ]
}

Please update the plugin and let me know how it's working for you.
