### ISSUE TITLE
[QUESTION] Records Insert with (Self) Lookup Field

### ISSUE THREAD

**Issue by AndreyShestakovACN** [forcedotcom/SFDX-Data-Move-Utility#493]
# Disposition:
**Source Org has Account records:**
- Parent records - where ParentId = null
- Child records - where ParentId != null

Child records retrieved into `csvfile`:
``` json
{
    "apiVersion" : "54.0",
    "allOrNone" : true,
    "objects" : [
        {
            "query" : "Select Id, ParentId, Name From Account Where ParentId != null",
            "operation" : "Insert",
            "externalId" : "Name",
            "master" : false
        }
    ]
}
```
See the `Account.csv` file atttached.
[Account.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9404285/Account.csv)

**Account records are inserted into the target org using the export.json file above**
See the `log` file attached.
[2022-08-23__11_29_10.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9404321/2022-08-23__11_29_10.log)

There are 2 jobs on the log:
1. Insert
2. Update

After doing some tests, I assume the `Insert` job creates all records (child and parent), but doesn't populate the self lookup `ParentId` field. The `Update` job updates the child records with `ParentId`.
See the target account csv files for reference:
[Account_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9404368/Account_insert_target.csv)
[Account_update_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9404370/Account_update_target.csv)

I also tested this with the Parent records inserted in the target org, as the prerequisite - and got similar results. It have been done using `Upsert` operation and with and without `"master" : true`, so the Parent records would not be duplicated. I assume the bahavior described above is related to records with not only **self** but any lookup fields, but properly tested it with self lookup field only.

# Question

I wonder if the insert of child records **with** a self lookup field populated can be done as **one** insert job ?

The use case for this is when there is a logic is being triggered `after insert` (trigger or flow), that is dependent on a record inserted with or without the self lookup field populated. In my tests, I see that the `after insert` logic treats the records inserted as they don't have the self lookup field populated.

**Comment by hknokh** [comment]
Hi.
It's impossible to do all in one insert job. Because sometimes you don't know the parent account record  id's in advance, since these are part of inserted records themselves.
