### ISSUE TITLE
[QUESTION] - How to use exclude parameter when object is not queryable

### ISSUE THREAD

**Issue by JaniszewskiMarcin** [forcedotcom/SFDX-Data-Move-Utility#494]
Hello,

Sorry for making another topic about that but I have no idea how to implement exclude parameter in export.json file If object is not queryable. I am getting still the same error as in issue https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/491 and have no idea how to implement that parameter in this case. This is what I tried:
```
{
"query": "SELECT all FROM ManagedContentInfo",
"operation": "Upsert",
"externalId": "Id",
"excluded": true
},
```
Thank you for your help in advance :)

**Comment by hknokh** [comment]
Hey
I suppose, that the ManagedContentInfo is also referenced elsewhere from other object in your configuration. So it is still included despite excluded=true. Review again your queries to get rid of all references to that object.
