### ISSUE TITLE
[QUESTION] - Migration of non-namespaced data to namespaced package

### ISSUE THREAD

**Issue by couturecraigj** [forcedotcom/SFDX-Data-Move-Utility#498]
- Ask your question or what kind of help you need.
I am trying to migrate non-namespaced data (a package we are creating) to namespaced package.  I have the field mapping which I think should work but it is not mapping the objects which is causing it to fail almost immediately when hitting custom objects and possibly custom fields (though I never got that far).

**Comment by hknokh** [comment]
Will check it ASAP.

**Comment by hknokh** [comment]
I'm closing this ticket for now. Please reopen if you still need a help.
