### ISSUE TITLE
[QUESTION] - Migration file with CSV file

### ISSUE THREAD

**Issue by ytiq** [forcedotcom/SFDX-Data-Move-Utility#499]
Thanks for a great plugin.

I have some files stored locally in my project and I need them to be uploaded as ContentVersion to Scratch Orgs.

1. I see that it is possible to migrate files between orgs, but can I import ContentVersion in a similar fashion to DataLoader? 
2. Can I migrate ContentVersion without ContentDocumentLink?
3. Can I migrate ContentVersion with 1 ContentDocumentLink?

**Comment by hknokh** [comment]
Hey
The Plugin is intended for the org2org migration. 
1. I think you can import manually content versions using export.json and ContentVersion.csv but no any advantage to use SFDMU i this over the DL
2. 3. I need to check if it's possible and how to exclude/limit the ContentDocumentLinks with the ExportFiles Add-On

**Comment by hknokh** [comment]
I've rechecked your points.

1. _Can I import ContentVersion in a similar fashion to DataLoader_ ? - not possible even using standard export.json
2. _Can I migrate ContentVersion without ContentDocumentLink_ ? -  not possible with the current version of ExportFiles Add-On
3. _Can I migrate ContentVersion with 1 ContentDocumentLink_ ? - not possible with the current version of ExportFiles

I'm putting now these new features to my future roadmap

**Comment by ytiq** [comment]
ok, thank you. Yes, I tried ContentVersion.csv and export.json, but it just ignores it. Ok, thank you will think then of something.

**Comment by hknokh** [comment]
Hello @ytiq,

Thank you again for the feature suggestion.
This capability is already supported in SFDMU and has been available for a long time.

How this is covered in the engine:
- File migration for ContentVersion, ContentDocumentLink, Attachment, and Note is supported by core:ExportFiles.
- Supported directions include org -> org, org -> csvfile, and csvfile -> org.
- Binary payload handling for CSV flows is supported through aseBinaryFilePath.

Please, see also the doc articles:
- [ExportFiles Core Add-On Module](https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module)
- [Scenario 2 Org to CSV Export with Attachment Binaries](https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module#scenario-2-org-to-csv-export-with-attachment-binaries)
- [Scenario 3 CSV to Org Import with Attachment Binaries](https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module#scenario-3-csv-to-org-import-with-attachment-binaries)

Best regards
