### ISSUE TITLE
field "allRecords" not documented

### ISSUE THREAD

**Issue by benahm** [forcedotcom/SFDX-Data-Move-Utility#5]
Hi, 

I see that the field "allRecords" is used in your export.json example 
But it does not appear in the documentation table 
Could you add its meaning 

Thank you

**Comment by hknokh** [comment]
Hello!
The allRecords parameter is outdated and not longer used.
I updated the json example.
Regards.

**Comment by hknokh** [comment]
Hello, @benahm 
I have recently restored back the allRecords property to be used again.
It is necessary for the filtering subset of child records related to the limited subset of the parent records.
Please update the plugin and see the latest documentation:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Plugin-configuration.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Plugin-configuration.-Full-configuration.)
Regards
