### ISSUE TITLE
[FEATURE REQUEST] - Data export to CSV file - order of columns

### ISSUE THREAD

**Issue by adamdzierzkosagecom** [forcedotcom/SFDX-Data-Move-Utility#506]
Hello
We store our exported data in the CVS format but sometimes when re-running the export, the order of columns changes, which messes up the git repository. What determines the order of columns? Is there a way to ensure that the order of columns will not change? 
The query from export.json is in the format:
`SELECT readonly_false FROM ObjectName__c
`
Thank you

**Comment by hknokh** [comment]
Hello.
Basically, the order of the columns in the resulting csv file is depends on the internal implementation of the csv-writer node.js module.  But from my side I'm passing an array of column headers as a result of the Object.keys() function.
Seems that this is what determines the end columns order, but I'm not completely sure.
