### ISSUE TITLE
[QUESTION] - Can I use the Values Mapping to modify date strings

### ISSUE THREAD

**Issue by ppeersgi** [forcedotcom/SFDX-Data-Move-Utility#512]
Is is possible to use the Values Mapping feature to do something like the following?

- Source is csv, target is salesforce
- In my source csv I have a column with the value "DDMM"
- Use Values Mapping feature so that this value becomes "1110" (based on the current date)

**Comment by hknokh** [comment]
Hey @ppeersgi 

It's now possible. I have recently added new eval() replacement feature.
Please update the plugin, then configure export.json  similar to the following:

{
    "objects": [
        {
            "operation": "Update",
            "externalId": "Name",
            "query": "SELECT TEST1__c FROM Account WHERE Name IN ('ACC_10000', 'ACC_10001')",
	    "useCSVValuesMapping": true,
	    "useValuesMapping": true
        }
    ]
}

In my example I have 'DDMM' value in the TEST1__c field

So create the **ValueMapping.csv**  with the content below:

ObjectName,FieldName,RawValue,Value
Account,TEST1__c,DDMM,"eval(new Date().getDate() + '' + new Date().getMonth())"

You can also transform the source field value with the js expression by adding RAW_VALUE reserved keyword

Please refer:
https://help.sfdmu.com/full-documentation/advanced-features/values-mapping

**Comment by ppeersgi** [comment]
Thanks! Js eval replacement works. Is it also possible to combine it with Regex replacement?

For example the following ValueMapping.csv:

ObjectName,FieldName,RawValue,Value
Account,TEST1__c,/DDMM/,"eval(new Date().getDate() + '' + new Date().getMonth())"

And then source value "ImportTest/DDMM/01" would become target value "ImportTest/1610/01".

**Comment by hknokh** [comment]
Hello @ppeersgi 
Added the option of conjuction eva() with regex
Please update and test now

**Comment by ppeersgi** [comment]
Works! Thanks!
