### ISSUE TITLE
[FEATURE REQUEST]-Target Org backup and restore feature

### ISSUE THREAD

**Issue by mbats-aware** [forcedotcom/SFDX-Data-Move-Utility#517]
Love the tool. One of my favourites!

I'd love to see native capability to perform a full backup of the affected target Org data before the source data is loaded.
Would be even better if you could run a command to roll back changes to the target data from the back up!

**Comment by hknokh** [comment]
Hello @mbats-aware 
Thank you for you feedback and for the suggestion!
Regarding target backup, the tool does not know which records should be backed up and sometimes you want to back up selectively but somtimes you want to do a full backup of all records. So you must tell this by providing dedicated export.json and putting csv file as the target. I see the best way to accomplish that as an independent job before acutal source->target migration.
Regarding rollback don't think that full rollback is possible to inject this feature into the tool architecture.
