### ISSUE TITLE
[QUESTION] - Standard Dataloader Functionality

### ISSUE THREAD

**Issue by BongskySFDX** [forcedotcom/SFDX-Data-Move-Utility#518]
Is there a way to use SFDMU like Data Loader?
The scenario is you have a prepared CSV file that already includes reference Ids from the related object and has been validated that these Ids exist in the target environment.

Now with Data Loader, you can use this CSV file as is. With SFDMU as per testing, you are required to put the reference data along with the CSV to be processed.

We are planning on using SFDMU via pipeline and we have users who are not well versed will SOQL and preparing other CSV files as a reference (Parent Records) will be a tedious process for these users.

I look forward to your response.

**Comment by hknokh** [comment]
Hello @BongskySFDX 
Yours is similar to this ticket
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/489
The Tool will work fine with the native DL format of the csv, but still, based on the Tool's overall architecture - it always requires a valid export.json file, where you list object fields you want to modify and external id field for each object.

If your ids is validated against the target org, I think taht you can just use Record Id as external id key for each object in the export.json. So the tool should correctly locate  every record from the csv in the target org and update it.

e.g.:

{
 "objects": [
{
    "query": "SELECT Name, Phone FROM Account",
    "externalId": "Id",
"operation": "Upsert"
},
{
    "query": "SELECT FirstName, LastName, AccountId FROM Contact",
    "externalId": "Id",
"operation": "Upsert"
}
]
}
The same thing regarding inserting of records.
But still you should provide the list of fields to update. The Tool has no OOTB feature to construct dynamic SOQL query based on the content of the source CSV file.
