### ISSUE TITLE
Invalid record hashcode. Unable to find matching record from the response returned by the bulk job.

### ISSUE THREAD

**Issue by ilanhazan** [forcedotcom/SFDX-Data-Move-Utility#52]
Hello,
When trying to copy all Contact records it produce some errors like "Invalid record hashcode. Unable to find matching record from the response returned by the bulk job.".
The export is 
{
            "operation": "Upsert",
            "externalId": "Email",
            "query": "SELECT Id, Name,Email,Platform_Role__c,LastName,FirstName,Salutation,Secondary_Email__c,MailingCity FROM Contact",
            "allRecords": false
        } 
The console output shows:
[WARN] [Batch# 7502g000000rYc5AAE:Insert] {Contact} Incompleted. 51901 records succeeded, 592 records failed.

However, no Contact records actually inserted into the target

**Comment by hknokh** [comment]
Hello,
By default the plugin uses the modern Bulk Api V2.0, 
Sometimes it can happen when the plugin is using this API
Try to switch back to the Bulk api v1.0 by setting  { bulkApiVersion : "1.0" }
Please, see the documentation:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Plugin-configuration.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Plugin-configuration.-Full-configuration.)
