### ISSUE TITLE
[QUESTION] - Anonymize data only if it is populated in Source org field

### ISSUE THREAD

**Issue by mark10281996** [forcedotcom/SFDX-Data-Move-Utility#520]
`Contact.Phone` 
`Contact` Object Settings:
mockCSVData: `true` 
updateWithMockData: `true`
Data Anonymization settings:
Object: `Contact`
Field: `Phone`
Pattern: `phone`
includedRegex: `^*`

Example: Phone value in source org: 123-222-3411. After executing sfdmu command sfdmu:run --sourceusername sandbox --targetusername csvfile. **Expected:** different phone number in CSV file. **Actual:** 123-222-3411 (Number stays the same)

Phone value in source org: Empty. After executing sfdmu command sfdmu:run --sourceusername sandbox --targetusername csvfile.
The value is still empty which is what I want. 

How do I anonymize field values that are not empty, but still keep a field value that is originally empty?

**Comment by hknokh** [comment]
Hi
First the phone pattern must start from lower letter- phone, not Phone.
Second i think you regex should be something like ^.*$

**Comment by mark10281996** [comment]
Sorry, that was a typo. I actually had phone lowercased. So I put "includedRegex": "*" and  that changes non empty values, but when phone field is originally empty it populates that field with a value. I don't want empty fields to be populated with a value. I want to have both capabilities to keep values that are already empty and only anonymize the field that has the value. How can I have both?

**Comment by hknokh** [comment]
Do you import csv file or it's org2org transformation?
Which value you try to inport which you say it is "empty", I suppose that it's recognizing it as non-empty.
Give me please an example of CSV row or record you try to import containing an empty phone.

**Comment by mark10281996** [comment]
I imported the csv file. I just want to update target org only. First I execute this command: `sfdmu:run --sourceusername sandbox --targetusername csvfile` to get the csv file with the anonymized data. See attached csvfile of the result. Originally, TestFirst1 TestLast1 contact record has a phone number value and the other contact record TestFirst2 TestLast2 has an empty phone value. See attached dev console screenshot of the original values in the org. I expected contact record TestFirst2 TestLast2 phone field value to be still empty instead of being populated with a value before executing the command `sfdmu:run --sourceusername csvfile --targetusername sandbox` to do the actual update. The export.json is shown like this: `{
    "objects": [
        {
            "query": "SELECT Id, FirstName, LastName, Phone FROM Contact",
            "operation": "Update",
            "externalId": "Id",
            "mockCSVData": true, 
            "updateWithMockData": true,
            "mockFields": [
                {
                    "name": "Phone",
                    "pattern": "phone",
                    "includedRegex": "*"
                    
                }



          ]
          
           
        }
    ]
}`
[Contact.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9961430/Contact.csv)
![Contact_records](https://user-images.githubusercontent.com/6540338/200576995-30294950-988b-408a-9d60-affa22aae8d0.PNG)


I hope this helps clarifies what I'm looking for. Thank you!

**Comment by hknokh** [comment]
Hello @mark10281996 
Yes. It was a bug
Fixed
Please update and retry
