### ISSUE TITLE
[BUG]-Field Mapping not working with namespace

### ISSUE THREAD

**Issue by fabm97** [forcedotcom/SFDX-Data-Move-Utility#521]
**Describe the bug**
Currently when mapping an objects with a namespace to objects with the same API name without namespace SFDMU will not use the mapping correctly. The records are inserted with the namespace still on the field names as I suspect.

**To Reproduce**
- Have two packages installed. One managed with namespace, one unlocked without namespace
- Try to migrate data from one org with only the managed package installed (ORG 1) to another org with both packages installed (ORG 2)
- Mapping is from NAMESPACE__APINAME__c to APINAME__c
- I receive an error that required fields are missing, that are present in the source csv when I look at it. But they still have the API Name with namespace as header

**Expected behavior**
Expected behavior would be that my data from Org 1 would be transferred into the objects of the unlocked package in Org 2.

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9981892/export.json.txt)

**Log file**
[2022-11-09__17_41_10.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9981867/2022-11-09__17_41_10.log)

**_target.csv** file.
[msMeetPlus__Meeting__c_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9981897/msMeetPlus__Meeting__c_insert_target.csv)

**Comment by hknokh** [comment]
Hi @fabm97 
According to the documentation which is saying "You should include all field listed in the sourceField property of the field mapping (or FieldName if you are using the csv) in the sobject's query string.":
https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping
all the fields you want to map in your fieldMapping definition should be listed in the query string.
For example **msMeetPlus__AddressSource__c** is missing in the query string to **msMeetPlus__Meeting__c**

**Comment by hknokh** [comment]
Hi @fabm97 
This bug should be solved.
Please recheck if it correctly recognizes the target mapped field.
