### ISSUE TITLE
[QUESTION] - Can we Transfer FeedPollVote and FeedPollChoice ?

### ISSUE THREAD

**Issue by SiLuLuLu** [forcedotcom/SFDX-Data-Move-Utility#523]
Hi,

I have tried to transfer the poll in chatter (FeedPollVote and FeedPollChoice), but i only get the  FeedPollVote , the choices link to the vote are not passd.

I would like to know is FeedPollChoice support by SFDMU ? Thank you so much.

here is the export json

{
    "objects": [
		{
            "operation": "Upsert",
            "externalId": "Name",
            "query": "SELECT Amount, CloseDate, Description, Id, LeadSource, Name, Probability, StageName, Type, AccountId FROM Opportunity",
			"afterAddons" : [
             {
                 "module": "core:ExportFiles",
                 "args" : {
                     "operation" : "Insert"
                 }
             }
         ]
        },
		{
            "operation": "Insert",
            "externalId": "Id",
            "query": "SELECT Id, Body, CreatedDate, IsRichText, LastEditDate, LinkUrl, Revision, Status, Title, Type, ParentId$Opportunity FROM FeedItem"
        },
        {
            "operation": "Insert",
            "externalId": "Id",
            "query": "SELECT Id FROM FeedPollVote"
        },
		{
            "operation": "Insert",
            "externalId": "Id",
			"master": false,
            "query": "SELECT ChoiceBody,Position FeedItemId FROM FeedPollChoice"
        }
    ],
    "promptOnMissingParentObjects": false,
    "promptOnIssuesInCSVFiles": false
}

**Comment by hknokh** [comment]
Hi @SiLuLuLu 
Yes it's supported.
I saw 2 possible problems with your export.json: 
The first one:
SELECT ChoiceBody,**Position FeedItemId** FROM FeedPollChoice
-> missing comma between Position FeedItemId
The second one:
SELECT Id FROM FeedPollVote
-> Missing lookup field ChoiceId to FeedPollChoice, so it can't bind Votes to the FeedPollChoices.
Should be: SELECT Id, **ChoiceId** FROM FeedPollVote
Also may be worth to add FeedItemId to the Votes object.
Refer:
https://developer.salesforce.com/docs/atlas.en-us.236.0.object_reference.meta/object_reference/sforce_api_objects_feedpollvote.htm
