### ISSUE TITLE
[BUG]-Mock CSV data is not working

### ISSUE THREAD

**Issue by aacostad-appsolutely** [forcedotcom/SFDX-Data-Move-Utility#525]
**Describe the bug**
I have configured a simple export to test the Data Anonymization functionality, but the resulting csv does not have data anonymized.

**To Reproduce**

1. Create an export.json as described in the "export.json" section.
2. Run the command: `sfdx sfdmu:run -s <sourceOrg> -u csvfile --loglevel TRACE --verbose`, where:
- \<sourceOrg\> is the alias for the org where data must be extracted.

**Expected behavior**
I expect having an output file Account.csv where the name of the accounts was anonymized.

**export.json**
`{
  "objects": [
    {
      "query": "SELECT Id, Name FROM Account ORDER BY Id ASC LIMIT 100",
      "operation": "Insert",
      "externalId": "Name",
      "updateWithMockData": true,
      "mockCSVData": true,
      "mockfields": [
        {
          "name": "Name",
          "pattern": "name"
        }
      ]
    }
  ]
}`

**Log file**
[2022-11-22__18_32_43.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10069789/2022-11-22__18_32_43.log)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
@aacostad-appsolutely  hi
You have typo in export.json
not "mockfields", but  "mock**F**ields"

**Comment by aacostad-appsolutely** [comment]
Thanks, now it worked!
