### ISSUE TITLE
[QUESTION] - Import file by Add-On but Error Maximum size of request reached

### ISSUE THREAD

**Issue by SiLuLuLu** [forcedotcom/SFDX-Data-Move-Utility#526]
Hi,

I tried a large volume for AddOnModule to import files, I wiil get the following log
[2022-11-23__10_27_38.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10076678/2022-11-23__10_27_38.log)
I would like to know how to avoid the problem [ERROR] {ContentVersion} The Insert API operation FAILED with message: ; nested exception is: 
	common.exception.ApiException: Maximum size of request reached. Maximum size of request is 52428800 bytes..

Thanks you for the help in advance.

**Comment by SiLuLuLu** [comment]
I think I found the problem, this is because the target Object can not be found.
[17:30:41.741] {Quote} Total retrieved within all stages (source/target): 1/0 records.

I used "externalId": "TechId__c", the record is existed in source Org and target Org with the same value of  TechId__c.

How do I check the problem?

**Comment by SiLuLuLu** [comment]
Hello @hknokh , 40M is not safe, I changed into 25M, 90chunk will still fail one or two, but the rest are basically passed.

**Comment by hknokh** [comment]
Interesting.... 
I'm thinking about to reduce to 15 as default and will add new parameter to adjust chunk size from the exort.json

**Comment by hknokh** [comment]
By the way, you can't upload very large single file, because particular content version is not splitted into bytes, but it's uploaded completely. 
Chunk - means a bunch of content versions which is uploaded at once, the total size of chunk can't exceed the defined max size.

**Comment by hknokh** [comment]
I added the maxChunkSize parameter to ExportFiles Add-On.
You can now take a control over the size of uploaded chunks from the export.json
The documentation is updated:
https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module

**Comment by SiLuLuLu** [comment]
@hknokh Thank you so much for the new feature

**Comment by hknokh2** [comment]
Hello @SiLuLuLu 
I've also added the new parameter **maxFileSize** to control max file size and to prevent issue of **Maximum size of request reached**
The Tool will ignore Files larger then **maxFileSize**. 
You cannot set this parameter to more then 37Mb. 
https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module
