### ISSUE TITLE
[FEATURE-REQUEST] - Avoid duplicates in SFDMU Insert

### ISSUE THREAD

**Issue by mmoyaferrer** [forcedotcom/SFDX-Data-Move-Utility#529]
I'm currently using SFDMU to deploy data in an automated way in a pipeline.

Until now, the pipeline always used the `Upsert` operation in our `export.json` file. I.e
```
{
    "objects": [
        {
            "query": "SELECT Id, Phone, TestObject3__c FROM Account WHERE Name LIKE 'TEST_ACC_%'",
            "operation": "Upsert",
            "externalId": "Name"
        },
    ]
}
```

Now, I want to introduce the `Insert` mode in my pipeline, because existing data should not be overridden in some scenarios. However, this `Insert` operation is not working as I would expect, as it duplicates rows, instead of not inserting a record if it already exists. That causes frequent issues in data duplication and unique fields.

According to [SFDMU docs][1]: `"Insert" - creates new records on the target org even old versions of these records already exist.`

What should be the way to use SFDMU in `Insert` mode avoiding duplication? Is using `Upsert` my only resource?

  [1]: https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

**Comment by hknokh** [comment]
Hello @mmoyaferrer 
I don't comletely understand your use case. What does it mean in some scenarios ?
Indeed, the only option to avoid the duplication and let the SFDMU decide if this is the same record is using **Upsert** operation. And the only way to detect the similar records is by externalId. The Insert op **DOES NOT** use the specified externalId field ar all, it simply ignores it, for Insert - the **Record Id is always in use** as the external ID field.
The viable alternative is to consider using the **Object Sets** feature in conjuction with Update/Insert operations to process the same object multiple times within the same migration.
Set up the first Object Set to Update existing records and the second - to Insert new records into the same sObject.
Refer:
https://help.sfdmu.com/full-documentation/advanced-features/multiple-object-sets

**Comment by mmoyaferrer** [comment]
> https://help.sfdmu.com/full-documentation/advanced-features/multiple-object-sets

Thank you for the info @hknokh, I finally relied on new unique custom fields to block the duplication of records. That has the disadvantage of getting some warning/errors by SFDMU when trying to insert those, however not something critical to take into account in my scenario.

**Comment by hknokh** [comment]
@mmoyaferrer 
OK. I think now I understand your use case.  You want to insert ONLY the new records , which do not exist in the target by the given key, and skip the rest of existing. The Upsert operation will modify the existing records, which scenario you want to avoid. I think that it would be worth to introduce a special operation for that purpose. I will add new feature and let you know when done. Could you please confirm that I understand correctly your requirement? Thx.

**Comment by mmoyaferrer** [comment]
> @mmoyaferrer OK. I think now I understand your use case. You want to insert ONLY the new records , which do not exist in the target by the given key, and skip the rest of existing. The Upsert operation will modify the existing records, which scenario you want to avoid. I think that it would be worth to introduce a special operation for that purpose. I will add new feature and let you know when done. Could you please confirm that I understand correctly your requirement? Thx.

Exactly, that's correct. Having it built-in would be great.

**Comment by hknokh** [comment]
Hello @mmoyaferrer 
I've added the new skipExistingRecords to the object definition, which prevents update existing records in any case.
Please update the SFDMU and check it.
Thanks.

**Comment by mmoyaferrer** [comment]
> Hello @mmoyaferrer I've added the new skipExistingRecords to the object definition, which prevents update existing records in any case regardless used Operation. (note that it will still delete records if Delete is used) https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format Please update the SFDMU and check it. Thanks.

Sure, I will let you know in case of any issues, thank you! I
