### ISSUE TITLE
Auto create picklist values

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SFDX-Data-Move-Utility#53]
Can the SFDMU be used to automatically copy picklist values from source to target org?
(or is there some alternative tool for that).

**Comment by hknokh** [comment]
Hello,
Yes if course, it can copy any type of fields except of binary data. The support to content like attachments or content document will be added.

**Comment by az-oolloow** [comment]
@hknokh sorry, i mean the actual schema (e.g. picklist metadata, NOT picklist data). If this is already available, how do i use this?

**Comment by hknokh** [comment]
@az-oolloow , 
Unfortunatelly, migration/creation/changing of metadata is not supported, because this is the tool intended to deliver solution for data migration not for metadata.
