### ISSUE TITLE
[QUESTION] - missing parent lookup records with all objects

### ISSUE THREAD

**Issue by Tadeas3** [forcedotcom/SFDX-Data-Move-Utility#534]
Hi,
I'm trying to create a simple csv-to-scratch-org job with SFDMU, but I got stuck. I exported data (from another org) to csv files and when I try to import them, I always get output like this:

```
=== UPDATING THE TARGET STAGE 1 ...
{Account} The Insert API operation has been started using REST API.
[Job# REST:Insert] {Account} The job has been created. Uploading data ...
WARNING: [WARN] [Batch# REST:Insert] {Account} Incompleted. 9 records processed, 9 records failed.
{Account} The Insert API operation has been finished.
{Account} Updating the Target has been completed. Processed 9 records.
WARNING: [WARN] {Asset} 5 missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details.
Command in progress ...... ?
Continue the job (y/n)? [n]: 
```

So basically, it's not able to create any Assets as it's not able to solve parent lookup to Account. MissingParentRecordsReport.csv looks like this:

```
Date update,Child Id,Child Lookup Id Field,Child Lookup Reference Field,Child SObject,Parent SObject,Parent ExternalId Field,Missing expected parent ExternalID value
2022-12-19  16:28:15.568,02i7E000004Y9qoQAC,AccountId,Account.GlobalId__c,Asset,Account,GlobalId__c,3609408
2022-12-19  16:28:15.568,02i7E000004XvNYQA0,AccountId,Account.GlobalId__c,Asset,Account,GlobalId__c,28593
2022-12-19  16:28:15.568,02i7E000004XzGrQAK,AccountId,Account.GlobalId__c,Asset,Account,GlobalId__c,28593
2022-12-19  16:28:15.568,02i7E000004Y2psQAC,AccountId,Account.GlobalId__c,Asset,Account,GlobalId__c,2584677
2022-12-19  16:28:15.568,02i7E000004XqneQAC,AccountId,Account.GlobalId__c,Asset,Account,GlobalId__c,2584677
```

Of course I checked the destination org if the accounts where created successfully and they were:

![image](https://user-images.githubusercontent.com/15797128/208471483-1b9f1be1-a7e8-46c6-86f8-38858b16a8ab.png)

What am I missing? There is a lot of custom fields on Asset (like over a hundred), is it possible that there is some kind of silent limit?

**Comment by hknokh** [comment]
Hello
I am very sorry)  As I've wrote here https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/533  for this moment I cant tackle configuration-related issues only clear bugs or maybe feature requests, which look important and can be added without big pain...)
 Now, regarding the limit of field number, the sf indeed has limitation of an overall length of query string, which can be executed using Salesforce api. The sfdmu internally splits large query string into multiple sub queries so don't think that it is the issue of limitation.
Need to investigate you case on your side.
