### ISSUE TITLE
Error "No such column 'Name' on entity 'Skill'." when UPSERTING SkillRequirement with related Skill object

### ISSUE THREAD

**Issue by MykhailoSlivisnkiy** [forcedotcom/SFDX-Data-Move-Utility#537]
When upserting SkillRequirement object with related Skill, the following error shows up

<img width="1388" alt="Screenshot 2022-12-23 at 16 42 56" src="https://user-images.githubusercontent.com/37076933/209353844-47c6baea-bc98-4f92-a486-ef903c8a7f95.png">

This happens even though the field Name is not part of the SOQL query and only during Upsert operaetion.

**Comment by hknokh** [comment]
Hi,
Thank you for using the SFDMU!
 This case cannot be handled, since it is not comply our **CASE OPENING GUIDELINES**.
