### ISSUE TITLE
Copy ContentDocument (files) along with ContentDocumentLink

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/SFDX-Data-Move-Utility#54]
Is it possible to copy ContentDocument with ContentDocumentLink from source to target, so that binary file content (ContentVersion) is also copied?
Trying to run this i got

```
The SOQL query for sObject ContentDocument does not include any field can be updated or inserted.
```

**Comment by hknokh** [comment]
Hello @az-oolloow 
Currently the transfer of binary data/attachments is not supported, but it will be implemented.
