### ISSUE TITLE
[QUESTION] - How do I select the "working directory" ?

### ISSUE THREAD

**Issue by martingaleh** [forcedotcom/SFDX-Data-Move-Utility#540]
I followed the instructions and make the following json called export.json:
`{
    "objects": [
        {
            "query": "SELECT Id, Name FROM Account",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}`
I saved it in ./scripts
Then I installed sfdmu, which ended seemingly well and ran:
sfdx sfdmu:run -sourceusername martingaleh@yahoo.com -targetusername martingaleh@yahoo.com.stage -p ./scripts

And I got:
`sfdx sfdmu:run --sourceusername martingaleh@yahoo.com --targetusername martingaleh@yahoo.com.stage
Execution of the command sfdmu:run has been started.
Command in progress ...... done
[ERROR] Command initialization error: Missing package.json file in the working directory..
Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
Total time elapsed: 00h 00m 00s 005ms .`  
Just in case it was something with sfdx, I ran sfdx force:source:retrieve -m CustomObject:Account and it went fine
my package.json is in the base directory ./ so I moved my export.json to the base directory and ran it there with no -p and got the same error.  I must be the only one with the world with this problem.  Is my installation just so abnormal?

**Comment by hknokh** [comment]
Hello, @martingaleh 
I am still checking your case, I will update you soon.
Thx.

**Comment by hknokh** [comment]
The correct syntax is:
sfdx sfdmu:run -sourceusername martingaleh@yahoo.com -targetusername martingaleh@yahoo.com.stage **-p="./scripts"**
OR
sfdx sfdmu:run -sourceusername martingaleh@yahoo.com -targetusername martingaleh@yahoo.com.stage **--path "./scripts"**
Please, let me know if you have any further questions.
Thx!

**Comment by martingaleh** [comment]
My package-json is in the base directory and vscode is working so I expect that means the package is acceptable.  I put my json script everywhere in hopes I would catch lighting.  It's still not doing it.
`base) ~/.../dev/cantor(main*)$ sfdx sfdmu:run -s production -u Dev -p="./scripts" 
 ›   Warning: sfdx-cli update available from 7.175.0 to 7.182.1.
Execution of the command sfdmu:run has been started.
Command in progress ...... done
[ERROR] Command initialization error: Missing package.json file in the working directory..
Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
Total time elapsed: 00h 00m 00s 011ms .
(base) ~/.../dev/cantor(main*)$ sfdx sfdmu:run -s production -u Dev 
 ›   Warning: sfdx-cli update available from 7.175.0 to 7.182.1.
Execution of the command sfdmu:run has been started.
Command in progress ...... done
[ERROR] Command initialization error: Missing package.json file in the working directory..
Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
Total time elapsed: 00h 00m 00s 005ms .`

**Comment by hknokh** [comment]
The filename is export.json correct ? Not package.json ? :)
Would it be a file permission issue?

**Comment by martingaleh** [comment]
My new command is:
 sudo sfdx sfdmu:run --sourceusername stage --targetusername mortDev --verbose  --path "./scripts"

It's still running so I can't tell if the solution was the sudo or if it was the no equal sign, which is in contrast to my last attempt and your last instruction.  Can I say, while you're reading, that this is solid Gold!!!

**Comment by hknokh** [comment]
Happy to hear that it's working you. 
Seems that sudo does a trick. 
Forgot to say you that need sudo to run it in macos....
