### ISSUE TITLE
[BUG]-Querying Child object records do not filter by the parent records

### ISSUE THREAD

**Issue by SKN536** [forcedotcom/SFDX-Data-Move-Utility#542]
**Describe the bug**
When migrating 

**To Reproduce**
Describe steps to reproduce the behavior.

**Expected behavior**

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello!
Thank you for using the SFDMU!
This case cannot be handled, since it does not comply our [Support Policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).
