### ISSUE TITLE
[QUESTION] - CareSpecialty (Health Cloud) "no fields to update or insert"

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/SFDX-Data-Move-Utility#546]
I'm trying to run the below query but keep getting a warning about no included fields to update or insert. I've tried using both "all" and declaring the fields separately.

Any special / different about the CareSpecialty object that I should be aware of?

```
"query": "SELECT all FROM CareSpecialty",
"operation": "Upsert",
"externalId": "Account__r.Name;Name"
```

```
"query": "SELECT IsActive, Description, EffectiveFrom, EffectiveTo, Name, OwnerId, SpecialtyCode, SpecialtyType, SpecialtyUsage FROM CareSpecialty",
"operation": "Upsert",
"externalId": "Account__r.Name;Name"
```

> The SOQL query for sObject CareSpecialty does not include any field can be updated or inserted

**Comment by hknokh** [comment]
@jonny-harte 
Health Colud does not installed on my side and I can't try it directly to reproduce your issue.
But the issue of no fields found can occur when SFDMU get the field metadata of this object and detected that all its fields are readonly for the current user. I don't know why, this should be checked on your side. Check the field permisisons etc.

**Comment by hknokh** [comment]
Closed as it's solved
