### ISSUE TITLE
[QUESTION]-Data anonymization not working

### ISSUE THREAD

**Issue by jcostacg** [forcedotcom/SFDX-Data-Move-Utility#547]
Not sure if I'm doing something wrong but this configuration is keeping the phone field value as the same as the source
        {
            "operation": "Upsert",
            "externalId": "FirstName;LastName;Email",
            "mockFields": [
                {
                    "name": "Phone",
                    "pattern": "phone",
                    "excludedRegex": "",
                      includedRegex": "*"
                },
                {
                    "name": "Fax",
                    "pattern": "phone",
                    "excludedRegex": "",
                    "includedRegex": "*"
                }
            ],
            "master": false,
            "query": "SELECT Id, Name, updateable_true FROM Contact"
        },

There is an * in includedRegex": "*", but for some reason it is not showing up here

**Comment by hknokh** [comment]
Hello @jcostacg 
This case does not comply the [Support Policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy) and typically isn't to be handled. 
Please, keep this in mind on next reaching out to me. Thanks.
---
Regarding your case.
- Can you clarify, please, what's the reason you should use data anonymization if you want (as you said) just to **keep** the **SAME** phone value **as the source** ? Anonymization is to **replace** the real value with **ANOTHER** fake value.
- Let say, you still want to make phone a fake. In this case, **none** of **includeRegex** or **excludeRegex** **can have empty value**. 
As I undrestand you question, you have the following config:
```json
{
     "name": "Phone",
     "pattern": "phone",
     "excludedRegex": "",
     "includedRegex": "*"
}
``` 
So try remove excludeRegex property.

**Comment by jcostacg** [comment]
``Sorry if I was not clear but I want the data to be anonymized.  However, using the configuration above results the same data on the target sandbox.
I´ve removed the excludeRegex property as you suggested but it is still not generating fake data .

Just to be clear, if the source Phone field has  the value +441112222222  both 
`{
     "name": "Phone",
     "pattern": "phone",
     "excludedRegex": "",
     "includedRegex": "*"
}`

or

`{
     "name": "Phone",
     "pattern": "phone",
     "includedRegex": "*"
}`

will result in the same +441112222222 on the target. I tried with different fields and got the same

**Comment by jcostacg** [comment]
nevermind, just found out that the updateWithMockData property was missing. Thanks for the support

**Comment by hknokh** [comment]
Always welcome!
Happy hear the it's solved.
