### ISSUE TITLE
[BUG] - Problem Value mapping with regex

### ISSUE THREAD

**Issue by Ewaken** [forcedotcom/SFDX-Data-Move-Utility#548]
Hi, I would like to modify Contact Email before insert/update it on target org and replace ".", "-", "@" with "_" but my regex seems to find records to update. I tried also the js way with evaluate but this doesn't work either. My regex seems to be ok where am I wrong?

Could you help me with that?

I attached my export.json and my ValueMapping.csv.

Thanks

**export.json**
```
{
    "promptOnMissingParentObjects": false,
	"objectSets": [
		{

			"objects": [
				{
					"_comment": "Account Personne Physique",
					"query": "SELECT Id,RecordTypeId,Name,Tech_idExternal__c, NumIdAccount__c,NumIdAccount_Calc__c,Type,TECH_CountryCode__c FROM Account WHERE  RecordtypeId = '012b0000000DrGeAAK'",
					"operation": "Upsert",
					"externalId": "Tech_idExternal__c",
					"useValuesMapping": true
				},
				{
					"_comment": "Contact Personne Physique",
					"query": "SELECT all,RecordTypeId FROM Contact WHERE RecordtypeId != '012b00000000mWGAAY' AND TECH_Refresh_Data__c != null AND TECH_Refresh_Data__c != ''",
					"operation": "Upsert",
					"externalId": "TECH_idExternal__c",
					"excludedFields": [
						"UID__c",
						"Identite_digitale__c",
                        "Personne_Physique__c"
					],
					"useValuesMapping": true
				}
			]
		}
	]
}
```
[ValueMapping.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10404243/ValueMapping.csv)

**Comment by hknokh** [comment]
Hello @Ewaken 
Thank you for reaching out to me!
I will do my best to review your issue ASAP, but sometimes it can take while.
You can see also the [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).
Thx.

**Comment by hknokh** [comment]
Hello  @Ewaken 
Thanks, you've found a bug
Should work now.
Please update and recheck

**Comment by Ewaken** [comment]
Hello @hknokh, thanks for your help and this quick fix. I will open a new feature request about the parsing of the ValueMapping.csv file.

**Comment by hknokh** [comment]
Happy to hear that it's solved!
And.waiting for your feature request.
Thx
This tiket has been closed as completed.
