### ISSUE TITLE
Audit Fields not set upon creation even though 

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#55]
Audit fields such as `CreatedDate` are filtered out when Inserting/Upserting records. This can also be seen in the generated target .csv which do not contain audit fields such as `CreatedDate`

**Expected Behavior**
Audit fields such as `CreatedDate`, `CreatedById`, `LastModifiedDate`, etc. should be set if the running user has the "Set Audit Fields upon Record Creation" permission.

**Steps to reproduce**
1. Assign permission 'Enable "Set Audit Fields upon Record Creation"' to the migration user.
2. Run `sfdmu:run --sourceusername <source> --targetusername <target>`

**Workaround**
Run the job in two separate commands instead
1. `--sourceusername <source> --targetusername csvfile`
2. `--sourceusername csvfile --targetusername <target>`

**Comment by hknokh** [comment]
Hello, @kevdo475 
I fixed the issue with the audit fields.
Please re-check.
