### ISSUE TITLE
[FEATURE-REQUEST]-When using objectSets the 'Target'-folder is overwritten

### ISSUE THREAD

**Issue by RensVerhagen** [forcedotcom/SFDX-Data-Move-Utility#555]
**Describe the bug**
When using objectSets in combination with createTargetCSVFiles, For each objectSet the target folder is created including target files, but for every subsequent objectSet the target folder is deleted first. This results in only having a target folder and files for the latest objectSet in the export.json

**To Reproduce**
Create a export.json using objectSets and set createTargetCSVFiles = true

**Expected behavior**
I would expect that mutliple target folders are created.

**export.json**
Attaching .json is not allowed

**Log file**
[2023-01-17__23_02_58.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10439842/2023-01-17__23_02_58.log)

**Comment by hknokh** [comment]
Hello!
Thank you for reaching out to me!
You are right that it's not correct to override the target folder each time.
I will think about how to organize output of multiple objectSets in multiple target directories.
I will update the ticket when done.

**Comment by hknokh2** [comment]
Hello @RensVerhagen 
The behavior regarding the target folder has been changed.
Separated folders are being now  created for each object set
https://help.sfdmu.com/full-documentation/reports/the-target-csv-files
Please update the plugin and retry

**Comment by RensVerhagen** [comment]
Thnx @hknokh ,

Tested the fix, files are not overwritten anymore:
![image](https://user-images.githubusercontent.com/20991258/215522839-bdabbbba-5505-47a6-b4f1-5567bdfcad77.png)

![image](https://user-images.githubusercontent.com/20991258/215523698-9c103c41-061c-4371-9b61-621f92499e44.png)


Though in terms of consistency might be better to store every set in it's own folder. E.g.:
- object-set-1
- object-set-2

**Comment by hknokh** [comment]
Hello. 
No. The first object set #1 is always should be in the target directory itself as it is currently for the single object set. It's done to prevent breaking changes.

**Comment by hknokh** [comment]
Closed since it's completed
