### ISSUE TITLE
[FEATURE REQUEST]-Make configurable columns delimiter for ValueMapping.csv

### ISSUE THREAD

**Issue by Ewaken** [forcedotcom/SFDX-Data-Move-Utility#558]
Hello again @hknokh, as you said earlier, extras commas are a problem for ValueMapping.csv. I tried ealier to use the eval() function inside the ValueMapping.csv to modify my datas. The problem is that if you use inside the eval() function, extra commas like "'sameStuff'.replace('stuff'**,** 'otherStuff')" you will have an error for your csv line. Also, "eval('sameStuff'.replace('stuff', 'otherStuff'))" will just be evaluated as a string.

To make the eval() function working with extra commas, I tried to change the delimiter for my ValueMapping.csv and it worked. I made these changes in your "common.ts" component:
![image](https://user-images.githubusercontent.com/54441591/213508346-4ff9df03-751e-450a-a9a4-875c0b99494d.png)

Could be possible to make configurable this delimiter?

**Comment by hknokh** [comment]
Hello!
Good feature.
Added to the roadmap

**Comment by hknokh** [comment]
Closed for now. 
I will update the ticket when this feature will be implemented.

**Comment by hknokh2** [comment]
Hello @Ewaken 

Thanks again for the suggestion.

I've implemented your feature.

Introduced 2 new global script props:
**csvReadFileDelimiter
csvReadFileDelimiter**

Documentation:
https://help.sfdmu.com/full-configuration#scriptobject-object
