### ISSUE TITLE
[BUG]- Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by mark10281996** [forcedotcom/SFDX-Data-Move-Utility#569]
Insert files using the core:ExportFiles module is causing the error Cannot create a string longer than 0x1fffffe8 characters and stops the job from completing. I've ran it with simulation mode off and I found that the job hangs up, but with simulation mode on I've been been get the error below in the logs.

Attached is export.json file being used. [export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10722540/export.txt)

[23:45:12.703] In progress... Completed 0/20 records.
[23:45:12.899] In progress... Completed 10/20 records.
[23:45:15.880] In progress... Completed 20/20 records.
[23:45:15.883] {ContentVersion} The Insert API operation has been started using REST API (SIMULATION MODE).
[23:45:27.805] {ContentVersion} The Insert API operation has been completed.
[23:45:28.242] [core:ExportFiles] {agf__ADM_Work__c} Processing chunk #108 of 27 items..
[23:45:28.479] In progress... Completed 0/27 records.
[23:45:28.573] In progress... Completed 10/27 records.
[23:45:28.825] In progress... Completed 20/27 records.
[23:45:30.604] In progress... Completed 27/27 records.
[23:45:30.606] {ContentVersion} The Insert API operation has been started using REST API (SIMULATION MODE).
[23:45:44.959] {ContentVersion} The Insert API operation has been completed.
[23:45:45.215] [core:ExportFiles] {agf__ADM_Work__c} Processing chunk #109 of 1 items..
[23:46:50.826] In progress... Completed 0/1 records.
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:643:37)
    at Buffer.toString (node:buffer:812:14)
    at Request.<anonymous> (C:\Users\mbuser\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\sfdx.js:456:55)
    at Request.emit (node:events:538:35)
    at IncomingMessage.<anonymous> (C:\Users\mbuser\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:645:28)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_STRING_TOO_LONG'
}
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:643:37)
    at Buffer.toString (node:buffer:812:14)
    at Request.<anonymous> (C:\Users\mbuser\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\sfdx.js:456:55)
    at Request.emit (node:events:538:35)
    at IncomingMessage.<anonymous> (C:\Users\mbuser\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:645:28)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_STRING_TOO_LONG'
}
Command in progress... done

**Comment by hknokh2** [comment]
Hello @mark10281996 
This is known nodejs memory limitation issue which can occur when constructing a string variable having extremely large size.
It occurs inside nodejs core code and I have no control over it.
From my side, as the current implementation of SFDMU file handling pipeline, I must convert your entire file from the binary data into a single base64 string variable for later processing. I can't work directly with binary data.
I need to check if I have any alternative option to remaster thius pipeline to allow processing huge files.
For now, I have to say that the SFDMU has a limitation for the single file size as foloowing:
To represent file of 100Mb the nodejs needs 3x1^8/4 = 75Mb of memory for base64 string variable.
So currently you can transfer file attachment not larger than 1.3Gb for 64bit machines and  682Mb for 32bit machines.
How long is your file you try to transfer ?

**Comment by mark10281996** [comment]
Hi @hknokh2, 

Thanks for looking at this issue so quickly. The largest file being transferred is 529.7MB (555468652 bytes). I did this query to find the largest file. SELECT ContentDocumentId, ContentDocument.ContentSize, LinkedEntityId, Visibility FROM ContentDocumentLink where LinkedEntityId in ( SELECT Id FROM agf__ADM_Work__c) and LinkedEntity.Type='agf__ADM_Work__c' ORDER BY ContentDocument.ContentSize DESC


What do you suggest to prevent the execution from stopping? Can I skip transferring large files?

**Comment by mark10281996** [comment]
I want to see if I can upsert the agf__ADM_Work__c records using the field agf__External_ID__c - Data type: Text(32) (External ID) (Unique Case Sensitive) as the external id and selectively insert attachments, but the plugin is doing an insert instead of updating any agf__ADM_Work__c  records. I have the external id field (agf__External_ID__c ) matching in  both the source org and target org 😞 .
{
      "deleteOldData": false,
      "excluded": false,
      "query": "SELECT Id, Name, agf__Status__c, agf__External_ID__c, RecordTypeId FROM agf__ADM_Work__c",
      "operation": "Upsert",
      "externalId": "agf__External_ID__c",
      "afterAddons" : [
        {
            "module": "core:ExportFiles",
            "args" : {
                "operation" : "Upsert",
            }
        }
      ]
      
    },

**Comment by hknokh** [comment]
Try to use sourceWhere parameter of the ExportFiles add-on and limit by ContentSize < n
Please try to find the largest n the sfdmu can proceed and let me know what is it. I have no option to check it on my side. Thank you in advance!

**Comment by mark10281996** [comment]
@hknokh, 
From testing, I found out that a file has to be 37 MB (38797312 bytes) or less. I created a 38 MB file and this error occurs **Error message: ; nested exception is: common.exception.ApiException: Maximum size of request reached. Maximum size of request is 52428800 bytes...** The error Cannot create a string longer than 0x1fffffe8 characters was only for one file that was 530 MB. My second largest file to migrate is 33 MB so I won't get that Maximum size of request reached. That error is from [salesforce ](https://help.salesforce.com/s/articleView?id=000384730&type=1) and they say to change the batch size, but I only tested it on the 1 file. However, the main error that is preventing me from migrating files is this error **Execution of the command has aborted due to unexpected error: Cannot convert undefined or null to object.**. I'm unable to migrate a lot of files at a time. I need to migrate over 7696 files to another org. Hope you're able to figure out the last issue that I reported. I appreciate your help.

**Comment by hknokh2** [comment]
@mark10281996 
Thanks a lot for the investigation.
I'm checking

**Comment by hknokh2** [comment]
@mark10281996 
- The issue of **Execution of the command has aborted due to unexpected error: Cannot convert undefined or null to object** has been fixed. 
- Added the new parameter **maxFileSize**
- The sfdmu will now automatically skip files larger then 37Mb. This will also prevent the issue of **Error: Cannot create a string longer than 0x1fffffe8 characters** 
- 
See the reference: https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module

Please update the Plugin and retry.

**Comment by mark10281996** [comment]
@hknokh2, thank you so much! I updated the plugin and tested with and without the maxFileSize argument. I had no issues when I added the argument  **"maxFileSize" : 38797312**. Without adding this argument, I got the error: **common.exception.ApiException: Maximum size of request reached. Maximum size of request is 52428800 bytes..**

**Comment by hknokh2** [comment]
@mark10281996 

Can't reproduce.

**I'm testing with 2 accounts:**
```json
{
 "objects": [
     {
         "operation": "Upsert",
         "externalId": "Name",
         "query": "SELECT Name FROM Account WHERE Name IN ('ACC_10000', 'ACC_10001')",

         "afterAddons" : [
             {
                 "module": "core:ExportFiles",
                 "args" : {
                     "operation" : "Insert",
			"deleteOldData": true
                 }
             }
         ]

     }
 ]
}
```

**In my tests**
First account has 15 files:
10 small files,
5 large fles of 15,20,25,36,37 Mb

Second acocunt has 10 files:
9 small files,
1 large file of 60 Mb

**It uploaded with success totally 24 files:**
From the first account uploaded all 15 files since they are <= 37 Mb
From the first account uploaded 14 files, it omits the large file of 60 Mb.

What is your file and how to reproduce ?

**Comment by mark10281996** [comment]
@hknokh, I can't reproduce. I'm not sure which files it was referring to when it gave me that error, but it's skipping files that are larger than 37 MB. It's working as expected. We can close the issue. Thanks again for your help :)
