### ISSUE TITLE
[BUG]-Problem Value mapping with .eval() and RAW_VALUE: The first value is taken as RAW_VALUE.

### ISSUE THREAD

**Issue by Ewaken** [forcedotcom/SFDX-Data-Move-Utility#570]
**Describe the bug**
Hello, I tried to modify Contact Email before insert/update it on target org with "RAW_VALUE" to catch the source value, but it seems "RAW_VALUE" take only one record value by batch or by objectSet. At the end, I have my contact records inserted with the same email and updated with an another email. _e.g: two records with the same modified email : "email_test_com@test.com"_

**To Reproduce**
sfdx sfdmu:run --sourceusername {sourceOrg} --targetusername {targetOrg}

**Expected behavior**
I would like that the RAW_VALUE take the value of each record Email field from org source.

**export.json**
```
{
    "promptOnMissingParentObjects": false,
    "csvReadFileDelimiter": ";",
	"objectSets": [
		{

			"objects": [
				{
					"_comment": "Account Personne Physique",
					"query": "SELECT Id,RecordTypeId,Name,Tech_idExternal__c, NumIdAccount__c,NumIdAccount_Calc__c,Type,TECH_CountryCode__c FROM Account WHERE  RecordtypeId = '012b0000000DrGeAAK'",
					"operation": "Upsert",
					"externalId": "Tech_idExternal__c",
					"useValuesMapping": true
				},
				{
					"_comment": "Contact Personne Physique",
					"query": "SELECT all,RecordTypeId FROM Contact WHERE RecordtypeId != '012b00000000mWGAAY' AND TECH_Refresh_Data__c != null AND TECH_Refresh_Data__c != ''",
					"operation": "Upsert",
					"externalId": "TECH_idExternal__c",
					"excludedFields": [
						"UID__c",
						"Identite_digitale__c",
                        "Personne_Physique__c"
					],
					"useValuesMapping": true
				}
			]
		}
	]
}
```
**ValueMapping.csv**
```
ObjectName;FieldName;RawValue;Value
Contact;Email;/(.+)/;eval('RAW_VALUE'.replace(/([.\\,@-]+)/gm, '_') + '@test.com')
```

**Comment by hknokh** [comment]
Hello!
Thank you for reaching out to me!
I will do my best to review your issue ASAP, but sometimes it can take a while.
You can see also the [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).
Thx.

**Comment by hknokh2** [comment]
Fixed.
Please update and recheck.

**Comment by Ewaken** [comment]
It works. Thank you for this fix.
