### ISSUE TITLE
[QUESTION]-DUPLICATE_VALUE error during upsert operation for CSV Data Load to Table

### ISSUE THREAD

**Issue by vuha-acn** [forcedotcom/SFDX-Data-Move-Utility#573]
**Describe the bug**
During the load of a CSV file using "operation": "Upsert", I'm getting the following error `DUPLICATE_VALUE:Decision Matrix Row with HashKey 3a38b7471455ed59c0b5c3d9f902766e and Decision Matrix Version 0lN0i000000015b already exists.`. 

**To Reproduce**
Execute the command `sfdx sfdmu:run --sourceusername csvfile --targetusername OrgID --verbose --filelog --loglevel=trace` using the export.json file and CSV file for a target table that has existing records.

**Expected behavior**
Records are to be upserted if existing and match.  If any differences, they are to be overwritten.

**export.json**

`{
    "objectSets": [
      {
        "objects": [
          {
            "query": "SELECT Id, Name FROM CalculationMatrixVersion",
            "externalId": "Name",
            "operation": "Readonly"
          },
          {
            "query": "SELECT InputData, OutputData, CalculationMatrixVersionId FROM CalculationMatrixRow",
            "operation": "Upsert"
          }
        ]
      }
    ],
    "excludeIdsFromCSVFiles": "true"
  }`

**Log file**
Attached.

**_target.csv** file.

Sample Errors:

`DUPLICATE_VALUE:Decision Matrix Row with HashKey d7fe41a04bb9446c9881e4f3cb5537f0 and Decision Matrix Version 0lN0i000000015b already exists.:--`

`DUPLICATE_VALUE:Decision Matrix Row with HashKey d7fe41a04bb9446c9881e4f3cb5537f0 and Decision Matrix Version 0lN0i000000015b already exists.:--`

[2023-02-21__22_04_54.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10816855/2023-02-21__22_04_54.log)

[CalculationMatrixRow.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10816856/CalculationMatrixRow.csv)

**Comment by vuha-acn** [comment]
@hknokh - Any chance you are able to look into this error?

**Comment by hknokh** [comment]
Hello!
Thank you for reaching out to me!
Sorry for the delay... 
I will do my best to review your issue ASAP, but sometimes it can take a while...
You can see also the [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).
Thanks !

**Comment by vuha-acn** [comment]
Sounds good @hknokh I just wanted to keep the bug open and not have it to be closed automatically for inactivity.  Let me know if you need any more inputs or questions.

**Comment by hknokh** [comment]
Sure. I forgot to put the issue in progress to prevent autoclose...)

**Comment by hknokh2** [comment]
Hello,
I haven't had the opportunity to check CPQ objects on my end.
However, it seems that the plugin is unable to match records in the Source and Target size, resulting in the creation of extra records.
You should ensure the uniqueness of all upserted objects by specifying an external ID with unique values across the entire org and equal in both source and target sides. Perhaps consider using compound external ID fields, as demonstrated in this full example of migrating a matrix model (replace the API field names with the actual API names you're using, and change the operation to Readonly where needed):

```json
{
   "objectSets":[
      {
         "objects":[
            {
               "query":"SELECT Id, Name FROM CalculationMatrix",
               "externalId":"Name",
               "operation":"Upsert"
            },
			 {
               "query":"SELECT Id, Name, CalculationMatrixId, VersionNumber FROM CalculationMatrixVersion",
               "externalId":"Name;VersionNumber",
               "operation":"Upsert"
            },
            {
               "query":"SELECT Name, InputData, OutputData, Dimension1Value, Dimension2Value, CalculationMatrixVersionId FROM CalculationMatrixRow",
			   "externalId":"Name;Dimension1Value;Dimension2Value",
               "operation":"Upsert"
            }
         ]
      }
   ]
}
```

**Comment by hknokh** [comment]
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.
