### ISSUE TITLE
[FEATURE REQUEST]-You should consider writing that objects must be case sensitive for child objects to be imported

### ISSUE THREAD

**Issue by martingaleh** [forcedotcom/SFDX-Data-Move-Utility#574]
**Is your feature request related to a problem? Please describe.**
It took me 20 minutes to figure out why child objects weren't being imported

**Describe the solution you'd like**
Maybe a sentence before the picture that says, "Be sure child objects are case sensitive like they are in the picture below if you want them to be imported."

**Comment by hknokh** [comment]
Hello
Don't completely understand. 
Which picture you are talking about ?
Where you propose to add the message ?
Is this the picture of complex object data migration in the quick start page ?
Thx.

**Comment by martingaleh** [comment]
![](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/images/diagram.jpg)
This picture with the export.json below it. It’s almost self explanatory, but since soql is not case sensitive and your item is, a little word of warning might be nice.

**Comment by hknokh** [comment]
Added the note you mentioned me.
