### ISSUE TITLE
[BUG] - Linking records in a 2-way lookup (one-to-one)

### ISSUE THREAD

**Issue by vmjelde** [forcedotcom/SFDX-Data-Move-Utility#576]
We have 2 objects with a lookup field to eachother:
- Object: CartItem, field: Application__c
- Object: Application__c, field: CartItem__c

How can we insert CartItems and Application with both these fields populated? 
Can we run insert CartItem, Insert Application, update Cart Item? Or does sfdmu check two-way-lookups (dependencies) and handles it?

**Comment by hknokh** [comment]
Hello, 
You can simply put to Insert the both objects.
Typically the sfdmu handles 2 way dependencies ootb

**Comment by vmjelde** [comment]
Hello,
Thank you for quick response.

It's great that sfdmu handles 2 way dependencies ootb, but do you have some guidance for it? I tried with two custom objects, but got "Missing expected parent ExternalID value".
See attached .zip for the dataset and logs.

[test-data.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10930908/test-data.zip)

**Comment by hknokh2** [comment]
@vmjelde 
There was a bug of handling circular references, which is fixed.
Please update the Plugin.
Also see the new article regarding your example:
https://help.sfdmu.com/examples/configuration/basic-examples
