### ISSUE TITLE
[BUG] Data import with setting Record Owner fails if Queue and Public Group exisit with the same Name

### ISSUE THREAD

**Issue by micha79x** [forcedotcom/SFDX-Data-Move-Utility#577]
**Describe the bug**

When migrating records including OwnerId field, we run into an issue if a record is owned by a Queue, and in parallel, a Public Group of the same name exists in the Org as well.

In the sample repo, the issue is stripped down to migrating a Case with only the Subject, Origin and Owner fields.

**To Reproduce**

- Clone the following Repository demonstrating the issue and run the following commands

```
sfdx force:org:create -f config/project-scratch-def.json -a SAMPLE-DATA
sfdx force:source:push -u SAMPLE-DATA
cd sample-data/
sfdx sfdmu:run --sourceusername csvfile --targetusername SAMPLE-DATA
```

**Expected behavior**

The record should be migrated including the Owner.

I think, the issue could be resolved by only querying the Group records of `Type = "Queue"` for merging the `Group` records into the UserAndGroup.csv file. All the other Types don't help in handling Ownership of records anyway.

**export.json**

See here: https://github.com/micha79x/sfdmu-owner-issue/blob/main/sample-data/export.json

**Log file**

[2023-03-15__10_51_46.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10978404/2023-03-15__10_51_46.log)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

[MissingParentRecordsReport.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10978410/MissingParentRecordsReport.csv)
[Case_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10978407/Case_insert_target.csv)

**Comment by hknokh** [comment]
Hello
Thanks for pointing me on the possible problem
I will look into in ASAP

**Comment by hknokh** [comment]
Added WHERE Type = "Queue" when  querying the Group object
Hope it will help.
