### ISSUE TITLE
[QUESTION] - RecordType is not set while importing from CSV

### ISSUE THREAD

**Issue by yuyutsa** [forcedotcom/SFDX-Data-Move-Utility#585]
@hknokh Hey, I am not able to achieve this. Can you check if something is wrong below?
I am trying insert an account record with the correct recordType. Tried several times the account is getting inserted with the master recordtype ID

Export.json:
{
"objects": [
{
"query": "SELECT Id, Name,RecordType.DeveloperName FROM Account limit 1",
"operation": "Insert",
"externalId": "RecordType.DeveloperName"
}
]
}

Account.csv:

Name,RecordType.DeveloperName
SFDMU test,AccRecType

**Comment by hknokh** [comment]
Hello, @yuyutsa 

Thank you for contacting me.

After reviewing the details you have provided, it appears that this is not a bug related to the Plugin. Unfortunately, I am only able to provide support for Plugin-related issues at this time.

For other issues, I would recommend referring to our documentation at [SFDMU Help Center](https://help.sfdmu.com/). 
Additionally, you can review our [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy) to see what types of issues we are able to assist with.

Thank you for your understanding.

Best regards,
I'm here to help.
