### ISSUE TITLE
[QUESTION] - How to load records in custom object with relationship to itself?

### ISSUE THREAD

**Issue by shamina-comf** [forcedotcom/SFDX-Data-Move-Utility#587]
We have a custom object with 3 record types: A,B,C
We need to import records with record type B such that it has a self reference to another record on the same object but with record type A.

How to setup the export json to upsert records for record type B with reference to parent record with record type A ?

**Comment by hknokh** [comment]
Hello,

Thank you for contacting me and apoligize for the delay in the response.

After reviewing the details you have provided, it appears that this is not a bug related to the Plugin. Unfortunately, I am only able to provide support for Plugin-related issues at this time.

For other issues, I would recommend referring to our documentation at [SFDMU Help Center](https://help.sfdmu.com/). 
Additionally, you can review our [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy) to see what types of issues we are able to assist with.

Thank you for your understanding.

Best regards
