### ISSUE TITLE
[FEATURE-REQUEST] - Can you see the full SELECT statement in the logs when using Select ALL?

### ISSUE THREAD

**Issue by jimbasilio** [forcedotcom/SFDX-Data-Move-Utility#591]
- Ask your question or what kind of help you need.

When using select all, in the logs each field is inserted for the actual SF query. However, in the logs it truncates with an ellipses after so many characters. I'd like to see all the columns outputted so I can quickly use these columns in a subsequent query.

Or maybe someone knows a quick SF hack to structure a select statement with all fields?

Thank you!

**Comment by hknokh** [comment]
Yes. Great idea. I believe adding a separate flag for logging full query strings would be beneficial. My preference is to leave the stdout logs concise as they are now. With the addition of the flag, the file log could be extended to display all fields.

**Comment by hknokh** [comment]
Hello
Sorry for the delay
This feature has been implemented.
Added logfullquery flag to log all selected fields.
Please refer:[Running the SFDMU](https://help.sfdmu.com/running)
Regards
