### ISSUE TITLE
[QUESTION] - Problem Setting a Target Field that does NOT exist in Source

### ISSUE THREAD

**Issue by LeeB-Development** [forcedotcom/SFDX-Data-Move-Utility#594]
**Ask your question or what kind of help you need.**
I am trying to set a Target field to a specific value using the Value Mapping feature. The field I need to set does NOT exist in the Source scheme (and should not exist there). Does the data move utility support this? I cannot seem to get it to work without a field existing in Source and Target.

Source Field
- Account Name, Account Id

Field Mapping
- Account Name -> Target Account.Name
- Account Id -> Test Account.External id

Value Mapping
- NA -> Test Account.Data Migration Flag = TRUE

Everything is working in my test except setting the Target field Test_Account__c.Data_Migration_Flag__c to TRUE. My thought is that the tool may not support setting a value on a field that does not exist in the source. We have several use cases like this so I was running this test to see if it would work. Please let me know if it is supported and if I am doing something wrong.

---
export.json
`{ "allOrNone":true, "promptOnMissingParentObjects":false, "promptOnIssuesInCSVFiles":false, "keepObjectOrderWhileExecute":false, "objects": [ { "query": "SELECT Id, Name FROM Account", "operation": "Upsert", "externalId": "Name", "useFieldMapping":true, "useCSVValuesMapping":true } ] }`

FieldMapping.csv
`ObjectName,FieldName,Target Account,,TestAccount__c Account,Name,Name Account,Id,External_Id__c`

ValueMapping.csv
`ObjectName,FieldName,RawValue,Value TestAccount__c,Migration_Flag__c,#N/A,1`

**Comment by hknokh** [comment]
Hello,

Thank you for your message. I will review your issue as soon as possible, but please note that it may take some time to address it thoroughly.
You can learn more about our support policy on our website: [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).

Thank you for your understanding and patience.

Best regards.

**Comment by hknokh2** [comment]
Hello,

I apologize for the significant delay. I have finally reviewed your case.

Firstly, I would like to mention that your case falls under a pure configuration question, which is not officially supported by me. However, I will still assist you by providing my observations.

Here are the key points based on what I see:

Field and value mapping in SFDMU:
You are correct. The SFDMU always works with fields that exist in both the source and target organizations, regardless of whether field mapping is utilized or not. The same applies to value mapping, which only operates on fields that exist in both organizations.

Value mapping usage:
When using value mapping, it is important to ensure that the source object is correctly set in the 'ObjectName' column. This object is mapped using the field mapping. In your specific case, please replace 'TestAccount__c' with 'Account' in your ValueMapping.csv file.

Handling values in value mapping:
When utilizing value mapping, it is crucial to ensure that all values of the respective field in all source records are NULL when #N/A is set in the ValueMapping.csv file. If not, you can use a regular expression such as /.*/ to set the target value to true regardless of the source value.

I hope this clarifies the points you raised. Please feel free to reach out if you have any further questions or require additional assistance.

Regards.
