### ISSUE TITLE
[BUG]-Not being able to use the OR operator in the WHERE clause of an object with the flag "master": false

### ISSUE THREAD

**Issue by Josecjr** [forcedotcom/SFDX-Data-Move-Utility#598]
**Describe the bug**
If I try to use the OR operator in a query with the Master flag  = false I'm getting this error (or similar ones): 

 FETCHING THE DATA (STAGE 2) ...
 [15:21:04.802] PASS 1
...............

[15:21:32.637] [ERROR] Error during execution of the command: 
(RecordType.name = 'CRM') OR (account__r.AccountNumber !=
                               ^
ERROR at Row:1:Column:3300
unexpected token: OR.
 [15:21:32.641] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).
 [15:21:32.644] Total time elapsed: 00h 43m 04s 905ms .

I need to filter the records due to the number of records this table has.  The query does not run without a filter.

**To Reproduce**
Add a master object (Like account)
Add a not master object (like contact)
add a where clause with an OR operator to the not master object (in this example, contact)
Run the plugin

**Expected behavior**
The query should work 

**export.json**

            "query": "SELECT Id, Name, updateable_true, createable_true FROM Obj WHERE RecordType.name = 'CRM' OR (ObjectA.Account__r.AccountNumber !='' and ObjectA.Account__r.org__c ='xxxx') " 
       

**_target.csv** file.
N/A

**Comment by hknokh** [comment]
Hello,

I wanted to let you know that I am currently still reviewing your case and will inform you as soon as I have any updates. Thank you for your patience and understanding.

Best regards.

**Comment by hknokh2** [comment]
Hello
Sorry for the long delay.
This issue has been fixed.
Please update the plugin and retry.
Regards.
