### ISSUE TITLE
No support for Person Account

### ISSUE THREAD

**Issue by benahm** [forcedotcom/SFDX-Data-Move-Utility#6]
Hello, 

When trying to move a person account, the plugin is trying to handle it as a normal account 
I'm getting the following error : _Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set._

Could you add support for Person Account

Thank you

**Comment by hknokh** [comment]
Hello! 
Thank you for the great suggestion.
I added support for person accounts to the Road Map as one of the nearest tasks.

**Comment by hknokh** [comment]
Hi @benahm 
I have added support for person accounts.

**Comment by benahm** [comment]
Thanks @hknokh, I will test that 👌
