### ISSUE TITLE
Support for polymorphic lookup fields

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#60]
When trying to insert FeedItems, the tool always queries Accounts to match the `FeedItem.ParentId` field.

It would be great if the parent object can be set by the user in the configuration file. This might also apply for other objects and fields such as the `WhatId` and `WhoId` fields on Activities.

**Comment by hknokh** [comment]
@kevdo475 thank you for the good idea
I will add the feature to the project Roadmap and will implement ASAP.

**Comment by hknokh** [comment]
I'm closing this issue for now and will update you about the progress.

**Comment by hknokh** [comment]
Hello @kevdo475 
The feature has been implemented.
View the article:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.5.-Advanced-features.-Polymorphic-Lookup-Fields.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.5.-Advanced-features.-Polymorphic-Lookup-Fields.)
