### ISSUE TITLE
[QUESTION]- FIELDS(CUSTOM) syntax is not supported?

### ISSUE THREAD

**Issue by mvcmania** [forcedotcom/SFDX-Data-Move-Utility#602]
**Describe the bug**
One of my export query has the new soql syntax which helps you to select all custom fields but it is failing during execution and throwing malformed syntax exception

**To Reproduce**
Use new soql functions like FIELDS(CUSTOM) or FIELDS(STANDARD)
**Expected behavior**
It should be supported in plugin as well as it is an legit function
**export.json**
`
{
    "objects": [
        {
            "query": "SELECT Name, Phone FROM Account WHERE RecordType.Name='Member'",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT FIELDS(CUSTOM) FROM Member__c limit 200",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT FIELDS(CUSTOM),Name,CurrencyIsoCode FROM Member_Unit__c limit 200",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}
`

**Log file**
`
Command initialization error: Malformed query string was defined for the object : SELECT FIELDS(CUSTOM) FROM Member__c limit 200. Error message: Error: line 1:13 mismatched input '(' expecting FROM
    at SyntaxErrorListener.syntaxError (/Users/erkan.cipil/.local/share/sfdx/node_modules/soql-parser-js/lib/ErrorListener.ts:14:11)
`

**Comment by hknokh2** [comment]
Hello!
Thank you for contacting me. Unfortunately, the syntax you mentioned is not supported by the SFDMU.
However, the SFDMU does have a built-in alternative for selecting a variety of field types. Please refer to the following link for more information:
[SFDMU Field Multiselect Documentation](https://help.sfdmu.com/full-documentation/advanced-features/field-multiselect)
If you have any further questions, feel free to ask.
Regards.
