### ISSUE TITLE
[QUESTION]- onBeforeAddons event fires after records are queried. 

### ISSUE THREAD

**Issue by zerkz** [forcedotcom/SFDX-Data-Move-Utility#608]
**Describe the bug**
[the documentation here](https://help.sfdmu.com/full-documentation/add-on-api/supported-events) states that `onBeforeAddons` are: 

* Triggered once per job 
* Triggered before the migration job is started 
* There are no records yet to access and modify.
* The script configuration can be modified

However, defining an `onBeforeAddon` seems to fire after queries/records are accessed. 

SFDMU version - v4.29.2

**To Reproduce**
See example export.json, have any `onBeforeAddon` defined. 

**Expected behavior**
I would expect onBefore to run before any API calls are done against a Salesforce org/instance, or atleast before queries.

**export.json**
```
{
    "beforeAddons": [
        {
            "description" : "test the module",
            "path": "../plugins/your_own_test_addon/",
            "args" : {
            }
        }
    ],
    "allOrNone": false,
    "alwaysUseRestApiToUpdateRecords" : true,
    "promptOnMissingParentObjects" : false,
    "objects": [
        {
            "query" : "select Id from User limit 1",
            "operation" : "Readonly"
        }
    ]
} 
```

**Log file**
```
[15:15:22.498] Preparing of the data migration job has been completed.
 
=== ANALYSING DATA...
[15:15:22.669] {User} The original query string of this object is returning 1 records from the Source org.
[15:15:22.892] {User} The original query string of this object is returning 1 records from the Target org.
 
=== Triggering Add-On events ...
[15:15:22.893] {Global} Add-On event:onBefore has been triggered.
```

**Comment by hknokh2** [comment]
Hello,

Regarding the log message you provided:

=== ANALYSING DATA...
[15:15:22.669] {User} The original query string of this object is returning 1 records from the Source org.
[15:15:22.892] {User} The original query string of this object is returning 1 records from the Target org.

This phase is part of the data analysis process. 

The documentation about the Add On states that the OnBefore event is triggered before the actual data retrieval process, not before the Salesforce org is accessed.

This behavior is expected. During the analysis phase, the SFDMU performs a set of technical queries, such as "SELECT COUNT() FROM User LIMIT 1," which is executed internally by SFDMU during the job preparation phase. This is used to analyze the overall data volume and is not the actual data retrieval from the org.

The message that indicates the start of the actual data retrieval process would typically look like this:

=== Fetching the data (STAGE 1) ...

If you have any further questions or need additional clarification, please let me know.

Regards

**Comment by hknokh2** [comment]
You're welcome! 
Yes, this part of the documentation can be confusing.
