### ISSUE TITLE
[BUG]-Org-to-Org Value Mapping for Checkbox Fields 

### ISSUE THREAD

**Issue by mattgrimwade** [forcedotcom/SFDX-Data-Move-Utility#611]
First, thank you for this fantastic tool! Apologies if I'm just missing something obvious on the below..

**Description**
Value mapping does not seem to work properly for org to org migrations when mapping checkbox fields, specifically from false to true. True to false does map correctly. The _target.csv has checkbox value replaced with an empty value.

It also seems to work correctly when first pulling into a csvfile and then using `useCSVValuesMapping` for the push to the org - this does map false to true. 

**To Reproduce**
Setup `ValueMapping.csv` to map a checkbox from false to true.
Run an org to org migration using the value mapping. 
Note: I am using the same org as the source and target in this example

**Expected Behaviour**
Checkbox field is updated from false -> true as per the value mapping. In the example CSVs I have included a text field which is being mapped and updated correctly.

**export.json**
```javascript
{
    "objects": [ 
        {
            "query": "SELECT Name, Is_Obfuscated__c, Gender__c FROM Account ORDER By CreatedDate DESC ",
            "operation": "Update",
            "externalId": "Id",
            "useValuesMapping": true
        }
    ]
}

``` 
**ValueMapping.csv**
```
ObjectName,FieldName,RawValue,Value
Account,Is_Obfuscated__c,false,true
Account,Gender__c,Male,Female
``` 

**_target.csv**
```
Is_Obfuscated__c,Gender__c,Id,Errors
,Female,0017Z00002JudqgQAB,
,Female,0017Z00002JufNHQAZ,
``` 

**Log**
[2023-07-10__11_56_50.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12001125/2023-07-10__11_56_50.log)

**Comment by hknokh** [comment]
Hello,

Thank you for your message. I will review your issue as soon as possible, but please note that it may take some time to address it thoroughly.
You can learn more about our support policy on our website: [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).

Thank you for your understanding and patience.

Best regards.

**Comment by mattgrimwade** [comment]
PR open for this issue
