### ISSUE TITLE
[FEATURE REQUEST]- Support FieldMapping when using sourceusername csvfile

### ISSUE THREAD

**Issue by IamDrowsy** [forcedotcom/SFDX-Data-Move-Utility#627]
We would like to upload data from csv files to Salesforce that come from different sources. But the columns of those files do not match fields in Salesforce. 
We could rename the columns to match the fields, but it would be nice when FieldMapping could be used to solve this with sfdmu only.
(The documentation does not state if FieldMapping is supported with csv import, but we tried it and it does not seem to work).

**Example**
Given the following 'Account.csv' and 'export.json', it would be nice if sfdmu would upsert an Account with `Name='MyAccount'` and `External_Id__c='X1234'`.

| Account_Name | Account_Id |
|--------------|------------|
| MyAccount    | X1234      |

```
{
    "objects": [
        {
            "query": "SELECT Account_Name,Account_Id FROM Account",
            "operation": "Upsert",
            "externalId": "Account_Id",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Account"
                },
                {
                    "sourceField": "Account_Name",
                    "targetField": "Name"
                },
                {
                    "sourceField": "Account_Id",
                    "targetField": "External_Id__c"
                }
            ]
        }
    ]
}
```

**Comment by hknokh** [comment]
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.

**Comment by IamDrowsy** [comment]
Hello,

thank you very much for your response and putting this on the roadmap.
I totally agree that the workaround is very easy and this should not have a high priority.

As a side note, I just wanted to mention that you currently can use the FieldMapping to import from csv files that are **named** differently (and even with multiple files).
So two files, `MainAccounts.csv`, `OtherAccounts.csv` with the correct columns can be imported with the following export.json:
```
{
    "objects": [
        {
            "query": "SELECT Name,External_Id__c FROM MainAccounts",
            "operation": "Upsert",
            "externalId": "External_Id__c",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Account"
                }
            ]
        },
        {
            "query": "SELECT Name,External_Id__c FROM OtherAccounts",
            "operation": "Upsert",
            "externalId": "External_Id__c",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Account"
                }
            ]
        }
    ]
}
```

Not sure if this is intentional and should/could be mentioned in the docs, but I found it interesting.

Thanks again for your efforts and sfdmu as a whole. 
Regards.

**Comment by hknokh** [comment]
Hello,

Thank you again for the feature suggestion.
This capability is already supported in SFDMU and has been available for a long time.

Please, see also the doc articles:

- [Fields Mapping](https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping)
- [ScriptObject.useFieldMapping](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object-object#usefieldmapping-boolean)
- [ScriptObject.fieldMapping](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object-object#fieldmapping-array-of-mappingitem)
- [ScriptObject.externalId](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object-object#externalid-string)
- [CSV Import and Export examples](https://help.sfdmu.com/examples/csv-import-export)

Additional details on your case:

1. `useFieldMapping` with `--sourceusername csvfile` is supported.
2. Mapping with different CSV file names is supported via `fieldMapping.targetObject`.
3. Recommendation for your sample:
- keep `query` fields as source CSV columns
- keep `useFieldMapping=true`
- map `Account_Name -> Name`
- map `Account_Id -> External_Id__c`
4. For Upsert, please also review the externalId matching note in the Fields Mapping article.
   The safest setup is to keep external key handling aligned with that documented behavior.

Best regards
