### ISSUE TITLE
[QUESTION] - Error during execution of the command: read ECONNRESET.

### ISSUE THREAD

**Issue by kvsr31** [forcedotcom/SFDX-Data-Move-Utility#629]
Hi team,

Thank you for building and constantly supporting the plugin to make salesforce customers life easy.

I'm getting the **ECONNRESET** error. Can you help me why i'm getting the **ECONNRESE T** error with following export.json?
<img width="890" alt="image" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/142727570/c68ed017-0430-4ef7-a6ec-c5142a6cbb3a">

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12388205/export.txt)
[2023-08-20__18_11_55.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12388206/2023-08-20__18_11_55.log)

Also, Can you answer the below questions?

1. Is there any size limitation on export.json file?
2. Does the sfdmu plugin sending the external Ids that we have configured in export.json along with request payload to salesforce call?
3. Does sfdmu plugin use the same soql query that we have configured in export.json or it can modify the soql query and it along with salesforce call to retrieve the data?
4. Which sfdx commands does the sfdmu plugin use to retrieve the data?

Thanks:)

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out and for your kind words.

Regarding the ECONRESET, it's related to a local internet connection issue.

To address your questions:

1. No.
2. The SFDMU only sends fields that are specified in the object's SOQL query, not any others.
3. Yes, it does add reference fields, for example: Account.Name into a query for Contact if it contains an AccountId lookup field and the external id for the Account is set to Name. Additionally, it modifies WHERE clauses to compose queries which can pull related child records.
4. SFDMU doesn't utilize SFDX to retrieve data; instead, it relies on the jsforce library. For obtaining the accessToken, it uses the sf org display command. You can toggle between the traditional sfdx force:org:display and the contemporary sf org display commands. For more details, refer here: https://help.sfdmu.com/running#available-command-flags.

Of note, I've reviewed your export.json. 
You have constructed an exceptionally long external id field, which is not necessary. 
I would recommend you examine this issue, which mirrors yours, and consider my advice there to simplify your externalIds as much as feasible: https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/609. An ECONRESET issue might also arise from utilizing excessively lengthy external ids.

Best regards.

**Comment by kvsr31** [comment]
Thank you for response @hknokh2. 

Does ECONNRESET error is throwing by jsforce library or sfdmu plugin?

I tried running the same export json multiple times but doesn’t worked. If it is related to internet issue, it has to work at least once right.

**Comment by hknokh2** [comment]
Firstly, please review your export.json. It has an incorrect externalId definition that includes a vast number of fields. I recommend reducing them significantly to just 1-2 fields. As I mentioned earlier, having too many fields can lead to an ECONNRESET issue, especially if the constructed query string can contain up to 1K fields.

Additionally, as a troubleshooting step, try using a basic export.json to see if it works for you from start to finish. Here's a reference to a basic example:
https://help.sfdmu.com/examples/configuration/basic-examples

From your logs, it's evident that the excessive number of fields is problematic.

**Comment by hknokh** [comment]
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.
