### ISSUE TITLE
Missing expected parent ExternalID value is Name?

### ISSUE THREAD

**Issue by mike-cleaver** [forcedotcom/SFDX-Data-Move-Utility#630]
Hey team, I am doing inserts, but it is failing for missing an parent record by name. 
The documentation says, for inserts, that Id will always be used. 
The data has Non-unique names so it is probably finding more than one record by name (The error message is wrong, please also fix that)
I am not setting externalId and when I did (I set it to Id) it did not change anything.

```
...Child SObject,Parent SObject,Parent ExternalId Field,Missing expected parent ExternalID value
...InsurancePolicy,SLA__c,Name,Test SLA
```

Can someone explain why the name is being used as parent externalID value, and how to stop it?
The child query includes the lookup field only (SLA__c) and the parent query includes the Id.

I am running Plugin version: sfdmu v4.29.7

**Comment by mike-cleaver** [comment]
updated to 4.30, no change.

**Comment by hknokh** [comment]
Hello,

Thank you for getting in touch.

Firstly, I'd like to highlight that your request does not align with our opening case guidelines as you have omitted the necessary export.json and log files.

However, based on the limited information available, my assumption is that your configuration might involve a lookup field pointing to a parent sObject that isn't listed in the export.json file. Consequently, SFDMU treats it as read-only and attempts to automatically assign an external ID field.

To gain a better understanding of our support policy, please refer to https://help.sfdmu.com/full-documentation/additional-information/support_policy. This resource outlines the specific issues I can assist with. In brief, I'm equipped to aid with matters that appear to be either bugs or gaps in documentation, provided the details are intricately linked to the questions you've posed.

Your understanding is greatly appreciated.

Best regards,

**Comment by mike-cleaver** [comment]
I didn't see the link in the readme, Can you update the template of cases to add the link?

You're right though, I should have looked at that document.

 [09:32:47.664] The parent object SLA__c for the child lookup field InsurancePolicy.SLA__c has been included into the process. The externalId is set to 'Name'.


the query had SLA__C rather than SLA__c which is why sfdmu didn't find the data. I had read that the exportjson queries were case sensitive but didn't think to check it. So dumb, thanks for your patience!

**Comment by mike-cleaver** [comment]
RTFM

**Comment by hknokh2** [comment]
Hello
Happy hear that it's resolved.
Good idea regarding to update the templates of cases 👍 I will check.
