### ISSUE TITLE
[QUESTION]-SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by shamina-comf** [forcedotcom/SFDX-Data-Move-Utility#633]
**Describe the bug**
getting this error when running command
  `SyntaxError: Unexpected token '?'`

**To Reproduce**
error happening when running this command
`sfdx sfdmu:run --sourceusername SOURCE_ORG --targetusername TARGET_ORG --path "./sfdmu/1_org_ref/1_Parent"`

Versions:
sfdx-cli/7.70.1-3d8a6229fc win32-x64 node-v12.18.3

sfdmu 4.30.0

**Expected behavior**
runs without error

**export.json**
```
{
    "simulationMode":false,
    "orgs":[
        {
            "name":"SOURCE_ORG",
            "instanceUrl":"https://domain.my.salesforce.com",
            "accessToken" : "XXX"
        },
        {
            "name":"TARGET_ORG",
            "instanceUrl":"https://domain.sandbox.my.salesforce.com",
            "accessToken" : "XXX"
        }
    ],
    "objects": [
        {
            "query": "select Name, AliasBO__c from Backoffice__c ",
            "operation": "Upsert",
            "externalId": "AliasBO__c"
        }   
    ]
}
```
**Log file**
no log generated

**_target.csv** file.
none

**Comment by hknokh** [comment]
Hello,

Thank you for getting in touch. Based on the information provided, it seems that this issue may not be directly related to the Plugin.

The issue appears to be related to your specific environment
I recommend trying the following steps:

- Reinstall or thoroughly check the SFDX-CLI and nodejs installations.
- Verify the target folder permissions to ensure it can be accessed from nodejs.

For issues of this nature, I encourage you to refer to the SFDMU Help Center documentation at https://help.sfdmu.com/. Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to better understand the types of issues that fall within the scope of my assistance.

Thank you for your understanding and cooperation.

Best regards.

**Comment by shamina-comf** [comment]
I got my answer; after upgrade to sf v2, we can run commands with either sfdx or sf,
this is mention in section "After You Move to sf (v2)" here :
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

PS: original syntax error is resolved after uninstalling and reinstalling sf cli
