### ISSUE TITLE
[QUESTION] - Is it possible to see the transformed and mapped field values that are inserted/updated?

### ISSUE THREAD

**Issue by AlwaysThinkin** [forcedotcom/SFDX-Data-Move-Utility#635]
In the object_insert_target and object_update_target CSVs I don't see the field values that I've transformed or mapped with valueMapping.csv and fieldMapping.csv. I see the columns for the fields but they contain either the source value or nothing at all. I can tell that the transforms and mappings worked by looking at results in the target but when a particular value is not working, is there a way to see what was attempted?

**Comment by hknokh** [comment]
Hello,

Thank you for your message. 

There is no way to see what is happening internaly when value mapping function is working.
Only the indication are target values.
As per a brief check on my side the target csv files show the values as they are updated in the target with or without transformation.

Best regards.

**Comment by AlwaysThinkin** [comment]
Oh, so the target csv files do show the transformed values? I was specifically looking at the RecordTypeId, which I'm hardcoding in the valueMapping.csv but all the rows for that column are null in my target csvs. However it does seem to be setting them correctly in the target org (and it's not using my default RecordType for my Profile as far as I can tell). Thanks for the prompt response and explanation of expected behavior.

**Comment by hknokh** [comment]
I've temporarily closed this case for now and will revisit it in the future. 
Once there's an update or outcome, I will reopen it and notify you.
Regards
