### ISSUE TITLE
[FEATURE REQUEST]-Store records as individual json files

### ISSUE THREAD

**Issue by loganm** [forcedotcom/SFDX-Data-Move-Utility#636]
I want to use SFDMU to enable developers to retrieve and commit RBC changes as flat files in the repository. This will allow the changes to be peer reviewed, and changes to RBC can be audited (particularly important in the financial industry).

It also means, we won't need them to write post deployment steps for the operations team to move certain RBC records in a deployment.

SFDMU gets pretty darn close. The frustration I have is that CSV files are not great for source control. Not all of the config analysts and developers on my project are comfortable with git, and expecting them to work on a single CSV file per object sounds like a recipe for merge conflicts and bad data.

I've been thinking it would be great to have a folder for each object, and to write individual files per record into those folder, named by the external id field.

A developer could retrieve all RBC with sfdmu, stage the files they've added/changed, and make a commit.

On the back of that change, the CI script can simulate the deployment to check for obvious issues, and the CD script can perform it.

This could be as simple as using --targetsource json instead of --targetsource csv

What do you reckon? Is this doable?

**Comment by hknokh** [comment]
Hello.

Thank you for your contribution and the idea!

Currently, I don't plan to add any new features, but I have placed your suggestion on my roadmap. While I can't guarantee when or if it will be implemented, please stay tuned for future updates.

Thank you for your support.

Regards.

**Comment by hknokh** [comment]
I'm closing this ticket for now. Please let me know if you have any further questions.
Thanks.
