### ISSUE TITLE
Can we process the each object in object list from export.json parallelly for ORG to CSV and CSV to ORG migrations?

### ISSUE THREAD

**Issue by kvsr31** [forcedotcom/SFDX-Data-Move-Utility#637]
Hi team,

Can you please answer the following question?

1. Can we process the each object in object list from export.json parallelly for ORG to CSV and CSV to ORG migrations?
[exportJson.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12605887/exportJson.txt)

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
Not clear what is your meaning of parallel.
In parallel meaning sequentially within the same job  no.
Need to run the sfdmu once per direction with the same configuration file.
Cheers.
