### ISSUE TITLE
[QUESTION]-Getting Access Token Expired Error

### ISSUE THREAD

**Issue by ChirayuMaheshwari** [forcedotcom/SFDX-Data-Move-Utility#639]
**Describe the bug**
We are trying to deploy the data in our orgs using sfdmu:run command but this fails with below error
```

 {
   "command": "sfdmu:run",
   "cliCommandString": "sfdx sfdmu:run -s csvfile -p data/tpm/records -u <username> -c <instanceUrl> --json",
   "endTime": "2023-09-20T09:20:42.919Z",
   "endTimeUTC": "2023-09-20T03:50:42.919Z",
   "message": "Command initialization error: Access token to the <username> has been expired or the user has no access permissions..",
   "fullLog": [
      "[09:20:35.329] Execution of the command sfdmu:run has been started.",
      " ",
      "LOADING AND VALIDATING THE EXPORT.JSON SCRIPT ...",
      " ",
      "OBJECT SET #1 STARTED",
      " ",
      "{\n   \"Running Plugin version\": \"4.30.0\"\n}",
      "{\n   \"Running Add-On API version\": \"1.5.0\"\n}",
      " ",
      "[09:20:35.348] Loading Core Add-On Module declarations ...",
      "[09:20:36.218] Connecting to the <username> using SFDX force:org:display ...",
      " "
   ],
   "stack": [],
   "startTime": "2023-09-20T09:20:35.328Z",
   "startTimeUTC": "2023-09-20T03:50:35.328Z",
   "status": 2,
   "statusString": "COMMAND_INITIALIZATION_ERROR",
   "timeElapsedString": "00h 00m 07s 591ms "
}
```

**To Reproduce**
Install sfdmu plugin and try to deploy the data in the org using sfdmu utility

**Expected behavior**
The data should have been deployed to the org successfully.

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello.

Thank you for reaching out to me. Based on the information you've provided, it appears that this is not a bug related to the Plugin.

For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/. Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.

One point I can mention you for your own further investigation, that may be you are using an org section in your export.json and provide expired access token or incorrect user name which are not matching the provided in command line. 

Thank you for your understanding and cooperation.

Regards.
