### ISSUE TITLE
[QUESTION] - I don't understand the format of the exported files

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/SFDX-Data-Move-Utility#640]
I want to export some CPQ records into a csv file. Here's my `export.json`

```json
{
    "objects": [
        {
            "query": "SELECT Id,Name FROM Product2 WHERE Id = '01t3H000003FayU'",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query":"SELECT Id, Name FROM SBQQ__PriceRule__c",
            "operation":"Upsert",
            "externalId":"Name;SBQQ__Product__c"
        }
    ]
}
```

And I'm running the following command `sfdx sfdmu:run --sourceusername CPQ2 --targetusername csvfile`

The resulting files are as seen below

<img width="360" alt="Screenshot 2023-09-20 at 15 49 56" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/8467087/63e29d86-d275-4c03-815b-138cbf85085e">

2 files are created on the root directory, and the same 2 files (but with different names) are created under a `target` folder.

Why?

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out. The CSV files located in the root directory serve as the output files, generated based on the 'targetusername csvfiles' setting you've chosen. Meanwhile, the CSV files in the 'target' subdirectory are intended for debugging and checking purposes.

For more information on the 'target' CSV files, you can refer to the following documentation: [SFDMU Target CSV Files Documentation](https://help.sfdmu.com/full-documentation/reports/the-target-csv-files).

In some cases, both sets of files may be identical if you're using CSV as the target.

Best regards,

**Comment by pgonzaleznetwork** [comment]
Thank you @hknokh . One last thing, I don't understand how to then import multiple files in bulk. Say I export 3 objects as csv files. How do I then import all 3 csv files into another org? If there's an example of this in the docs, please let me know, I couldn't find it.

**Comment by hknokh2** [comment]
Once you have the 'export.json' file containing 3 objects and you've exported data from the source into CSV files, you can then import this data into the CPQ-TARGET org. To do this, swap the 'sourceusername' and 'targetusername' flags as shown below:
```
sfdx sfdmu:run --sourceusername csvfile --targetusername CPQ-TARGET
```
This command will allow you to import from the previously created CSVs into the CPQ-TARGET organization
Use the same 'export.json file' for the import job.

**Comment by pgonzaleznetwork** [comment]
Thanks!
