### ISSUE TITLE
[QUESTION] - use field / value mapping if blank

### ISSUE THREAD

**Issue by brendanmcdaniel** [forcedotcom/SFDX-Data-Move-Utility#642]
I was wondering if anyone has come across a situation whereby you need to map an external I'd field but only if the source doesn't currently have a value.

Example:

I have a refreshed sandbox and production data set has been deployed via sfdmu.

I have since created a few different records that don't have external Ids populated, I want to promote the new records to a new environment but also in the process would like to produce the external Id for the newly created records.. is this possible?

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out.

In your situation, it’s necessary to generate entirely new external ID values for new records while transferring them to the new environment. This might be attempted using the data anonymization feature. However, this feature unfortunately does not include a built-in filtering option for the scenario you're describing.

You may potentially find a solution with the Transformation Add-On for SFDMU. This add-on permits the transformation of records during the migration process, which can facilitate the assignment of external IDs to records that don’t presently have them, utilizing a custom JavaScript expression.

For further details and guidance, please refer to the following documentation: [SFDMU Transformation Add-On Documentation](https://help.sfdmu.com/full-documentation/add-on-api/records-transform-core-add-on-module)

Additionally, consider exploring the Js Eval Replacement feature, which similarly allows the use of custom JavaScript expressions to populate the target record field: [Js Eval Replacement](https://help.sfdmu.com/full-documentation/advanced-features/values-mapping#js-eval-replacement)

Cheers.

**Comment by brendanmcdaniel** [comment]
This is great, I am experimenting with the transformation add-on as we speak, it looks like it may make the export.json more cumbersome than it is already but could do the trick.

With regard to the [Js Eval Replacement](https://help.sfdmu.com/full-documentation/advanced-features/values-mapping#js-eval-replacement) is it possible to reference parent fields or fields on said object, that could make things a bit cleaner.

**Comment by hknokh2** [comment]
No. 
JS Eval only working with the same field.
