### ISSUE TITLE
Cannot use namespaced lookup fields where __c appears in the middle of the field developer name

### ISSUE THREAD

**Issue by jimletts** [forcedotcom/SFDX-Data-Move-Utility#643]
**Describe the bug**
When a lookup field named like xxx__**c**yyyy__c is used, a runtime error states that the field xxx__**r**yyyy__c cannot be found. Note that the field names are almost, but not quite, identical.

**Root Cause**
The method getFieldName__r in common.ts assumes that the only place a "\_\_c" can appear is at the end of a field name. When a namespace is used with the field name, the string "\_\_c" can appear in the middle of the field name, specifically when lower case  "c" is the first character of a namespaced field name.

**Proposed Fix**
In components>common_components>common.ts, methods getFieldName__r(...) and getFieldNameId(...),

replace each instance of the failing pattern:
``return name.replace("__pc","__pr").replace("__c","__r");``
with a suitable replacement based on:
``return name.replace(/__pc$/,"__pr").replace(/__c$/,"__r");``

**To Reproduce**
1. Create a lookup custom field in a managed package with any package name (e.g. namespace xxx), where the field's developername starts with a lower case "c", e.g. xxx__cyyyy__c
2. Make a reference to that field in export.json
3. run the job

**Expected behavior**
SFDMU correctly accesses the field xxx__**c**yyyy__c.

**Log file**
When including a lookup field named like xxx__cdefgh__c, an error is generated in Stage 1
```
[ERROR] Error during execution of the command: 
 field1__r.Name, xxx__ryyyy__c.Name, field2__r.Name
                              ^
ERROR at Row:1:Column:7373
Didn't understand relationship 'xxx__ryyyy__c' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).
```

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me and for the suggestion.
I will take a look at this and let you know if there are any updates.
Cheers.

**Comment by hknokh** [comment]
Hello,

I apologize for the delay in addressing your ticket. Due to current time constraints, I can't promptly attend to this ticket. I'm closing it for now as postponed, but I value your inquiry and will revisit it when time permits.

Thank you for your patience and understanding.

Best regards.
