### ISSUE TITLE
[QUESTION] - Import using composite key (fields from the same object)

### ISSUE THREAD

**Issue by elizabethiko** [forcedotcom/SFDX-Data-Move-Utility#645]
I have an object which doesn't have a unique identifier to use as externalId - there is a combination of 3 fields which makes the unique value. I'm trying to use composite key as described here, but it still creates duplicates on each load: 
https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys
https://help.sfdmu.com/examples/configuration/csv-import-export#example-2-update-object-having-composite-external-id-key

Could you please provide a working example of using composite key (fields from the same object) when upserting records to not create duplicates.

**Comment by elizabethiko** [comment]
any updates? Please provide information if that is possible with the tool.

**Comment by hknokh** [comment]
Hello,

There's no need for a special example of using a composite key beyond what's provided in the documentation. To create a unique key for the given object list, separate the fields with a semicolon (;).

I believe the issue you're encountering is related to another configuration in the export.json file, which isn't working as expected. Unfortunately, I'm unable to diagnose or offer a direct solution. I suggest addressing the issue on your side.

Thank you.

**Comment by elizabethiko** [comment]
Hello, 
Could you please provide an example with sample metadata (fields used as key), sample input file, export.json and command to run - I have follow the article - and daya is not loaded - it complains about missing columns, or not creating any data - so information provided int he referenced articles is not enough - that is why I'm asking for sample working example.

**Comment by AlwaysThinkin** [comment]
Hi Elizabeth, I had a similar experience with composite keys used on a single object and getting duplicates but it's working for me now. Are you loading data from a source org query or from a CSV?

         {
            "query": "SELECT all FROM Term__c",
            "operation": "Upsert",
            "externalId": "Name;Degree_Offering__c"
          }

I'm not adding any flags to the command, just using:
sf sfdmu:run --sourceusername orgalias1 --targetusername orgalias2

I'm not using a csv file as my source, just querying my source org directly. What does your export.json look like?

**Comment by hknokh2** [comment]
Hello,

The option excludeIdsFromCSVFiles=true is not designed to be used with complex external ID keys. Please provide the complete CSV data.

Here's a minimal working example:

**export.json**

```json
{
    "objects": [
        {
            "query": "SELECT Id, Name FROM Account WHERE Name IN ('ACC_10000', 'ACC_10001')",
            "operation": "Upsert",
            "externalId": "TEST1__c;TEST1__c"
        }
    ]
}
```

**Account.csv**
Id,Name,IsPersonAccount,$$TEST1__c$TEST1__c
0018d00000N237jAAB,ACC_10000,false,ACC_10000 Test2;ACC_10000 Test2
0018d00000N237kAAB,ACC_10001,false,ACC_10001 Test2;ACC_10001 Test2

Regards

**Comment by elizabethiko** [comment]
@hknokh2 , it worked now, the issue was that in this example there is _**Account.**_ in the header - so please revise if the example in the documentation is correct: https://help.sfdmu.com/examples/configuration/csv-import-export#example-2-update-object-having-composite-external-id-key
```
Name,Account.$$Key1__c$Key2__c
Account1,"Key1;Key2"
Account2,"Key3;Key4"
```
Question has been answered, so it can be closed now.

**Comment by hknokh2** [comment]
Ok, I'm happy that you're sutisfied from the outcome.

But it's strange, since as I designed the Tool, it should not work properly until you add the columns of Key1__c and Key2__c to the CSV file.
Othewise it will complain about missing columns and also will update these fields with blank values since they are not exist in the source CSV.

Regarding extra "Account." in the expression of "Account.$$Key1__c$Key2__c", you are right. I will correct the example in the doc.
