### ISSUE TITLE
[QUESTION]-using CSV file for --sourceusername causes "command failed"

### ISSUE THREAD

**Issue by AlwaysThinkin** [forcedotcom/SFDX-Data-Move-Utility#646]
**Describe the bug**
When replacing the org alias in --sourceusername with a csv filename for a file in the same path as the export.json, the command:

`sf sfdmu:run --sourceusername Talkdesk_Activity.csv --targetusername pmx.opm4
`

results in the following error:
`[12:59:45.355] [ERROR] Execution of the command has aborted due to unexpected error: Command failed: sfdx force:org:display --json --targetusername Talkdesk_Activity.csv.
[12:59:45.357] [ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername Talkdesk_Activity.csv`

Also, why does the error show that it's attempting to use the sourceusername parameter for the targetusername force:org:display alias? Restoring the --sourceusername to an authenticated org alias works as expected and displays the source org first and the target org second in the log files. Why would this process use the sourceusername parameter for the targetusername?

**To Reproduce**
Run the command with the csv file located in the same directory as the export.json and with an the alias of an authorized org as the --targetusername. It immediately returns the error above regardless of changes to the order of parameters, the name of the csv, the inclusion of .csv or not, the target org alias.

**Expected behavior**
I expect the process to ignore authenticating and connecting to a source org since that is replaced by a CSV, then to read the CSV and import it to the target org.

**export.json**
It does not appear that the process even gets to the action of parsing the export.json since it errors out on the authentication.
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12860138/export.json)

**Log file**
[2023-10-10__13_24_19.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12860145/2023-10-10__13_24_19.log)

**Comment by hknokh2** [comment]
Hello
When using csv files as a source  you should write like --sourceusername csvfile ("csvfile" as a reserved keyword to proceed with all csv files located in export.json directory).
The command syntax which you have used  is not correct.
See the related documentation.
Regards.

**Comment by hknokh2** [comment]
The process iterates through each object in export.json. It then searches within the export.json directory for a file with a name matching that of the current object. If the file is not found, or if there are discrepancies in the columns or data, a warning is recorded in CSVIssuesReport.csv. CSV files which are located in the directory, but not listed in the export.json are ignored.

FieldMapping.csv is used to define field mappings during runtime, regardless of whether the source is a CSV file.

MissingParentRecordsReport.csv is designed to report any missing dependencies, irrespective of the type of source used.
