### ISSUE TITLE
CSV Import option in not visible in 4.0 version of SFDMU GUI app. 

### ISSUE THREAD

**Issue by chanchalpawan2** [forcedotcom/SFDX-Data-Move-Utility#647]
**Describe the bug**
.CSV Import/export options are not visible in 4.0 version of SFDMU GUI app. 

**To Reproduce**
Open the the SFMDU app 4.0 version. You will notice only connected Salesforce Orgs for migration and not from CSV to Salesforce or Salesforce to CSV
**Expected behavior**
It should have CSV option as source and target , Same as earlier version of SFDMU GUI app.

**Comment by hknokh** [comment]
Closed as a duplicate
