### ISSUE TITLE
.CSV Import/export options are not visible in 4.0 version of SFDMU GUI app.[QUESTION] - Question title

### ISSUE THREAD

**Issue by chanchalpawan2** [forcedotcom/SFDX-Data-Move-Utility#648]
I was wondering if someone has figured it out.
.CSV Import/export options are not visible in 4.0 version of SFDMU GUI app.

To Reproduce
Open the the SFMDU app 4.0 version. You will notice only connected Salesforce Orgs for migration and not from CSV to Salesforce or Salesforce to CSV
Expected behavior
It should have CSV option as source and target , Same as earlier version of SFDMU GUI app.

**Comment by hknokh2** [comment]
Hello.
The csv option is appearing at the last (preview) step. The csv files sources are not relevant for building the configuration.
Regards.
