### ISSUE TITLE
[BUG]-<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>

### ISSUE THREAD

**Issue by adesmarais944** [forcedotcom/SFDX-Data-Move-Utility#649]
**Describe the bug**
When running a query against the Account object while including **createable_true**, along with several other fields; this error is thrown during the Fetching data Stage 1: 
**[ERROR] Error during execution of the command: <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>.
[ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).**

**To Reproduce**
Create an export.json with an Account object query that includes **createable_true**. _Note: Our Account object does currently have 665 custom fields on it._ I am able to successfully use **createable_true** when querying the Case object which only has 230 custom fields.

**Expected behavior**
To be able to leverage **createable_true** when querying this Account object.

**export.json**
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12886216/export.json)

**Log file**
[2023-10-12__14_51_47.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12886214/2023-10-12__14_51_47.log)

**_target.csv** file.
N/A

**Comment by hknokh2** [comment]
Hello.

The issue could likely be due to the large number of fields. 
Apart from reducing the number of queried fields, I'm not sure of another solution.

Regards.
