### ISSUE TITLE
[QUESTION] - Using SFDMU with Hyperforce instances

### ISSUE THREAD

**Issue by Cullly** [forcedotcom/SFDX-Data-Move-Utility#651]
Does SFDMU v4.30.0 support sandboxes on the Hyperforce infrastructure? 
I've been able to move data between non-Hyperforce instances, but I get the following error early on in the execution when trying to point to a Hyperforce instance.
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
I've originally experienced this error when moving large data volumes, but it consistently happens with Hyperforce instances even when moving a single, small record. I found [this issue with jsforce](https://github.com/jsforce/jsforce/issues/1239) which seems to imply version 1.x doesn't support Hyperforce instances. Has anyone had success using SFDMU against Hyperforce instances?

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. At this time, I cannot upgrade to jsforce v2.0 due to a number of breaking changes. These changes necessitate refactoring certain parts of the Tool's code, which is not planned for the immediate future.

Cheers.

**Comment by hknokh2** [comment]
I understand your concerns, especially with your organization's transition to hyperforce. Currently, jsforce 2.0 is still in beta, which means its stability and full functionality might not be guaranteed. I'm afraid I don't have a specific timeline for when the necessary updates will be on my agenda. I appreciate your patience and understanding as I navigate through these developments.

**Comment by jimbasilio** [comment]
Thanks so much. I understand and appreciate you. :)
