### ISSUE TITLE
[BUG]-SFDMU does not retrieve data from Source Org from Product object when we include "excludedFields": "ExternalDataSourceId"

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#653]
**Describe the bug**
When including Product in the Export.json file and we add "excludedFields": "ExternalDataSourceId", SFDMU does not retrieve the data from product. However in the First step (analysing data) SFDMU is clearly showing that there are records in the Source Org

**To Reproduce**
Execute the following export.json file
```
{
  "objectSets": [
    {
      "objects": [
        {
          "query": "select Name from Product2",
          "operation": "Upsert",
          "excludedFields": "ExternalDataSourceId",
          "externalId": "Name",
          "master": "true"
        }
      ]
    }
  ]
}
```

**Expected behavior**
Data from Source Product should be imported in Target Product object

**export.json**
It is above in the example

**Log file**
Attached

**_target.csv** file.
It has not been generated because no rows were extracted from source
[2023-10-21__12_56_18.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13059883/2023-10-21__12_56_18.log)

**Comment by jorgesolebur** [comment]
Quick note - if I remove 
`"excludedFields": "ExternalDataSourceId"`
from export.json file, it works !

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. 

Please, note that the ```excludedFields``` is an array property:
https://help.sfdmu.com/faq/configuration/what-kind-of-fields-can-i-exclude-with-excludefields-feature

Cheers.
