### ISSUE TITLE
[QUESTION] - use bulk api to export records to csv

### ISSUE THREAD

**Issue by alexsied** [forcedotcom/SFDX-Data-Move-Utility#654]
Is there a way to use the bulk api when exporting data into CSV files ?

right now, when I'm performing a readonly operation, to export a high volume of records (around 84000), it's the rest api that is leveraged.

Am I missing something ?
The command to run sfdmu: sf sfdmu:run --sourceusername a-alias  --targetusername csvfile
Here is my export.json:
{
    "apiVersion": "59.0",
    "bulkThreshold": 10,
    "objects": [
        {
            "query": "SELECT Id, Name FROM Account",
            "operation": "Readonly"
        }
    ]
}

Thank you for your help.

Alex

**Comment by hknokh2** [comment]
Hello
Thanks for contacting me.
Are you asking about the bulk api query?

**Comment by alexsied** [comment]
hello,
yes exactly.when I'm executing a readonly, bulk api query is not performed, I think it's the rest api that is leverage.
because of the volume of records, I need the bulk query to be used.
thank you
alex
    Le mercredi 25 octobre 2023 à 20:31:05 UTC+2, Haim Knokh ***@***.***> a écrit :  
 
 


Hello
Thanks for contacting me.
Are you asking about the bulk api query?

**Comment by hknokh2** [comment]
The tool is designed to automatically switch to the Bulk API when querying more than 200 records, or any number specified by the 'bulkThreshold' setting. However, it's important to note that utilizing the Bulk API for queries does not produce any visible changes or indications within your Salesforce organization, unlike when using the Bulk API for CRUD operations, which results in the creation of batch jobs.

To determine whether the Bulk API has been utilized for a query, you can check the consumption of REST API limits post-execution, as this is where the usage would be reflected.

**Comment by alexsied** [comment]
hello,
I checked the consumption as you suggested, and noticed that it's the rest api that is consumed (DailyApiRequests).
Is there something I shoud set ?
thank you

**Comment by hknokh2** [comment]
Hello,

Apologies for the confusion. There are two parameters that control different thresholds:

**bulkThreshold:** This parameter controls the threshold for using the Bulk API for insert/update operations.
**queryBulkApiThreshold:** This parameter controls the threshold for using the Bulk API to query records.

I have just updated the repository, adding the new queryBulkApiThreshold parameter. Please update the plugin to reflect these changes.

The reference article is below:
https://help.sfdmu.com/full-configuration

So your export.json should look something like this:
```
{
"apiVersion": "59.0",
"queryBulkApiThreshold": 100,
"objects" : [
		{
			"query": "SELECT Id, Name FROM Account",
			"operation": "Readonly"
		}
	]
}
```

Note, the default queryBulkApiThreshold is set to 30000 records.

**Comment by alexsied** [comment]
many thanks @hknokh 
This is exactly what was needed !

**Comment by alexsied** [comment]
many thanks @hknokh
Test was successful
This is exactly what was needed !

If I may suggest: I looked into the code, and it seems that queryAll is not permitted if bulk query is activated. SFDMU falls back to rest api.
Do you think it's possible to remove this condition ?

**Comment by hknokh2** [comment]
Could you please provide the file and the line in the source code where you see it ?

**Comment by alexsied** [comment]
> Could you please provide the file and the line in the source code where you see it ?

Sorry, I missed your message.
This condition is here:
file is : src\modules\components\common_components\sfdx.ts
line: 82
useBulkQueryApi = useBulkQueryApi && !useQueryAll;
