### ISSUE TITLE
[BUG] - COMMAND_ABORTED_BY_USER without any action

### ISSUE THREAD

**Issue by LoganTann** [forcedotcom/SFDX-Data-Move-Utility#656]
**Describe the bug**

The console window closes in the middle of a scenario run.

**To Reproduce**

- I created a migration scenario using SFDMU Gui 4.0.0 in Windows
- I ran a simple migration scenario of Contacts and Accounts with an External Id field
- The window closed after "Command in progress... done"

**Expected behavior**

A simple scenario with 1 relationship should work

**export.json**

Many custom fields were redacted.

```json
{
    "objects": [
        {
            "query": "SELECT AccountId, AssistantName, AssistantPhone, Birthdate, CreatedDate, Department, Description, DoNotCall, XXX__c, Email, EmailBouncedDate, EmailBouncedReason, Fax, FirstName, HasOptedOutOfEmail, HasOptedOutOfFax, HomePhone, Id, IsDeleted, IsEmailBounced, Jigsaw, JigsawContactId, LastActivityDate, LastCURequestDate, LastCUUpdateDate, LastModifiedDate, LastName, LastReferencedDate, LastViewedDate, LeadSource, XXX__c, MailingAddress, MailingCity, MailingCountry, MailingGeocodeAccuracy, MailingLatitude, MailingLongitude, MailingPostalCode, MailingState, MailingStreet, MobilePhone, Name, OtherAddress, OtherCity, OtherCountry, OtherGeocodeAccuracy, OtherLatitude, OtherLongitude, OtherPhone, OtherPostalCode, OtherState, OtherStreet, Phone, PhotoUrl, SDBX_ExtId__c, Salutation, XXX__c, SystemModstamp, Title FROM Contact WHERE SDBX_ExtId__c != '' AND Account.SDBX_ExtId__c != '' LIMIT 5",
            "operation": "Upsert",
            "externalId": "SDBX_ExtId__c"
        },
        {
            "query": "SELECT Id, XXX__c, AccountNumber, AccountSource, XXX__c, XXX__c, XXX__c, AnnualRevenue, BillingAddress, BillingCity, BillingCountry, BillingGeocodeAccuracy, BillingLatitude, BillingLongitude, BillingPostalCode, BillingState, BillingStreet, XXX__c, XXX__c, XXX__c, XXX__c, CreatedDate, XXX__c, Description, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, XXX__c, Fax, XXXX__c, XXX__c, Industry, XXX__c, IsCustomerPortal, IsDeleted, XXX__c, Jigsaw, JigsawCompanyId, LastActivityDate, LastModifiedDate, LastReferencedDate, LastViewedDate, XXX__c, Name, XXX__c, XXX__c, NumberOfEmployees, Ownership, XXX__c, Phone, PhotoUrl, XXX__c, Rating, SDBX_ExtId__c, XXX__c, XXX__c, XXX__c, ShippingAddress, ShippingCity, ShippingCountry, ShippingGeocodeAccuracy, ShippingLatitude, ShippingLongitude, ShippingPostalCode, ShippingState, ShippingStreet, Sic, SicDesc, Site, XXX__c, SystemModstamp, TickerSymbol, Type, XXX__c, Website FROM Account WHERE SDBX_ExtId__c != ''",
            "operation": "Upsert",
            "externalId": "SDBX_ExtId__c"
        }
    ]
}

```

**Log file**

[2023-10-31__17_16_38.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13219026/2023-10-31__17_16_38.log)

**_target.csv** file.

I cannot send it due to sensitive data.

However, there are many errors : 

```
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:Account_Trigger: execution of AfterInsert

caused by: System.DmlException: Update failed. First exception on row 13 with id 0011X00001E1w3BQAR; first error: DUPLICATE_VALUE, duplicate value found: Account_Unique_Name__c duplicates value on record with id: 0011X00001E1vGrQAJ: []

Class.Account_Trigger_Helper.setAccountManager: line 97, column 1
Trigger.Account_Trigger: line 32, column 1:--

---

INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST:bad value for restricted picklist field: FAC-Services&Equipme:XXXXREDACTEDXXXX__c
```

**Comment by hknokh2** [comment]
Hello.
Thank you for contacting me.
This is not a bug in the sfdmu.
Please, check your flow (triggers, validation rules).
I can't assist you with this.
Regards.

**Comment by LoganTann** [comment]
The error might indeed be caused due to a validation rule. However, the error displayed is misleading ("COMMAND_ABORTED_BY_USER")

**Comment by hknokh2** [comment]
Hello.

Thank you for clarifying.

When the tool encounters missing lookup values, it issues a warning to the user and provides a choice to either continue with the execution despite the warning or to abort the execution. If the user doesn't respond, the tool defaults to 'n' after a timeout period, opting not to execute and instead to stop the process.

Should you prefer to bypass all prompts and proceed with execution silently, even when warnings occur, you can make use of the --noprompt flag. For more details on this, please visit: https://help.sfdmu.com/running.

Therefore, the "Aborted by the user" message outputted by the tool is an accurate reflection of the process.

Best regards.

**Comment by LoganTann** [comment]
Oh I see, thanks for the answer !
