### ISSUE TITLE
[BUG]-Windows 10 Installation Warnings

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#657]
**Describe the bug**
Warnings and install errors when running sfdx plugins:install sfdmu on Windows 10

**To Reproduce**
On my Windows 10 machine sfdx plugins:install sfdmu

**Expected behavior**
Not receiving message below. First pass at re-installing plugins the install failed. Tried a 2nd time and succeeded with the below messages:

Warning: sfdmu > @salesforce/dev-config > tslint-microsoft-contrib@5.2.1: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more    
 »   information.
 »   Warning: sfdmu > madge > detective-postcss > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
 »   Warning: "@salesforce/plugin-packaging > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
 »   Warning: "@salesforce/plugin-packaging > @oclif/core > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".

These warnings can only be addressed by the owner(s) of sfdmu.
We suggest that you create an issue at https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues and ask the plugin owners to address them.

**Comment by hknokh2** [comment]
Hello.
Thank you for your message.
It seems that the issue you're encountering is indeed a bug with the SFDX CLI, which may stem from the specific configuration of your environment. At present, I am unable to provide assistance with this matter as it depends heavily on the broader infrastructure setup.
Best regards.
