### ISSUE TITLE
[QUESTION]-Execution of the command has aborted due to unexpected error: missing ) after argument list.

### ISSUE THREAD

**Issue by DougMidgley** [forcedotcom/SFDX-Data-Move-Utility#658]
**Describe the bug**
Getting the error "Execution of the command has aborted due to unexpected error: missing ) after argument list." when running sfmdy with. Particularly odd thing is that the file which is mentioned doesn't exist - under sfmc directory, only LIB exists, not SRC, and if i used LIB then the line doesn't exist, so its all a bit strange.

Uninstall and reinstall tried on both sf and sfdmu.
versions 
@salesforce/cli/2.14.6 win32-x64 node-v19.8.1
sfdmu 4.30.0

> [10:22:54.515] [ERROR] Execution of the command has aborted due to unexpected error: missing ) after argument list.
> [10:22:54.518] [ERROR] [STACK TRACE] SyntaxError: missing ) after argument list
>     at C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJobTask.ts:1685:71
>     at Array.forEach (<anonymous>)
>     at C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJobTask.ts:1679:49
>     at Array.forEach (<anonymous>)
>     at ___mockRecords (C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJobTask.ts:1655:17)
>     at ___createUpdateData (C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJobTask.ts:1231:25)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async MigrationJobTask.updateRecords (C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJobTask.ts:1064:18)
>     at async MigrationJob.updateRecordsAsync (C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\models\job_models\migrationJob.ts:522:37)
>     at async RunCommand.executeJobAsync (C:\Users\douglas.midgley\AppData\Local\sf\node_modules\sfdmu\src\modules\commands_processors\runCommand.ts:251:5)
> [10:22:54.523] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).

**To Reproduce**
install sf cli
install sfdmu -> `sf plugins install sfdmu`
run sfmdu -> `sf sfdmu run  --targetusername $org  --path "scripts\devops\helperscripts\anonymize"`

**Expected behavior**

**export.json**
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13259195/export.json)

**Log file**

[2023-11-05__10_42_02.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13259192/2023-11-05__10_42_02.log)

**Comment by hknokh2** [comment]
Hello.

Thank you for reaching out.

Please be aware that the tool outputs are generated directly by the Node.js application, and as such, I don't have control over the error messages produced by the compiled code.

Concerning the issue you've mentioned, I'll make sure to check into it. However, I must inform you that my current availability for this project is quite limited, so I'm scheduling it into my pipeline for a more in-depth review later on.

Best regards.

**Comment by DougMidgley** [comment]
Seems like it might come from the mock handler when you put in string value with single quotes
"c_set_value('draft')" seems to be ok while "c_set_value(draft)" is not. 
There is no string example in the documentation so wasnt clear for me, but seems could be the case.

Is there any way to add a check for this given the error isnt exactly clear?

**Comment by hknokh2** [comment]
Hello,

You are correct. You should use the value "draft" in quotes for setting quotas. This is because the function ```eval()``` evaluates the value placed within brackets. 
The variable ```draft``` is undefined locally in your context, so using the string "draft" is the appropriate approach.

Best regards.
