### ISSUE TITLE
Mitigate transient command initialization failures ("Command initialization error: Access token to the XYZ has been expired or the user has no access permissions."

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/SFDX-Data-Move-Utility#664]
We periodically see this error in our CI/CD builds when running an sfdmu:run to import data from CSV files into a newly born scratch org:

```
 Command initialization error: Access token to the XYZ has been expired or the user has no access permissions..
 Execution of the command sfdmu:run has been completed. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
```

Last night, there was a lengthy duration of very reproducible occurrences of the error. Generally, a restart of the build will fix the problem but last night, reliable reproduction of the error continued for about 12 hours before returning to it's normal infrequency. 

During that period, I added some debug output to SFDMU to figure out what exactly was failing. It was the call to the `jsForce.identity()` method over here:

https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/components/common_components/sfdx.ts#L520

The `identityAsync()` method is only called one place:

https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/models/script_models/scriptOrg.ts#L182

And the return value isn't used. It appears as though calling identityAsync() is purely being used to 'validate' the connection. However, the code a few lines below the identityAsync() call will quickly smoke out an invalid connection:

https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/master/src/modules/models/script_models/scriptOrg.ts#L188

It's my supposition that Salesforce's Identity API has latency (possibly even worse with Hyperforce) and it's causing the newly born scratch org's user identity URL to return a 404. This is the Exception that is thrown from the `jsForce.identity()` call:

```
     [exec] [21:58:36.585] ERROR_HTTP_404: Bad_Id
     [exec]     at HttpApi.getError (/home/esposito/.local/share/sf/node_modules/jsforce/lib/http-api.js:250:13)
     [exec]     at /home/esposito/.local/share/sf/node_modules/jsforce/lib/http-api.js:95:22
     [exec]     at tryCallOne (/home/esposito/.local/share/sf/node_modules/promise/lib/core.js:37:12)
     [exec]     at /home/esposito/.local/share/sf/node_modules/promise/lib/core.js:123:15
     [exec]     at flush (/home/esposito/.local/share/sf/node_modules/asap/raw.js:50:29)
     [exec]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
     [exec]   errorCode: 'ERROR_HTTP_404'
     [exec] }
```

This feature request is to remove the call to `identityAsync()` since it's just extra unused code.  Additionally, logging the raw Exception payload would be super helpful for debugging future incidents like this.

**Comment by alanjaouen** [comment]
faced the same issue on scratch org created on hyperforce

**Comment by hknokh2** [comment]
Hello,

Thanks a lot for your suggestion!
I agree, the issue with the calling to identity does seem odd. So I'm adding it to my development pipeline. Please bear in mind, due to time constraints, it might take a while, but I'll try to address it as soon as possible since it appears to be a critical issue. Rest assured, I'll keep you updated on any progress.

Cheers.

**Comment by hknokh2** [comment]
Hi
This issue has been resolved.
