### ISSUE TITLE
[QUESTION]-Execution stops when including a lookup field that has a lot of records

### ISSUE THREAD

**Issue by mark10281996** [forcedotcom/SFDX-Data-Move-Utility#665]
**Describe the bug**
Execution stops when including a lookup field that has more than 948001 records.  There was no errors displayed. 
The lookup field was to case object and case object has 9582207 records. 
**To Reproduce**
Describe steps to reproduce the behavior.
1) Setup export.json that queries an object with only 8 records, but has a lookup field that has more than 948001 records. This was ran in simulation mode. 
2) sfdx sfdmu:run -s prod -u uat -p ./data_results --noprompt --verbose 
**Expected behavior**
I expected the execution to not stop and continue querying all the records of the lookup field in the query, I found out if I exclude the field Case__c "excludedFields": ["Case__c"], then the execution will complete successfully. 

**export.json**
Attach your **export.json** file
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13392714/export.json)

**Log file**
Attach your full **.log** file.
[2023-11-16__23_58_36.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13392702/2023-11-16__23_58_36.log)

**Comment by hknokh2** [comment]
Hello,

Thank you for getting in touch with me. Here's some information in response to your query:

- Unfortunately, there's no guarantee that the plugin can handle all records in large-size data sets, nor is there a specific maximum record amount that can be queried. This really needs to be determined experimentally based on the end-users' environment and their data.
- It's standard for the tool to stop without providing output errors if there's an out-of-memory issue. You might want to consider increasing the Node.js memory heap size. This guide could be helpful: [Resolving JavaScript Heap Out of Memory Error](https://help.sfdmu.com/troubleshooting/plugin-wont-run/i-have-an-javascript-heap-out-of-memory-error-how-to-resolve).

Cheers.

**Comment by mark10281996** [comment]
Hi @hknokh2,
Thank you! Changing the nodejs memory heap fixed it.
