### ISSUE TITLE
HOW to Data Anonymization 

### ISSUE THREAD

**Issue by ghost** [forcedotcom/SFDX-Data-Move-Utility#666]
By Using SFDMU TOOL how we can replace the last 4 digit of the phone number in asterisk.

**Comment by hknokh2** [comment]
Hello,

Thank you for contacting me. Unfortunately, the Data Anonymization feature does not support this functionality. However, you can achieve the desired outcome by using the Regex Replacement or JS Eval Replacement options available in the Value Mapping feature. For more information and guidance, please refer to this link: [https://help.sfdmu.com/full-documentation/advanced-features/values-mapping](https://help.sfdmu.com/full-documentation/advanced-features/values-mapping).

Best regards.
