### ISSUE TITLE
[QUESTION] -  Unable to run script. Check whether sfdx-cli is installed and available in the system path and the Plugin is installed.

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#671]
I'm geeting below error when I click run the script button.

I've installed both sfdx and sfdmu plugin

Please help

<img width="1372" alt="Screenshot 2023-12-07 at 5 09 21 PM" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/18720022/cb48d136-03c5-4a3e-b8ba-3643bf926778">
- Ask your question or what kind of help you need.

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. It seems that you're experiencing an environmental issue, which I can't help you with this. The problem appears to be related to running the SFDMU plugin on your machine. I recommend executing the CLI command directly in the terminal or console to observe any messages it produces. Additionally, you can examine the log file generated by the app to understand the error in detail. Often error details are also visible in the sidebar; you can access this by clicking on the floating button located at the top right side of the screen.

Cheers.

**Comment by hknokh** [comment]
Can you send me the log file? You can find it by going to File -> Open Application Folder in Explorer. In the logs folder, locate the latest file with the .log extension. Please try to replicate the issue and then send me that log file. This might help me understand what's happening.

**Comment by hknokh2** [comment]
Hello,
We've fixed an issue with script execution via button on macOS. 
Please update the app to apply this fix. 
Now, clicking the button will open Terminal to run the script. Remember to close the Terminal manually after the script completes.
Best regards.
