### ISSUE TITLE
[Question] Why data move utility is not made availalbe as supported feature in Salesforce like data loader?

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/SFDX-Data-Move-Utility#674]
Hello, 
I've been using data move utility for a long time. We use this tool to migrate data between different Salesforce sandbox from prod. We also use this tool for CPQ reference data migration (bundle, price/product rule etc) as well.

This is extremely powerful tool and not many developers/admins are aware of it.

Why can't this tool be used as supported tool by Salesforce like data loader? 

There is very little support available and not many Youtube videos to make sure this popular.

**Comment by hknokh2** [comment]
Hello!

Firstly, I'm glad to hear that you're using SFDMU with such great success. Secondly, you've indeed raised a very interesting question. To establish SFDMU as an officially supported tool, akin to Data Loader, it needs to be widely promoted internally across the Salesforce organization. As the sole developer and maintainer of this open-source project, I am the only one who can undertake such promotion. However, at this juncture, I am content with the current level of SFDMU's popularity and do not plan to initiate aggressive promotion, at least in the near future. My approach primarily relies on word-of-mouth and the fact that this product has already proven itself valuable to many users.

Best regards.
