### ISSUE TITLE
[QUESTION] - How to combine accounts from several extractions in one CSV?

### ISSUE THREAD

**Issue by andrii-solokh** [forcedotcom/SFDX-Data-Move-Utility#675]
I have checked documentation several times but didn't find a way how can I combine accounts from several extractions in one CSV and then using one more job to fetch related contacts.

The first group should be selected from child to parent.
A second group of accounts should be masters selected directly by record types.

Third operation query all related contacts from CSV from first and second extractions. 

The problem I'm facing is that after second extraction, executed CSV with accounts is overwritten 

```
{
  "allOrNone": true,
  "useSeparatedCSVFiles": false,
  "objectSets": [
    {
      "objects": [
        {
          "query": "SELECT all FROM Product2 WHERE Product_Hierachy__c IN ('12345', '54321')",
          "operation": "Upsert"
        },
        {
          "query": "SELECT all FROM PriceBookEntry",
          "master": false,
          "operation": "Upsert"
        },
        {
          "query": "SELECT all FROM OpportunityLineItem",
          "master": false,
          "operation": "Upsert"
        },
        {
          "query": "SELECT all FROM Opportunity",
          "master": false,
          "operation": "Upsert"
        },
        {
          "query": "SELECT all FROM Campaign",
          "master": false,
          "operation": "Upsert"
        },
        {
          "object": "Account",
          "query": "SELECT all FROM Account WHERE RecordType.DeveloperName IN ('X1', 'X2')",
          "master": false,
          "operation": "Upsert"
        }
      ]
    },
    {
      "objects": [
        {
          "object": "Account",
          "query": "SELECT all FROM Account WHERE RecordType.DeveloperName IN ('X3', 'X4')",
          "operation": "Upsert"
        }
      ]
    },
    {
      "objects": [
        {
          "query": "SELECT all FROM Account",
          "useCSVValuesMapping": true,
          "operation": "Upsert"
        },
        {
          "query": "SELECT all FROM Contact",
          "master": false,
          "operation": "Upsert"
        }
      ]
    }
  ]
}
```

**Comment by hknokh** [comment]
Hello,

I apologize for the delay and the inadvertent closure of the issue.

Firstly, let me provide some insight into how SFDMU handles ObjectSets. ObjectSets comprise a collection of independent migration configurations, each with its own set of objects to migrate. Therefore, when you execute SFDMU with an export.json file containing several sets of objects, it is akin to running SFDMU multiple times with separate export.json files. As a result, each subsequent run of the Plugin is not aware of the previous runs, leading to the records of the same sObject being overwritten each time.

Secondly, concerning your specific use case, I recommend utilizing the following third object set:

```json
{
  "objects": [
    {
      "query": "SELECT all FROM Account WHERE RecordType.DeveloperName IN ('X1', 'X2', 'X3', 'X4')",
      "useCSVValuesMapping": true,
      "operation": "Readonly"
    },
    {
      "query": "SELECT all FROM Contact",
      "master": false,
      "operation": "Upsert"
    }
  ]
}
```

By setting the operation to Readonly, you can prevent the overriding of existing aggregated accounts. Additionally, filtering by record type enables the selection of only the necessary account records and limits the child contact records to those associated with these account records.

Best regards.

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.
