### ISSUE TITLE
[FEATURE REQUEST]- Add Parameter for 'yes' on command line

### ISSUE THREAD

**Issue by unizhu** [forcedotcom/SFDX-Data-Move-Utility#676]
**Is your feature request related to a problem? Please describe.**
When some data issues happen, only few seconds left to input yes for confirmation , But I just wanna type y and let it process... 
If I am doing something else , the migration will be canceled. 

`bash
Command in progress... done
[16:51:53.33] [ERROR] Execution of the command has aborted by the user.
[16:51:53.34] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 5 (COMMAND_ABORTED_BY_USER).
`

**Describe the solution you'd like**
If there is a '-y' flag to default any prompt for yes that will be good and also can be used for daily backend scheduled jobs.

**Comment by hknokh2** [comment]
Hello,

Thanks for reaching out, and apologies for the delay in my response. To suppress prompts and automatically answer 'yes' to all prompts, allowing you to continue working despite warnings, you can use the existing flag: --noprompt. For more information, please visit: [SFDMU Running Guide](https://help.sfdmu.com/running).

Cheers.
