### ISSUE TITLE
Support for SF instead of SFDX

### ISSUE THREAD

**Issue by LaurentDelcambre** [forcedotcom/SFDX-Data-Move-Utility#678]
Hi,

First thank you for a very good product.

In our company we are using SF as standard CLI and are not allowed to use SFDX as it is not supported anymore.

Do you have any plans to move to the up-to-date SF tool?

Do current users have both installed on their machine? Last time I tried that it created issue on my personal machine so I uninstall SFDX.

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out, and I appreciate your kind words! Concerning the SF CLI, SFDMU is compatible with the latest SF CLI version. You can easily install this product as is with: sf plugins install sfdmu. To run it, use: sf sfdmu run --sourceusername source@org.org --targetusername target@org.org. Essentially, you just need to replace sfdx command:subcommand with sf command subcommand, and it should work seamlessly for you.

Cheers.

**Comment by LaurentDelcambre** [comment]
Hello Haim,

Thanks for coming back to me.
This makes sense and it is now working fine.
I would humbly suggest an update to the setup documentation :)

Thanks again and have a good day
