### ISSUE TITLE
[BUG]-related lookups from managed packages will sometimes have the first letter of their field name overwritten

### ISSUE THREAD

**Issue by SnowBirdMV** [forcedotcom/SFDX-Data-Move-Utility#680]
When pulling down a lookup field from a managed package that begins with the letter 'c' the plugin will incorrectly replace it with the letter 'r'

**To Reproduce**
Have a managed package with a field on an object beginning with 'c' IE 'managedPackage__objectname.contact__c' then add that object/field to the export.json and attempt to pull the data down to a csv

**Expected behavior**
the related object to have a proper lookup and not have the first letter overwritten by 'r'

**Log file**
`[14:36:49.890] [ERROR] Error during execution of the command: 
InForceEW__billtocontactid__r.Name, InForceEW__rontact__c.Name, InForceEW__paymenttermid__r.Name
                                    ^
ERROR at Row:1:Column:4801
Didn't understand relationship 'InForceEW__rontact__c' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
[14:36:49.899] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).`

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me.
I will take a look at your case and let you know if there are any updates.
Cheers.

**Comment by hknokh** [comment]
Hello
The issue has been fixed
Regards

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions or the bug is still here.

Regards.
