### ISSUE TITLE
[QUESTION] - Error while loading files using this configuration

### ISSUE THREAD

**Issue by SF-VOL360** [forcedotcom/SFDX-Data-Move-Utility#684]
**Describe the bug**
Error while loading files using this configuration

**To Reproduce**
I am trying to load files using SFDMU to Saleforce org asand getting error as .

Error (1): Nonexistent flags: --sourceusername

I already have specified --sourceusername in my command.
I might be missing some configuration and need your help on this. I tried to follow the instruction and everything (SFDX CLI, npm etc.) all properly set.

**Expected behavior**
There should be an error.
**export.json**
Here is my export.json

{
    "objects": [
        {
            "query":"SELECT TITLE,VERSIONDATA,PATHONCLIENT,DESCRIPTION FROM ContentVersion",
            "externalId": "FILES_EXTERNAL_ID__C"
            "operation": "Insert"
            "afterAddons" : [
                {
                    "module": "core:ExportFiles"
                }
            ]    
        }
    ]
}

**Log file**
Attach your full **.log** file.

**_target.csv** file.
Target is my Salesforce org and my source is my CSV file
I have kept CSV file ( Content version field specified with these fields TITLE,VERSIONDATA,PATHONCLIENT,DESCRIPTION, FILES_EXTERNAL_ID__C) to be imported in same folder where export.json file is.
This is the command I am running
sfdx sfdmu:run --sourceusername csvfile --targetusername <mySalesforceTargetOrgUsername>
Please suggest what I could be missing.

**Comment by SF-VOL360** [comment]
sfdx sfdmu:run --sourceusername csvfile --targetusername <mysalesforceorgusername for target>
[24:27:36.359] Execution of the command sfdmu:run has been started.
=== Loading and validating the export.json script ...
=== OBJECT SET #1 STARTED
Running Plugin version: 4.32.2
Running Add-On API version: 1.5.0
[24:27:36.375] Loading Core Add-On Module declarations ...
[24:27:36.430] Loading Add-On module core:ExportFiles ...
Command in progress... done

[24:27:36.454] [ERROR] Command initialization error: There are no objects to process..
[24:27:36.463] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
[24:27:36.466] Total time elapsed: 00h 00m 00s 096ms .
************************************************

Also I changed the export.json to like this
{
    "objects": [
        {
            "operation": "Insert",
            "query":"SELECT TITLE,VERSIONDATA,PATHONCLIENT,DESCRIPTION,FILES_EXTERNAL_ID__C FROM ContentVersion",
            "afterAddons" : [
                {
                    "module": "core:ExportFiles"
                }
            ]    
        }
    ]
}

**Comment by SF-VOL360** [comment]
Can someone update on my request pls.

**Comment by hknokh2** [comment]
Hello,

Please note that the ContentVersion object is not supported for direct migration. Instead, it should be transferred using the method described in the SFDMU documentation: [Export File Core Add-On Module](https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module). This process should be carried out alongside the main object, such as an account.

I suggest adding any other object to which you intend to attach files and configuring the core:ExportFile add-on accordingly.

Best regards.

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. 
I'm closing it for now. Please let me know if you have any further questions.

Thank you.
