### ISSUE TITLE
[QUESTION] - Migrate data with lookup existing only in target

### ISSUE THREAD

**Issue by landscronar** [forcedotcom/SFDX-Data-Move-Utility#686]
Hello,
I am trying to understand if following scenario can be achieved with SFDMU solution in one job.

I have following objects (in the same org, if that is important): 

```
Custom_Object_A
Id, Name, Field_A1, Field_A2

Custom_Object_B
Id, Name, Field_B3, Field_B4, Field_Lookup (lookup to Custom_Object_c)


Custom_Object_C
Id, Name, Description
```

I need to migrate data from **_Custom_Object_A_** to **_Custom_Object_B_**:
-  they have different names of the fields, so I am using field mapping and  it is working fine. 
- In addition, the migrated records (in **_Custom_Object_B_**) need to have lookup value in _Field_Lookup_ field (lookup to **_Custom_Object_C_**). 

At the moment I am able to do it with following options only:
### 1 option:
 - Run first job to migrate the records from **_Custom_Object_A_** to **_Custom_Object_B_**
 - Run another job for **_Custom_Object_B_**, which will do field transformation (because **_Custom_Object_B_** has lookup to **_Custom_Object_C_** already) and update the field Field_Lookup

### 2 option:
 - Add lookup from **_Custom_Object_A_** to **_Custom_Object_C_** (with no values)
 - Configure field transformation for the **_Field_Lookup_** field

 When I am trying to migrate all in one job (without lookup from Custom_Object_A to Custom_Object_C) the transformation returns null value in **_formula.lookupValue_** .

  
 I tried to do transformation with:
-  beforeUpdateAddons with source and target reference (on both objects) 
- dataRetrievedAddons  with source and target reference (on both objects)
-  adding mapping for the lookup field. 
- Multiple scenarios with  objectSets to separate it
- including **_Custom_Object_C_** specifically in the list of object and with WHERE clause (it returns one record only)
- only specifying **_Custom_Object_C_** in transformation (then all records are being selected for lookup, but transformation still returns _null_

but it is not working for me.  I checked examples in documentation, but it looks like those scenarios have lookups (like OwnerId or lookup to same Account object in modification documentation) 

So, I am wondering if I am doing something completely wrong or that is not possible to do in one job. 

Here is one example of many configurations I tried: 

```json
{
        "objects": [
            {   
                "query": "SELECT Id, Name FROM Custom_Object_C WHERE Name = 'LookUpName'",
                "operation": "Readonly",
                "ExternalId": "Name"
            },
             {
                "fieldMapping": [
                     {
                         "targetObject": "Custom_Object_B"
                      },
                     {
                          "sourceField": "Name",
                          "targetField": "Name"
                      },
                     {
                          "sourceField": "Field_A1",
                          "targetField": "Field_B3"
                      },
                     {
                          "sourceField": "Field_A2",
                          "targetField": "Field_B4"
                      }
                 ],
                 "query": "SELECT Id, Name, Field1, Field2 FROM Custom_Object_A",
                 "operation": "Upsert",
                  "useFieldMapping": true,
                  "externalId": "Name",
                  "beforeUpdateAddons" : [
                    {                        
                        "module" : "core:RecordsTransform",
                        "args": {
                            "fields": [
                                {
                                    "alias": "lookupValue",
                                    "sourceObject": "Custom_Object_C",
                                    "sourceField": "Id",
                                    "isConstant": true,
                                    "lookupSource": "source",
                                    "lookupExpression": "source.Name == 'LookUpName'"
                                }
                            ],
                            "transformations": [
            
                                {
                                    "targetObject": "Custom_Object_B",
                                    "targetField": "Field_Lookup",
                                    "formula": "formula.lookupValue"
                                }
            
                            ]
                        }
                    }
                ]
              
            
            
        }
        ]
}

```

Thank you!

**Comment by hknokh** [comment]
Hello,

I apologize for the accidental closure of the case. 
I recommend using ObjectSets instead of transforming records directly. Your solution should comprise two distinct object sets:

1. The first object set is designed to migrate records from Custom_Object_A to Custom_Object_B, complete with field mapping.
2. The second object set focuses on populating Field_Lookup. It will include Custom_Object_B and Custom_Object_C. The query for Custom_Object_B should specify Field_Lookup, with "operation": "Upsert" and "master": false (since it's child or related records). Custom_Object_C should be set to "Operation": "Readonly", as the objective is not to modify this data but to utilize it for selecting related child records from Custom_Object_B.

Best regards.
