### ISSUE TITLE
[QUESTION] - Dear Team Previously I am able to connect my source and target org via SFDMU tool

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#689]
- Ask your question or what kind of help you need.
Now I am not able to connect the source and target . I am getting Failed to execute force:org:list command or no SFDX orgs were detected in your system. I have run the same command in my terminal as well but no result is there. How we can connect with GUI. 

Regards
Gourav Narula

**Comment by hknokh** [comment]
Hello
The old gui 3.X is using SFDX CLI. The salesforce made this outdated and it can cause the connection issue.
Please switch to 4.X
Also please see my replies to #690
