### ISSUE TITLE
How to import a data from csv file to an salesforce org

### ISSUE THREAD

**Issue by ifthikar-ahmed** [forcedotcom/SFDX-Data-Move-Utility#694]
How to import a data from csv file to an salesforce org

**Comment by hknokh2** [comment]
Hello
There are many articles in the doc about csv.
The main point is to set --sourceusername csvfile in the command line.
Please search for csv in the Sfdmu Help Center for the relevant articles.
Regards.

**Comment by ifthikar-ahmed** [comment]
HI

Below is the command i am executing :

sf sfdmu run --sourceusername csvfile --targetusername luxehavensb -p
".\dmuscript"


and below is Export JSON :

{
    "objects" : [
        {
            "query": "SELECT Id, Name , pba__Description_pb__c FROM
pba__Listing__c",
            "operation": "Insert",
            "externalId": "Id",
            "useFieldMapping" :true,
            "fieldMapping": [
                {
                    "targetObject": "RE_Listing__c"
                },
                {
                    "sourceField": "Name",
                    "targetField": "Name"
                },
                {
                    "sourceField": "pba__Description_pb__c",
                    "targetField": "RE_Description__c"
                }
            ]
        }
    ]
}


it is not working , i tried checking the documentation , no luck

Regards,
Ifthikar Ahmed

**Comment by hknokh2** [comment]
Hello
Normally, I am providing support only if I suspect that it might be a bug in the plugin itself, but here I see the clean configuration problem.
You don't provide what does not work, log files and example of csv file you try to import. 
What I can see right now, that you use field mapping bit the field mapping is not supported when csvfile is used as the  source or the target. May be this is the reason that your job is failed.
Please recheck the documentation again for example of right format of source csv file. 
Regards.

**Comment by ifthikar-ahmed** [comment]
Pls update this in knowledge base , i searched for the in csv import export
section and i did not find the information that you shared with me

**Comment by hknokh2** [comment]
You are right it's not documented. I am going to add it there.
Thanks.

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.
