### ISSUE TITLE
[QUESTION] - useFieldMapping usage ?

### ISSUE THREAD

**Issue by Windyo** [forcedotcom/SFDX-Data-Move-Utility#695]
Opening a question because unsure if bug.
I am trying to use the FieldMapping to generate a CSV file for an external target.
The test config I am using is: 
 ```json
{
    "objects": [
        {
            "query": "select Name from Account",
            "useFieldMapping": true
        }
    ]
}
```
In the same directory, I have FieldMapping.csv
```csv
ObjectName,FieldName,Target
Account,,ClientData
Account,Name,Test__c
```
running 

`sf sfdmu:run --path .\config\data\ -s admin@myaccount.com.test -u csvfile`

Results in the file having `Id,Name` as headers.

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
It is working as expected. The field mapping is not intended to work with csv target. You can not use it to rename csv columns.
Cheers.

**Comment by Windyo** [comment]
Hi,
OK too bad - I'll run a script post-run then.
TY for the answer.
