### ISSUE TITLE
[QUESTION] - SFDMU Users, GroupMember, etc

### ISSUE THREAD

**Issue by MichaelPStimpson** [forcedotcom/SFDX-Data-Move-Utility#696]
Hello, I'm just starting to work with this tool and I see the [documentation ](https://help.sfdmu.com/faq/common-questions/can-i-migrate-users-with-the-plugin) says it does not support User, Group, Profile, or DandBCompany!

I'm looking to create users and group member records in addition to other tables and I'd like to use SFDMU as much as possible through out the process! Is there a recommended alternative tooling option?

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. 

It's correct, these objects are not supported by the Sfdmu for migration. But they still can be used with Readonly operation to serve lookup parent values for other objects.

For alternative free tooling solutions for transferring these objects, consider using any other tools, like a standard sf dataloader or “sf data import tree” CLI command. 
Dataloader does not support relationships between objects. Data tree import - yes, however it requires more complex setup.

Cheers.

**Comment by MichaelPStimpson** [comment]
Thank you!
