### ISSUE TITLE
[FEATURE REQUEST] - Change locale for mockFields anonymization?

### ISSUE THREAD

**Issue by hvilminko** [forcedotcom/SFDX-Data-Move-Utility#699]
SFDMU uses the Casual module for anonymizing data. Is it somehow possible to pass the wanted locale to casual when configuring the mockFields object? Snippet from the casual documentation:

> You can get localized version of casual generator:
> var casual = require('casual').ru_RU;
> casual.street; // 'Бухарестская'

This would be very handy because now I'm stuck with creating English (US) names, addresses etc.

**Comment by hknokh** [comment]
Hello,

Thank you for your message and for the excellent suggestion! I've added this feature to my development roadmap. Due to my current time constraints, it might take some time to implement. Please stay tuned for updates.

Best regards.
