### ISSUE TITLE
Can we use the csv files generated by org to org migration in simulation mode for csv to org migration?

### ISSUE THREAD

**Issue by kvenkatasivareddy** [forcedotcom/SFDX-Data-Move-Utility#703]
Hi team,

I assumed that csv files generated in simulation will be same as non-simulation mode in org to org migration. 

In simulation mode i'm not seeing any failures. Where as for the same export json with the only difference is non simulation mode i'm seeing the many failures in target csv files. I'm not understanding why the simulation mode is not generating the same set of failures that's happening in non-simulation mode.

I have attached the export json, logs and target csv files for both simulation mode and non-simulation mode below. Please have a look at it.

with simulation mode: 
[simulationMode.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14819421/simulationMode.zip)

without simulation mode:
[non-simulationmode.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14819425/non-simulationmode.zip)

Thanks
Sivareddy

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
I will take a look at your case and let you know if there are any updates.
Cheers.

**Comment by kvenkatasivareddy** [comment]
Any update on this @hknokh2 ?

**Comment by hknokh2** [comment]
Hey
No update yet.
Regards

**Comment by hknokh** [comment]
Hello,

Please note that the simulation mode does not update the target organization. It is designed solely to check the metadata and query the source organization. The purpose of the simulation mode is to verify data integrity and identify potential configuration issues related to objects, fields, and relationships, as well as to assess the volume of data that will be updated in the target.

The issue you're experiencing stems from the actual update of records on the target side, which does not occur in simulation mode.

Best regards

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Comment by kvenkatasivareddy** [comment]
thank you for the clarification @hknokh :)
