### ISSUE TITLE
field integrity exception: PricebookEntryId (pricebook entry is in a different pricebook than the one assigned to the opportunity)

### ISSUE THREAD

**Issue by kvenkatasivareddy** [forcedotcom/SFDX-Data-Move-Utility#704]
Hi Team,

I'm trying to migrate the opportunityLineItem along with it's lookup objects. I've attached the export json below. 

The product[Laptop in below image] associated with the opportunity record have multiple pricebookentry records(with standard price book and custom price book) in the target pricebookentry table.

<img width="672" alt="image" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/113102274/fa8383d1-5551-46f6-824a-5721e99d8dfc">

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14824003/export.txt)

[Opportunity_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14824005/Opportunity_insert_target.csv)
[OpportunityLineItem_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14824006/OpportunityLineItem_insert_target.csv)

Error:
`field integrity exception: PricebookEntryId (pricebook entry is in a different pricebook than the one assigned to the opportunity)
`

Current behaviour: 
  In the case opportunityLineItem record insertion, the plugin is picking the first come **PricebookEntry** record[3 row in the above image] instead of the correct **PricebookEntry** record[4th row in the above image] which has been associated with the Opportunity object. Since the **Pricebook2** is different in both **PricebookEntry** and **Opportunity** tables, the insertion operation for **OpportunityLineItem** object is failing with  `field integrity exception`

Expected behaviour
  It should able to pick the correct record and create the OpportunityLineItem record successfullly.

Is there a way i can solve this with sfdmu plugin?

Thanks,
Sivareddy

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. It appears you have a question regarding configuration. At this time, I'm unable to provide support for such inquiries. I appreciate your understanding.

Cheers.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
