### ISSUE TITLE
How to use FieldMapping with csv2org migration

### ISSUE THREAD

**Issue by AlwaysThinkin** [forcedotcom/SFDX-Data-Move-Utility#705]
Hi,
I'm doing a migration from Raiser's Edge (RE) to Salesforce and hoping to find a way to map the RE column headers to Salesforce fields. The RE exports generate column headers for its fields dynamically and it would be easier to map them all in a FieldMapping.csv file than to replace the column headers with Salesforce field names programmatically. I've tried doing this with either the sourceField in the query or the targetField in the query and with the importCSVFilesAsIs as true or false but the mapping is ignored. Hopefully there's a way to do this directly in SFDMU that I can use and can document for others who attempt this type of migration.

Thanks!
Luke C

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
Field mapping works only for org2org. 
Cheers.
