### ISSUE TITLE
[QUESTION] - Is there a way to assign the Standard price book to the products  in target org that we are migrating?

### ISSUE THREAD

**Issue by kvenkatasivareddy** [forcedotcom/SFDX-Data-Move-Utility#706]
Hi team,

Is there a way to assign the standard price book to products that are newly inserted to target org automatically with the plugin?

I'm facing the `Before creating a custom price, create a standard price.` issue always when i'm trying to insert records to pricebookentry table. It would be helpful, if anyone provide the solution for this.

Thanks
Sivareddy

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
Normally I'm providing support in cases that i can see possible bug in the plugin. The plugin can only to import/export existing data, not create anything new  
Cheers.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
