### ISSUE TITLE
Data Secuirty

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#707]
@hknokh2 ,

Q1. When we are trying to migrate the data via SFDMU tool from one org to another org as you know that we are migrate our client data are you storing those data in cloud anywhere. as a backup, If there is any data breach Bility will be happened because it is an open-source tool. 

Q2. As you we know this tool is open-source tool, in future some phishing attack will happen if this tool is using any vulnerability scanner to secure our data.
Q3. This SFDMU tool is registered tool. If it is when this tool is register can you, please let us know.

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

In the old version we have the three option  in GUI  to  migrate the data from one org to another org. 

1. Salesforce org to Salesforce org 
2.  Salesforce Org CSV file
3. CSV file to Salesforce Org 
In the new version there is no such option available in the GUI. 

We can only migrate the data from Salesforce org to Salesforce  org

Regards
Gourav Narula

**Comment by hknokh2** [comment]
Hello
Please see this artcile regarding your question (Other changes from Version 3)
https://help.sfdmu.com/sfdmu-gui-app
Cheers.
