### ISSUE TITLE
Error during analysing of the org metadata: The object is missing in the source

### ISSUE THREAD

**Issue by DDsalesforce141297** [forcedotcom/SFDX-Data-Move-Utility#709]
Hi,

I am using SFDMU migration tool in my project for data migration. In that 3 of the objects is not supporting for migration operation. I have all the necessary access to the org and I have tried using other data loader tools for checking it is working fine and I confirm that this issue is related to the sfdmu tool.

while trying to fetch the object from the org throwing error please, check the attached log file

[2024-04-10__11_36_51.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14928106/2024-04-10__11_36_51.log)

Please, help us to resolve the issue as soon as possible.

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. If you're sure there are no issues with the permissions, the problem might be related to the default API version set in SFDMU. You can address this by updating the `apiVersion` in your `export.json` file to the latest version, as shown below:

```json
"apiVersion": "60.0"
```

Cheers.

**Comment by DDsalesforce141297** [comment]
Hi @hknokh,

Thanks a lot, it worked.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
