### ISSUE TITLE
[Feature Request] Mapping table for source and target fields

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#71]
It would be great if the user could have the ability to create a CSV similar to how field value mapping is done, to map source and target fields. This would open up the flexibility to use the tool to migrate data between two separate environments where field names are different.

For instance, something like:
SourceObjectName | TargetObjectName | SourceFieldName | TargetFieldName 
------------ | ------------- | ------------- | -------------
Case | CustomCase__c | CaseNumber | MigrationId__c

**Comment by hknokh** [comment]
@kevdo475 
Nice feature, thanks for the suggestion.

**Comment by hknokh** [comment]
Hello @kevdo475 
The custom field mapping was implemented
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.3.-Advanced-features.-Fields-Mapping.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.3.-Advanced-features.-Fields-Mapping.)
