### ISSUE TITLE
Is there an issue with the help.sfdmu.com site - Malwarebytes suddenly alerting RTP detection

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#712]
Today when visting https://help.sfdmu.com Malwarebytes v 4.6.13 (latest) is blocking the site and indicating an RTP detection. Location 173.214.170.82. Event details say Malware and Compromised.

**Comment by hknokh2** [comment]
Hey.
It's the correct new IP. No any issues, I've moved the website from heroku to regular webhosting of (https://www.interserver.net/). It's their public web address for webhosting, maybe it's become compromised somewhere. don't know. 
I will  concider to buy a dedicated IP for the sfdmu through.
Regards.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Comment by hknokh2** [comment]
Additionally, I will let you know when will change the IP to a clean one.

**Comment by veaux** [comment]
Ok. I largely posted since I ended up not going to the Help site because of the warnings so thought others may as well. My Malwarebytes is just set at the defaults and it blocked me from visiting unless I overrode the suggestion...which I didn't.

**Comment by hknokh2** [comment]
Ok, thx for the alert. I wrote to the hosting support and switching ip is in progress.

**Comment by hknokh2** [comment]
@veaux 
The issue has been resolved, it's switched to 216.158.238.100
Please check on your side
