### ISSUE TITLE
[Feature Request] Handle RecordType.DeveloperName in addition to RecordTypeId

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#72]
It would be great if the tool could allow for `RecordType.DeveloperName` to be set when retrieving and loading records. If this is done together with the existing automatic CSV source transformation, then it would open up the possibility to migrate data between orgs where the record types have different naming.

**Comment by hknokh** [comment]
@kevdo475 Thank you for the suggestion. 
I am putting it in the milestone.

**Comment by hknokh** [comment]
@kevdo475 
Do you mean to add an option for another csv configuration file to describe the mapping between the source RT name and the target one? For example the source RT name is: "TheSourceAccountRT" and the same RT on the target is named "TheTargetAccountRT".  Is this what you mean?

**Comment by kevdo475** [comment]
Yes. I mean if the RT name or developer name can be used it could potentially be in the same configuration file as for normal fields (Value Mapping.csv).

**Comment by hknokh** [comment]
Hello @kevdo475 
It is implemented. You can use record type mapping as in the example:

**ObjectName,FieldName,RawValue,Value
Account,RecordType.DeveloperName,TestAccountRT;Account,TestAccountRT2;Account**

Consider putting Name of the object after the semicolon for the values.

**Comment by SiLuLuLu** [comment]
Hi @hknokh , I didn't quite understand the feature for recordType.
In the source org I have a RT developername is Complaint, but in taget org the developer name is CustomerComplaint.

I have the export.json and the ValueMapping.csv
`{
    "objects": [
        {
            "operation": "Insert",
			"useCSVValuesMapping": true,
            "useValuesMapping": true,
            "query": "SELECT Id,RecordTypeId,CurrencyIsoCode,SeqensId__c,Status,Origin FROM Case WHERE recordTypeId In (Select Id from RecordType where sObjectType='Case' and name = 'Complaint')"
        }
    ],
    "promptOnMissingParentObjects": false,
    "promptOnIssuesInCSVFiles": false
}`

ObjectName,FieldName,RawValue,Value
Case,RecordType.DeveloperName,Complaint;Case,CustomerComplaint;Case

But it always created in Rt default, am i missing something ?
Thank you
