### ISSUE TITLE
[FEATURE REQUEST]-Ability to have a mapping of old (source) SF IDs and new (target) SF IDs

### ISSUE THREAD

**Issue by akingumusel** [forcedotcom/SFDX-Data-Move-Utility#729]
**Is your feature request related to a problem? Please describe.**
When data is migrated from one production org to another, there is also the need of updating all external systems that store a reference to the records. While we are able to create external id fields in some objects and store it there via a transformation, it is not always the case for certain OOTB objects (not exposed to Object Manager)

Hence it is crucial to have the mapping of source Saleforce IDs and target Salesforce IDs, so that;
- References can be updated in satellite systems.
- The reporting/analytics part can be merged if this is a Production to Production migration.

**Describe the solution you'd like**
When "**createTargetCSVFiles**" option is enabled in the export.json, it creates the csv files storing the data, new Salesforce IDs, as well as any Errors that happened for that row during the migration.
Additionally, another column can be added to these CSV files, like "[Old Id]" to have the direct mapping at the row level.

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
I will take a look at your case and let you know if there are any updates.
Cheers.

**Comment by hknokh** [comment]
Hello.

Thank you for your contribution!

I have placed your suggestion on my roadmap and I'm closing it for now. 
While I can't guarantee when or if it will be implemented, please stay tuned for future updates.

Thank you for your support.

Regards.
