### ISSUE TITLE
[QUESTION] - Field Mapping is not working for ID field 

### ISSUE THREAD

**Issue by ruqianq** [forcedotcom/SFDX-Data-Move-Utility#747]
This question is related to [https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/282](url), even though it marked as closed, but I dont see the confirmation.  
I am trying to do the same load the legacy id into target org on different field under the same object.  I am using simple insert operation, no need to do comparison.  However, the legacy id field would got override by the ID.  Apparently it start with the insert, then conduct an update, dont know why this is happening.  Here is my code:

{
            "operation": "Insert",
            "useFieldMapping": true,
            "query": "select Description, Fax, Id, Name, Phone, ParentId  from Account"
}

fieldMapping.csv
ObjectName,FieldName,Target
Account,,Account
Account,Id,Legacy_Id__c

<img width="353" alt="Screenshot 2024-05-01 at 4 49 10 PM" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/8145994/f07d3d76-c15f-473d-a050-1349f3546c1c">

**Comment by hknokh** [comment]
Hello, @ruqianq

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by ruqianq** [comment]
Hi I think I found out the root cause, and in fact my query miss one field 'ParentId' somehow that trigger the update after insert.

**Comment by hknokh2** [comment]
Hello,

You can find a detailed response to your question in this article:
- [Fields Mapping: Mapping External ID Field](https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping#mapping-external-id-field)

I've also updated the relevant issue that you mentioned. 
I hope this helps. Please let me know if you need further assistance.

Regards.

**Comment by hknokh2** [comment]
By the way, I highly recommend using my [SFDMU GUI Desktop App](https://github.com/forcedotcom/SFDX-Data-Move-Utility-Desktop-App). It can really help you with configuring field mapping, creating and managing your export.json file, and launching jobs in general.

**Comment by hknokh2** [comment]
Do you use objectSets?

**Comment by ruqianq** [comment]
correct
