### ISSUE TITLE
[QUESTION] -  Data Anonymization patterns not available

### ISSUE THREAD

**Issue by PotSeht** [forcedotcom/SFDX-Data-Move-Utility#748]
Hi,

On the  [Data Anonymization page](https://help.sfdmu.com/full-documentation/advanced-features/data-anonymization), it _used_ to also provide either a link or a list of patterns available (cant recall).

I've also checked the [MockField page](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/mock-field-object), which just says _These patterns are usually provided by the anonymization tool or library._ which is not overly helpful.

This seems to have been removed since, could this be added back into the documentation?

Thanks!

**Comment by hknokh** [comment]
Hello, @PotSeht

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello,

Thank you for reporting the issue in my documentation. I have updated the relevant sections:

[Export JSON File Objects Specification: Mock Field Object](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/mock-field-object)
[Advanced Features: Data Anonymization](https://help.sfdmu.com/full-documentation/advanced-features/data-anonymization)
I hope this helps. Please let me know if there's anything else I can assist with.

Regards.

**Comment by PotSeht** [comment]
amazing, thank you!

**Comment by hknokh2** [comment]
You're welcome! I just fixed a misspelled link I found here.
