### ISSUE TITLE
[QUESTION] - ExportFiles Module Linked Entity ID Error 

### ISSUE THREAD

**Issue by ruqianq** [forcedotcom/SFDX-Data-Move-Utility#754]
Hi team, I ran into a problem when I want to migrate account with its related files
Here is the my code:
`{
    "simulationMode": true,
    "keepObjectOrderWhileExecute": true,
    "promptOnMissingParentObjects": false,
    "objects": [
        {
            "operation": "Upsert",
            "query": "SELECT Id, Name FROM Account where Id ='001DR00001XHANUYA5'",
            "externalId": "Name",
            "afterAddons" : [
                {
                    "module": "core:ExportFiles",
                    "args": {
                        "operation": "Insert"
                      }
                }
            ]
        }
    ]
}`

it outputs three files as below:
<img width="460" alt="Screenshot 2024-05-06 at 2 48 04 PM" src="https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/8145994/27cf7d8c-4732-4e76-8075-377c953f3c07">

however the ContentDocumentLink_insert_target.csv has the error:
ContentDocumentID,Errors,LinkedEntityID,ShareType,Visibility
069020000025WmjAAE,Linked **Entity ID: id value of incorrect type**: ZYHu43lPH5mcVyfl0H,ZYHu43lPH5mcVyfl0H,V,InternalUsers

One thing to note, the source org is classic and target org is lightning, I did enable the features to ensure the uploading are files not as attachments.  

Thanks!

**Comment by hknokh** [comment]
Hello, @ruqianq

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello
Core export files add on does not work in simulation mode.

**Comment by ruqianq** [comment]
Aha, good catch, here is the error after I turn off the simulation mode
ContentDocumentID,Errors,LinkedEntityID,ShareType,Visibility
069020000025WnKAAU,**Visibility InternalUsers is not permitted for this linked record.**,0010200000SDNi3AAH,V,InternalUsers

**Comment by hknokh2** [comment]
Check your permissions. 
Since this issue is not covered by our support policy, I'm unable to assist further. 
Apologies for any inconvenience.

**Comment by ruqianq** [comment]
No worries, thank you so much, I kinda have a feeling that might be the case.  Very appreciated your response.
