### ISSUE TITLE
[FEATURE REQUEST] - CPQ specific export/import scripts

### ISSUE THREAD

**Issue by rdehler** [forcedotcom/SFDX-Data-Move-Utility#757]
Salesforce CPQ has a predictable data model.  Numerous places recommend SFDX DMU as the solution to deal with CPQ data export (for backup and source control), as well as migration to subsequent environments.  It would be nice to see some guidance on how to perform these activities with prepackaged SBQQ specific queries.

**Comment by rdehler** [comment]
This would be a great starting point:
https://gist.github.com/JeroenSfdc/a8d15c725e14090b3413ac1f20d58b61

**Comment by hknokh** [comment]
Hello, @rdehler

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Hello,
I'm not very familiar with CPQ, so I can only add this configuration to the SFDMU knowledgebase with a few possible comments. I'll do that as soon as possible.
Regards.
