### ISSUE TITLE
[QUESTION] - Trying to connect to orgs in sfdmu macOs

### ISSUE THREAD

**Issue by SBitzenis** [forcedotcom/SFDX-Data-Move-Utility#765]
Hello, when clicking on "Detect available SFDX connections" i am getting an error :

Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path.

I tried already to add sf to /etc/paths file but I am still getting this error. any help appreciated !

**Comment by hknokh** [comment]
Hello, @SBitzenis

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by SBitzenis** [comment]
missed step 4 in macOs, where you have to open it from the terminal, my bad !
