### ISSUE TITLE
[QUESTION] - Change default workspace directory

### ISSUE THREAD

**Issue by SBitzenis** [forcedotcom/SFDX-Data-Move-Utility#766]
Currently when I create a workspace (macOs) the default workspace directory is under /var/root/Documents/sfdmu-gui-app/workspaces/...

The thing is that I don't have access to the root folder myself, and I haven't figured out a way to change that directory from within the GUI app. Is there something I can do to change the workspace default directory ?

**Comment by hknokh** [comment]
Hello, @SBitzenis

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hi
You need to adjust the app settings file.
Visit here:
https://help.sfdmu.com/sfdmu-gui-app#configuration-file-description
Take a look on the appRoot and dataRoot settings.
Please learn also there where you can find this file.
Regards.

**Comment by SBitzenis** [comment]
Thank you @hknokh for the prompt response and assistance !
