### ISSUE TITLE
[FEATURE-REQUEST] - Ability to adjust where clause for Group object

### ISSUE THREAD

**Issue by degnoskeVA** [forcedotcom/SFDX-Data-Move-Utility#778]
Hello, 
I know Group and User records aren't supported. But I noticed I was able to Insert GroupMember records when the type was 'Queue'
I read in the documentation that the default query for Group is "SELECT Id FROM Group WHERE Type = 'Queue'"
But I'm not sure if there is a way to overwrite this and switch it to Type = 'Regular'.

Appreciate any insight!

**Comment by hknokh** [comment]
Hello, @degnoskeVA

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by degnoskeVA** [comment]
Bump

**Comment by hknokh** [comment]
Hello,

I wanted to let you know that I am still reviewing your case and will inform you as soon as I have any updates. Due to my current time constraints, this process may take longer than usual.

Thank you for your patience and understanding.

Best regards

**Comment by hknokh** [comment]
Hello,

Thank you for your patience. Overriding the Group query is not supported; only the User query can be overridden. However, I've converted this into a feature request for further review. Please note that there is no guarantee that this update will be implemented. I will provide further updates if there are any developments.
I'm closing this case for now.

Best regards.

**Comment by twardegaSFDC** [comment]
Thank you for your feedback. My end goal is to facilitate creation of test user accounts with the necessary perm set/public group assignments in a multiple work-stream environment. Users and Public Groups can be moved outside of SFDMU but for the users/public groups moved - it would be great to have OOTB SFDMU support to do Public Group assignments not based on record ids from source system, e.g. using Public Group Name/Username. I understand that SFDMU does not currently support this OOTB and a custom solution is needed.
