### ISSUE TITLE
[FEATURE REQUEST] - Add filter on contentdocument / limit when using ExportFiles Core Add-On

### ISSUE THREAD

**Issue by jawills** [forcedotcom/SFDX-Data-Move-Utility#779]
When using the ExportFiles Core Add-On, I would like to be able to filter on the `ContentDocument` object, and not just the `ContentVersion` object. Ideally a limit and/or sort order can be applied to this filter.

Use case for this would be Conga Templates, where Conga only takes the most recently uploaded file. It is unclear to me how to transport the most recent file from the source org to the target org with the current status.
 
Ideally this is passed as an arg, like so:
```json
"afterAddons": [
  {
    "module": "core:ExportFiles",
    "args": {
      "operation": "Insert",
      "contentDocumentWhere": "ORDER BY CreatedDate ASC LIMIT 1 "
    }
  }
]
```

**Comment by hknokh** [comment]
Hello, @jawills

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh** [comment]
Your MR has been merged
