### ISSUE TITLE
[BUG] SFDMU run with --json generates output JSON with wrong format (not parseable)

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#784]
**Describe the bug**
Calling SFDMU run with --json parameter should generate the output in JSON. While trying to store the output in a file for further treatment, the file does not seem to have teh right format. There are special characters at the end of the JSON file which makes it impossible to parse later on

**To Reproduce**
Run SFDMU run command with --json parameter and store the result in a JSON file
`sf sfdmu run -s csvfile -u targetOrg -p ./scripts/sfdmu/someSfdmuFolder/ --noprompt --json >> ./result.json`
Open the result.json file and go to the end of the file. It contains special characters which makes it impossible to parse:
![CleanShot 2024-06-05 at 11 43 02@2x](https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/31279773/55cbc4c5-3132-4a5c-810f-6778847b801d)

**Expected behavior**
result.JSON file should be parseable (so no special characters at the end of the file

**export.json**
[export.json](https://github.com/user-attachments/files/15572835/export.json)

**Log file**
[2024-06-05__11_36_43.log](https://github.com/user-attachments/files/15572844/2024-06-05__11_36_43.log)

**_target.csv** file.
NA

**Comment by hknokh** [comment]
Hello, @jorgesolebur

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh** [comment]
Hello,

I wanted to let you know that I am still reviewing your case and will inform you as soon as I have any updates. Due to my current time constraints, this process may take longer than usual.

Thank you for your patience and understanding.

Best regards

**Comment by hknokh2** [comment]
Hello,
I investigated this issue, and unfortunately, I can't fix it. The --json flag uses a standard SFDX API method to print to stdout (whether it's the console or a file, as you specified), and it seems that it adds extra symbols at the end of the file. This behavior is outside of my control and appears to be a bug in the CLI. These extra symbols will need to be removed manually from the JSON file after it is created.

**Comment by hknokh2** [comment]
@mshanemc, can you see this issue? 
I'm using styledJSON method to print json into stdout.

**Comment by hknokh2** [comment]
@jorgesolebur If you need an execution log in json format, note that --json flag also produces .log file file in json format.
