### ISSUE TITLE
[BUG] - Incorrect comparison when comparing 2 Long Text Area fields between source CSV and target SF if the long text area includes the character "

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#788]
**Describe the bug**
SFDMU compares all fields from source and target in order to identify if there is a need to update/insert the target.
When SFDMU compares Long Text Area fields between Source = CSV and Target = Sandbox, and if the long text area field in Salesforce includes the character ", SFDMU does not correctly compare both fields. Reason been: 
- In the CSV file, the long text area field will include double character "" to represent the character "
- In SF sandbox, the long text area field will include only 1 character " to represent the character "

This is because the character " is special, and if we want to insert the character " into a text area field in Salesforce from a CSV file, we need to put it 2 times. 

**To Reproduce**
- Use any Text field from any object, and configure SFDMU to do UPSERT on that object
- Create a record in that object in SF, and fill in a value with " character. For instance 'This is character " is special'
- Use the SFDMU export.json file to export the data from that object into a CSV file. The TEXT field used will have this value in the CSV: "This is character **""** is special"
- Run again SFDMU with source as CSV and target as sandbox. We do not expect any UPDATE as we didn't change anything anything. However SFDMU will try to update the record in SF because teh text field is different in source and target

**Comment by hknokh** [comment]
Hello, @jorgesolebur

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh** [comment]
Hello,

I wanted to let you know that I am still reviewing your case and will inform you as soon as I have any updates. Due to my current time constraints, this process may take longer than usual.

Thank you for your patience and understanding.

Best regards

**Comment by hknokh2** [comment]
Hello
Can't reproduce. Used  SFDMU v4.35.0
**export.json**:
```json
{
    "objects": [
        {
            "query": "SELECT Id, TEST_TEXTBOX__c FROM Account WHERE Name = 'ACC_10000'",
            "operation": "Update",
            "externalId": "Name"
        }
    ]
}
```

**source org**:
![image](https://github.com/user-attachments/assets/94118add-7b81-4728-a46d-3da1051d597b)

**Account.csv**:
Id,IsPersonAccount,Name,TEST_TEXTBOX__c
0018d00000qoZ5EAAU,false,ACC_10000,"""test"""

**target org (after import csv)**
![image](https://github.com/user-attachments/assets/a49b9887-e978-4688-8373-b343ccb8950f)

**log file after the second update, when the first insert with special character is done**

```bash
UPDATING THE TARGET (STAGE 1) ...
 [11:55:38.735] {Account} Updating person Accounts and Contacts ...
 [11:55:38.735] {Account} 1 target records remained untouched, since they do not differ from the corresponding source records.
 [11:55:38.736] newLine
 [11:55:38.736] Nothing was updated.
 [11:55:38.736] newLine
```
