### ISSUE TITLE
Parent is not updating for Hierarchy Data Type

### ISSUE THREAD

**Issue by mramasubbareddy** [forcedotcom/SFDX-Data-Move-Utility#79]
Hi Team,
I am using this tool for SF Data Migration and it's more useful. I am trying to migrate Account Object Data from one Org to another Org. While exporting Account object data Parent Id is not updating in the target org.

**SOQL Query: SELECT Name,Parent.External_ID__c,Parent.Id from Account**

**Comment by hknokh** [comment]
Hello @mramasubbareddy 

Your query is not correct.

You can't use compound fields such as Parent.External_ID__c and Parent.Id in your query, only original sobject's fields can be used (without dot).

Assume, your unique external id field across both the Source and the Target envs is **External_ID _c**, so to Insert Accounts along with their parents you can use something like this:

{
    "objects": [
        {
            "query" : "SELECT Name, ParentId FROM Account",
            "operation": "Insert",
            "externalId": "External_ID__c"
        }
    ]
}

To update or upsert existing records just change the **operation** parameter to Update or Upsert respectively.

Hope this will help!

**Comment by mramasubbareddy** [comment]
Hi @hknokh,

Thanks for the response. Initially i have used ParentId column alone  but i am facing error saying MissingParentRecords. Now i have changed my query as follows and started working.

{
"objects": [
{
"query" : "SELECT Name, ParentId,Parent.External_ID__c FROM Account",
"operation": "Insert",
"externalId": "External_ID__c"
}
]
}

**Comment by hknokh** [comment]
@mramasubbareddy 
Cool! 
But it is a little bit weird because it should add Parent.External_ID__c internally at the runtime so you don't need to add this yourself with the SOQL due to this is external id for the Account. 
I have make a check.

**Comment by hknokh** [comment]
Hello @mramasubbareddy 
I re-checked it and understand what is happening.
You probably tried to perform Update when the Target was empty and the plugin coud not find what to update.
So you get missing parent records issue means that there is no matching records on the Target side to update.
Could you make another check with this:
{
"objects": [
{
"query" : "SELECT Name, ParentId FROM Account",
"operation": "Upsert",
"externalId": "External_ID__c"
}
]
}
**Upsert** will check if the records exists in the Target and will automatically Insert/Update what's needed.
And you don't need Parent.External_ID__c 
Tell me if it is working.
Thanks
