### ISSUE TITLE
[QUESTION] - Use new Record Ids in transformation

### ISSUE THREAD

**Issue by Libertha** [forcedotcom/SFDX-Data-Move-Utility#790]
Goal:
migrate records from one production to another production and transform a key that contain some recordIds combined.

Issue:
We need the newly created recordIds to be used in the transformation to build the key. However the transform will only use old recordids and not the recordIds of the newly created records.

Example:
OLD ORG
Unique_Key__c = {oldrecordId1}{oldrecordId2}{oldrecordId3}

NEW ORG
Unique_Key__c = {newrecordId1}{newrecordId2}{newrecordId3}

export.json:
{
    "objects": [
        {
            "operation": "Upsert",
            "query": "SELECT Old_Quote_Id__c FROM Quote WHERE Old_Quote_Id__c = '0Q0W5000004lFkTKAU'",
            "externalId": "Old_Quote_Id__c",
            "afterAddons": [
                {
                    "module": "core:ExportFiles"
                }
            ]
        },
        {
            "operation": "Readonly",
            "query": "SELECT all FROM Survey_Question__c",
            "externalId": "Lift_Survey__r.Name;Name"
        },
        {
            "operation": "Readonly",
            "query": "SELECT all FROM Survey_Question_Option__c",
            "externalId": "Survey_Question__r.Lift_Survey__r.Name;Survey_Question__r.Name;Name"
        },
        {
            "operation": "Upsert",
            "query": "SELECT all FROM Survey_Response__c WHERE Quote__r.Old_Quote_Id__c = '0Q0W5000004lFkTKAU'",
            "externalId": "Name",
            "afterAddons": [
                {
                    "module": "core:ExportFiles"
                }
            ]
        },
        {
            "operation": "Upsert",
            "query": "SELECT all FROM Survey_Answer__c WHERE Survey_Response__r.Quote__r.Old_Quote_Id__c = '0Q0W5000004lFkTKAU'",
            "externalId": "Name"
        }
    ],
    "dataRetrievedAddons": [
        {
            "module": "core:RecordsTransform",
            "args": {
                "fields": [
                    {
                        "alias": "responseId",
                        "sourceObject": "Survey_Answer__c",
                        "sourceField": "Survey_Response__c"
                    },
                    {
                        "alias": "questionId",
                        "sourceObject": "Survey_Answer__c",
                        "sourceField": "Survey_Question__c"
                    },
                    {
                        "alias": "optionId",
                        "sourceObject": "Survey_Answer__c",
                        "sourceField": "Answer_Option__c"
                    }
                ],
                "transformations": [
                    {
                        "targetObject": "Survey_Answer__c",
                        "targetField": "Unique_Key__c",
                        "formula": "formula.responseId + formula.questionId + formula.optionId "
                    }
                ]
            }
        }
    ]
}

**Comment by hknokh** [comment]
Hello,

The purpose of the core:RecordsTransform module is to build compound source values to update target records, rather than to modify target records based on other target records. 
Therefore, your goal cannot be accomplished using this module.

Regards

**Comment by hknokh** [comment]
Arranged as a feature request:

https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/792

**Comment by Libertha** [comment]
@hknokh thank you for investigating.

I thought it might work the same way as it works to do the lookup updates which happens after an insert for example.
So it would be more of a "post processing" where you can transform the newly created records and then be taken into the update.

Do you have any suggestions in how i could accomplish this? or it is just not possible with sfdmu?

**Comment by hknokh2** [comment]
It technically can't be post-processing because the transformation is applied during the normal object update cycle. Using an add-on to modify records after the target records are ready would require an extra update to the target with the transformation result, which is not possible. I hope you understand the technical obstacle preventing me from adapting the module to your use case. We need to think about another approach using different SFDMU features or a set of features.

**Comment by hknokh2** [comment]
Again, I will see if I can do something but it can take a while.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
