### ISSUE TITLE
[FEATURE REQUEST] - Fields skipped if user does not have access

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#793]
**Describe the bug**

Wen we run an export or an import, if the current user does not have explicit rights on fields (using Profiles or PSets), the field values are skipped and there is no error or warning anywhere

**Expected behavior**

We could either have:
- a message in output telling that some field values have been skipped
- an option --skiplfs that would not remove values in case the user does not have explicit  rights (like for when the user is System Administrator)

Would it be possible to implement such evolution to simplify the use and troubleshooting of SFDMU ?

Thanks :)

**Comment by hknokh** [comment]
Hello, @nvuillam

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh** [comment]
Hello, Nicolas

I wanted to let you know that I am currently still reviewing your case and will inform you as soon as I have any updates. 
Due to my current time constraints It can take a while.
Thank you for your patience and understanding.

Best regards.

**Comment by hknokh** [comment]
I believe the skipped fields are already reported in the log, but I need to verify the logging. In any case, the most efficient solution is to ensure that skipped fields are reported in the log.

**Comment by nvuillam** [comment]
@hknokh thanks, it will help a lot :)
In the console log they are not visible, i noticed it by seing empty columns in the CSV log

**Comment by hknokh** [comment]
Hi

Thank you for your feature request. I am closing this issue for now. I will review the feature request at a later time, but please note that there is no guarantee that this update will be implemented. I will provide further updates if there are any developments.

Best regards.

**Comment by nvuillam** [comment]
@hknokh that would really be a game changer for SFDMU, making it much more reliable, especially related to import in production org, I pray you to really consider such enhancement :)
