### ISSUE TITLE
Geolocation and Address Data Type Data not updating in Target Org

### ISSUE THREAD

**Issue by mramasubbareddy** [forcedotcom/SFDX-Data-Move-Utility#80]
Hi Team,

I am trying to migrate BillingAddress and Lat_and_Long__c fields data from one org to another org.  BillingAddress and Lat_and_Long__c field data not updating in target org.

Field Name | DataType
-- | --
BillingAddress | Address
Lat_and_Long__c | Geolocation

**SOQL Query:**

{
        "query": "SELECT Name,External_ID__c,BillingAddress,Lat_and_Long__c from Account",
        "operation": "Upsert",
        "externalId": "External_ID__c",
        "allRecords": true
}

please help

**Comment by mramasubbareddy** [comment]
Hi @hknokh,

Thanks. I have tried the same its working fine. Can we have handle this internally?.  I mean whenever we give BillingAddress in the query can we form query internally with BillingStreet, BillingCity etc columns?.

**Comment by hknokh** [comment]
It is possible but I am just curious why it is so necessary for you, I mean having address fields handled internally, not having split into the parts manually in the SOQL?..

**Comment by mramasubbareddy** [comment]
it will be helpful. Sometime new people to the tool may not aware of splitting into the parts in the SOQL  and simply they will give actual field name the query and they will struggle to find the solution.  i would suggest this as nice to have feature.

**Comment by hknokh** [comment]
ok, understand, thank you!

**Comment by hknokh** [comment]
Hello @mramasubbareddy 
The BillingAddress, ShippingAddress, MailingAddress feature is implemented. 
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.2.-Advanced-features.-Compound-Fields.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/4.2.-Advanced-features.-Compound-Fields.)

**Comment by mramasubbareddy** [comment]
Thanks @hknokh
