### ISSUE TITLE
[QUESTION] - Have multiple queries for 1 object (account) and then pull contacts for all those

### ISSUE THREAD

**Issue by riekusr** [forcedotcom/SFDX-Data-Move-Utility#804]
I want to create a usable sample set, therefore i want to grab 100 accounts from each type for example. 

Example for accounts I want 200 total, 100 of each type: 
Select Id, Name from Account WHERE type='1' limit 100
Select Id, Name from Account WHERE type ='2' limit 100

Then I want to have all contacts of the fetched accounts. 

What works: 
- Creating objectSets with the Accoutn query and contact query (master false) in 1 objects array

But this means It isn't very modulair and I need to repeat a lot more objects for every 'type' of account. 

Is there a way to run Account queries first, and then reference the fetched accounts to do the rest of the related operations?

**Comment by hknokh** [comment]
Hello, @riekusr

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello
No it's not possible.
Each object set acts as an independent job within a specific run.
