### ISSUE TITLE
[QUESTION] - Ability to load GroupMember records using SFDMU

### ISSUE THREAD

**Issue by twardegaSFDC** [forcedotcom/SFDX-Data-Move-Utility#811]
**Is your feature request related to a problem? Please describe.**
After I load User records and Group records using Data Loader (since User and Group records cannot be loaded using SFDMU), I would like to load GroupMember records using a CSV file, or directly from another environment.

**Describe the solution you'd like**
I would like to be able to specify external Id as in the section below, and load GroupMember records after I load Group and User records using Data Loader:
                {
                    "query": "SELECT Id, GroupId, UserOrGroupId FROM GroupMember",
                    "operation": "Upsert",
                    "externalId": "UserOrGroup.Name;Group.Name"
                }

At present loading of GroupMembers does not appear to use extern Id as specified - Groups and Users with matching names have been created in target environment using the Data Loader.

**Comment by hknokh** [comment]
Hello, @twardegaSFDC

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by twardegaSFDC** [comment]
Hi, 
Looks that the case will be closed in the next 3 days. If you have some advice how to load GroupMember records using external ids from Group and User tables (e.g. Name field), instead of depending on Salesforce record ids I will really appreciate it.
Tom

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out to me. Based on the information you've provided, it appears that this is not a bug related to the Plugin.

For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/ or check the developer forums.

Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.

In your specific case, you can try to adapt columns generated by the DataLoader to import with SFDMU. Note that the Data Loader does not support relationships. I suggest you use SFDMU both for import and export.

Thank you for your understanding and cooperation.

Regards.

**Comment by hknokh** [comment]
After double-checking the issue:

Group members can already be loaded by SFDMU. However, you still need to adapt your CSV to align with the format supported by SFDMU for loading related records. You must add an extra lookup or external ID column linked to the existing Group records.

**Comment by degnoskeVA** [comment]
Just to save you some time @twardegaSFDC, as I also recently had a similar question. It's worth noting that GroupMember records are currently only supported for Queues, not Public Groups.
Feature Request: https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/778
