### ISSUE TITLE
[QUESTION] - SFDMU Populating the wrong lookup relationship due to multiple lookup options

### ISSUE THREAD

**Issue by mmoya-cloudteam** [forcedotcom/SFDX-Data-Move-Utility#812]
- I am trying to insert "RecordsX", which has a lookup to "Period". If I do a SOQL query to "Period" by the name "2024/004", I will get multiple results. When retreving the records for the later insertion, SFDMU is populating the ID of "Period" with the first result, however this is not correct. I have edited the CSV files to use the correct lookup ID, but still sfdmu is overriding the lookup Id in the `target` folder. Additionally, I have tried using `"importCSVFilesAsIs": true`, but it didn't work. What is the way to override the lookup Id in the CSV?

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out to me. Based on the information you've provided, it appears that this is not a bug related to the Plugin.

For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/ or check the developer forums.

Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.

Thank you for your understanding and cooperation.

Regards.
