### ISSUE TITLE
[QUESTION] - UNABLE_TO_LOCK_ROW issue

### ISSUE THREAD

**Issue by ruqianq** [forcedotcom/SFDX-Data-Move-Utility#814]
Hi team,

Do you run into this issue in SFDMU? 
UNABLE_TO_LOCK_ROW:unable to obtain exclusive access to this record or 1 records
I was migrating 50000 Cases from prod to a UAT sandbox, however, most of the record failed on this error.  Any thoughts?

Thank you!

**Comment by hknokh** [comment]
Hello, @ruqianq

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out to me. Based on the information you've provided, it appears that this is not a bug related to the Plugin.

For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/ or check the developer forums.

Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.

Thank you for your understanding and cooperation.

Regards.
