### ISSUE TITLE
[QUESTION-GUI] - SF CLI is no longer detected

### ISSUE THREAD

**Issue by bdJohnson72** [forcedotcom/SFDX-Data-Move-Utility#819]
I love the GUI app and a session working and configured. Then it stopped detecting my CLI. When I get to the congifuration step and select > Detect Available SFDX connections. I get the error "Failed to Execute the command...."Check whether the CLI is installed.."

I know I have the SF CLI installed, and it was working, but then it stopped. 

And thank you for this amazing tool!

**Comment by hknokh** [comment]
Hello, @bdJohnson72

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello
May I know which version of the gui are you currently using?

**Comment by bdJohnson72** [comment]
I am using 4.6.0

**Comment by mrcdsouza** [comment]
I had the same issue when running the app via the icon on Mac OS. Once I ran the application from the command line (/Applications/sfdmu-gui-app.app/Contents/MacOS/sfdmu-gui-app) , it was able to detect sf and find my connections. I did have the sf executable in my PATH.

**Comment by hknokh2** [comment]
Thanks, @mrcdsouza 
Yes. That's correct. You need to run this application properly exactly as described in the doc, not via the icon. The main application entry had no necessary permissions for sfdx cli.

**Comment by bdJohnson72** [comment]
That worked sorry for the late response. I was away for a bit. Not sure how I ever got it working.  Thank you for the help
