### ISSUE TITLE
Specify Operation in Configuration File

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#820]
Firstly, let me thank you for the many productive improvements in the recent release of the GUI app. I was able to use it to create an export.json. However, I might be missing something as I did not see where I can specify an INSERT/UPSERT/DELETE in the GUI.I had to manually edit the export.json to add the "operation" member.

**Comment by hknokh** [comment]
Hello, @mrcdsouza

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by mrcdsouza** [comment]
Most welcome @hknokh No rush as I can manually edit the export.json. I wasn't sure if I was missing some operation setting in the new GUI. I was very familiar with the previous GUI.

**Comment by mrcdsouza** [comment]
I was able to find the Operation option which is under Queries & Filters.
