### ISSUE TITLE
[GUI-BUG] - Incorrect Data displayed in Query Test Result

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#821]
In the GUI, for number fields Level__c and Order_By__c, a Date Value is displayed instead of a integer:

<img width="937" alt="image" src="https://github.com/user-attachments/assets/8451964f-c23d-4b04-acaa-8e50c20df433">

here is the data in SOQLXplorer:

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/9c8e93ac-59ab-49b9-ac32-10a77647cbfa">

**Comment by hknokh** [comment]
Hello, @mrcdsouza

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh** [comment]
@mrcdsouza 
This issue has been fixed since v4.8.1

**Comment by mrcdsouza** [comment]
Thank you for the fix and for your great data migration application.

[A black and green logo  Description automatically generated]<http://www.ptc.com/>

Carlton D’Souza
Director – Solution Demo Engineering

(845) 262-3468
***@***.******@***.***>
ptc.com<http://www.ptc.com/>


From: Haim Knokh ***@***.***>
Date: Tuesday, August 13, 2024 at 10:03 AM
To: forcedotcom/SFDX-Data-Move-Utility ***@***.***>
Cc: D'Souza, Carlton ***@***.***>, Mention ***@***.***>
Subject: Re: [forcedotcom/SFDX-Data-Move-Utility] [GUI-BUG] - Incorrect Data displayed in Query Test Result (Issue #821)

@mrcdsouza<https://github.com/mrcdsouza>
This issue has been fixed since v4.8.1

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
