### ISSUE TITLE
Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path - MacOs Sonoma

### ISSUE THREAD

**Issue by Matiaserodriguez** [forcedotcom/SFDX-Data-Move-Utility#845]
Hi! I have my Macbook pro M1 with Sonoma 14.5, and the GUI app isn't recognizing the sfdx-cli.
The error that pops up under connection says:

"Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path."

The logs are:
⇨ LOG MESSAGE:WARNING: [index.controller.js:189] Error refreshing connections: Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path.
⇨ LOG MESSAGE:INFO: [index.controller.js:185] Refreshing connections...
⇨ LOG MESSAGE:INFO: [sfdmu-service.js:49] Looking for the available SFDX orgs...
⇨ LOG MESSAGE:INFO: [sfdmu-service.js:26] Executing the CLI command sf org list --json...
⇨ LOG MESSAGE:INFO: [console-service.js:88] Command sf org list --json is starting to execute...
⇨ LOG MESSAGE:INFO: [console-service.js:133] Command sf org list --json is exited with code 127.
⇨ LOG MESSAGE:WARNING: [sfdmu-service.js:29] Failed to execute the command sf org list --json.
⇨ LOG MESSAGE:WARNING: [sfdmu-service.js:81] Unable to retrieve the list of SFDX orgs due to: Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path.
⇨ LOG MESSAGE:WARNING: [index.controller.js:189] Error refreshing connections: Failed to execute SFDX command. Check whether sfdx-cli is installed and available in the system path.

I've already added the path to the CLI to my .zshrc folder. Also, I'm able to run the command: sf org list --json, and get back the org list from the terminal. 

Not sure how to fix the issue. Any help? Thanks!

**Comment by hknokh** [comment]
Hello, @Matiaserodriguez

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hey
Please refer here
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/819

**Comment by Matiaserodriguez** [comment]
I understand. It was solved by running it from the terminal as stated in the documentation:
/Applications/sfdmu-gui-app.app/Contents/MacOS/sfdmu-gui-app

Thank you very much!

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
