### ISSUE TITLE
[QUESTION] - Does the plugin will read all the records for the master slave objects in export json  from source and target org for migration?

### ISSUE THREAD

**Issue by kvenkatasivareddy** [forcedotcom/SFDX-Data-Move-Utility#849]
Hi Team, 

Does the plugin will read all the records for the master slave objects in export json for migration process?

Example scenario:

Export.Json [exportjson.txt](https://github.com/user-attachments/files/16508656/exportjson.txt)

Logs: 
[logs.txt](https://github.com/user-attachments/files/16508838/logs.txt)

I'm trying to update the 1 Asset record from source to target. The child lookup object wasn't added to export json. And the plugin is executing the lookup objects which not as part of export json with Readonly operation. 

In my case it is `SBQQ__QuoteLine__c` object which is being referenced by Asset object with fieldname as `Quote_Line_Lookup__c`. The `SBQQ__QuoteLine__c` object has around 8 million records. 

10:24:59.782] {SBQQ__QuoteLine__c} Fetching the Target data from Org (STAGE 2: all records) ...
[10:24:59.782] {SBQQ__QuoteLine__c} Query string: SELECT Id, Name  FROM  SBQQ__QuoteLine__c.
[10:24:59.782] {SBQQ__QuoteLine__c} Using Bulk API Query to retrieve the data ...

Failing with polling timeout error. 

As per my understanding, the plugin should read only the parent(Asset object) related records for the `SBQQ__QuoteLine__c` object instead of reading whole 8 million records.

Can you help me to understand the issue here?

Thanks in advance :)

**Comment by hknokh** [comment]
Hello, @kvenkatasivareddy

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello
In order to read all records specified by the object's query you should set master=true for the desired object

**Comment by kvenkatasivareddy** [comment]
@hknokh thanks for the quick reply.

How do we limit the records being pulled from child/reference objects, since my understanding is that the where conditions or limits do not apply to the Object where master is false. And it instead gets picked up based on the external Id.

**Comment by hknokh2** [comment]
The first way is: 
Put master=true on every child object, and then you can try to arrange the query to select all the child records you need.

The second way is: 
Create a formula field for the Asset object that concatenates the fields of Name and Asset_ID__c, then use this field as an external ID for the Asset object. This will avoid blocking the automatic selection of related records by SFDMU.

**Comment by kvenkatasivareddy** [comment]
@hknokh correct me if my understanding is wrong.

Below log is where it first checks for the count of records. This is to decide on the API to be used (Rest or Bulk)
```
"ANALYSING DATA...",
    "[12:58:50.664] {Product2} The original query string of this object is returning 308 records from the Source org.",
    "[12:58:50.890] {Product2} The original query string of this object is returning 2894 records from the Target org.",
    "[12:58:51.40] {Pricebook2} The original query string of this object is returning 13 records from the Source org.",
    "[12:58:51.184] {Pricebook2} The original query string of this object is returning 39 records from the Target org.",
    "[12:58:51.541] {PricebookEntry} The original query string of this object is returning 2 records from the Source org.",
    "[12:58:51.694] {PricebookEntry} The original query string of this object is returning 2 records from the Target org.",
```
As we saw yesterday, it pulls the correct number of records based on the main object and pulls correct references from Source.
  ```
"SOURCE:",
    "=============",
    "[12:58:51.697] newLine",
    "FETCHING THE DATA (STAGE 1) ...",
    "[12:58:51.698] {PricebookEntry} Fetching the Source data from Org (STAGE 1: all records) ...",
    "[12:58:51.698] {PricebookEntry} Query string: SELECT Id, IsActive, Pricebook2Id, Product2Id, UnitPrice, UseStandardPrice, $$Pricebook2.Name$Pricebook2.Description$Product2.Name$Product2.ExternalId$Product2.ProductCode$Product2.StockKeepingUnit, Pricebook2.$$Name$Description, Product2.$$Name$Exte... FROM  PricebookEntry WHERE Name = 'Opsera SDLC'.",
    "[12:58:51.703] {PricebookEntry} Using REST API to retrieve the data ...",
    "[12:58:51.899] {PricebookEntry} Data retrieval (Source) has been completed. Got 2 new records.",
```
Whereas from Target it pulls all the records
```
"TARGET:",
    "=============",
    "[12:58:52.267] {PricebookEntry} Fetching the Target data from Org (STAGE 2: all records) ...",
    "[12:58:52.267] {PricebookEntry} Query string: SELECT Id, IsActive, Pricebook2Id, Product2Id, UnitPrice, UseStandardPrice, $$Pricebook2.Name$Pricebook2.Description$Product2.Name$Product2.ExternalId$Product2.ProductCode$Product2.StockKeepingUnit, Pricebook2.$$Name$Description, Product2.$$Name$Exte... FROM  PricebookEntry WHERE Name = 'Opsera SDLC'.",
    "[12:58:52.268] {PricebookEntry} Using REST API to retrieve the data ...",
    "[12:58:52.448] {PricebookEntry} Data retrieval (Target) has been completed. Got 2 new records.",
    "[12:58:52.449] {Product2} Fetching the Target data from Org (STAGE 2: all records) ...",
    "[12:58:52.449] {Product2} Query string: SELECT Id, IsActive, Name, Description, DisplayUrl, ExternalId, Family, ProductCode, QuantityUnitOfMeasure, StockKeepingUnit, $$Name$ExternalId$ProductCode$StockKeepingUnit  FROM  Product2.",
    "[12:58:52.450] {Product2} Using REST API to retrieve the data ...",
    "[12:58:53.523] In progress... Completed 2001 records.",
    "[12:58:53.526] In progress... Completed 2894 records.",
    "[12:58:53.545] {Product2} Data retrieval (Target) has been completed. Got 2894 new records.",
    "[12:58:53.546] {Pricebook2} Fetching the Target data from Org (STAGE 2: all records) ...",
    "[12:58:53.546] {Pricebook2} Query string: SELECT Id, IsActive, Name, Description, $$Name$Description  FROM  Pricebook2.",
    "[12:58:53.546] {Pricebook2} Using REST API to retrieve the data ...",
    "[12:58:53.757] {Pricebook2} Data retrieval (Target) has been completed. Got 39 new records.",
    "[12:58:53.757] Data retrieval (STAGE 2) has been completed.",
```
Now this does not mean all records pulled are considered.
Instead it analyses and then it figures the records to update.

Now coming to the issue, I tried few options to ensure that all records are pulled, using below arguments
pollingQueryTimeoutMs  - to increase the time out. This is by default 4 mins.
But irrespective of giving a higher value, it always times out after 4 mins.
tried using Bulk API V1 with different batch count. and parallelBulkJobs
but felt like it didn't impact

**Comment by hknokh** [comment]
1. There are system restrictions for the polling timeout; you cannot set it to wait indefinitely.
2. But your issue is not with the polling timeout, but with the number of fetched records. You have over 800K records, which is too much and will likely cause a Node.js memory issue.
3. When analyzing the overall volume of records at the initial step, it always uses the original query string for each object. This record count is used to determine whether to use the bulk or REST API. However, when the records are actually fetched—specifically for `master=false` (child records)—it does not fetch all the records as calculated in the first step.
4. The only way to prevent fetching all records is to **not** use complex external IDs. Otherwise, as mentioned, it will pull all records and then work with a specific subset. The reason for pulling all records is that the tool cannot accurately calculate the dependent records when using compound external IDs, as it becomes a very complex task. Therefore, I decided to fetch all records.
5. SFDMU is primarily designed to be used with small data volumes and to automatically handle relationships between records. The main goal of this tool is to keep the data flow secure, with all data processed in memory. For large datasets, it's always better to use the standard Data Loader (though I haven't tested it with millions of records, and it might also fail to handle that )).

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
