### ISSUE TITLE
[FEATURE REQUEST] - Documentation update: Clearing field values

### ISSUE THREAD

**Issue by hvilminko** [forcedotcom/SFDX-Data-Move-Utility#851]
There was no "documentation bug report" kind of category here so I'm filing this as a feature request instead.

The help center site gives an example about clearing field values here:
https://help.sfdmu.com/examples/record-transformation#example-2-clear-all-text-fields-in-an-sobject

The problem is that this mockfield pattern does not actually work:
`"pattern": "c_set_value(null)"`

SFDMU uses the Bulk API by default so field updates with null values are just ignored. With Bulk API you need to use the "#N/A" syntax if you want to clear a field. So the correct syntax is:

` "pattern": "c_set_value('#N/A')"`

**Comment by hknokh** [comment]
Hello, @hvilminko

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Ok, thank you for letting me know about the error in the documentation. I will fix it.

**Comment by hknokh2** [comment]
@hvilminko, the documentation has been fixed.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
