### ISSUE TITLE
Please find the below question which I need the answer urgent. Please provide your answer ASAP

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#859]
- Ask your question or what kind of help you need.
Q1. Data transfer is there from source to destination ..has it been done through batches or patches?????

Q2. What is the list of all libraries used that are public with library owners? Please provide a detail.

Q3 . Where do we get patches and updates for this tool????

**Comment by SFDMUTOOL** [comment]
Hey @hknokh ,

Can u please provide your inputs, its very urgent for us.

**Comment by hknokh2** [comment]
1. The Gui app does not do data transfer, it only creates export.json and can run the plugin in console. Plugin does a direct data transfer from source to destination. Regarding batches / patches - don't understand the question.
. I can't provide you such list, need to fetch it using dependencies, using appropriate tools 
3. All updates from the official forcedotcom repo.

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

Regarding the Patches and batches means when we transferring the data from one org to another org the records will transfer in batch form or patch form .

**Comment by hknokh2** [comment]
Hey, sorry I don't know how the jsforce manages this.
