### ISSUE TITLE
Data Migration from Source Org to Destination Org

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#862]
Q1. Do we have another profile other then admin or the tool is govern by the different level of permission. While during the data migration from Source org to Destination org.

Q2. What Algorithm is used for SSL.

**Comment by hknokh** [comment]
Hello, @SFDMUTOOL

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
1. You can have a user with any level of permissions that has access to the sObjects and fields specified in the running `export.json`.
2. SFDMU uses the jsforce v1.11.1 library, which relies on the standard Node.js [request](https://www.npmjs.com/package/request) module. As my understanding, this module connects using TLS 1.3 by default, which is the current standard (refer to [Node.js TLS documentation](https://nodejs.org/api/tls.html)).

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

I would request you if you please provide any update on this it much appreciated we have a demo with our client day after tomorrow. 

Regards
Gourav  Narula
