### ISSUE TITLE
[QUESTION] - False Missing Parents Errors

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#863]
I am trying to migrate data of a custom object called Assets. This object has two self-joins Top_Level and Parent and a field Level which indicates the position of the Asset in the tree. I executed a data transfer of all Assets which ran successfully. I then ran a data transfer for all assets that have Top_Level != null. Unfortunately, the data transfer fails due to missing parents for Top_Level. However, when I check the missing parents data, these Top_Level Assets exist in the target org. I'm baffled as to why the sfdmu app doesn't find the Top_Level assets.

**Comment by hknokh** [comment]
Hello, @mrcdsouza

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers
