### ISSUE TITLE
General Query 

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#867]
Q1. How can I get the copy of source file while doing the migration from one  org to another org. 
Q2. In future if you stop this tool how you notify to us that this tool  we have stopped ? 
Q3. How you notify if you update the software version, licenses update and new libraries and new features u have added in this tool.

**Comment by SFDMUTOOL** [comment]
Hey @hknokh ,

Can u please provide the answer for the above question

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

Can you please provide any update on this 

Regards
Gourav Narula

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

We need answer of this question please provide the same. We need to demonstrate to our client

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
