### ISSUE TITLE
[QUESTION] - How to move object up or down in GUI app.

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#885]
I am unable to move objects in the GUI tool. The up and down arrows do not get enabled. Please advise. Thanks

**Comment by hknokh** [comment]
Hello, @mrcdsouza

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello,
Currently, it's not possible.
Generally, it's not necessary since the SFDMU reorders the objects at runtime during the job execution.

**Comment by mrcdsouza** [comment]
Thanks. So basically SFDMU reorders all masters before children. It's even smarter than I thought it was. 😃

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mrcdsouza** [comment]
> Hello, Currently, it's not possible. Generally, it's not necessary since the SFDMU reorders the objects at runtime during the job execution. Can I ask you what is your use case for such reordering in the export.json?

Regarding your question about the use case, may be I am not using the tool correctly but here's what i am currently doing: 

1. Migrate all the Master data
2. Turn all the Master entries to ReadOnly
3. Migrate all Level 1 children
4. Turn all the Level 1 entries to ReadOnly
5. Migrate all Level 2 children

As a result, I would like to group entries based on how I execute the process so that I do not have to scroll up and down the list of entries.

**Comment by hknokh2** [comment]
Hello.
You don't need to do that.
The tool handles relationships automatically. 
Just add parent lookup fields in child objects and run all objects at once.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
