### ISSUE TITLE
[FEATURE-REQUEST] - Stop migration job while receiving warning

### ISSUE THREAD

**Issue by alanjaouen** [forcedotcom/SFDX-Data-Move-Utility#888]
Hi 

## Question

Is there a way to configure an export so any received warning will result on an execution fail? (aka exit 1)

## Context

I setuped SFMDU at my company to automate datamigration and versioning (by using versionned csv export). 
We validate any change by running the import on a CI environement, but if there is migration error, the error is displayed as warning and sfdmu returns 0, making the error invisible if the logs are not checked

exemple
```
WARNING: [00:08:31.669] [WARN] [Batch# REST:Insert] {MyObject__c} Completed with issues. 200 records processed, 1 records failed.
[...]
[00:08:36.615] Command succeeded.
[00:08:36.615] Execution of the command sfdmu:run has been completed. Exit code 0 (SUCCESS).
```

**Comment by hknokh** [comment]
Hello, @alanjaouen

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh** [comment]
Hello,
Thank you for your suggestion. I’ve added a new flag to treat warnings as errors to the implementation roadmap. 
I’ll update you once it’s completed.
For now, the case is closed and will be reopened when the update is ready.
Regards.

**Comment by jorgesolebur** [comment]
+1 - great idea
