### ISSUE TITLE
Auto-number fields ignored when used as sourceField in fieldMapping

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#89]
If an auto-number field is used as a sourceField in a fieldMapping, it's ignored when trying to use it to set a new targetField.

My scenario:
I want to use `Case.CaseNumber` from my source as an external Id in my target. Here's a simplified version of how cases are set up in my export.json:
```
{
    "query": "select CaseNumber from Case",
    "operation": "Upsert",
    "externalId": "CaseNumber",
    "useFieldMapping": true,
    "fieldMapping": [
        {
            "sourceField": "CaseNumber",
            "targetField": "MigrationID__c"
        }
    ]
}
```

**Comment by hknokh** [comment]
Hello @kevdo475 
The issue should be solved

**Comment by kevdo475** [comment]
Hi @hknokh, this bug has reappeared in the latest version of the plugin.

**Comment by hknokh** [comment]
Hi, @kevdo475 
The issue is solved again. I fixed another issue that caused the regression.

**Comment by hknokh** [comment]
Hi, @kevdo475 
Please re-check now from v3.4.15

**Comment by kevdo475** [comment]
@hknokh Works now, thanks!
