### ISSUE TITLE
[QUESTION] - Any idea what is the best way of mapping the mismatched fields between the orgs?

### ISSUE THREAD

**Issue by mohanta-pankaz** [forcedotcom/SFDX-Data-Move-Utility#896]
I have an object Partner Account which is having a lookup to Opportunity. 
On Source org the lookup API name is OpportunityLookup__c
But on Target org the lookup API name is Opportunity__c (API name is different)

```
{
    "objects": [
        {
            "query": "SELECT Id,Opportunity__c,OpportunityLookup__c FROM Partner_Account__c",
            "operation":"Upsert",
            "externalId":"X18_Record_ID__c",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Partner_Account__c"
                },
                {
                    "sourceField": "OpportunityLookup__c",
                    "targetField": "Opportunity__c"
                }
            ]
        }
    ]
}
```

I am getting below error : 

ERROR at Row:1:Column:166
Didn't understand relationship 'OpportunityLookup__r' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
[21:37:44.30] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).

**Comment by hknokh** [comment]
Hello, @mohanta-pankaz

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello,  
I noticed that you've included `Opportunity__c`, which is a target field, in your query string.  
When using field mapping, only the fields from the source should be included in the query string.  

Please refer to the **Additional Notes** here:  
[Additional Notes - Field Mapping](https://help.sfdmu.com/full-documentation/advanced-features/fields-mapping#additional-notes).

The source fields in the query are mapped internally to the specified target fields, so you'll need to remove `Opportunity__c` from the query.  

Hope this helps! 🙂

**Comment by mohanta-pankaz** [comment]
Thanks @hknokh2 for a quick response. I checked the load trying your suggestion but still I am getting the same error.
Below is my current setup query -

```
{
    "objects": [
        {
            "query": "SELECT Id, OpportunityLookup__c FROM  Partner_Account__c",
            "operation":"Upsert",
            "externalId":"X18_Record_ID__c",   
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Partner_Account__c"
                },
                {
                    "sourceField": "OpportunityLookup__c",
                    "targetField": "Opportunity__c"
                }
            ]
        }
    ]
}
```


Error : 

[11:36:22.831] [ERROR] Error during execution of the command: 
SELECT Id, Opportunity__c, OpportunityLookup__r.Name FROM Partner_Account__c
                           ^
ERROR at Row:1:Column:28
Didn't understand relationship 'OpportunityLookup__r' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
[11:36:22.833] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).

**Comment by hknokh2** [comment]
Ok, please provide full log file to examine, not just the piece showing the error.

**Comment by mohanta-pankaz** [comment]
[2024-10-01__11_34_55.log](https://github.com/user-attachments/files/17200140/2024-10-01__11_34_55.log)
Please find the attached log for reference

**Comment by mohanta-pankaz** [comment]
[2024-10-01__11_34_55.log](https://github.com/user-attachments/files/17200174/2024-10-01__11_34_55.log)
@hknokh2  Please find the attached log file for reference

**Comment by hknokh2** [comment]
Hello
Your issue with the query should be solved.
Please reinstall and check
Thanks

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
