### ISSUE TITLE
Trouble identifying test data without missing parent lookup records + MissingParentRecordsReport.csv empty

### ISSUE THREAD

**Issue by EliasLahham** [forcedotcom/SFDX-Data-Move-Utility#9]
I've been using this plugin in an attempt to have test data from one org populate any other org I spin up. Since I'm new to this plugin, I wasn't sure what the best way is to determine the test data I want from the source org. My method included selected around 15~ account ids as test data and adding a WHERE clause with all those ids in my query in the export.json. I then went to all the related records of those 15~ accounts and kept adding the ids of related records like contacts and other custom objects.

In the end my export.json had quite a few queries that hand picked specific ids. Creating the csvfile by using this method seemed to be ok as all the data checked out, but when moving the data from the source (csv) to my target org I kept on encountering missing parent lookup record errors almost constantly. The error message in the command line would say to check MissingParentRecordsReport.csv, but that never got populated. I also attempted looking at the SF jobs logs to see if that was any help, but I kept coming back to looking at my records one by one to find the culprits which is very time consuming. Long story short, is there an easier method of identifying data to export to the point where I'm not running into error after error/is there an easier method of identifying missing parent lookup records?

Another issue I had due to this is that some records were being inserted like my Accounts, but when it gets to contacts and a missing parent lookup record error happens it stops the insert process. However, those accounts that were inserted are still inserted in my target org so when I run the SFDMU command again I will have duplicate records. Is there a way to roll this back in case of an error so I don't have duplicate records being inserted every time I encounter an error?

**Comment by genoud** [comment]
Hello @EliasLahham 

For Missing Parent REcords, you need to set the flag `promptOnMissingParentObjects `to `false `in your `export.json`. Then you will have the file populated.

To prevent duplicate upon multiple run, use `Upsert `operation instead of `Insert`.

Regards

**Comment by hknokh** [comment]
Thank you for the response @genoud )

**Comment by hknokh** [comment]
@EliasLahham 
Regarding the empty MissingParentRecordsReport.csv file it should be fixed now. 
Please, let me know if you still have an error of missing lookups with empty report file.
Regards.
