### ISSUE TITLE
[QUESTION] - External-Id based on Name and SetupOwnerId$Profile for CustomSetting

### ISSUE THREAD

**Issue by Schuchie** [forcedotcom/SFDX-Data-Move-Utility#903]
Hey!

We are trying to migration Custom Settings. Custom Settings have always as SetupOwner. Which can be an Org or Profile. For our case we have Profiles only and we have used the Polymorphic Field as followed `SetupOwnerId$Profile`. Sadly we do not have a real unique field on our object. Also the Name of the settings is not fully unique. So is there an Option to use a combination of `SetupOwnerId$Profile` and the Name-Field as External-Id? That would be 100% unique, but Im unsure if that gets handled correctly.

Cheers
Nils

**Comment by hknokh** [comment]
Hello, @Schuchie

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by Schuchie** [comment]
Hey @hknokh,
any update?
Cheers
Nils

**Comment by hknokh** [comment]
Hello
Try to use `Name;SetupOwner.Name` as an external id for the CustomSettings objects.
Regards.

**Comment by Schuchie** [comment]
Hey @hknokh,
that behaves a little bit strange. When I'm adding this to the `export.json` and exporting from the org I would expect the SetupOwner.Name be pulled into the column external-column, but thats not happing:
```
{
            "query": "SELECT id, Name,SetupOwner.Name, SetupOwnerId$Profile FROM clm__TopLvlObjects__c",
            "operation": "Upsert",
            "externalId": "Name;SetupOwner.Name"
        },
```

I only get the name-value,but not the setupowner-name-value. 2 of the selected records have a profile attached and one has the org as setup owner.

**Comment by Schuchie** [comment]
@hknokh  any update?

**Comment by Schuchie** [comment]
*bump* @hknokh

**Comment by hknokh2** [comment]
Hello. 
Query string for objects dies not accept referenced fields separated by dot, like SetupIwner.Name, only the fields which are directly owned by the queried object. 
That is why such field will not be finally exported.
When you use complex external id the values from both fields are internally converted and merged in memory into a single field in a special format and used to compare records, but still not exported or elsehow affected the target org.
Cheers

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Comment by Schuchie** [comment]
Hey @hknokh,

I think there is still something not working correctly.
I've the following record setup and it still fails on the second upsert. SFDMU still tries to insert the second record. The first one gets upserted correctly.
![image](https://github.com/user-attachments/assets/101b455c-e7a3-42fe-9558-2e3d9bebd667)
