### ISSUE TITLE
[FEATURE REQUEST] - Add the option to use the externalId in ScriptObject Object to match records using case-sensitive or case-nonsensitive

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#907]
**Is your feature request related to a problem? Please describe.**
Currently when we use the externalId configuration parameter in ScriptObject Object to define an externalId, SFDMU matches the field values using case-sensitive all the time. This creates an issue if that externalId field is defined in Salesforce as case-nonsensitive. 

**Describe the solution you'd like**
Add an additional parameter externalIdIsCaseSensitive that can be defaulted to true (normal behaviour) but can be added in ScriptObject Object if we want to change that behaviour. If externalIdIsCaseSensitive = false, then SFDMU will compare records without take into account case-sensitive in the field defined in externalId

**Comment by hknokh** [comment]
Hello, @jorgesolebur

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh** [comment]
Hello,
Thanks for your suggestion! 
While it seems like a simple adjustment, it’s actually quite challenging to implement. There’s a risk of serious regression issues, especially with complex external IDs. The plugin’s case-sensitive architecture adds to the difficulty. So, I’m going to hold off on this for now.
Best regards.

**Comment by jorgesolebur** [comment]
Understand, no worries ! thanks anyways !
