### ISSUE TITLE
Nothing is getting copied to target org

### ISSUE THREAD

**Issue by adayIvey** [forcedotcom/SFDX-Data-Move-Utility#911]
I am not sure what is going on I am trying to copy opportunities between to sandboxes and I not the query returns data and it looks like data is being selected but nothing is being processed and I am not sure why.

I have included two logs, the first one I added a query limit of 2000 record the other does not, but it fails with this "Execution failed due to errors or warnings. Ensure SFDX CLI is installed, the plugin is in place, and review script and error logs for issues." on the screen but no details in the log.

I know you are busy but I could really use some help (I have included my processing logs)

[2024-10-21__09_40_23.log](https://github.com/user-attachments/files/17461826/2024-10-21__09_40_23.log)
[2024-10-21__09_54_58.log](https://github.com/user-attachments/files/17462010/2024-10-21__09_54_58.log)

**Comment by hknokh** [comment]
Hello, @adayIvey

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by adayIvey** [comment]
Thanks :)

**Comment by hknokh2** [comment]
Hey @adayIvey 
It seems like you're running into an insufficient heap memory issue. You can check out this link for more details:  
[Bulk API Query Management Limitations](https://help.sfdmu.com/faq/bulk-api-query-management/what-are-the-limitations-on-data-volume-processing).
I believe your Opportunity object might have too many fields to query. This guide might help:  
[JavaScript Heap Out of Memory Error Troubleshooting](https://help.sfdmu.com/troubleshooting/unexpected-behavior-errors/javascript-heap-out-of-memory-error).
If that doesn’t work, the only option might be to reduce the number of records or fields you're querying.
Regards

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
