### ISSUE TITLE
[QUESTION] - missing parent lookup records error displayed for no reason

### ISSUE THREAD

**Issue by JannisBernhardt** [forcedotcom/SFDX-Data-Move-Utility#929]
**Describe the bug**
While trying to migrate CPQ data (Product2 and SBQQ__ProductFeature__c, I always get the orror message "23 missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details."

**To Reproduce**
run SFDMU

**Comment by hknokh** [comment]
Hello, @JannisBernhardt

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh** [comment]
Hi,

This case is now closed. 
If you encounter any other bugs while using SFDMU, please don’t hesitate to reach out.

Regards.
