### ISSUE TITLE
[QUESTION] - Update/Upsert target file differs between SFDMU versions.

### ISSUE THREAD

**Issue by jack-bennett-osf** [forcedotcom/SFDX-Data-Move-Utility#930]
Not sure if this is a question or a bug, but we have noticed that when an update is run (either as an Update or Upsert operation in the export.json), the target file now differs on version 4.36.7.

As a test, I had a csv file to "update" a few existing Account records. I used the Upsert operation in the export.json file. Once the operation completed, the data was updated as expected in Salesforce, but the target file only referenced four columns: Errors, Id, ParentId and RecordTypeId.

Previous to upgrading to version 4.36.7, I was on version 4.36.0. When running the same "update/upsert" on the older version, i would get a target file that would generate with **all** of the columns that were stated in the csv previously. I have just tested this by downgrading to version 4.36.0 and works as I have just explained.

Is this a change that was expected for 4.36.7? If so, is there a way I can still have the target file generate the entire contents as it would in 4.36.0? This is integral to our current implementation, as another team consumes these target files using automated reconciliation and expects that the updated target files include **all** of the columns that they were originally expecting.

**Comment by hknokh** [comment]
Hello, @jack-bennett-osf

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by jack-bennett-osf** [comment]
Hi @hknokh, any updates on this?  Thanks :)

**Comment by hknokh2** [comment]
Hello,
I haven't made any changes affecting the target CSV files between versions 4.36.0 and 4.36.7, and I can't replicate the behavior you're describing on my end. 
Unfortunately, I don't have any specific suggestions beyond downgrading to the version that works correctly in your environment.
Regards.

**Comment by hknokh** [comment]
Hi,  
This case is now closed.  
If you have any suggestions on how to exactly reproduce this issue on my end, feel free to reach out.  
Regards.
