### ISSUE TITLE
[FEATURE REQUEST] - Extract Unique Records by External ID

### ISSUE THREAD

**Issue by PotSeht** [forcedotcom/SFDX-Data-Move-Utility#931]
Sometimes, we may be working with an org that has poor data quality, primarily, duplicate records.  Take the below example of three accounts, each with the same name.   Importantly, there is no other _writeable_ fields that can be used to distinguish one from another.

We may use this to seed data with production data, but disregard duplicated records.

Take the below example of three accounts with the same name.

![image](https://github.com/user-attachments/assets/d779a77f-3693-4e65-a4aa-91509cdbb93e)

If I run an Upsert using externalId : Name from this environment to a sandbox, the three records migrate across.   However, upon running the same command again, the result is five records.

I believe this is because at the point of the second run, the source and target is matching against one of the accounts, but not the other two.  So it updates one record, and creates two others, which at least seems to be true in some form from the isolated test I ran below.

![image](https://github.com/user-attachments/assets/b6a1c7ef-2715-450d-93b9-6978b5437896)

It would be helpful to only extract unique values based on the external ID supplied, so that only one record is migrated across and all child records use that single key to relate to.   E.g  3 accounts with 1 contact each, would result in the contacts all consolidating under the one unique account upon migration.  

My line of thinking was a parameter against ScriptObject that basicallly retrieves the first hit of each key and disregards the rest when querying.  

That being said Im unsure if my use case is common enough to warrant this feature request, please consider it though! 🙂

**Comment by hknokh** [comment]
Hello, @PotSeht

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Hello!

Thank you for your suggestion.

While this could be a useful improvement in some cases, I have a couple of concerns:

1. The main purpose of an external ID is to uniquely distinguish between records. If that’s not sufficient, you can use [[Composite External ID Keys](https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys)](https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys) to ensure uniqueness. Therefore, maintaining the uniqueness of external IDs is a responsibility to address at your end.

2. This enhancement is quite complex and could lead to unexpected regressions, which I would prefer to avoid.

For these reasons, I will not be implementing this feature request.

Best regards.

**Comment by PotSeht** [comment]
Hello @hknokh 

I appreciate considering the feature and understand your stance.  I have been using composite external keys which is definetely helpful, although ultimately it does require looking at the data (we have clients where multiple external references may be duplicated for some bizarre reason).

I have started performing a check such as  SELECT COUNT(ID), EXTID FROM SOBJECT GROUP BY EXTID HAVING COUNT(ID) > 1 which is a good indicator of whether the dataset contains duplicates across the one or more keys.
