### ISSUE TITLE
[QUESTION] - Error:  Could not locate this record in the API response

### ISSUE THREAD

**Issue by PotSeht** [forcedotcom/SFDX-Data-Move-Utility#932]
Hi there

I am getting this error **Could not locate this record in the API response** whilst migrating about 20k accounts from a production environment to a sandbox.  I am utilising the Bulk API 2.0 and am getting this error for a subset of records.

I dont see anything in the documentation that speaks to this specifically - Could you please give a little insight as to why this error might surface?   If I flip it to Bulk API V1.0 and reduce the v1batchsize it works fine, so perhaps volume is playing a role here?

Thank you!

**Comment by hknokh** [comment]
Hello, @PotSeht

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by jorgesolebur** [comment]
I am also receiving the same error recently. Is it a prasing issue on CSV ?

**Comment by jorgesolebur** [comment]
@PotSeht if this helps I realised i got this error because i was doing an upsert and some of the records didnt have any value in the ext id

**Comment by PotSeht** [comment]
Thank you @hknokh and @jorgesolebur.

I ended up using Bulk API V1 which removed the issue, but interestingly when I isolated my export json (I had numerous object sets and probably >20 objects), to just the Account/Contact objects, this issue disappeared using Bulk API V2.  I dont have anything that is reproducible at this stage but will keep an eye on it.  @jorgesolebur I believe I was using Account Name as an Ext ID, but will definetely keep this in mind in future.

**Comment by jorgesolebur** [comment]
Thanks for the trick. I upidated as well from v2 to v1 in another issue and it helped me to fix the issue. I think there is sometimes an issue where SFDMU does not wait for the job to be completed and starts with the next action (or maybe SF says it completed import but it was not really completed). But yeah this is also helping me! I am moving to v1 serial and it works, and worst case I can use REST API which is synchronous and that will work for sure
