### ISSUE TITLE
[QUESTION] How does SFDMU handles a slave object with several master objects ?

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/SFDX-Data-Move-Utility#933]
Assume the following situation: I have an export.json file with 3 objects: A, B, C. 
Object C has 1 lookup to A and 1 lookup to B.
Object A and B have their own query filters and are both defined as MASTERS
Object C does NOT have any query filter and is NOT defined as master (master = false)

Question: What will be the final set of records retrieved for object C ? My assumption, from the definitions of documentation, is that it should retrieve the MINIMAL scope - i.e. list of records that have a valid lookup to object A AND a valid lookup to object B (its not an OR but AND). 

However, while testing it, it's not working like this. I have the feeling it is either an OR or it just pulls ALL records from object C.

PS: Object A, B, C use a simple external ID (not composite) and the total number of records in object C is 7k records

**Comment by hknokh** [comment]
Hello, @jorgesolebur

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by jorgesolebur** [comment]
Adding an additional detail - objects A, B and C are in UPSERT mode (not sure if this has a difference in SFDMU behaviour)

**Comment by hknokh2** [comment]
Hello!

For your questions:
- The autolookups are working as `OR`, collecting child records related to all parent objects.
- Operation type makes no sence.

Best Regards

**Comment by jorgesolebur** [comment]
Thanks @hknokh 
Last question  - how this feature work when master is the child object and slave is the parent? Are parent records pulled only for the child master records defined in the query for the child object?
After my testing it seems it works like this, but would like to confirm.

Thanks

**Comment by hknokh** [comment]
Hello,  
Just FYI, hknokh and hknokh2 are my two different accounts—same person :)  

Regarding your question:  
That's correct. When the master is the child lookup object, SFDMU retrieves all parent records (from the slave object) referenced by the child records (of the master object).

Regards,

**Comment by jorgesolebur** [comment]
Thanks Boss !

**Comment by hknokh** [comment]
Hi,

This case is now closed. If you encounter any other bugs while using SFDMU, please don’t hesitate to reach out.

Regards.
