### ISSUE TITLE
[BUG] - Comparison of source and target records stopped working

### ISSUE THREAD

**Issue by kalius** [forcedotcom/SFDX-Data-Move-Utility#934]
**Describe the bug**
Comparison with target records stopped working with newer version (I don't have exact version number when this stopped working). I have an old computer with old version and this comparison still works.

**To Reproduce**
Export to csv and then import this csv to the same org that was used for export.

**Expected behavior**
It shouldn't update records because field values are exactly the same.

**export.json**
{
    "createTargetCSVFiles": true,
    "excludeIdsFromCSVFiles": true,
    "promptOnIssuesInCSVFiles": false,
    "objects": [
        {
            "query": "select Name from Account",
            "operation": "Upsert",
            "externalId": "Name"
        }
     ]
}

Version: 4.36.7

Log files attached.
[2024-11-22__13_55_34 - export.log](https://github.com/user-attachments/files/17870433/2024-11-22__13_55_34.-.export.log)
[2024-11-22__13_57_44 - import.log](https://github.com/user-attachments/files/17870434/2024-11-22__13_57_44.-.import.log)

**Comment by hknokh2** [comment]
Hello!

This issue doesn't appear to be a bug in the SFDMU core, but rather related to the specifics of the data model and the actual data in the orgs. As outlined in my [Support Policy](https://help.sfdmu.com/additional-information/support_policy), I am unable to provide assistance for this type of issue.
I appreciate your understanding.

Regards.

**Comment by hknokh** [comment]
Hello, @kalius

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh2** [comment]
I only changed how `null` values are refelected in the content sent to the V2 for update.
Ok. For now, I put this issue into `pending` for the possible future review.

**Comment by hknokh2** [comment]
Hello,  
I identified the issue in one of the latest releases that affected the comparison function and caused the bug you experienced.  
The issue has been resolved. Please update the plugin and let me know if it works.  
Thanks!

**Comment by kalius** [comment]
> Hello, I identified the issue in one of the latest releases that affected the comparison function and caused the bug you experienced. The issue has been resolved. Please update the plugin and let me know if it works. Thanks!

Perfect, yes, now it works as before. Thanks!!!
