### ISSUE TITLE
[BUG] - Support SELECT all FROM Product2

### ISSUE THREAD

**Issue by PotSeht** [forcedotcom/SFDX-Data-Move-Utility#938]
Hi @hknokh 

I am trying to migrate Product2 records from sandbox to sandbox, and am hitting the below error.  The field is fine from an FLS perspective.

`[12:13:36.877] [ERROR] Error during execution of the command:
 Recommended_Retail_Price__c, ExternalDataSource.DeveloperName
                              ^
ERROR at Row:1:Column:3200
Didn't understand relationship 'ExternalDataSource' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..
[12:13:36.879] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).`

I have tried using ScriptObject's `excludedFields`, targetting both `ExternalDataSource` and `ExternalDataSource.DeveloperName`, to no avail.   The [documentation](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object-object#excludedfields-array-of-string) for externalFields states fields specified here are excluded from the SOQL query, perhaps this is not entirely true, or possibly some kind of bug?

My Export JSON looks like this:

```
{
    "objects": [
        {
            "query": "SELECT all FROM Product2",
            "operation": "Upsert",
            "externalId": "Name",
            "excludedFields": ["ExternalDataSource,ExternalDataSource.DeveloperName"]
        }
    ]
}
```

Whilst I have a workaround, explicitly stating _each and every_ field on Product2 which can be tedious.  It would be great to investigate if this is something that could be easily rectified.

Thank you very much

**Comment by hknokh** [comment]
Hello, @PotSeht

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Hello
It does not look as a FeatureRequest.
Please rename your ticket accordingly, I will take a look on it asap.
Regards.

**Comment by PotSeht** [comment]
Hello - I marked it as this as I wasnt sure whether it was truly a bug or not.  I have renamed.

Thank you

**Comment by PotSeht** [comment]
Hi @hknokh 

I've realised the underlying field is actually called _ExternalDataSourceId_.  Upon populating this under `excludedFields` it is working as expected.

```
{
    "objects": [
        {
            "query": "SELECT all FROM Product2",
            "operation": "Upsert",
            "externalId": "Name",
            "excludedFields": ["ExternalDataSourceId"]
        }
    ]
}
```

One suggestion I have is that perhaps this field acts similarly to RecordTypeId, where it has to be explicitly defined in the query in order to be included.  This I imagine would gracefully handle both scenarios, orgs that do/dont leverage _Product2.ExternalDataSourceId_

Thanks

**Comment by hknokh2** [comment]
@PotSeht hello
Implemented exclusion of ExternalDataSourceId from using in multiselect field.
Regards
