### ISSUE TITLE
[BUG] - When using more complicated WHERE clause in query, strange things happen

### ISSUE THREAD

**Issue by anna-walach-wexinc** [forcedotcom/SFDX-Data-Move-Utility#939]
**Describe the bug**
I want to restrict data retrieved from the org and try to create where clause with a "not in ()" statement and one more statement. The SFDMU adds additional "not" in the next part of the query and then throw "invalid query error".

**To Reproduce**
Create a query with where clause containing a "not in ()" phrase and then another phrase after it, .e.g 
`where industry not in ('Electronics') and industry != null` 

**Expected behavior**
The where clause of query should behave the same way as it behaves in Developer Console and not get "not" operator in random places.

**export.json**
`{
  "objects": [
    {
      "operation": "Upsert",
      "externalId": "Name",
      "query": "select id, name, industry, type from account where industry not in ('Electronics') and industry != null",
      "master": true
    }
  ]
}
`

**Log file**
[2024-11-29__18_37_50.log](https://github.com/user-attachments/files/17962016/2024-11-29__18_37_50.log)

**Comment by hknokh** [comment]
Hello, @anna-walach-wexinc

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh2** [comment]
Hello,

The NOT clause is not supported by SFDMU and may cause various issues. Please avoid using it.

Regards.
