### ISSUE TITLE
[BUG] - Nested self lookup records are failing. MissingParentRecordsReport.csv is generated

### ISSUE THREAD

**Issue by ahmet-eren** [forcedotcom/SFDX-Data-Move-Utility#945]
**Describe the bug**
Bifrost_Test_System_Exec_Rq_Param_Config__c custom object has Parent_Parameter__c custom lookup field to itself. It is being used as nested records.

**To Reproduce**
Execute export.json file

**Expected behavior**
All the records are created/updated in the target org with the right hierarchy. 

**export.json**
```
{
    "allOrNone": true,
    "excludeIdsFromCSVFiles" : true,
    "objects": [
        {
            "query": "SELECT createable_true FROM Bifrost_Test_System__c",
            "operation": "Upsert",
            "externalId": "Name"
        },
        {
            "query": "SELECT createable_true FROM Bifrost_Test_System_Execution_Config__c",
            "operation": "Upsert",
            "externalId": "Test_System__r.Name;Name"
        },
        {
            "query": "SELECT createable_true FROM Bifrost_Test_System_Exec_Rq_Param_Config__c",
            "operation": "Upsert",
            "externalId": "Test_Execution_Config__r.Name;Name;Parent_Parameter__r.Name;Parent_Parameter__r.Parent_Parameter__r.Name;Parent_Parameter__r.Parent_Parameter__r.Parent_Parameter__r.Name"
        }
    ]
}
```

**Log file**
[2024-12-18__21_09_33.log](https://github.com/user-attachments/files/18192882/2024-12-18__21_09_33.log)

**Comment by hknokh** [comment]
Hello, @ahmet-eren

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers
