### ISSUE TITLE
[QUESTION] - How to import an export.json file for config

### ISSUE THREAD

**Issue by ldaggett-godaddy** [forcedotcom/SFDX-Data-Move-Utility#946]
I am trying to set up a system where my team can share export.json files to seed sandboxes. We are using the GUI application instead of the CLI. However, when I create a new workspace, connect two environments, and try to upload a json file, using "import from export.json File" under Configuration, nothing happens. Am I missing a step? Is there any walkthru on how to import a file into the app? Does the import file need to be in a specific location? 

Thanks.

**Comment by ldaggett-godaddy** [comment]
Sorry for raising the issue -- turns out my json file had a comma missing. Fixed it and it imports as expected!

**Comment by hknokh** [comment]
Hello, @ldaggett-godaddy

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers
