### ISSUE TITLE
custom External Id of polymorphic lookup not supported

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#95]
**Test Setup**
export.json test setup:
```
{
    "query": "select Id,CreatedDate,ParentId,FromAddress,FromName,ToAddress,CcAddress,BccAddress,Incoming,MessageDate,MessageIdentifier,Status,Headers,Subject,TextBody,HtmlBody from EmailMessage",
    "operation": "Upsert",
    "externalId": "MessageDate"
},
{
    "query": "select Body,BodyLength,ContentType,CreatedById,CreatedDate,Description,Id,IsDeleted,IsPrivate,Name,ParentId$EmailMessage from Attachment where Parent.Type = 'EmailMessage'",
    "operation": "Upsert",
    "externalId": "Name"
 }
```
**Bug**
Currently when trying to migrate a child object with a specified object as the polymorphic parent, the following error message is received:
```
[ERROR] Error during execution of the command: 
Name, ParentId, CreatedBy.Name, Parent.MessageDate FROM Attachment
                                ^
ERROR at Row:1:Column:136
No such column 'MessageDate' on entity 'Name'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
```
This seems to be standard behavior and occurs when running the following query:
```
select Parent.MessageDate, Id from Attachment
```
**Solution Suggestion**
If an object is defined for a polymorphic lookup field (such as `select ParentId$EmailMessage from Attachment`), then the `TYPEOF` operator needs to be used to correctly fetch the externalId of the parent:
```
select typeof Parent when <$ParentObject> then <Parent.ExternalId> end, <child fields> from <child object>
```
Example:
```
select typeof Parent when EmailMessage then MessageDate end, Body, ContentType, Id, IsPrivate, Name from Attachment
```

**Comment by hknokh** [comment]
Hello @kevdo475 
The issue should be solved. I've used your idea about TYPEOF. 
Please check.

**Comment by jonny-harte** [comment]
Is there anymore documentation on this? I'm having a similar issue with changing the User externalId to CommunityNickname. The below query isn't working?

`SELECT TYPEOF Owner WHEN User THEN CommunityNickname END, all, RelatedRecordId FROM ServiceResource`

**Comment by dinhphieu** [comment]
Following this too, ``

**Comment by dinhphieu** [comment]
Following this too

**Comment by dinhphieu** [comment]
Following this too

Tried multiple combinations for the Task object with query1, query2, query3 which you can find below and none of them worked, giving the exact error as OP or just completely skipping the "TYPEOF <CONDITION> END" query with a success and no records processed

```
{
  "objects": [
    {
      "master": true,
      "query": "SELECT createable_true FROM Lead WHERE Id = '00Q3M000006CgctXXX'",
      "externalId": "Id",
      "useFieldMapping": true,
      "fieldMapping": [
        {
          "targetObject": "Lead"
        },
        {
          "sourceField": "Id",
          "targetField": "TempExternalId__c"
        }
      ]
    },
    {
      "master": false,
      "query1": "SELECT WhoId$Lead FROM Task",
      "query2": "SELECT TYPEOF Who WHEN Lead THEN TempExternalId__c END, createable_true FROM Task",
      "query3": "SELECT TYPEOF Who WHEN Lead THEN Id END, createable_true FROM Task",
      "excludedFields": [
        "RecurrenceActivityId"
      ],
      "operation": "Upsert",
      "externalId": "Id",
      "useFieldMapping": true,
      "fieldMapping": [
        {
          "targetObject": "Task"
        },
        {
          "sourceField": "Id",
          "targetField": "TempExternalId__c"
        }
      ]
    }
  ]
}
```

**Comment by hknokh** [comment]
Hello.

I sincerely apologize for the extended delay in resolving your ticket. I understand that you have been waiting for a resolution, and I regret any inconvenience this has caused.

Due to my current time constraints and commitments, I am unable to provide timely support for this project. However, please be assured that I value your inquiry and will review this ticket again as soon as my schedule permits.

Your patience is greatly appreciated, and I will do my best to address your concerns as soon as possible.

Thank you for your understanding.

Best regards.

**Comment by hknokh** [comment]
I've temporarily closed this case for now and will revisit it in the future. 
Once there's an update or outcome, I will reopen it and notify you.
