### ISSUE TITLE
[FEATURE REQUEST] - Quality of Life: Include success + failure information in Data Processing Summary

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#97]
It would be helpful if the total number of success and failures of each object can be added to the summary.

Right now, the summary only shows the number of processed records, but to see success/failures I have to browse through the different batches or look into the target csv files.
```
=== DATA PROCESSING SUMMARY
{RecordType} Total processed within all steps (Insert + Update): 0 records
{User} Total processed within all steps (Insert + Update): 0 records
{Account} Total processed within all steps (Insert + Update): 629 records
{Contact} Total processed within all steps (Insert + Update): 88 records
```

**Comment by hknokh** [comment]
Hi @kevdo475 
Thank you for the suggestion
